### ISSUE TITLE
Basic layer properties 'opocity'

### ISSUE THREAD

**Issue by chchwy** [pencil2d/pencil#10]
I was thinking that having an “opacity” option for the layers would be great. I usually use a “rough” layer under my “inked” layer; and I put the rough at 20% opacity or so.

This could be implemented like in After Effects :

Layers could get some properties when it is “maximized” : this would be a nice “structure” to put in place, which would allow to be extended with other properties later ! Eventually, those properties could be animated with keyframes…

by Gordie

**Comment by Jose-Moreno** [comment]
@chchwy This is related to #459 , although the other one is a duplicate, it had someone already assigned to work on it, however i don't know if @Spark01 is still working on that feature, maybe we can close this one and put Gordie's comment there for consistency.

**Comment by chchwy** [comment]
Duplicated issue confirmed. Thanks @Jose-Moreno
