### ISSUE TITLE
version numbers broken on macOS

### ISSUE THREAD

**Issue by core-code** [pencil2d/pencil#1006]
i've downloaded version 0.6.1 ( https://github.com/pencil2d/pencil/releases/download/v0.6.1.1/pencil2d-mac-0.6.1.1.zip ) but when selecting it in the Finder, it says it is version 0.6.0

**Comment by Jose-Moreno** [comment]
@core-code Thanks for reporting! Can you try one of the latest development builds for MAC to see if it says the same? 

You can find them here: https://www.pencil2d.org/download/#nightlybuild

**Comment by core-code** [comment]
latest development version has version 0.6.2, so i assume thats fine, thanks

**Comment by Jose-Moreno** [comment]
@core-code Yes those development builds are the ones that will become 0.6.2 stable maintenance version in the upcoming release. So then it seems the one with issues is the current release. We'll have to wait for a MAC dev(s) to come discuss about this, as I'm not sure if it's feasible to patch the stable version for MAC to change the versioning number considering the new release is around the corner. Either way thank you once more for reporting this issue.

**Comment by chchwy** [comment]
@core-code Thanks for reporting. I forgot changing the version number for Mac OS last time. It will be correct in the next release.

**Comment by scribblemaniac** [comment]
Just for reference, this was fixed in https://github.com/pencil2d/pencil/commit/14a031b915521bddddb6adc68e5a9c063c7987b0.
