### ISSUE TITLE
Restoring work

### ISSUE THREAD

**Issue by AdwaithAbhilash** [pencil2d/pencil#1009]
### --System Information--
+ Pencil2D Version:

+ Operating System:

+ RAM Size:

+ Graphics Tablet:

---

**Comment by chchwy** [comment]
Hi @AdwaithAbhilash 
Can you please tell us more about your situation?

**Comment by Jose-Moreno** [comment]
I'm closing this issue. The user didn't provide more information after 2 years. While it's probably related to file recovery methods, we can't work without proper information to help us find the root problem. 

For anyone wanting to look at current recovery methods for Pencil2D files please take a look at our forum guide on the topic https://discuss.pencil2d.org/t/pencil2d-project-file-corruption-prevention-partial-recovery-guide/3105

Additionally chchwy has submitted a new set of features to help recover work on common cases such as application crashes. You can read more about that here: https://github.com/pencil2d/pencil/pull/1436 and you should be able to benefit form it by using the latest nightly builds after August 25th
