### ISSUE TITLE
wrong cursor icon when using a tablet

### ISSUE THREAD

**Issue by jin-eld** [pencil2d/pencil#1017]
### --Issue Summary--

When using a tablet, wrong cursor icons are displayed, for instance, I select the drawing pen, then I
move the cursor into the drawing area. While doing so I pass a window border, which changes the cursor to a "move border arrows" icon, the icon stays when I move the cursor into the drawing area. This makes it hard to aim at the exact position where you want to start painting.

As soon as I draw a pixel the icon corrects itself.

The screenshot tool would always capture a normal cursor and not the icon displayed, so I had to photograph my screen :)

![image](https://user-images.githubusercontent.com/1308196/42726438-1c75e36c-879d-11e8-8a05-c0bec3c9d853.png)

### --Steps to reproduce--

Use your tablet pen to select a drawing tool, then move into the drawing area, observe the pen cursor/pointer icon.

### --System Information--
+ Pencil2D Version:

git revision 33a13d2aef2c31aa87c3a1428f412773b08397f1

+ Operating System:

Linux, Fedora 27

+ RAM Size:

4GB

+ Graphics Tablet:

Huion H610
---

**Comment by J5lx** [comment]
Confirmed on Arch Linux with Pencil2D 0.6.1.1 and Huion 420, issue occurs when hovering over UI using the tablet rather than a regular mouse.

**Comment by Jose-Moreno** [comment]
As referenced in the Ubuntu 18.10 appimage tracker this is also happening in that distro.

**Comment by J5lx** [comment]
As forum user danya [notes](https://discuss.pencil2d.org/t/stuck-cursor-icons-on-linux-when-using-tablet/4509?u=j5lx), this issue does only occur with docked windows, floating windows do not have this problem. Additionally, there appears to be (at least in 2017) [a very similar issue](https://discuss.pencil2d.org/t/stuck-curson-icons-on-mac-osx-when-using-tablet/1320?u=j5lx) on macOS which I suppose might very well be related.

**Comment by Jose-Moreno** [comment]
@J5lx @chchwy  I'm reopening this. I've just tested the latest september 24th nightly build AppImage under Ubuntu 18.10 and this issue was only fixed for the mouse input. However when using a stylus tablet input, the problem remains the same.

**Comment by J5lx** [comment]
Ah yes, I’m remember this, we talked about it on Discord a while ago. The issue is actually fixed for most “versions” of Pencil2D (such as Flatpak and compiled from source), but in the AppImage it still occurs. My personal hunch was that it might be related to the very old version of Qt used in our AppImages, but I wasn’t able to find suitable builds of newer versions at the time, so I haven’t been able to check whether that’s true.
