### ISSUE TITLE
Trimmed tab title in Color Inspector

### ISSUE THREAD

**Issue by jcome** [pencil2d/pencil#1025]
### --Issue Summary--
Color Inspector tab title trimmed 

### --Actual Results--
<img width="429" alt="2018-07-24 9 02 22 am" src="https://user-images.githubusercontent.com/417336/43110796-8b88c852-8f20-11e8-92b2-792c649f68d2.png">

### --System Information--
+ Pencil2D Version:
Version: 0.6.1.1
commit: 4f73eb168e0539e02789f0fdf009f18588278a02
date: 2018-07-17_10:20:55
Development build

+ Operating System: macOS High Sierra (10.13)

**Comment by chchwy** [comment]
Please check with Nightly 6 Aug 2018
