### ISSUE TITLE
Resizable tear-off dock(window)

### ISSUE THREAD

**Issue by jcome** [pencil2d/pencil#1026]
### --Issue Summary--
when a dock (window) is tear-off, and its windows size is not able to change anymore.

### --Expected Results--
It would be nice to make those tear-off docks are resizable.

### --System Information--
+ Pencil2D Version:
Version: 0.6.1.1
commit: 4f73eb168e0539e02789f0fdf009f18588278a02
date: 2018-07-17_10:20:55
Development build

+ Operating System: 
macOS High Sierra (10.13)

**Comment by chchwy** [comment]
A little weird as I can resize them on Windows 10. Will check on Mac later.

**Comment by scribblemaniac** [comment]
Detatched panels are resizable. I have tested this with v0.6.5 on macOS High Sierra and I can confirm they can be resized as long as you are not trying to shrink it beyond the minimum size. Close this issue.
