### ISSUE TITLE
I can't save my animation/project.

### ISSUE THREAD

**Issue by noru123** [pencil2d/pencil#1030]
Hello!  Whenever I save an animation project, there are no problems. But when i tried to save a recent animation project, it came up with an error message thing. I'm not sure if this is a bug or something to do with my computer but if you could do something, that would make my day!

System info (idk):
Pencil version: 0.5.4
Build ABI: x86_64-little_endian-llp64
Kernel: winnt 10.0.17134
Product name: Windows 10 (10.0)

![sketch](https://user-images.githubusercontent.com/41934339/43435785-87ecad38-944f-11e8-9685-7a4945a39dbe.png)

**Comment by chchwy** [comment]
Hi @noru123 
Please switch to the newer version and stop using v0.5.4 since the dev team has fixed a lot of file saving issues. Feel free to raise another issue if you get file-save errors in the latest version. I'm closing this one.
