### ISSUE TITLE
Broken sound playback in AppImages

### ISSUE THREAD

**Issue by J5lx** [pencil2d/pencil#1033]
### --Issue Summary--
Our current AppImage releases are unable to play sound, though movie export is unaffected. The root problem is that linuxdeployqt currently lacks proper support for GStreamer and does not include required modules (most likely sinks in our case). Due to the nature of the problem, playback might still work on *some* distributions, but beyond the tested systems this issue is likely to affect most modern and/or non-Debian-based distributions (as our AppImage build system is Ubuntu Trusty). Fortunately, it seems that the issue can be worked around on our side (see Further Information below).

### --Actual Results--
The sound clips cannot be heard.

### --Expected Results--
During playback of an animation with sound clips, the sound clips can be heard through the systems audio hardware.

### --Steps to reproduce--
Open any project containing sound, then attempt to play it back.

### --System Information--

[The original report on our forum](https://discuss.pencil2d.org/t/no-sound-in-appimage-builds/2847?u=j5lx) concerned an unknown version of Pencil2D on Fedora 26. I have confirmed the issue with our released AppImage of version 0.6.1.1 on Arch Linux.

### --Further information--

- probonopd/linuxdeployqt#96
- probonopd/linuxdeployqt#123

**Comment by J5lx** [comment]
I just noticed that this problem apparently also affects our timeline as sound clips added in the AppImage always appear as if they were just a single frame long.

**Comment by eszlari** [comment]
This should work with the flatpak version (https://github.com/pencil2d/pencil/issues/1036), because the runtime there includes GStreamer.

**Comment by chchwy** [comment]
Can anyone recheck this issue with v0.6.2?

**Comment by eszlari** [comment]
I tested it with 0.6.2 (flatpak version) and I can confirm that it works!

**Comment by chchwy** [comment]
Thank you @eszlari 

How about the AppImage version? Could anyone help confirm? @J5lx @mapreri

**Comment by scribblemaniac** [comment]
I can confirm that the AppImage version is *still broken* on Ubunut 18.04. Spits out a bunch of GStreamer errors.

**Comment by chchwy** [comment]
Thanks @scribblemaniac
