### ISSUE TITLE
flatpak

### ISSUE THREAD

**Issue by eszlari** [pencil2d/pencil#1036]
I'm in the process of making pencil2d available on https://flathub.org:

https://github.com/flathub/flathub/pull/527

If you want to have commit access, please comment in that pull request.

**Comment by Jose-Moreno** [comment]
@J5lx @CandyFace @scribblemaniac @chchwy

**Comment by Jose-Moreno** [comment]
@eszlari Thanks I've already tagged the core devs about this. :slightly_smiling_face:

**Comment by chchwy** [comment]
Welcome, @eszlari. Please let us know what we can help you.

**Comment by eszlari** [comment]
After the PR is accepted, a new repository will be created (https://github.com/flathub/org.pencil2d.Pencil2D). In the common case, when there is a new release of Pencil2D, all one has to do, is to update the URL and the checksum of the release tarball in the YAML file and commit to the master branch. Then the new version will be compiled and if that is successful, it will be uploaded to Flathub.

To compile and test locally:

```
$ flatpak-builder --force-clean --ccache --install build_dir org.pencil2d.Pencil2D.appdata.xml
$ flatpak run org.pencil2d.Pencil2D
```

**Comment by scribblemaniac** [comment]
Since the flatpak has been set up and working since v0.6.4, I'm going to close this issue.
