### ISSUE TITLE
Manjaro Linux critical cursor lag when using a graphics tablet stylus

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1041]
### --Issue Summary--
User "Asru" on discord has mentioned that they can't use the stylus correctly as there was a noticeable cursor lag when using a Wacom graphics tablet. 

When using the "dotted cursors" option this was most noticeable for the user, as the circle outline wouldn't follow the stylus motion and cursor.

When they use the mouse however, the cursor follows just fine, the problem only happens when using the graphics tablet.

Apparently #877 is related as well as this user comment which mention that on **Manjaro** [he's experiencing similar issues](https://github.com/pencil2d/pencil/issues/877#issuecomment-403116089)

They mentioned that there was a swap between the icons using the wacom tablet as outlined in #1017 which seems like a critical linux issue right now.

### --Expected Results--
There should not be cursor lag from using a graphics tablet in any linux distro.

### --Steps to reproduce--
These details were nto given because it seems that the issue is present soon after the application is started

### --System Information--
+ Pencil2D Version:
Version: 0.6.1.1
Operating System: Manjaro Linux 17.1
CPU Architecture: x86_64

**Comment by ebarranco** [comment]
I have the same problem, lag when I try to resize the brush and when I try to make zoom using my wacom tablet. This doesn't happen with the mouse. I use Manjaro too. My version is from git compiled today. Same behaviour with appimage.

**Comment by Jose-Moreno** [comment]
@ebarranco Thank you for confirming Enrique!

**Comment by J5lx** [comment]
I don’t have the slightest lag with my Huion tablet, never had – even though the person in the other thread did state that they were using a Huion tablet as well. There must be some other factor involved in this. I noticed that all of the tablet lag reports on Linux seem to be coming from Manjaro users (in fact a disproportionally large amount of Linux bug reports in general seem to be coming from Manjaro users). Meanwhile another person in the other thread mentioned it worked fine for them, and they were a Fedora user. I think we should have a closer look at Manjaro here… and if that’s not it, well idk.

**Comment by J5lx** [comment]
Tried 0.6.5 on Manjaro, still no lag for me. It must be something else after all, but I don’t know what…

**Comment by ebarranco** [comment]
Hi! I haven't use Pencil since then, I tried with Pencil v0.6.5 right now the problem no longer exist. I think it's just solved.

**Comment by chchwy** [comment]
Thank you @ebarranco for the report. I am closing this issue.
