### ISSUE TITLE
Exporting Problem

### ISSUE THREAD

**Issue by anim8tor** [pencil2d/pencil#1049]
### --Issue Summary--
When I tried to export my animation in the form of a movie, it only downloads halfway and then stops.

### --Actual Results--
When I open the video, it only plays half of the animation.

### --Expected Results--
The animation should download all the way.

### --Steps to reproduce--
I made an animation.
I want to export the animation in the form of a movie.
The animation starts exporting, but when it gets to around 60% finished, it stops.
When I open the movie, the first half of the movie is fine, but the second half is completely blank because it didn't download all the way.

### --System Information--
+ Pencil2D Version:
Version: 0.6.1.1
Operating System: Windows 10
CPU Architecture: i386

+ Operating System:
 Windows10

+ RAM Size:
49.1MB

+ Graphics Tablet:
WACOM Intuos

**Comment by anim8tor** [comment]
1. I used MP4.
2.1086 frames
3. 12 GB

**Comment by Jose-Moreno** [comment]
@anim8tor Hey, it's been a few weeks I was wondering If you managed to export your work with the latest development build I linked before? If you did please comment back so we can close this issue, otherwise please let us know if the same behaviour continues.

**Comment by anim8tor** [comment]
It still hasn't worked, but I figured out another way to download it. Thank
you for checking in! Also, feel free to close the issue.

**Comment by Jose-Moreno** [comment]
@anim8tor Hmm. If you want upload your work file so we can take a look. There might be an issue that prevents Pencil2D from exporting it properly and we could fix it. In the latest builds the export memory was greatly reduced so I thought it would work, but maybe it's better to test with your file directly.
Of course If you don't want to publicly share your file in here, you can send it to pencil2danimation@gmail.com We'll respect your privacy and only use it to test this problem so hopefully none else has to go through this problem :slightly_frowning_face:

**Comment by scribblemaniac** [comment]
This issue seems very similar to a one reported recently on Discord, which was solved by upgrading the ffmpeg version (96dca6dcde1e85f1b7a6425dc7a1faa4255196b6). Given that this change could solve the issue and we can't really do more about this without more information, I am going to close this.
