### ISSUE TITLE
undo crashed

### ISSUE THREAD

**Issue by wesen** [pencil2d/pencil#105]
these are mostly notes to myself when using pencil. crash while doing an undo:

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.yourcompany.Pencil          0x0000000100007389 BitmapImage::operator=(BitmapImage const&) + 31 (bitmapimage.cpp:85)
1   com.yourcompany.Pencil          0x000000010004f203 BackupBitmapElement::restore(Editor_) + 119 (editor.cpp:540)
2   com.yourcompany.Pencil          0x000000010004f5f7 Editor::undo() + 435 (editor.cpp:593)
3   com.yourcompany.Pencil          0x00000001000bfdc9 Editor::qt_metacall(QMetaObject::Call, int, void__) + 4181 (moc_editor.cpp:360)
4   QtCore_debug                    0x0000000101fc450b QMetaObject::metacall(QObject_, QMetaObject::Call, int, void**) + 293

**Comment by CandyFace** [comment]
is this still an issue, I haven't been able to crash Pencil by spamming undo in a long time now?

**Comment by Kaikogf** [comment]
I don't understand the notes left by @wesen, but if all that meant that Pencil2D crashed at the time while undoing changes, then I will consider this issue fixed since I experienced no crash with Pencil2D.

If so (anyone understanding this issue?) it can be closed

**Comment by CandyFace** [comment]
Yeah I think we can close this. There hasn't been any activity since last time I asked and I haven't been able to crash pencil by clicking undo for a long time now.

If the issue arises again, we can just open a new issue :)
