### ISSUE TITLE
Implement individual division lines for the grid system

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1066]
### Issue Summary
Implement independent grid / reticule division separation. This would allow the individual control of the grid / reticule horizontal (along the Y-axis) and vertical (along the X-axis) separation lines to create both uniform and non-uniform quadangular tiles that would correctly adapt to the aspect ratio of any given canvas size.

It's proposed that this setting occupies the same space on the preferences.

This will also help to implement further down the line a reactive field chart + studio templates that the animator can adapt according to their shot specifications.

**Comment by davidlamhauge** [comment]
I would like to work on this issue.
I have ideas on how this should be implemented.

**Comment by Jose-Moreno** [comment]
@davidlamhauge Thank you. Just tried it out and it works correctly on Version: 0.6.2
commit: ecbe8537aff9e70e99e16797383d21aedf5e39fe
date: 2018-10-05_13:12:56
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

One thing though, on the last version users could have a grid tile as small as a 1:1-pixel unit (this is was an intentional consideration for pixel art animators). Now it seems X and Y values are limited to 10 and it won't go lower than that. If possible please let the grid X and Y values go as low as 1-pixel. Other than that everything works great.

I'll close this issue as the main topic (Implementing individual properties for the grid) has been solved. :slightly_smiling_face:

**Comment by davidlamhauge** [comment]
@Jose-Moreno If a 1:1-pixel unit is asked for, it is easy to change. 
To me, it made no sense to have a grid smaller than 5x5 so it set this limit, thinking that no one would ever go that low :smiley:
