### ISSUE TITLE
Migrate timeline "frame size" slider widget from preferences to timeline

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1074]
### Issue Summary

Changing the timeline frame container width is currently done through the preferences with a slider. While this is interactive, it's a bit buried and the user has no idea it exists. It would also be more efficient if we managed to use the widget a slider to act sort of like a "timeline magnification slider" but directly on the timeline instead of staying in the preferences.

(Pending: Add mockup, immediate reference After Effects magnifying slider)

Along with this I'd like to ask that the maximum width of the frames would also be increased. Wider keyframe drawing containers would help accommodate future thumbnails as seen in the timeline re-write proposal.

**Comment by Jose-Moreno** [comment]
@CandyFace Yes it is! I was just separating a lot of these piled up issues from the feature tracker and to avoid confusion I also labeled it with the "timeline" label to indicate that all of these are related. I forgot to reference the timeline re-write issue though :sweat_smile:
Aside form that maybe I should put them into a "timeline" milestone as well? :thinking: What do you think?

**Comment by CandyFace** [comment]
I think it's nice to have to as a separate issue :) and adding it to a timeline milestone good too

**Comment by Jose-Moreno** [comment]
Fixed by #1121 
We might have to revisit the code once the timeline is rewritten, and it can use some enhancements in the UI/UX front (e.g it's very hard to select super thin frames) but for now it works as intended. Thanks!
