### ISSUE TITLE
Improve layer management behavior

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1080]
### Issue Summary

Currently when ordering layers on the timeline, the layer that is being dragged and the layer that is serves as reference when dropped on top will switch places while disregarding the visual cue that indicates if the layer should be placed above / below an existing layer. The latter is the only thing that's close enough to being a bug.

This confuses users as they expect layers to be positioned above or below the reference layer as the preview "gutter line" (space between layers) indicates.
With that said switching layers is actually useful in certain scenarios, but it should be considered as an alternate behavior rather than the default functionality.

- [x] Main functionality: Change the default behavior when dragging a layer from "switch" to "push"

For quality of life improvements to said functionality, as such when a user reorders a set of layers they should be able to:

- [x] Have the "gutter line" be an accurate representation of where the layer will be positioned when dragging and dropping above or below a reference layer.
![image](https://user-images.githubusercontent.com/4912907/50457475-c4b4c080-0929-11e9-8f4a-b5340d6f4e14.png)
- [x]  Have layers pushed above and below the dragged layer that has been inserted where the visual cue occurred.

- [ ] Change the layer order method behavior to "switch" when using a modifier key (SHIFT). This mode will allow the layer to exchange places with the other layers instead of inserting itself into the "gutter".

Alternatively instead of using a modifier key if you dropped the layer on top of another layer instead of the "gutter", Pencil2d should recognize each as distinct behavior and act accordingly.

**Comment by CandyFace** [comment]
Can this be closed now?

**Comment by Jose-Moreno** [comment]
@CandyFace I'd have to test the newly implemented functionality. I'll gladly close it or update it once I test it, so please don't close it just yet.

**Comment by chchwy** [comment]
Please test the 30 Jan nightly build

**Comment by Jose-Moreno** [comment]
Alright. Tested. I'll close this as the main functionality change was enabled and is working as expected, gutter and all. However I still think the previous behavior is still useful as a secondary functionality for organizational purposes, specifically in scenarios with several layers where switching layers is required (e.g you are experimenting with depth or you are animating certain parts going in front or behind other layers). 

For now I'll just leave that alternate option proposal unticked in the closed issue, but will recycle the proposal as a future enhancement in case there are requests from the user community to "bring it back" or to fill-in for corner cases such as the ones I mentioned. Thanks again to everyone for the hard work! @CandyFace @chchwy @davidlamhauge :tada:

**Comment by davidlamhauge** [comment]
Thanks for your hard work @Jose-Moreno .
I have only heard/seen complaints about the swap places behavior. I don't think anyone will miss it, now that layer dragging will work as expected.
