### ISSUE TITLE
Implement a "reverse keyframe order" operator

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1081]
### Issue Summary

This is a common function that allows as the name implies to reverse the keyframe position relative to a selection, as such this would take the selected frames and switches their order while maintaining their visual position on the timeline.

e.g Let's say we have the following drawings:

[ 1 ] [ 3 ] [ 5 ] [ 7 ]

If I copy  / duplicate these drawings I would end up with a repeated action but in certain actions you want the animation to "go back" so you'd have to manually switch their order. 

[ 1 ] [ 3 ] [ 5 ] [ 7 ] / [ 1 ] [ 3 ] [ 5 ] [ 7 ]  <-> [ 1 ] [ 3 ] [ 5 ] [ 7 ] /  [ 7 ] [ 5 ] [ 3 ] [ 1 ]

That is fine when you have as few keys as the example, but sometimes you have actions with as many as 50 drawings, and keeping track of so many of them in Pencil2D is actually difficult, so if you're not careful there will be a mistake, plus reversing more than 10 drawings manually always becomes an efficiency sink.

**Comment by CandyFace** [comment]
Will be fixed when either #1343 or #1106
