### ISSUE TITLE
Loading a file removes the application icon on windows until next restart

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1092]
### Issue Summary

Every time I load a file the application icon on the top left corner and on the taskbar is lost, and instead replaced by a white sheet of paper on Windows. If possible someone please confirm if this happens in other operating systems.

### Expected Results

The Pencil2D icon should always be consistent regardless of the operation.

### Video or Image Reference
**Before**
![image](https://user-images.githubusercontent.com/4912907/46518362-65b74200-c839-11e8-9e8c-4946f33d27be.png)
![image](https://user-images.githubusercontent.com/4912907/46518454-deb69980-c839-11e8-9619-2ed3bdaf64e3.png)

**After Opening File**
![image](https://user-images.githubusercontent.com/4912907/46518343-5637f900-c839-11e8-8427-a2d902e95ca1.png)

![image](https://user-images.githubusercontent.com/4912907/46518470-ee35e280-c839-11e8-9b14-7ad2788b7011.png)

### Steps to reproduce

1. Start Pencil2D
2. Open a File
3. Icon is lost.

### System Information
+ Pencil2D Version:

Version: 0.6.2
commit: ecbe8537aff9e70e99e16797383d21aedf5e39fe
date: 2018-10-05_13:12:56
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by scribblemaniac** [comment]
I can confirm that this does *not* happen on macOS 10.13.

**Comment by chchwy** [comment]
Please test the nightly build 27 Feb 2019

**Comment by Jose-Moreno** [comment]
Can confirm this is fixed in;
Version: 0.6.2
commit: dc86a40224fcf9c1e437534a9d3018e4391205a8
date: 2019-02-27_13:24:45
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64
