### ISSUE TITLE
Loading a file and exiting will change "open recent" file order

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1093]
### Issue Summary

Basically I noticed that If you open a file, and exit the application, the next time you open it, the recent files order will be inverted, and it will continue to shift everytime you open a file (ascending vs descending and viceversa)

### Expected Results
Well normally a user should expect always that their working files order are the same unless changed. I I think it's most natural that the last opened files go from top to bottom, being the bottom one the least recent.

### Steps to reproduce
**Pencil2D starting state**
_Open recent files are ordered by last opened state_

![image](https://user-images.githubusercontent.com/4912907/46518529-4a990200-c83a-11e8-96f4-4e15005524f6.png)

1. I'll open the last one opened (first one in list) "BUG_VECTOR_DRAWING....."
2. Opening a file does not change this immediately.
![image](https://user-images.githubusercontent.com/4912907/46518626-c430f000-c83a-11e8-8fc5-e0567869f08b.png)

3. Restart the software.
4. Go to Open recent and notice the list is inverted, the last opened file is still first but the other files are not in the same order.
![image](https://user-images.githubusercontent.com/4912907/46518667-f2163480-c83a-11e8-857a-255acf79d313.png)

5. Do it again, and the order will change again.

### System Information
+ Pencil2D Version:
Version: 0.6.2
commit: ecbe8537aff9e70e99e16797383d21aedf5e39fe
date: 2018-10-05_13:12:56
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by Jose-Moreno** [comment]
@MatthewMcGonagle Sure thing! thank you for your interest in our project. If you need anything let us know :slightly_smiling_face:

**Comment by MatthewMcGonagle** [comment]
I think a simple solution would be to just traverse the order of `filenames` in the opposite order inside `setRecentFiles()`. So something like:

```
void RecentFileMenu::setRecentFiles( QStringList filenames )
{

    clear();

    if ( filenames.empty() )
        return;

    QStringList::iterator filename = filenames.end(); 

    do
    {
        filename--;
        if ( *filename != "" ) {
            addRecentFile( *filename );
        }
    } while ( filename != filenames.begin() );
}
```
This is kind of ugly using an iterator and a while loop. I don't see any way to make reverse iterators for a `QList`. Do you know of any way to do this nicely with Qt?

**Comment by Jose-Moreno** [comment]
@MatthewMcGonagle I'm not sure Qt isn't my forte. I found about this on their documentation tho:

http://doc.qt.io/qt-5/qlist.html#crbegin

Also a related entry in stackoverflow which might help: https://stackoverflow.com/questions/1339121/how-to-reverse-a-qlist

With that said maybe core Pencil2D developers like @scribblemaniac or @chchwy can help you further.

If you want you can also use the [**#pencil channel on IRC**](http://webchat.freenode.net/?channels=#pencil2d) to chat and since that's linked to the [**discord -#general-development channel**](https://discordapp.com/invite/8FxdV2g) as well so your questions will reach the devs promptly so they can assist you with your queries in case it takes too much time to sort it out through github :slightly_smiling_face:

**Comment by chchwy** [comment]
Thanks @MatthewMcGonagle you make things clear.
Would you like to send a PR?

**Comment by MatthewMcGonagle** [comment]
@Jose-Moreno Thanks for the help. I'll take a look.

@chchwy It's not quite sure to me why the bug results in the last opened file being the in the correct place while the rest of the list is reversed. So I want to take a longer look at it before I submit a PR.

**Comment by scribblemaniac** [comment]
@MatthewMcGonagle I was also unconvinced that reversing the list was the only issue, so I just dug into it. The reason why the last opened file is in the correct position is because it is being called a second time (after loading) from `MainWindow2::readSettings`. If you remove that it should work as expected. In fact I think you can remove the `LAST_PCLX_PATH` setting entirely if you feel up to it.

Adding from oldest to newest when loading a file as you proposed is still necessary. @Jose-Moreno was on the right track for a better way to loop through it in reverse order:
```
for(auto riter = filenames.crbegin(); riter != filenames.crend(); riter++)
...
```

**Comment by MatthewMcGonagle** [comment]
@scribblemaniac Okay, I think I see what you are saying. You are referring to the lines 

```
    QString myPath = settings.value(LAST_PCLX_PATH, QVariant(QDir::homePath())).toString();
    mRecentFileMenu->addRecentFile(myPath);
```
inside `MainWindow2::readSettings()` in `app/src/mainwindows2.cpp`. Removing these two lines seems to be okay. 

Should they be removed?

I'm not sure if I'm comfortable enough with the code base to remove the `LAST_PCLX_PATH` setting; I see it is being by other member functions of `MainWindow2`.

**Comment by scribblemaniac** [comment]
@MatthewMcGonagle Sorry, I totally forgot to reply to your message until now. Yes I believe those were the lines I was talking about. If LAST_PCLX_PATH is still being used by other methods, then you can just leave it in, that's no big deal. If it is unnecessary we can remove it later.

**Comment by MatthewMcGonagle** [comment]
@scribblemaniac Thanks for getting back to me, especially after a busy time of year. I'll take a look at it, but probably won't get around to submitting a pull request until next week.

**Comment by MatthewMcGonagle** [comment]
@scribblemaniac I've submitted a pull request. I didn't remove LAST_PCLX_PATH as it is used by other methods in `app/src/mainwindows2.cpp`, and I can't tell if how these methods are using it is critical to other parts of the application. So I thought it was best to play it safe and leave it alone.

**Comment by chchwy** [comment]
I am closing this issue as it has been resolved. Thank you @MatthewMcGonagle!
