### ISSUE TITLE
Pencil2D crashes after selecting the camera layer when move tool is selected

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1095]
### Issue Summary

As the title says, Pencil2D crashes immediately after selecting the camera layer with the move tool active. This is actually very, very likely to happen so I think it's a critical fix we should prioritize. The problem seems to be related to the move tool since no other tool has this issue.

### Expected Results

Pencil2D should not crash due to any combination of layers and tools being selected, or at all.

### Steps to reproduce

1. Open Pencil2D
2. Pick the move tool
3. Select the camera layer.
4. BAM, instant crash (on windows)

Note: please review if this happens as well on MAC and Linux. thanks!

### System Information
+ Pencil2D Version:

Version: 0.6.2
commit: ecbe8537aff9e70e99e16797383d21aedf5e39fe
date: 2018-10-05_13:12:56
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by scribblemaniac** [comment]
Should be fixed in the next nightly build. Thanks for reporting.
