### ISSUE TITLE
Range function visual widget not properly updated when using menu option

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1097]
### Issue Summary
Turning timeline range ON/OFF via menu command does not activate / deactivate the frame range visual widget respectively.

### Expected Results
Either the menu option or the timeline widget should work the same (i.e enabling / disabling the yellow frame markers)

### Steps to reproduce

1. Open Pencil2D
2. Go to Animation > Range > Turn it ON
3. Notice that the visual frame range (yellow frames) does not appear, but the functionality is active.

Alternatively,
2. Turn the Range function ON on the timeline. See the yellow frames appear to mark the range
3. Go to Animation > Range > Turn it OFF
4. Notice how the yellow frames are STILL activated but the functionality is not working.
5. Pressing Start Playback button will deactivate the yellow frames visual aid when it finishes playing.

### System Information
+ Pencil2D Version:

Version: 0.6.2
commit: ecbe8537aff9e70e99e16797383d21aedf5e39fe
date: 2018-10-05_13:12:56
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by Jose-Moreno** [comment]
@davidlamhauge Ah, good eye! I hadn't noticed that. Hmm well considering that the range spinboxes turn off after deactivating the range checkbox, I'd say it's not wanted behaviour, however if you consider it useful (to edit the range freely) I can make another issue for that. It depends on how people approach the tool. 
In my case I immediately try to edit the range first and then turn the checkbox on, just because I see the spinboxes enabled. But it may be more logical and clear to the user to only enable the spinboxes when the checkbox is turned.

**Comment by Jose-Moreno** [comment]
This has been confirmed to be fixed in Version: 0.6.2
commit: 6471882892c0d34ac20b0a70b9591685c9f68d04
date: 2018-10-12_11:17:33
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

Closing this issue.

**Comment by Jose-Moreno** [comment]
I made a mistake. This issue is still not fixed.

**Comment by chchwy** [comment]
Please test the nightly build 27 Feb 2019

**Comment by Jose-Moreno** [comment]
Can confirm this is now working on
Version: 0.6.2
commit: dc86a40224fcf9c1e437534a9d3018e4391205a8
date: 2019-02-27_13:24:45
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

Thanks a lot @chchwy !
