### ISSUE TITLE
Selection Flipping is not undoable / redoable

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1098]
### Issue Summary

A very simple user experience issue / bug. when flipping a selection either on the X or Y axis, this command is not undo-able / redo-able.

### Expected Results
Due to the nature of art, most if not all drastic changes in a drawing should be undoable. Flipping a drawing changes it's direction and sometimes artists try to find the best way to present them.

Note: This is not a critical bug by any means, you can flip the drawing again instead of undoing, but from a functionality standpoint all of these commands should be undo-able.

### Steps to reproduce

1. Draw something
2. Enclose it with the selection tool
3. Go to Edit > Selection > Flip X / Y
4. Press Ctrl + Z or go to Edit > Undo

### System Information
+ Pencil2D Version:

Version: 0.6.2
commit: ecbe8537aff9e70e99e16797383d21aedf5e39fe
date: 2018-10-05_13:12:56
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by chchwy** [comment]
will take a look after merging the Undo Refactoring PR

**Comment by Jose-Moreno** [comment]
[2020] **Testing on 0.6.5** Currently it seems you can undo the selection flipping, but it's still a bit buggy. After flipping the selection, if you immediately undo while the selection marquee still enabled this will delete from view the drawing inside the selection.

I assume that since it also removes the selection, anything that it's inside is being treated as part of the selection by the Canvas Painter. 

So the drawing disappears, but if you redo again you'll see the drawing reappear again and the flip is undone, also a marquee selection appears along the drawing even though it should be treated as a separate event (it should required an extra undo/redo step).
