### ISSUE TITLE
BMP Image sequence export suffixed sequence numbers added after file extension

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1099]
### Issue Summary

When exporting an BMP image sequence, the file numbering suffix will be added AFTER the filetype extension.

### Video or Image Reference
![image](https://user-images.githubusercontent.com/4912907/46566638-10863980-c8e8-11e8-9f34-349454d82c36.png)

### Expected Results
The incremental numbered suffix should always appear before the file extension.

### Steps to reproduce
1. Create enough drawings to export an image sequence
2. Got o File > Export > Image Sequence
3. Change the FORMAT extension to bmp.
4. Browse a folder and name the sequence
5. Export the sequence and review the final export on the chosen folder.

### System Information
+ Pencil2D Version:

Version: 0.6.2
commit: ecbe8537aff9e70e99e16797383d21aedf5e39fe
date: 2018-10-05_13:12:56
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by scribblemaniac** [comment]
Duplicate of final point in #1090

**Comment by Jose-Moreno** [comment]
@scribblemaniac Ah, I swear I didn't get that on my email :stuck_out_tongue_closed_eyes: Sigh. I'll close this then, since you already referenced it, if anyone wants to see the additional information they should be able to visit this issue.
