### ISSUE TITLE
AVI format movie exports with considerable lower quality than other formats

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1100]
### Issue Summary

After testing the movie export section I noticed that the AVI format image quality was significantly lower than that of MP4 format, and even webm format, which is rather odd considering AVI should be an uncompressed format mean for console editing, (and used over other formats when everything else fails).

In the example MP4 I exported the data rate was displayed as 844kbps while the same video exported as an AVI format exported at 128kpbs. Using VLC to analyze these videos, using the codec properties dialog, mentions that the AVI file has an "FMP4 MPEG-4" video format with an MP3 audio format. Normally AVI movie audio is expected to be WAV instead.

### Expected Results

AVI format movies should be at least of better quality (and size due to bigger data rate) than of other compressed / lossy formats.

### Steps to reproduce

1. animate something
2. export an mp4 for reference
3. export an avi for comparison, and use your preferred video analysis tool or player to learn about the AVI encoding.

### System Information
+ Pencil2D Version:

Version: 0.6.2
commit: ecbe8537aff9e70e99e16797383d21aedf5e39fe
date: 2018-10-05_13:12:56
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by scribblemaniac** [comment]
Should be fixed with 517df7a. I will open another issue eventually to discuss other potential parameter changes and to share some data which I used to determine the new avi quality level.
