### ISSUE TITLE
Range input boxes come activated even when the checkbox is not ticked during application initialization

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1101]
### Issue Summary
As noted by @davidlamhauge (Thank you!)
The range feature numerical input spinboxes are turned ON when the program starts, and only resume their normal behaviour after deactivating the range checkbox once.

I'd say it's not wanted behaviour. It really depends on how people approach the feature itself, however it may be more logical and clear to the user to only enable the spinboxes when the checkbox is turned and deactivate them when the checkbox is not ticked.

### Steps to reproduce

1. Open Pencil2D
2. Note the range numerical input start / end spin boxes are active
3. Turn the range function ON by ticking the checkbox
4. Turn the range fucntion OFF by ticking the checkbox. Notice that the input boxes are greyed out.

### System Information
+ Pencil2D Version:

Version: 0.6.2
commit: ecbe8537aff9e70e99e16797383d21aedf5e39fe
date: 2018-10-05_13:12:56
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by davidlamhauge** [comment]
IF we agree upon this as an unwanted behavior, then I would like to claim it.
Maybe some new potential developer should have it, since it is an easy fix.

**Comment by scribblemaniac** [comment]
I agree this is unwanted behavior. It should be consistent one way or another.

**Comment by CandyFace** [comment]
Agreed

**Comment by Jose-Moreno** [comment]
This has been confirmed to be fixed in Version: 0.6.2
commit: 6471882892c0d34ac20b0a70b9591685c9f68d04
date: 2018-10-12_11:17:33
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

Closing this issue. Thank you everyone for discussing and David for implementing it.
