### ISSUE TITLE
Implement Insert - Split, Delete - Unite: adjacent keyframe management behaviors

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1116]
### Issue Summary

Along with with #882 I've been requested having the following operators:

- [ ] Insert Keyframe - Split keyframe: this would insert a keyframe or if we selected an amount of keyframes it would insert as many as selected on the current frame and displace all the adjacent drawings to the right or left (optional) of the insertion.
- [ ] Duplicate Insert-Split: This would allow for duplicated keyframes to be inserted next to the current frame instead of being duplicated on the first empty frame space. It's important to note that currently to simulate this behavior you have to first move any drawing(s) next to the current drawing you want to duplicate and then press the duplicate button. Ideally this should be made automatically when duplicating a frame to avoid changing the "free slot"  behavior.
- [ ] Delete Keyframe - Join keyframe: this would instead delete the selected keyframe(s) and displace all the adjacent drawings from the right or left (optional) to fill-in the empty space that was left by the removed drawing container(s).

**Comment by Jose-Moreno** [comment]
After some consideration, and someone asking about it here: https://discuss.pencil2d.org/t/ripple-delete-would-be-cool/3202, I also think there should be an additional functionality or "mode" to these operations that can affect all the layers timing. Right now it's proposed to affect only the active layer, but it should have a mode to affect all the layers above and below.

This would be similar to inserting /deleting a frame with the "column operations" that Krita has now, which affects all the adjacent layers both active and passive moving keyframes to the left / right of the active frame when performing either insert or delete operations.

Granted this could be an enhancement of this enhancement, but I'm not sure If I should open another issue for that but rather ask for this to be implemented as a whole with the base "active layer" functionality.

**Comment by davidlamhauge** [comment]
As soon as the copy/move/reverse/delete feature is accepted and merged, this will be a walk in the park.
For Insert:
A function can move all layers the desired length ahead, from the chosen offset in the timeline, and call the notifyAnimationLengthHasChanged function.
For delete:
A function can delete the desired number of frames from all layers, from the chosen offset in the timeline, move the trailing frames in the layers the same amount back in the timeline, and call the notifyAnimationLengthHasChanged function.
Some checking should be done, but the groundwork has been done.

**Comment by J5lx** [comment]
Resolved via #1343
