### ISSUE TITLE
Undoing Selection Flip X / Y will delete the drawing

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1120]
### Issue Summary

Testing the program I forgot to report this. Basically if you select an area and use the Selection Flip X / Y function and then undo that operation, the drawing will be deleted. You can redo the drawing being deleted to the flipped state though.

Current workaround is flipping the selection again in the same axis

### Expected Results
Flipping Selection should be un-doable /re-doable

### Steps to reproduce

1. Draw something
2. Press CTRL + A or Create a Box Selection over the strokes
3. Go to Edit > Selection > Flip x/y
4. Remove selection. You can keep it too, it doesn't matter.
5. Press CTRL + Z. Drawing disappears.

### System Information
+ Pencil2D Version:
Version: 0.6.2
commit: 6471882892c0d34ac20b0a70b9591685c9f68d04
date: 2018-10-12_11:17:33
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by CandyFace** [comment]
I'll check if I can reproduce this in the undo-redo rewrite branch.
