### ISSUE TITLE
Please add to README FreeBSD as an OS where Pencil2D runs

### ISSUE THREAD

**Issue by yurivict** [pencil2d/pencil#1128]
The FreeBSD port is available: https://www.freshports.org/graphics/pencil2d

**Comment by yurivict** [comment]
> The README currently only contains manual downloads

It also says "Pencil2D is an animation/drawing software for Linux, macOS, and Windows." It now also works on FreeBSD. -)

> ffmpeg is not specified as a dependency for your package

Fixed. Thanks for pointing this out!

**Comment by scribblemaniac** [comment]
> It also says "Pencil2D is an animation/drawing software for Linux, macOS, and Windows." It now also works on FreeBSD. -)

Ah of course, added.

**Comment by yurivict** [comment]
Thanks!

**Comment by Jose-Moreno** [comment]
@yurivict Hi. So can we consider this as solved? FreeBSD has been added to the README and the website description to indicate Pencil2D now can be installed under this environment and we issued a limited announcement on social media regarding this. 

Unless there's anything else pending please consider closing this issue. Thank you for porting Pencil2D to FreeBSD! :slightly_smiling_face:

**Comment by yurivict** [comment]
Yes, thanks!
