### ISSUE TITLE
[ISSUE] The Drawing tools left round marks on most strokes

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#1154]
### Issue Summary

While laying strokes using different drawing tools, most of the strokes have a dot at the end of the stroke

 
#

+ Pencil2D Version:
20/12/2018

 

+ Operating System:
Win 8.1 x 64 bits

 

+ RAM Size:
32GB

 

+ Graphics Tablet:
HUION HD185

![defeito pencil2d](https://user-images.githubusercontent.com/28032931/50739451-72e92180-11d8-11e9-812d-5e93d9ec44ec.gif)

**Comment by CandyFace** [comment]
Related to https://github.com/pencil2d/pencil/issues/677

It's not a consistent bug though, I have tried to replicate using 3 different tablet brands without experiencing this problem on mac.

**Comment by scribblemaniac** [comment]
@Kaikogf What is your operating system?

**Comment by davidlamhauge** [comment]
XP-PEN 22E pro on MacBook and HUION 580 on Ubuntu 18.04 tested: No problems... Can't replicate the error.

**Comment by chchwy** [comment]
I can replicate this issue. Win 10 + Wacom Bamboo CTH670

**Comment by Jose-Moreno** [comment]
@davidlamhauge @chchwy @Kaikogf We were on discord with Candyface and Scribblemaniac a few hours ago testing 667 which is related to this one. Scribblemaniac managed to implement a few fixes while I kept testing compiled versions with 5.12. It seems 5.12 didn't fix out issue, but the changes made to scribblearea.cpp did you can read the history in the #general-development channel hopefully a PR will be made soon so KaikoGF can test as well with a nightly build to close both issues soon enough.

**Comment by Kaikogf** [comment]
> @Kaikogf What is your operating system?

Win 8.1 x 64 bits

**Comment by Kaikogf** [comment]
I managed to build the last code [07/01/2019] in order to test this issue, and it is still present

**Comment by Jose-Moreno** [comment]
@Kaikogf The fix we were testing before is still not merged, so wait a bit until it is reviewed :slightly_smiling_face:

**Comment by Jose-Moreno** [comment]
@Kaikogf Can you please test nightly build for JAN 30th 2019 and confirm if this has been fixed for you? Here's a direct link to the build.
**Win 64**: https://drive.google.com/open?id=12ekVl_44GTCGJLh_3zcyjLhlwa6jAoXV

**Comment by Kaikogf** [comment]
@Jose-Moreno 
Tested here with the build you provided and the round dots are no longer present. So I am going to close this issue

Thank you!
