### ISSUE TITLE
Bucket tool doesn't work with tablet

### ISSUE THREAD

**Issue by chchwy** [pencil2d/pencil#1164]
### Issue Summary

Bucket tool doesn't work with tablets, but it works with mouse. I guess it's related to the mouse/table event handling.

### Steps to reproduce

1. Start Pencil2D and select a Bitmap Layer
2. Draw a circle by pen/pencil tool
3. Use the bucket tool to fill the circle with my Wacom table. It should fill the circle but it doesn't.
4. Use the mouse instead, and the bucket tool fills the circle without problem.

### System Information
Windows 10 + Qt 5.9.3 64bit

**Comment by chchwy** [comment]
Just realised that bucket tool didn't implement those tablet event handling function. I will be doing it now.

**Comment by Jose-Moreno** [comment]
If it helps I recorded this quick video. The Pencil2D used was compiled in 5.11.3 as well, tested it with 5.12 but not with anything below those two versions. Double clicking with a stylus in a  very specific way seems to invoke the mouse event so the fill tool can work:

https://youtu.be/mSZjbUT6F30

**Comment by CandyFace** [comment]
Ah yes of course, yeah I didn't implement tablet events for some of the tools, as there was no need for that precision but if mouse events are disabled entirely now when a tablet is active, then that will of course cause problems.
