### ISSUE TITLE
Specific tools working with mouse but not with tablet

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1165]
### Issue Summary

Alright as discussed i'm raising a single issue since all of these seem to be related to #1164 and the fix should be related as well.

So after testing the latest source code (JAN 22nd 2019) and compiled with Qt 5.12 (the version has no effect in this as previously thought because I compiled it with 5.11.3) I've gathered a list of the tools that are working with a mouse input but not with tablet input:
- [x] Eyedropper
- [x] Polyline
- [x] Smudge / blur tool (test it by pressing ALT)
- [x] Selection tool**

** This one is the most critical in terms of destroying the artwork. In the case of the selection tool the clicks are acknowledged and it creates a selection box, but it also creates a second duplicate selection, so even though you can still create the selection, it is behaving strangely and the results are quite worrying as it completely destroys the drawing, however it works as expected when using the mouse.

### Expected Results

Each tool should work in the same way when using both a stylus and a mouse.

### Video or Image Reference + Steps to reproduce
The video below will provide a clear understanding of the current issues:

https://www.youtube.com/watch?v=pME-hLPT1l8

### System Information

Version: 0.6.2
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

+ Graphics Tablet:
Genius MousePen 8x6

**Comment by chchwy** [comment]
Please test with 30 Jan nightly build

**Comment by Jose-Moreno** [comment]
@chchwy Okay tested. Everything is working as expected except for the following:

**1. Eyedropper**, even though it's working now with both mouse and tablet input, the preview functionality has changed. In the previous nightlies if you use the eyedropper tool or invoke the tool via pressing the ALT modifier, you automatically get the preview square without clicking. Now you only get it when you click and drag over the paint. This is just a minor difference, and while I think it's more logical to invoke the "preview picker" only when you are actively searching for the color (e.g click & drag) we have to document this behavior change in the release notes and future documentation.

**2. Selection Tool** The selection is now mostly working with both mouse and tablet input. However when moving the selected drawing with my tablet I am having a very low reproduction behavior (2 out of 50, and counting, attempts) that triggers a behavior which seems to be related to **Issue C** from #1053 which I added recently, Since I don't have conclusive evidence that it's related to this issue or tablet events I'll mark it as solved. Thank you everyone! :smile: :tada:
