### ISSUE TITLE
Canvas zoom factor abrupt change disrupts navigation workflow

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1169]
### Issue Summary

A new issue related to navigation on the canvas, specifically the canvas zoom functionality. Currently there is an input gesture to activate the zoom where clicking & dragging upwards zooms in and dragging downwards zooms in. The issue occurs when you have previously zoomed in, and then click to zoom out the factor will change abruptly. Same happens when you zoom out and then zoom in.

### Expected Results

Previous zooming operations should not affect the zoom factor abruptly. Zooming should always interpolate from the current zoom factor to the next regardless of the current and final values.

### Video or Image Reference
https://youtu.be/AB9jfLrHloo

### Steps to reproduce

1. Open Pencil2D
2. Drawing something to have as a reference point to see.
3. Zoom out (click and drag downwards)
4. Zoom in (click and drag upwards)
5. Notice the drastic change in zoom factor.

### System Information
Version: 0.6.2
commit: fe450b794aca754768f9e5dfe02e6abcdcc29189
date: 2019-02-05_13:58:04
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by chchwy** [comment]
Please test with the 19 Feb nightly build.

**Comment by Jose-Moreno** [comment]
Can confirm the bug is gone. It seems dragging speed does affect zoom factor but it is mostly noticeable when dragging upwards to zoom out but that's not a bug, rather a user experience thing. Right now zooming in/out behaves in a responsive manner. Thanks a lot!

**Comment by CandyFace** [comment]
The zoom functionality should not be affected by dragging using the hand tool... I'd consider that a bug.

**Comment by CandyFace** [comment]
@scribblemaniac Ah yes of course, I completely forgot about that feature. Disregard my comment :P
