### ISSUE TITLE
hangup while trying to move a selection

### ISSUE THREAD

**Issue by wesen** [pencil2d/pencil#117]
Selection was on a bitmap layer

**Comment by Jose-Moreno** [comment]
@feeef @tasaif @chchwy Guys does this bug still apply? Can we use the suggestions made by wesen to improve how the selection tool works? If not then let's close this issue, or make a new one with relevant & updated information.

**Comment by feeef** [comment]
This should be closed. Since December 2015 a selection only redraws what it moves as @wesen was suggested.
