### ISSUE TITLE
Quick Sizing is broken

### ISSUE THREAD

**Issue by BugReporter-01** [pencil2d/pencil#1182]
### Issue Summary
Quick Sizing doesn't work, the issue first appeared in the **Nightly Build from 2019-01-31** (832d3db6d5fdfb117dc9a7b4945592387c489059) and still presented in 2019-02-25. The Dotted Cursor also became broken in that build, but it's already fixed (8b577e868bacb1083ab12487e097cd8af59739d5).

### Actual Results
`Shift/Ctrl+LMB Dragging` performs regular drawing.

### Expected Results
`Shift/Ctrl+LMB Dragging` changes tool size/feather.

### Steps to reproduce
Enable `Use Quick Sizing` option, try to change size or feather of the Pencil or other drawing tool using `Shift/Ctrl+LMB Dragging`.

### System Information
+ Pencil2D Version: Nightly Build 2019-02-25 (69f034760d59e6e93e32d092bc016bbdbc797c3d)
+ Operating System: Windows 7 x64
+ RAM Size: 4GB
+ Graphics Tablet: the issue behaves the same with a mouse or tablet

**Comment by CandyFace** [comment]
I can't reproduce this, Shift+LMB dragging behaves as expected, no matter the tool I use.
CMD+LMB dragging too produces feather adjustment to brush tool.

**Comment by Jose-Moreno** [comment]
I can confirm this **does not** work on:
Version: 0.6.2
commit: 69f034760d59e6e93e32d092bc016bbdbc797c3d
date: 2019-02-25_11:13:47
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

So it's a windows problem so far.

**Comment by BugReporter-01** [comment]
Hope it could be fixed, especially since we don't have any shortcuts to change size and feather. (I know it's already [planned](https://github.com/pencil2d/pencil/issues/1016).)

Also, I've noticed that the Quick Sizing circle is displayed with the Paint Bucket Tool, but it doesn't seem to actually change any parameters. It's presented in 0.6.2 Stable also. That's not a nuisance, but is that a bug? Should I open a separate issue for it?

**Comment by chchwy** [comment]
I will have a look tonight.

**Comment by Jose-Moreno** [comment]
@BugReporter-01 Thanks submitting it as a separate issue would be helpful. We categorize those as "user experience" bugs so it would be low priority, but it definitely would help to have it submitted separately otherwise it might be forgotten.

**Comment by chchwy** [comment]
Please test the nightly build 26 Feb 2019

**Comment by Jose-Moreno** [comment]
Confirmed to be working on:
Version: 0.6.2
commit: ab160626bfc8d9acd923570b3373b50ccb7042ab
date: 2019-02-27_00:09:57
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by BugReporter-01** [comment]
@chchwy, it works for me too. Thank you for the quick fix.
