### ISSUE TITLE
"Reset to default" action modifies tool settings unexpectedly

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1183]
### Issue Summary

Resetting the tools to their current default values bring a few issues that can worsen the user experience.

I'll outline the tools most affected by this issue and open a separate report to request the that these defaults become unified and also sensible for any user.

**Pencil tool**
For this tool the antialias is turned off. Considering the Pencil tool antialias toggle was removed in previous versions it's very odd and undesired that the "reset to default" command makes the tool work with aliased strokes.

**Brush tool**
feather is set to 80, the slider widget max value is 64 whereas the spinnerbox max value is 80 however this doesn't render any pixel at all. Re-setting the value manually to 80 doesn't prompt this behavior so the problem lies with the "reset to default" command.

### Expected Results

Pencil tool should always be antialiased when resetting the tool defaults
Brush tool high feather value should not stop the tool from painting when using the reset command

### Steps to reproduce

1. Increase the size of the pencil tool. Make a reference stroke
2. Increase the size of the brush tool. Make a reference stroke.
3. Go to TOOLS >Reset to Default
4. Repeat step 1 & 2 and notice the difference between each. Pencil stroke will be aliased. Brush will not paint.

### System Information
+ Pencil2D Version:
Version: 0.6.2
commit: 69f034760d59e6e93e32d092bc016bbdbc797c3d
date: 2019-02-25_11:13:47
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by chchwy** [comment]
Please test the nightly build 1 March 2019
