### ISSUE TITLE
Unify tool settings for tools default reset and first time user experience

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1184]
### Issue Summary
As the title indicates, this is a request to unify the reset valies and the default values that users find when opening pencil2d for the first time.

|          | Antialias Toggle | Size | Pressure Toggle | Feather | Use Feather | Stabilizer | Bezier | Color Tolerance |
|----------|------------------|------|-----------------|---------|-------------|------------|--------|-----------------|
| Pencil   | N/A              | 8    | ON              | N/A     | N/A         | STRONG     | N/A    | N/A             |
| Brush    | ON               | 24   | ON              | 48      | ON          | NONE       | N/A    | N/A             |
| Eraser   | ON               | 24   | ON              | 48      | OFF         | NONE       | N/A    | N/A             |
| Pen      | ON               | 12   | ON              | N/A     | N/A         | STRONG     | N/A    | N/A             |
| Polyline | ON               | 8    | N/A             | N/A     | N/A         | N/A        | OFF    | N/A             |
| Bucket   | N/A              | N/A  | N/A             | N/A     | N/A         | N/A        | N/A    | 32              |
| Smudge   | N/A              | 24   | N/A             | 48      | ON          | N/A        | N/A    | N/A             |

**Note:** _all the sizes are given in pixels_

**Note**: The brush slider and spinnerbox widgets **max value** should be set equal to the max value for the size widgets. e.g currently 200px

**Comment by chchwy** [comment]
Please test the nightly build 1 March 2019
