### ISSUE TITLE
Quick Sizing enabled on Paint Bucket Tool, but does nothing

### ISSUE THREAD

**Issue by BugReporter-01** [pencil2d/pencil#1186]
### Issue Summary
With the Paint Bucket Tool selected it's possible to invoke the Quick Sizing interface, but it doesn't seem to actually change any parameters except the Dotted Cursor radius, although its radius doesn't represent anything related to this tool and probably shouldn't be displayed at all.

### Actual Results
With the Paint Bucket Tool selected `Shift+LMB Dragging` invokes the size-feather circle. It's possible to change the radius of that circle, but the tool parameters doesn't change. `Ctrl+LMB Dragging` also invokes the circle, but its radius couldn't be changed. Dotted Cursor is displayed, although not being useful.

### Expected Results
1. Quick Sizing should actually adjust the tool parameters (Color Tolerance), or be disabled for this tool.
2. Dotted Cursor probably shouldn't be displayed for the Paint Bucket Tool, since it doesn't represent any parameters of that tool. Compare with the Eyedropper Tool.

### Steps to reproduce
Ensure that `Dotted Cursor` and `Use Quick Sizing` options are enabled, select the Paint Bucket Tool, try to use Quick Sizing (`Shift+LMB Dragging` and `Ctrl+LMB Dragging`), and observe Dotted Cursor.

### System Information
+ Pencil2D Version: Nightly Build 2019-02-27 (dc86a40224fcf9c1e437534a9d3018e4391205a8), also checked on 0.6.2 Stable
+ Operating System: Windows 7 x64
+ RAM Size: 4GB
+ Graphics Tablet: the issue behaves the same with a mouse or tablet

**Comment by scribblemaniac** [comment]
I noticed this as well, and when I looked into it I discovered that the quick sizing does do something with the bucket tool: it changes the "Stroke Thinkness" parameter when using it on a vector layer. This property does not apply to bitmap layers so it is hidden when a bitmap layer is active. When using the tool with the bitmap layer, quick sizing should be disabled or adjust the color tolerance. Unfortunately with the way the current code for quick sizing is set up, I do not think either of these solutions will be easy to do.
