### ISSUE TITLE
Update checker fails to probe current version (0.6.3) and displays an error message

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1195]
### Issue Summary

It seems checking for updates in v0.6.3 prompts the user with an error message as it's trying to see if the current version is lower than itself.

### Expected Results

Ideally It should say something along the lines of "your version is up to date" when probing the current download version.

### Video or Image Reference

Candyface tested that the feature works in 0.6.2 (macOS) but he was using the Qt version.
![image](https://user-images.githubusercontent.com/4912907/54541811-9cf15980-4968-11e9-8d3c-3a1e8dd04386.png)

For for myself, on Windows using the release download version it hosts the error
![image](https://user-images.githubusercontent.com/4912907/54541857-b7c3ce00-4968-11e9-88cf-6aadbfa2f97f.png)

### Steps to reproduce

1. Go to the HELP menu
2. Press the "Check for Updates" action
3. Wait for it to populate the progress bar. It will show an error.

Note: If it doesn't report an error, please comment your operating system.

### System Information
+ Pencil2D Version:

Version: 0.6.3
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by scribblemaniac** [comment]
I cannot replicate this issue, this is what it looks like for me on the official v0.6.3 build on macOS:
![Screen Shot 2019-03-21 at 12 41 28 AM](https://user-images.githubusercontent.com/3461051/54736780-5d965900-4b72-11e9-98bc-120c14bc5a20.png)

Make sure that your internet connection is good and that you can open/download this file: https://github.com/pencil2d/pencil/releases.atom

And also make sure you don't have Godot open :wink:

**Comment by chchwy** [comment]
I probably know why.

The version check url is https
Qt needs two extra OpenSSL DLLs (`ssleay32.dll` and `libeay32.dll`) to establish HTTPS connections on Windows.

These 2 DLLs are not included in the Qt package, have to download separately at <http://slproweb.com/products/Win32OpenSSL.html>

A quick workaround is to use http instead of https.

**Comment by scribblemaniac** [comment]
Reopening, the fix was reverted to restore Windows build functionality. HTTP is being used instead currently on all systems as a workaround.

**Comment by Jose-Moreno** [comment]
Should we kick this back to 0.6.5 or 0.6.6 milestones?

**Comment by scribblemaniac** [comment]
Yes sure, we'll try to re-fix this for 0.6.5.

**Comment by chchwy** [comment]
Closing
