### ISSUE TITLE
Improve selected drawings rotation manipulation

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1197]
### Issue Summary

Rotating a selected drawing usually feels "jumpy". I noticed that the drag gesture needs to be done from the leftmost inner boundary of the selection to allow for more control. 

It seems (intuitively at least) that the horizontal distance between the leftmost boundary and the cursor position is used to calculate the rotation of the drawing, so the farther the cursor is, the wider the rotation angle. This is why when rotating from the top right most region of a selected drawing make it looks like the drawing "jumps" very noticeably.

**Update [20/03/2019]** I noticed that if you select the drawing by pressing CTRL+A the rotation does take the origin to be the center of the selection, so:

- **Manual Selection:** Origin is computed from where the selection was started (usually top-left but it can be top right / bottom right if you made the selection from right to left from either)

- **Automatic Selection**: Origin is computer always in the center of the selection so if you start grabbing from it it will correctly shift left or right, but starting from the boundaries will make the rotation jump.

### Expected Results

This is very annoying to be honest because 9 times out of 10 you will have to correct the rotation angle due to the huge shift in angle. 

Ideally the rotation of a drawing should work like the current rotation of the canvas view / camera view, where the cursor position is used to smoothly drag the drawing CW or CCW. 

I understand this may be because the selection "origin" starts at the top-left corner of any selection box, but when rotating the actual center depends on the drawing boundary it seems, so it doesn't make sense to have the origin and the rotation center be separate unless the user specifically wants that so they rotate a transformation cage instead that moves the drawing instead of the drawing bitmap surface itself.

This is worth discussing in the context of and when a proper transformation cage is implemented in order to have a true free transform widget that allows for moving, rotating, scaling, trasnforming corners freely or with a "perspective" constraint.

### Steps to reproduce

1. Open Pencil2D
2. Create a reference drawing (I always make an arrow)
3. Select the drawing
4. pick the move tool, and try to rotate the drawing from the right side region of the selection.
5. Undo the rotation
6. Now try to start your rotation from the leftmost part of the selection that's closer to the selection box. 
7. You'll notice that the selection is much more smoother, and you can control the rotation much better.

### System Information
+ Pencil2D Version:

Version: 0.6.3 (and below)
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by scribblemaniac** [comment]
@Jose-Moreno Please test this issue with the latest code, it should be fixed now with d1d29218d8d924b1b32ad088a8fab7ca872b15a4.

**Comment by Jose-Moreno** [comment]
@scribblemaniac Alright I tested this and indeed now the rotation is much more smoother than before. I can see that the rotation is following the cursor, which feels nice.

There is still one issue however that I failed to notice and report originally. IF you follow the same reproduction steps with the fixed version from source, when you release the mouse and click again, the rotation resets and starts rotation from the new point instead. In fact even if you release and press in the same spot you left off, the rotation gets reset to the initial state on each click & drag action.

I think it should be possible to save the current rotation, that is how much rotation has been temporarily applied in the rotation "modal" so people can keep rotating in whichever orientation they want. Normally if you're rotating large objects on the screen, your hand will get tired, and you'll stop and try to accommodate your arm to continue the motion, but once you resume the motion it will reset the rotation, which would be a completely frustrating experience for the user :yum: 

In the future (and a separate request) we should be able to see the "temp" rotation number in the status bar or a dedicated window that shows the transformation info once we implement a fully functional transform tool.

Other than that It's looking and working great!

**Comment by scribblemaniac** [comment]
@Jose-Moreno I have just modified it to behave as you described. The new changes are in #1226 because changing it in master would cause new conflicts with #1223.

**Comment by scribblemaniac** [comment]
@Jose-Moreno Can you please verify that this issue has been fixed?

**Comment by Jose-Moreno** [comment]
@scribblemaniac I'll test as soon as I'm able by today's evening. Thanks!

**Comment by Jose-Moreno** [comment]
@scribblemaniac Ok I tested the latest master (up to https://github.com/pencil2d/pencil/commit/5341b85338e14a6f8e048023d0a4f2d4eb0e20d4 ) And the original rotation issue seems to be completely fixed :tada: 

**However** something happened between 0.6.4 and current master where now the undo procedure reverts not only the transform but also the selection.

Even when you apply the transform, it reverts back to a step before the selection, so you can't undo inside the selection like before (and this is true for other transforms).

The real problem starts to surface with the current master undo / redo stack, mainly because undoing works fine with the new logic (the transformation is undone as it crunches both selection and applied transform steps) but when redoing you take more steps, or should I say the actual amount of steps, so you see the selection tool appearing now, moving to the position where the transform was (if moved) then you see the new transform you're redoing.

I'm not sure if this is a side effect of the improvement or an intentional behavior. Not sure if it's worth changing it again if the undo / redo will be replaced, but it is quite confusing to have mismatched number of steps of undo/ redo for simple transformations.

Do you want me to report this as a separate issue for a regression targeted for the upcoming release or what should we do in this case?

**Comment by scribblemaniac** [comment]
I don't think these changes would cause that issue. Alternatively, it could have been the selection refactoring. Anyway I think this should be brought up in the undo/redo branch document. There would be no point fixing it in master if we're going to replace all of that before the next release.

Thanks for testing. Closing this issue now!
