### ISSUE TITLE
Pencil2D 0.6.3 packaging update

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1200]
Hi!
We recently bumped Pencil2D to it's 0.6.3 release version, we are still waiting to emit the announcement, so If possible please help us update your respective ports, repositories and packages. If you need anything let us know :smile: 

- [x] **FreeBSD** @yurivict 
- [ ] **AUR (Arch Linux)** @J5lx
- [x] **Debian** @mapreri 
- [x] **RPM (Fedora)** @blackfile
- [x] **Homebrew Cask (macOS)** @scribblemaniac
- [x] **Flatpack** @eszlari 

If there's any other contributor or packaging that I'm forgetting please comment and i'll update the list right away.

_Updated list thanks to Scribblemaniac mindful guidance :wink:_

**Comment by blackfile** [comment]
Hi @Jose-Moreno Pencil2D 0.6.3 is currently in the testing period and should be available in 7 days.

More info https://bodhi.fedoraproject.org/updates/?packages=Pencil2D

Cheers!

**Comment by yurivict** [comment]
On 3/19/19 7:24 PM, Morr wrote:
>
>
> We recently bumped Pencil2D to it's 0.6.3 release version, we are 
> still waiting to emit the announcement, so If possible please help us 
> update your respective ports, repositories and packages. If you need 
> anything let us know 😄
>
>   * *FreeBSD* @yurivict <https://github.com/yurivict>
>   * *Debian* @mapreri <https://github.com/mapreri>
>   * *Flatpack* @eszlari <https://github.com/eszlari>
>

It was already updated in the FreeBSD a few days ago.


Yuri

**Comment by eszlari** [comment]
https://github.com/flathub/org.pencil2d.Pencil2D/commit/7d29d2e0298add6dbe509802bfa811eead212e98

**Comment by mapreri** [comment]
Thanks for the ping!  Debian is currently frozen for the upcoming stable release, so I'll upload this to experimental in the upcoming days. :)

**Comment by scribblemaniac** [comment]
For the record, the Homebrew Cask had already been updated.

**Comment by Jose-Moreno** [comment]
Thank you everyone for your reports and speedy updates, we'll keep this information in mind to address any related support query that we get. Pencil2D will keep moving forward and it's thank to all of your dedicated support and assistance. Have a great week! :smile:

**Comment by mapreri** [comment]
It seems the ChangeLog.md file was not updated for this release, the diff shows adding the info concerning 0.6.2; I think updating this file should go in whatever release checklist you are following, as updating the chagelog post release kind of defeats its purpose ;)

**Comment by mapreri** [comment]
(same for the readme; the released one should really point to the stuff concerning the new version)

**Comment by Jose-Moreno** [comment]
@mapreri You're right. I think only there's been a commit https://github.com/pencil2d/pencil/commit/977e142ec22cc58949b5c83ded55c3b63232170f made to update the README.md 4 hours ago. As I mentioned there was a bump to the newest version but we still haven't made the announcement that there's a new version available.

I personally just learned yesterday of this checklist https://github.com/pencil2d/pencil/wiki/Release-checklist which was shared to me when I made this issue to contact "every" maintainer. I hope that the next release can be a bit less bumpy, but since we've mostly focused our effort into thoroughly testing and making the release actually stable (so we wouldn't get burned by minor issues like what 0.6.2 had i.e the copy/paste problem) there are still pending issues to be addressed.

**Comment by mapreri** [comment]
Yup, I know everything is not yet perfect :)

BTW, uploaded to Debian experimental, will sync to ubuntu later!  https://tracker.debian.org/news/1035924/accepted-pencil2d-063-1-source-into-experimental/

**Comment by scribblemaniac** [comment]
Closing as this has been superseded by #1215.
