### ISSUE TITLE
Movie & Animated GIF export file extension missing in non-english locale

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1225]
### Issue Summary
There's been a few cases where the movie and animated GIF export have been reported not to work properly.

After investigating this issue I've found that there is a particular set of conditions that trigger this behavior.

1. The user must be using a non-english language locale. Although most of the users reporting this issue had Pencil2D set to use Spanish language localization (ES) it might be possible that other languages are affected by this.

2. All of the reports have come from users having Windows OS from versions 7 through 10. 
**Note:** _While it is possible that this issue can happen in other OS, so far this is the only one that has been reported._

When setting the locale to Spanish, and attempting to export either a movie or a GIF, what happens is that Pencil2D does not automatically append the corresponding extension. This causes ffmpeg not to be able to read what kind of filetype the user wants to export thus not exporting anything (which was the main reason behind the reports).

The current workaround provided to users is that they have to manually add the extension on the name prompt. However if you remove the extension from the file name, in the English language Pencil2D will automatically append it again, while in the Spanish localization it will not.

What I found is that when using either export option (movie, GIF) there is an additional separator added which is preventing the extension from being appended.

Export - English Locale [EN]
![image](https://user-images.githubusercontent.com/4912907/58768343-61c1f800-855f-11e9-8431-8ecbd55ce27c.png)

Removing the extension appends the filetype automatically
![image](https://user-images.githubusercontent.com/4912907/58768334-54a50900-855f-11e9-9e0f-e4f06120f376.png)

Export - Spanish Locale [ES]
![image](https://user-images.githubusercontent.com/4912907/58768358-af3e6500-855f-11e9-8b8d-befb774b275f.png)

Removing the extension does NOT append the filetype
![image](https://user-images.githubusercontent.com/4912907/58768370-e44ab780-855f-11e9-9f4f-327a9729fb76.png)

I've noticed this does not happen in the options dialog for image / image sequence export. I've been told their code base is also different from that of Movie and Animated GIF export dialogs.

### Expected Results
Regardless of language, Pencil2D should automatically append the filetype after the user types the filename in the OS file explorer when selecting a location to export.

### Steps to reproduce

1. Go to EDIT > PREFERENCES > GENERAL > Change the language to [Spanish]
2. Proceed to export either a movie or a GIF.
3. Press browse (buscar) button
4. When the file explorer opens, remove the extension from the name e.g untitled.mp4 > untitled
5. Press Save / Accept / Ok
6. Notice that the extension is now missing from the filename.

### System Information
+ Pencil2D Version:
Version: 0.6.3
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by Jose-Moreno** [comment]
We've identified that this problem happened due to incorrect whitespace added in the Spanish translation of the filetype (i.e `*. gif`, `*. mp4`, etc). This can be easily fixed in Transifex (our translation platform) but scribblemaniac proposed that we required a more definitive solution to avoid future mistakes made by the translators. For now we'll patch the translations and open a new issue afterwards for the string substitution enhancement that was proposed.

**Comment by Jose-Moreno** [comment]
fixed by https://github.com/pencil2d/pencil/commit/220a27a06756bc524230211c7b80a9183eac6d23

**Comment by niebert** [comment]
This problem is reproducible on MacOSX 10.12.6 with an english language in Pencil2D 0.6.4 english Pencil2D User Interface and german setting of  the operating system.

**Comment by scribblemaniac** [comment]
@niebert Yes this has been fixed since 0.6.4. Unfortunately 0.6.5 is not currently available for your OS version. This issue can be worked around by manually adding the ".gif" extension.
