### ISSUE TITLE
Keyboard shortcut conflict

### ISSUE THREAD

**Issue by setanarut** [pencil2d/pencil#1228]
### Issue Summary
"Move Frame Backward" and "Preferences" have the same shortcut as Default

### Actual Results
"Preferences" doesn't open by default when I press the shortcut **⌘,**
 "Move Frame Backward" is activated.

### Expected Results
"Preferences" must be default when i press **⌘,**
 

### Video or Image Reference

![aa](https://user-images.githubusercontent.com/36481442/59887349-b1137f80-93cb-11e9-9667-35fee8a35ce9.jpg)

 

### System Information
+ Pencil2D Version:
Version: 0.6.4

 

+ Operating System:
macOS Mojave (10.14)
CPU Architecture: x86_64
 

+ RAM Size:
8GB

**Comment by Jose-Moreno** [comment]
@hazar-e Hi. By default Preferences does not have any assigned any keyboard shortcut. However please let us know if it did come like that for your mac version download so one of our mac devs can review if there is a conflict in the source code.

Other than that you can change the hotkey by going to Pencil2D Menu > Preferences > Shortcuts > Preferences and change the hotkey to something more appropriate.

![image](https://user-images.githubusercontent.com/4912907/59887907-ccaa6600-938a-11e9-9682-84a58fc722dd.png)

**Comment by hazar-e** [comment]
hi @Jose-Moreno i have macbook pro 2016 Turkish Q Keyboard
<img width="690" alt="Ekran Resmi 2019-06-21 02 56 22" src="https://user-images.githubusercontent.com/36481442/59888411-3bf67900-93d0-11e9-8cb8-957c4790bca2.png">

⌘, shortcut is the standard "Preferences" shortcut for All Apps on MacOS
**MoveFrameBackward** should be different shortcut by default.

<img width="220" alt="Ekran Resmi 2019-06-21 02 47 43" src="https://user-images.githubusercontent.com/36481442/59888275-a0fd9f00-93cf-11e9-8876-cfc2860ee9c0.png">

<img width="595" alt="Ekran Resmi 2019-06-21 02 42 49" src="https://user-images.githubusercontent.com/36481442/59888311-c4c0e500-93cf-11e9-9700-6a23fe5bcb67.png">

**Comment by scribblemaniac** [comment]
I can confirm this issue, the preferences shortcut is always command+',' on mac and Qt sets this automatically so there is likely very little we can do to remove it (maybe there is some OS-specific hack). I remember having the same issue a long while ago. The obvious workaround is to simply change the MoveFrameBackwards key to something else. Changing the Preferences shortcut will not change it to something else. Personally I use [ and ]  for GotoNextFrame and GotoPreviousFrame respectively, and then command+[ and command+] for the corresponding move frame actions. I would be in favor of changing it, but we'll see what the other devs think.

**Comment by CandyFace** [comment]
If Qt sets the preferences shortcut by default and we can't change it, then we should consider removing the key in shortcuts, or call it something different like "alt to preferences" for alternative shortcut to access preferences.

As for the goto next and previous keys, what @scribblemaniac suggested is fine with me.
