### ISSUE TITLE
macOS dark mode not detected automatically

### ISSUE THREAD

**Issue by hazarek** [pencil2d/pencil#1229]
### Issue Summary

1. Pencil2D does not automatically detect macOS dark mode. requires terminal command to be activated.
`defaults write org.pencil2d.Pencil2D NSRequiresAquaSystemAppearance 0`

2.  **Background Color,**  **Timeline** colors and **About window** are not compatible with dark mode.

 

### Video or Image Reference
About window

![Jun-21-2019 02-32-37](https://user-images.githubusercontent.com/36481442/59888888-69dcbd00-93d2-11e9-90b5-c33ceefd723b.gif)

Timeline and Background color
<img width="1050" alt="Ekran Resmi 2019-06-21 02 33 48" src="https://user-images.githubusercontent.com/36481442/59888915-811baa80-93d2-11e9-9ea4-41a72b39ef35.png">

### System Information
Pencil2D Version: 0.6.4
Operating System: macOS Mojave (10.14)
CPU Architecture: x86_64

**Comment by scribblemaniac** [comment]
Dark mode should be detected automatically on macOS Mojave and newer. Let's focus only on that issue here. The other issues are not mac-specific and have already been discussed in #550.

Pencil2D does not set the NSRequiresAquaSystemAppearance property, so it should follow whatever the default is on your system. Can you please share the output of this command:
```
defaults read NSRequiresAquaSystemAppearance
```

**Comment by CandyFace** [comment]
Qt is still not fully dark mode compatible, I've already reported one issue to the Qt team about this. https://bugreports.qt.io/browse/QTBUG-72486

We can workaround the issue by manually styling the widgets for now.

**Comment by hazar-e** [comment]
ok sorry. i am using dark mode always, i am big fan of dark mode. you can close this known issue.

**Comment by CandyFace** [comment]
So are we but there are things of higher priority to be made first :)
We'll keep the issue open until the issues has been fixed.

**Comment by J5lx** [comment]
What exactly is needed for this issue to move forward? A reply about the dark mode detection problem? Bug fixes in Qt’s dark mode support? The about dialog as well as the timeline have already been fixed a while ago.
