### ISSUE TITLE
Fps text-box focus issue

### ISSUE THREAD

**Issue by hazar-e** [pencil2d/pencil#1230]
### Issue Summary
sorry my english

If the canvas is not clicked, the fps change is not accepted and cursor is blinking

![Jun-21-2019 18-44-28](https://user-images.githubusercontent.com/36481442/59934635-ae10a180-9454-11e9-823c-03ae3a10a1b2.gif)

 

### Actual Results
I set the **R** key for **Play** I change fps and press enter and the cursor hangs and playback does not work.

<img width="269" alt="Ekran Resmi 2019-06-21 18 49 12" src="https://user-images.githubusercontent.com/36481442/59935082-a8678b80-9455-11e9-98a3-62ff23572562.png">

### Expected Results
Fps change should be accepted when enter or other keys are pressed.
 

### Steps to reproduce

1. Set **R** shortcut for **Play**

2. Change fps with this box;
<img width="85" alt="Ekran Resmi 2019-06-21 19 00 44" src="https://user-images.githubusercontent.com/36481442/59935657-f16c0f80-9456-11e9-99d9-52b2ed297c00.png">

3. Press **Enter**

4. Press **R**

 

### System Information
Pencil2D Version: 0.6.4
Operating System: macOS Mojave 10.14.5 (18F132)
CPU Architecture: x86_64

**Comment by scribblemaniac** [comment]
Fixed in #1253.
