### ISSUE TITLE
[ISSUE] The Quick Sizing Tool does not work properly

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#1234]
### Issue Summary

When checking the **_Use Quick Sizing_** (on Preferences Panel) it doesn't work on the whole canvas
 

### Actual Results
The Quick Size tool only works on the middle of the canvas.
 

### Steps to reproduce
Open Pencil2D as default. Select any drawing tool and lay down the pen in the middle of the canvas. When using the Quick Sizing (CTRL+Drag Left/Right) the size tool will jump to "1" when dragging Left, and "200" when dragging right, while resizing correctly in the middle of the canvas. 
 

### System Information
+ Pencil2D Version:
NightlyBuild 02JUL2019

 

+ Operating System:
Win8.1x64bits
 

+ RAM Size:
32GB
 

+ Graphics Tablet:
Huion HD185

**Comment by Jose-Moreno** [comment]
@Kaikogf I can confirm this behavior under Windows 7 while using both tablet and mouse on the latest nightly build, in 0.6.4 stable release it is working as intended though, I wonder what happened :sweat_smile:

**Comment by Jose-Moreno** [comment]
[2020] This keeps happening in the latest nightly builds & master branch to date.

**Comment by scribblemaniac** [comment]
This has been closed because the quick sizing should work anywhere on the canvas now. However I believe there were still some issues with controlling it in the latest version that I will try to fix at some point (soon hopefully).
