### ISSUE TITLE
no se puede exportar un archivo

### ISSUE THREAD

**Issue by isaacsanchezcaldron** [pencil2d/pencil#1236]
### System Information
+ Pencil2D Version:

 

+ Operating System:

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by Jose-Moreno** [comment]
@isaacsanchezcaldron Hola. Por favor al menos escribe la información que se solicita en la plantilla. De otra forma es muy dificil verificar si es un error del programa que ya esta solucionado o algún problema nuevo...

Igual si no se está seguro de que sea un error porfavor primero consulta los foros de pencil2D en http://discuss.pencil2d.org

Si no te exporta archivos de pelicula o secuencia de imagenes, te encuentras usando Windows10 y tienes  habilitada la localización del programa en español, es probable que el problema radique en que al guardar el nombre y la ubicación del archivo no se este aplicando la extension automaticamente. 

Normalmente el nombre del archivo debe salir así antes de exportar:

![image](https://user-images.githubusercontent.com/4912907/61196660-d8413200-a695-11e9-9d42-f503a9625e93.png)

Sino, debes agregar la extensión explícitamente en el explorador de archivos que abre Pencil2D desde el cuadro de opciones para exportación, así:

![image](https://user-images.githubusercontent.com/4912907/61196675-eee78900-a695-11e9-9e1f-b8060e35b11c.png)

Por favor confirma los detalles de la plantilla y si estos pasos resuleven tu problema, de otra manera este reporte se considerará nulo y será cerrado pronto. Saludos.

**Comment by isaacsanchezcaldron** [comment]
si me sirvio gracias

**Comment by Jose-Moreno** [comment]
This was related to #1223 and #1224
