### ISSUE TITLE
I cant open sounds!

### ISSUE THREAD

**Issue by klooooom** [pencil2d/pencil#1239]
### Issue Summary
I downloaded a sound and I can't upload it.
 

### System Information
+ Pencil2D Version:

 

+ Operating System:

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by Jose-Moreno** [comment]
@klooooom A few considerations:

1. To import a sound go to the top bar menu and use `File > Import > Sound ` This will prompt you to create a new sound layer if there's not one already created.
2. If you already had a sound layer in Pencil2D, you have to select it first before importing the sounds.
3. Pencil2D supports WAV and MP3 files, however for now please use WAV files. If you're on windows it seems that some rare mp3's do not work, so please convert them to WAV using a free audio editor like Audacity http://audacityteam.org
