### ISSUE TITLE
extract adjustingTool and featherAdjustingTool to their own tools

### ISSUE THREAD

**Issue by wesen** [pencil2d/pencil#124]
To make the code in scribbleArea a little bit cleaner, and maybe to reuse it for other tools.

**Comment by Jose-Moreno** [comment]
Closing this after 6 years of inactivity. scribbleArea has been changed a lot over the years and I've been told the functions mentioned here no longer exist. Thank you for your assistance in the past and for helping out with Pencil2D. Good luck!
