### ISSUE TITLE
Timeline update issue after applying transformation

### ISSUE THREAD

**Issue by CandyFace** [pencil2d/pencil#1250]
### Issue Summary
![test](https://user-images.githubusercontent.com/1045397/63458266-cb60ec80-c452-11e9-8761-6c6a153e08c8.gif)

### Actual Results
As shown In the gif, after following the same steps and clicking the add keyframe button, no keyframe is being visually added (though it's there) until you click next to the frame or does something that initiates a timeline render update.

### Expected Results
The timeline should be updated and the new keyframe shown no matter the condition if you press add keyframe.

### Steps to reproduce
1. Create a selection
2. Transform the selection
3. Move the cursor to the timeline and click on an empty spot on the same layer.
4. Apply the transformation
5. Click add keyframe (on the timeline)

result: timeline hasn't updated and therefore shows no new keyframe.

**Comment by davidlamhauge** [comment]
I have done a heavy debugging of this today, and I can't fix this.
Everything seemingly works. The new keyframe is created, Pencil2D emits the updateTimeLine() signal, the Layermanager recognizes the new keyframe. Only problem is that it is not shown on the timeline, until the next scrub.
I'm out of ideas.

**Comment by CandyFace** [comment]
@davidlamhauge you say that updateTimeline is emitted, but it the actual paintEvent() method called in TimelineCells when that happens?

**Comment by davidlamhauge** [comment]
@CandyFace the paintEvent() method is called, but can you tell me the number of line in TimeLineCells where frame should be painted?

**Comment by CandyFace** [comment]
@davidlamhauge we draw the frames in Layer::paintFrames, which is called from Layer::paintTrack which is called from TimeLineCells::DrawContent which is called from TimelineCells::paintEvent

**Comment by davidlamhauge** [comment]
Ok @CandyFace the drawContent is NOT called. This if-sentence (line 417) stops it.
```
    bool isPlaying = mEditor->playback()->isPlaying();
    if ((!isPlaying && !mTimeLine->scrubbing) || mCache == nullptr)
```

**Comment by scribblemaniac** [comment]
`TimeLineCells::mouseReleaseEvent` isn't getting called because of the modal dialog popup. Based on my cursory look at the issue, it's not going to be an easy fix. We have to make sure scrubbing still works, but that it asks the user before switching to any other frames (otherwise the transformation will show up on those frames and potentially get applied on a new frame). Probably the easiest thing to do would be to apply the transformation automatically, skipping the dialog completely, at least when changing frames.

**Comment by Kaikogf** [comment]
@CandyFace 
I followed your description of the issue and it is working OK on my windows 8,1

**Comment by Jose-Moreno** [comment]
I can confirm this happens consistently with the provided reproduction steps in Windows 10 on the latest nightly build (2020-01-09)

@Kaikogf The way to make it happen is that you have to apply the transformation only using the warning that appears after clicking on the timeline. 
That is, you select the drawing, move the selection and then click on the timeline to move the playback indicator.
After that a warning will appear, if you press "Yes" and apply the transformation, immediately create a keyframe, the keyframe is created, but the timeline is not updated.

Can you test again with this consideration? Thanks 🙇

**Comment by Kaikogf** [comment]
@Jose-Moreno 
I tested it again and the issue is appeared as you described :+1:     Not sure what happened before
