### ISSUE TITLE
onion skin effect in ubuntu only between keyframes

### ISSUE THREAD

**Issue by pentatheus** [pencil2d/pencil#1266]
I have never used pencil2d so i dont know if the skin effect must work this way or not, but it seems strange, i  am not even a designer and never used a skin effect before.

I tried to use the forum to ask but it failed in my registration: We cannot detect if your account was created, please ensure you have cookies created. And no email received.

Could you say if this is normal?, i see that onion seems that only work if it cant reach the previous keyframe, if the previous keyframe distance in frames to my current frame is greater than the number of onion frames i cant see the onion skin effect.

![Peek 2019-09-17 17-36](https://user-images.githubusercontent.com/47463891/65058454-8efeae80-d974-11e9-8ff1-e3d3ac3cb0bb.gif)

I have tested this with same results in 
stable version
pencil2d-linux-2019-07-03.AppImage
pencil2d-linux-2019-09-10.AppImage

i am using
Linux version 5.3.0-10-lowlatency (buildd@lgw01-amd64-010) (gcc version 9.2.1 20190905 (Ubuntu 9.2.1-7ubuntu2)) #11-Ubuntu SMP PREEMPT Mon Sep 9 16:01:51 U
TC 2019

Thx and sorry if this is the way it must work.

**Comment by davidlamhauge** [comment]
@pentatheus What I see is the expected behaviour.
Onion skins are explained in this video
https://www.youtube.com/watch?v=jrWae4vX2WM

**Comment by pentatheus** [comment]
Thx @davidlamhauge , i close the thread then.
