### ISSUE TITLE
[ISSUE] when closing the ABOUT window 

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#1273]
### Issue Summary

 
When closing the "About" information window, it will draw a line on the canvas

 

 

### Steps to reproduce
Open pencil2D 
Make a small dot on the canvas and go to the main bar and open the About window  > HELP > ABOUT

Move the ABOUT window far from the dot you just draw. Close it hitting the “OK” button. Result: The window will close and no lines or strokes will appear on the canvas

Open pencil2D again > draw a dot > open the ABOUT window > move it far from the dot > and now close the window hitting the "X". A line will be draw between the dot and the last "X" position
This happen when using a pen tablet. With mouse it is OK

 

### System Information
+ Pencil2D Version:
Build pencil2D last code (01OCT2019)

 

+ Operating System:

 
Windows 8,1 x 64bits

+ RAM Size:
32GB
 

+ Graphics Tablet:
HUION 185HD

**Comment by scribblemaniac** [comment]
There are similar issues with the dialog that comes up when you try to modify a hidden layer. This might be fixed by #1269 because of the modifications to how tablet and mouse events are handled.

**Comment by Jose-Moreno** [comment]
@Kaikogf @scribblemaniac I've tested this with Jan 9th build. The mentioned issue doesn't seem to occur in my case, however I can't close the about dialog by pressing the [X] button when using a stylus.

Can you test this? If it happens to you as well we'd make a new bug report for that issue separately and close this one as fixed.

**Comment by scribblemaniac** [comment]
I cannot reproduce this either with Linux 19.10 + Huion H430P.

**Comment by Kaikogf** [comment]
@Jose-Moreno 
I cannot reproduce your [X] issue. I tested this with the last build [25fev2020] and there is no sight of the issue. I am closing this and if you experience an issue you can open a new post as you suggested.

Thanks! :+1:
