### ISSUE TITLE
Partial file wipe when dragging keyframes

### ISSUE THREAD

**Issue by scribblemaniac** [pencil2d/pencil#1280]
### Issue Summary

Dragging keyframes on the timeline appears to cause them to be lost in some circumstances.

### Actual Results

Please see the Steps to reproduce for details, but basically when dragging frames and then saving, sometimes these frames are not reloaded next time the file is opened.

### Expected Results

Obviously the frame's contents should remain the same no matter where on the timeline it is.

### Steps to reproduce

1. Load a file with many bitmap frames all together at the beginning.
2. Do not play the project or view any frames other than the first one.
3. select all the frames on the timeline for the bitmap layer.
4. Click and drag those frames one one frame to the right.
5. Save the file (maybe it has to be with Save As?).
6. Close Pencil2D.
7. Reopen the file.
8. Observe that some of the frames you have dragged are blank.

### System Information
+ Pencil2D Version: v0.6.4

+ Operating System: macOS 10.13. Currently I can't reproduce this on Linux but I can reproduce it 100% on macOS.

+ RAM Size: 16 GB

+ Graphics Tablet: None

---

### Technical Details

When dragging non-dirty frames, the images should be renamed in the temporary directory rather than saved from memory. However it seems that only frames that are not in the cache are being wiped, which suggests that it is still trying to save it from memory.

**Comment by scribblemaniac** [comment]
Alright I have some more information on this now. I was having a lot of difficulty reproducing this, but I should have listened to myself: "Currently I can't reproduce this on Linux but I can reproduce it 100% on macOS." This appears to be a macOS only issue. In addition to that, this will only cause issues when the .app bundle is used rather than running the executable file inside of it directly. This means that you cannot reproduce this by using the Qt Creator "Run" button or by executing `Pencil2D.app/Contents/MacOS/pencil2d`. This also means that it is going to be very difficult to view debug messages for this.

[Here is a project file and a video](https://github.com/pencil2d/pencil/files/3833609/Archive.zip) demonstrating exactly how I reproduced the issue with that project. That video is with v0.6.4, but I have also confirmed that this has not been fixed in the latest nightly build, or by manually building the latest master (90e7164349d8d542bc2e96a546716ac5d9156883) with either Qt Creator's flags or the CI flags, and with or without macdeployqt and macdeployqtfix.

**Comment by Jose-Moreno** [comment]
@scribblemaniac So would this mean that what the Windows users have been reporting is yet another issue related to the raw file / drawings disappearance? sigh :weary:

**Comment by scribblemaniac** [comment]
As a followup, I was able to reproduce this bug in Windows 10 so it very well could be the cause of the many issues that have been reported for it lately.

Closed by 4cde4da529ce6f1af5a0340f369d01b0eac322b3. With this I hope we will be rid of the dreaded file wipe once and for all.
