### ISSUE TITLE
EDITED: DeleteCurrentLayer shortcut under PreferencesPanel doesnt work

### ISSUE THREAD

**Issue by ghost** [pencil2d/pencil#129]
Last build 30July
Win7 64bits

Assigning a shortcut keyboard for the feature "DeleteCurrentLayer" doesn't work and the letter shortcut doesn't appear on the Main Menu-> Layer, after having customized it.

But deleting a Layer does work if going directly to the Main Menu bar--> Layer --> DeleteCurrentLayer

**Comment by Jose-Moreno** [comment]
@feeef @tasaif @chchwy This bug still exists in ** Nightly Build Jan 15 2016**

**Comment by CandyFace** [comment]
Fixed in PR #658.

Closing.
