### ISSUE TITLE
Hang opening animation

### ISSUE THREAD

**Issue by hugmax** [pencil2d/pencil#1291]
### Issue Summary
After 2 days making an animation,. 24Mb  file, the program hangs when I try to open it.

 

### System Information
+ Pencil2D Version:
0.6.4
 

+ Operating System:
win 7
 

+ RAM Size:
16Gb
 

+ Graphics Tablet:
Bamboo

**Comment by Jose-Moreno** [comment]
@hugmax Hi. It would be nice if you could share the problem project file so developers can inspect why this should be happening.

Also if possible can you let us know some more details? Like:

- how big is the resolution size (e.g 1920 x 1080)
- how many frames there are
- how many layers

As far as I have experienced, Pencil2D tends to take more time saving than loading. But if you have really big images, it will take a long time loading regardless of your computer specs.

I too use Windows 7, so if there is a specific issue with your file I can help the devs to debug it and find what problem exists.

**Comment by hugmax** [comment]
I installed the latest beta and imported the project file layers one by one...
the error was at the sound files, it had multiple files, I just combined all the sound files and the project is now working fine.
this is the file.

[https://gofile.io/?c=LvcZ1A]

**Comment by Jose-Moreno** [comment]
@hugmax Thank you for your report! Hmm, can you let us know a few more things?

1. How many sound files were there in total? 
2. Also were all the sounds placed in the same layer or were they placed in multiple sound layers? This actually makes a difference as I'm aware that there was an issue that occurred when there were many sound files in a single layer, but this was fixed.
3. Were the sounds either `.wav` or `.mp3`? There are some mp3's that are still using patented codecs in the web, so this can make them not sound at all when using Pencil2D or other open-source applications, but one of them could have caused the hang.
4. Did the sounds names have any special character? something like #$%°! or accents for languages like french or spanish? e.g êâîûô / àèìòù / áéíóú / etc.

Thanks again for taking the time to comment as this helps narrowing down the problems. :pray:

**Comment by hugmax** [comment]
cheers
br
