### ISSUE TITLE
Play button shows tooltip as "Start"

### ISSUE THREAD

**Issue by yu-tang** [pencil2d/pencil#1300]
https://github.com/pencil2d/pencil/blob/91951c56ee28acb4d4ffc8e50d3da4bbfaf612fe/core_lib/src/interface/timecontrols.cpp#L194

**Comment by Jose-Moreno** [comment]
Hi thank you for reporting this. 

I noticed that In the editor the tooltips show normally when Pencil2D is initialized. "Start" being the leftmost button.
![image](https://user-images.githubusercontent.com/4912907/70393972-3ad8f880-19be-11ea-8975-74854e9c748c.png)

![image](https://user-images.githubusercontent.com/4912907/70393980-49bfab00-19be-11ea-8e96-91f75ad67e58.png)

However when you press play the first time once the playback is happening the button changes state to either "Start" (before playback) and "Stop" (during playback)

![image](https://user-images.githubusercontent.com/4912907/70394076-42e56800-19bf-11ea-9385-da4c4eb4a46c.png)

![image](https://user-images.githubusercontent.com/4912907/70394078-4ed12a00-19bf-11ea-9335-182238989890.png)

I personally agree that this tooltip should at least revert back to "Play" to be consistent with the initial behavior.
