### ISSUE TITLE
White screen lookin like a stick [BUG OR ISSUE]

### ISSUE THREAD

**Issue by GlamosFoxil** [pencil2d/pencil#1305]
The white screen isnt showing up its just going up like an stick but not a full screen
![Screenshot_1](https://user-images.githubusercontent.com/59926693/72447554-63e16b80-376a-11ea-9fa8-cbecf4ae4673.png)

**Comment by davidlamhauge** [comment]
Looks odd @GlamosFoxil . Never seen it before. Looks like you've set camera size width to 10?
What does it say if you double-click on the camera layer? (the gray part of the layer).

**Comment by Jose-Moreno** [comment]
@GlamosFoxil I'm in the same opinion of David, seems like your camera width became too small.
Note that you're always looking "through" a virtual camera towards an pseudo infinite paper.

For quick assesment you can turn the camera off by clicking the small grey dot on the left hand side of the camera layer. if everything turns white, it means you hid the camera viewfinder succesfully.

Press the grey dot again to turn the layer back on, then double click your camera layer to change the size of the camera to a more sensible size and report back if this worked for you or not so we can close this.

**Comment by davidlamhauge** [comment]
If  not @GlamosFoxil has more to say, I think we can close this again?

**Comment by CandyFace** [comment]
Agreed, closing until more info has been given or we can confirm whether it's a bug or not.
