### ISSUE TITLE
Rotating Tool

### ISSUE THREAD

**Issue by marcello257** [pencil2d/pencil#131]
Is it possible to rotate an object on a second level bitmap, without rotating automatically an object on the first bitmap level.

As an example:

A person is walking (bitmap level 1) with a hamer (bitmap level 2)in his hand .

En because his arm/ hand is moving while he walks the hamer is rotating a bit.

This is not possible in pencil on the moment because if the animator rotate the hamer (on level 2) het also rotate the person on level 1.

**Comment by tinwelint** [comment]
+1 on this feature

**Comment by chchwy** [comment]
Already implemented (Select an area and use move tools with Ctrl+drag)
