### ISSUE TITLE
I am not able to enter Pencil's forum. My antivirus is blocking the page

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#1312]
Kaspersky is blocking the entire forum. It has to do with a validation license. It expired day 25th of Feb

**Comment by chchwy** [comment]
I can't get into the forum, too.

**Comment by J5lx** [comment]
I'm super sorry about that and it's fixed now. My certificate renewal setup on that server isn't working nearly as well as is should and I'm going to replace it with one that's working more reliably.

**Comment by chchwy** [comment]
@J5lx thanks for the quick fix. :D

**Comment by Kaikogf** [comment]
Thank you @J5lx ... Now it is ok
