### ISSUE TITLE
Polyline Tool lost visual update during line creation

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1320]
### Issue Summary

Polyline tool is not visible when creating a line. It only appears after confirming the operation (pressing Enter / Return) or double clicking.

When using the tablet, it sort of blinks briefly but it's still not visible.
When using mouse it never appears until the line is confirmed and dumped onto the canvas.

### Expected Results

The polyline tool should still show when creating the line, otherwise it is difficult to know what you are drawing.

Note: This is just a thought, but I've noticed that **changing visibility modes** during the line creation period, **visually updates the polyline tool representation**, in fact if you change it continuously by pressing one of the shortcuts, you can see it updating at that rate, so i'm wondering if any of that code could be effecting the polyline tool?

### Video or Image Reference

Pending Update

### Steps to reproduce

1. Create a new file
2. Select the polyline tool
3. Click and try to create a line.
4. Notice the missing representation.

### System Information
+ Pencil2D Version:

Nightly build

commit: 7b0d1134d2853e4371c3cc8e3dd021ed00f2cf64
date: 2020-03-19_18:05:15

Operating System: Windows 10 Pro (v1909)
CPU Architecture: x86_64
Qt Version: 5.12.6

+ Graphics Tablet:

Driver: 6.3.38-2
Device: Intuos5 PT S
Model: PTH-450
Version: 1.0.7.109

**Comment by scribblemaniac** [comment]
I've already fixed this, I just forgot to push the changes. It will be done soon.

**Comment by scribblemaniac** [comment]
Fixed with b94f1313e3e02329caebd3524530e472cb58a566
