### ISSUE TITLE
Selection tool resets camera frame visually when zooming

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1321]
### Issue Summary

I discovered this by accident. Using the selection tool resets the position, tilt and scale of the camera frame as if you had a way to temporarily invoke CTRL + H as a modifier.

This only seems to happen when zooming in or out. And it only affects the camera frame representation, not the actual drawing nor any camera motion interpolation.

### Expected Results

You should be able to use the selection or any other tool normally without the camera frame area resetting itself as this creates visual confusion.

### Steps to reproduce

1. create a new pencil2d file
2. Select a the bitmap layer
3. zoom out with the mouse wheel or using the hand tool
4. choose the selection tool
5. Simply click on the canvas and drag a selection
6. Notice how the camera frame is reset.

### System Information
+ Pencil2D Version:

Nightly build

commit: 7b0d1134d2853e4371c3cc8e3dd021ed00f2cf64
date: 2020-03-19_18:05:15

Operating System: Windows 10 Pro (v1909)
CPU Architecture: x86_64
Qt Version: 5.12.6

**Comment by scribblemaniac** [comment]
Please try to reproduce this issue with the latest code. I suspect it has been fixed.

**Comment by davidlamhauge** [comment]
I can't reproduce on my Ubuntu 18.04.

**Comment by Jose-Moreno** [comment]
@scribblemaniac I tested this using the latest master code and the latest nightly build under Windows 10. Fortunately I couldn't reproduce it so good job! I'd say this particular issue is fixed then 😄 

Now the only zoom related issue that's open is #1286 which is related directly to #1169 which strangely was fixed before, but i keep having the exact same behavior as that one in the compiled & nightly build versions and even with the same reproduction steps using CTRL + RMB & CTRL + MMB with any tool including the hand tool 😔 

While testing this though I noticed that when using the hand tool, pressing MMB immediately and permanently switches to the selection tool behavior (but not the icon) in both builds 😓  Want me to open a new issue for the latter?

**Comment by Jose-Moreno** [comment]
Since David tested this under Linux Ubuntu, I'll close this as fixed, if anyone knows exactly which commit fixed it let me know to edit this comment.

**Comment by Jose-Moreno** [comment]
@scribblemaniac Ugh, I have to reopen this I found by accident the same problem but it seems to be activated with different reproduction steps and it happens using both selection and move tools. 

Can you test if you have the same issue as well?

1. Reopen Pencil2D (this is important as it seems after the bug activates i can't reset it otherwise to default state)
2. Pan the canvas (this is only to see the comparison)
3. Create a selection. Note nothing happens.
4. Now Pan the canvas again.
5. Use the selection tool. Now you'll see the camera painter jumping to the previous "state"

I noticed that after activating the bug, if i create a new file and use the selection tool, Pencil2D will show me what i saw on the canvas on the previous file as a ghosted image. So it's like the states are not being properly reset after this.

The other way to invoke this is:

1. Reopen Pencil2D (this is important as it seems after the bug activates i can't reset it otherwise to default state)
2. Draw something
3. Create a selection over the drawing. Note nothing happens.
4. Pick the Move Tool and move the selection. Click outside to deselect the drawing. Marquee disappear
5. Click with the move tool in an empty space. Now you'll see the camera painter jumping to the previous "state". IT happens as well with the selection tool after the previous steps.

**Comment by Jose-Moreno** [comment]
**Closing**
Fixed via https://github.com/pencil2d/pencil/commit/97963e80231ee3ccb1b37e3e4577fb59c9619f97
