### ISSUE TITLE
New layers should become automatically selected after creation

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1327]
### Issue Summary

This is something that I've been thinking for a long time. Seems like a minor issue but this should lead the user to not second guess themselves during an intense workflow.

The idea is that any action should always put the user in a state where they are aware of the UI and how to use it.

Creating a new layer should make this new layer selected because you are creating it with the purpose of using it next. Even if you create many layers (e.g bitmap) at the same time to use them later, the last one that was created should be your starting point to work on your animation.

Currently creating a layer leaves the selection focus on the original layer, and when you start drawing you expect that it's actually the new one that's selected.

**Comment by davidlamhauge** [comment]
Totally agree.
Before we got the more saturated colors in the timeline, I often added a new layer and started animating, and then realizing that I was animating on the wrong layer.
Are you going to code this yourself @Jose-Moreno ? I'm sure you call pull it off.
If not, I would like to do it.

**Comment by CandyFace** [comment]
Agreed, it's also a common behavior in other programs. You create a layer because you want to work on it, so it doesn't make sense that it's not being selected after creation.

**Comment by Jose-Moreno** [comment]
@davidlamhauge I was simply reporting for now. I'm not sure how I would tackle this as I've never meddled with the code in a complex way. I did notice an issue with the onion skin panel and the previous / next shortcuts, so since that was my responsibility I'll probably help with that instead. 

If you want to tackle this, by all means go ahead. Either way it's a necessary enhancement we all could benefit from 😄
