### ISSUE TITLE
Image sequence export incorrectly adding extension

### ISSUE THREAD

**Issue by scribblemaniac** [pencil2d/pencil#1330]
### Issue Summary

Under some circumstances, the image sequence export will add ".png" in the wrong place and when it is not needed. The number may also be inserted in the wrong place.

### Actual Results

When I go to export an image sequence and choose a new filename or location, it will mess up the naming of the files. It's easier to say what's happening with an example. If I set the name to `test.png`, it will save as `test.png<number>.png`. However, if I go to export that same file sequence again without changing the filename, it will export as `test<number>.png`. This is particularly problematic when you just want it to export as `<number>.png`, because it will instead export as the hidden file `.png<number>.png`.

### Expected Results

The behavior should be the same whether a new file name/location is specified or not. It should only add an extension if one does not already exist, and it should always insert the number before the extension.

### Steps to reproduce

1. Go to File > Export > Image Sequence...
2. Press change the file location and name.
3. Press OK
4. Observe where it has been exported to.
5. Repeat steps 1, 3, and 4, but not 2.

### System Information
+ Pencil2D Version: Nightly Build 2020-03-30_13:30:35 AppImage (d1add7b12ad464ede3e6e303d98a65db9a5edb41)

+ Operating System: Ubuntu 19.10

+ RAM Size: 16 GB

+ Graphics Tablet: N/A

**Comment by Jose-Moreno** [comment]
Confirmed under Windows 10 v1909. By following the reproductions steps I get two different image sequences:
+ [name][.png]<number>.png 
+ [name]<number>.png
