### ISSUE TITLE
GIF Animation Export - no file generated - MacOS Sierra

### ISSUE THREAD

**Issue by niebert** [pencil2d/pencil#1336]
### Operating System: MacOSX Sierra 

GIF-Animation export does not create file. Process bar runs for up to 50%, Then the processbar vanishes and not file appears in the filesystem. No error message was generated.

### Issue Summary
GIF Animation Export - no file generated on MacOSX Sierra

**Comment by Jose-Moreno** [comment]
@niebert Hi. Would you mind letting us know which version of Pencil2D you're using? If you can please go to **Help >About** and use the `[Copy to clipboard]` button to get this information and paste it in your reply.

If by any chance you don't have this button your Pencil2D version might be older than the required minimum we currently support and we encourage you to upgrade it as having an older version will leave you to suffer from several critical issues that have been fixed already.

By default your problem could be related to various scenarios, so when entering the **Animated GIF** export dialog, make sure to inspect the following:
1. The file location path is accessible on your computer. e.g. If you are saving to network drives or an external server with drive mapping try to save in the desktop or a documents folder you can easily access.
2. The filename has an appended filetype (e.g myAnimation.gif) //Note: If there is no filetype, please add it manually by using the `[Browse...]` button.
![image](https://user-images.githubusercontent.com/4912907/79500738-8ea1c100-7ff2-11ea-95f1-8f63240cbb6b.png)

3. The Start and End frame are properly assigned to match with your first and last keyframes (this should be automatic but it doesn't hurt to check)
4. That, if you have more than one camera layer, the camera layer you are using corresponds to the one you require to frame the action.

We'll be pending your response so we can have more information to properly asses this issue.

**Comment by niebert** [comment]
Version: 0.6.4
Operating System: macOS Sierra (10.12)
CPU Architecture: x86_64

**Comment by Jose-Moreno** [comment]
@niebert We're going to close this since after 4 1/2 months there been no additional input regarding the troubleshooting recommendations that were issued.

In principle GIF export is working for all platforms, and usually when something that is tested heavily doesn't work it is most likely due to very specific problems with our users work environment (or else, in this case, all other macOS sierra users would be complaining too).

While using a relatively older macOSX version could lead to potential issues with the export plugin the dev team is not aware of, unless you provide us with more feedback, it's hard to look for these problems since we don't have legacy versions of the operating systems we support at our disposal.

If you keep having this problem, please comment again on this thread and we'll reopen the ticket.

**Comment by niebert** [comment]
No worries, if that is not a common problem, I am fine, all the best, Jose

**Comment by Jose-Moreno** [comment]
@niebert Hi. Happy New Year. Actually in the past 2 months or so we found a wave of people using legacy macOS versions with similar problems and we had a lot of progress in finding the issue (as well as looking into solutions).

For now the following issue https://github.com/pencil2d/pencil/issues/1543 has been opened to track this problem with older macOSX versions. Included in the description there is an advanced workaround in case you want to try them out (e.g compiling FFMPEG for your specific system, along the link to a guide by another user found in the Pencil2D forums)

I put a "never forget" tag on this one in case we have more updates I can share later on directly, or at least when we find a definite solution. For now thank you for your patience and best wishes for 2021.

**Comment by niebert** [comment]
For us as computer scientist it is easy to compile FFMPEG. May be the workaround for a standard users would be to export to a sequence of images from Pencil2D and [generate the animated GIF with ImageMagick](https://webinista.com/updates/how-to-create-animated-gifs-imagemagick/) or other tools the users know for generating animated GIF.  It is good that exporting into list of images works fine with Pencil2D and the generation of the animation in Pencil2D is well done. Congratulations. I guess it procides standard users a good tool to start working with animation on the authoring side. BTW I added Pencil2D to the [Wikiversity Learning Resource about 2D animations](https://en.m.wikiversity.org/wiki/2D_Animation/Open_Source_Software). Thank you for your feedback. Best wishes for 2021, Bert
