### ISSUE TITLE
vcruntime140_1.dll missing

### ISSUE THREAD

**Issue by DaveLampton** [pencil2d/pencil#1337]
### System Information
+ Pencil2D Version: Nightly build 13 April 2020

 

+ Operating System: Win10Pro_x64 v1909

 

+ RAM Size: 16 GB

 

+ Graphics Tablet: n/a

**Comment by Jose-Moreno** [comment]
@DaveLampton  Hi Dave, thank you for your report. This is a common issue for Windows users who might not be receiving widows updates regularly.

This DLL file should come with Visual Studio Runtime distributables. So firstly can you try running the `vc_redistx64.exe` installer that comes bundled with Pencil2D?

You can find this in the same folder where you unzipped the program.

If by chance you can't find it there and are missing any other files, please take some time to read through this guide I specifically put together for Windows 10 users.

https://discuss.pencil2d.org/t/guide-how-to-train-your-pencil2d-windows/4106

It's important that you "unblock" the file and then unzip it properly so all the necessary ingredients are unpacked. Once you do then try installing the file i mentioned and see If Pencil2D runs.

If not please reply with your results so the devs can investigate this problem further.

**Comment by Jose-Moreno** [comment]
[2020] Closing this as the answer with the solution was already provided in the previous comment but the OP didn't provide further feedback. 

For reference these kind of issues are Windows related, and while Pencil2D only provides some relevant components, the best course of action is to download the specific missing components installer either via Windows Updates or directly from Microsoft's website.
