### ISSUE TITLE
Build error with qt-5.15.0 - src/graphics/bitmap/bitmapimage.cpp:615:41: error: ‘path’ has incomplete type

### ISSUE THREAD

**Issue by benkohler** [pencil2d/pencil#1370]
Build against newly released qt-5.15.0 fails.

> x86_64-pc-linux-gnu-g++ -c -include .obj/core_lib -O2 -pipe -march=native -std=c++11 -fPIC -std=gnu++11 -D_REENTRANT -Wall -Wextra -DAPP_VERSION=\"0.6.4\" -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050600 -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Isrc -Isrc/graphics -Isrc/graphics/bitmap -Isrc/graphics/vector -Isrc/interface -Isrc/structure -Isrc/tool -Isrc/util -Isrc/managers -Isrc/external -Isrc/external/linux -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtMultimedia -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I.moc -isystem /usr/include/libdrm -I.ui -I/usr/lib64/qt5/mkspecs/linux-g++ -o .obj/bitmapimage.o src/graphics/bitmap/bitmapimage.cpp
src/graphics/bitmap/bitmapimage.cpp:615:41: error: ‘path’ has incomplete type
  615 | void BitmapImage::drawPath(QPainterPath path, QPen pen, QBrush brush,
      |                            ~~~~~~~~~~~~~^~~~
In file included from /usr/include/qt5/QtGui/qtransform.h:43,
                 from /usr/include/qt5/QtGui/qimage.h:48,
                 from /usr/include/qt5/QtGui/qpixmap.h:49,
                 from /usr/include/qt5/QtGui/qpainter.h:48,
                 from /usr/include/qt5/QtGui/QPainter:1,
                 from src/graphics/bitmap/bitmapimage.h:21,
                 from src/graphics/bitmap/bitmapimage.cpp:17:
/usr/include/qt5/QtGui/qmatrix.h:54:7: note: forward declaration of ‘class QPainterPath’
   54 | class QPainterPath;
      |       ^~~~~~~~~~~~
make[1]: *** [Makefile:1494: .obj/bitmapimage.o] Error 1

**Comment by chchwy** [comment]
Hey @benkohler, thanks for reporting.
I have added the missing header file in f6173dd91. Can you pull and compile again?
