### ISSUE TITLE
Sudden new issues with tools distorting lines with tablet computer.

### ISSUE THREAD

**Issue by pocketbrows** [pencil2d/pencil#1396]
### Issue Summary

I've been using pencil2D for a while now and haven't had much of an issue when it comes to drawing/writing before, but for some reason it's been acting up on me and now I can't seem to write clearly unless I go incredibly slowly and fully lift my stylus up into the air between letters. (i.e, not hovering over the screen but not touching it so that the cursor shows up but doesn't draw, but like fully lifting it so the cursor disappears). 
I have a tablet computer with a built in stylus, and my lines seem to come out distorted if I go too quickly. Sometimes the issue happens even when I'm not drawing quickly. It also seems to like to draw a straight line sometimes coming off of where I begin drawing, and doing circles or round shapes too quickly produces incredibly jagged shapes.

What strikes me as really odd is that this issue wasn't happening before to this degree, if at all. I have no idea why it suddenly started behaving strangely, I wasn't doing anything different than I normally do on my computer. 
 

### Actual Results
Lines turn out sharp and jagged with angles or divots/indents appearing when they shouldn't.
 

### Expected Results
A line that looks like how I drew it, like how it looks in other programs.
 

### Video or Image Reference
![bug issue](https://user-images.githubusercontent.com/68365512/87627908-6c086c80-c6f5-11ea-8954-5037471d586a.PNG)
Writing comparison. I used the basic microsoft snipping tool to screenshot and write, for comparison.

![demo 2](https://user-images.githubusercontent.com/68365512/87629196-2d27e600-c6f8-11ea-810a-d28bc3b1bafe.PNG)
Drawing circles. White circles are drawn in Pencil2D, blue ones in snipping tool.

![demo3](https://user-images.githubusercontent.com/68365512/87629254-49c41e00-c6f8-11ea-9346-074472f1ede5.PNG)
Opened a new document, the distortion isn't quite as bad as it is on the project I was working on, though still quite distorted.

![demo4](https://user-images.githubusercontent.com/68365512/87629686-1afa7780-c6f9-11ea-908f-892789667080.PNG)
When drawing, the issue isn't as apparent, and drawing slower seems to minimize distortion. Doing circular shapes quickly seems to really cause major issues, however, as is seen in the left side of the tree leaves. 

![demo5](https://user-images.githubusercontent.com/68365512/87630535-eab3d880-c6fa-11ea-822f-3c6a88d875b6.PNG)
This is the result of me drawing a very fast circle.
 

### Steps to reproduce
Open Pencil2D and draw a line or shape at moderate to quick pace.
 

### System Information
+ Pencil2D Version:
Version 0.6.4
 

+ Operating System:
Windows 10
 

+ RAM Size:
8 GB
 

+ Graphics Tablet:
Tablet/touchscreen computer: Lenovo ThinkPad Yoga 14

**Comment by chchwy** [comment]
Hey @pocketbrows, thanks for reporting.
Can you please download nightly builds and see if you still have the issue?

https://www.pencil2d.org/download/#nightlybuild

**Comment by Jose-Moreno** [comment]
@pocketbrows Along with what chchwy suggested, please also take a moment and review our Windows 10 guide here for various general tips that will definitely affect your Pencil2D use on that OS https://discuss.pencil2d.org/t/guide-how-to-train-your-pencil2d-windows/4106

And please read this reply on the forum related to similar a issue and test out the steps in the guide that are similar and possible with your touchscreen drivers. Most likely however **enabling compatibility with Windows 7** for the Pencil2D.exe will do the trick, but if it doesn't please let us know, as it's important for troubleshooting the root cause.

https://discuss.pencil2d.org/t/pencil2d-automatically-creates-straight-line-when-i-put-my-drawing-pencil-on-it/4465/2

**Comment by pocketbrows** [comment]
Installing the nightly build fixed the problem, thank you!
