### ISSUE TITLE
crash on linux during playback + camera pan

### ISSUE THREAD

**Issue by mikshaw** [pencil2d/pencil#140]
Make a couple of frames, set playback to loop, and play.
Then switch to camera layer, select hand tool and drag a bit (I was attempting to frame the animation with the camera).
It won't necessarily crash right away, but within a few drags it will.

I also experienced a crash a couple of times in WindowsXP while testing this, but not while dragging. Only after i tried to close the program (still during playback) that it crashed. I haven't been able to reproduce it.

Debian Sid x86_64, Qt 4.8.5
Windows XP, SP3 virtual machine, July30 nightly build of Pencil.

**Comment by Jose-Moreno** [comment]
@mikshaw @feeef In Windows 7 Ultimate SP1 64 bits, Nightly Build from JAN 15 2016 does not crash when dragging the camera view after using the hand tool while the animation playback is looping, nor it crashes when trying to exit the program while the playback is looping.

However we need to have in mind that the camera interpolation function was removed, that means that moving the camera with the hand tool, does not create new frames automatically, nor stores position changes between keyframes.

Also the software does not have an exit dialog working as reported in #282 and #387 

I think it's not possible to reproduce this bug unless these two features become active again, so what do you think we should do here, do we keep this, or should we close this?

**Comment by CandyFace** [comment]
If the feature that produced the bug isn't active or has been removed, then the issue itself is invalid. I'm closing this for now. When/if the this issue becomes should come back, feel free to make a new post or comment here again, then'll re-open it.
