### ISSUE TITLE
[ISSUE] When first adding a new layer the system will add a wrong name

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#1414]
### Issue Summary
as example, there is NO sound layer on the timeline:
When importing an audio (File > Import > Sound...) we are asked to create a new sound layer. The windows property's panel will pop-up showing **Sound Layer** as its default name. After hitting OK, the system will add a sound layer with the name **Sound Layer 2**

### Actual Results

It is added a wrong default name

### Steps to reproduce
File > Import > Sound > Let its default name **Sound Layer** on the property panel and hit OK  
Then select a WAV sound track and hit enter. The layer will be created with the name **Sound Layer 2**

NOTE: this issue will also happen when creating a new bitmap or vector layer instead

### System Information
+ Pencil2D Version:
last version (v0.65) 

+ Operating System:
Windows 10 

+ RAM Size:
32GB

+ Graphics Tablet:
Huion HD 185

**Comment by Jose-Moreno** [comment]
I can confirm this issue under Windows10. When adding a new layer of a certain type for the first time, the counter starts automatically at 2, and if you delete the previously default layers and create them anew, the naming scheme also falters.

When creating a new file after using a default startup preset with no layers (except the default camera layer) creating a new layer of any other type exhibits the same behavior. The name field upon layer creation shows the proper name, but the created layer changes the name by adding a number as if it was duplicated somehow.

Seems like the initial index for layer types always starts from 1 and not from 0.
