### ISSUE TITLE
CanvasPainter incorrectly showing elements from previously selected frames & layers

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1426]
### Issue Summary

Using the selection tool in specific ways will break the canvas painter into showing selected elements on incorrect layers, frames and even new files. This behavior is also affecting the onion skins once it becomes broken. The issue also happens when clicking with the move tool after using the selection tool.

Basically these are the three main problems that stem form this issue:
1. Problem between keyframes (noticeable with onion skins; can't properly align frames due to missing skins when clicking)
2. Problem between layers (noticeable with/without layer opacity)
3. Problem between files (noticeable when creating new files)

Note: Input hardware is not a factor. This problem occurs regardless of mouse or tablet being used.

### Expected Results

Transforming selections with or without onion skins on different layers should not render previously selected elements to avoid confusion for the user.

### Video or Image Reference

https://youtu.be/-o0M9mDTegU

### Steps to reproduce

Between Keyframes
1. Create a New file (Important as it's possible any minute selection on a previous file has already affected the behavior)
2. Turn on onion skins to see the problem more clearly.
3. Draw something for reference on keyframe 1
4. Create a second keyframe and draw on it as well
5. Choose a keyframe (it can be the first) and place the playback header on the frame
6. Create a selection anywhere you want, doesn't have to be on top of the content.
7. [Optional] You can test leaving the selection enabled or hiding it, it doesn't seem to matter, but could help debugging.
8. Move to the other keyframe and create a selection or click with the move tool. You'll notice the previous keyframe onion skin disappears.
9. Go back to the first keyframe and create a selection or click with the move tool. You'll notice the second keyframe does NOT disappear.

Between Layers
1. Create a New file (Important as it's possible any minute selection on a previous file has already affected the behavior)
2. Turn on layer visibility: relative to see the problem more clearly.
3. Draw something for reference on the first bitmap layer available on keyframe 1
4. Create a second bitmap layer and draw on it as well.
5. Choose a layer keyframe (it can be the first) and place the playback header on the frame
6. Create a selection anywhere you want on the chosen layer, doesn't have to be on top of the content.
7. Move to the other layer and create a selection or click with the move tool. You'll notice the other layer content disappears.
8. Go back to the first keyframe and create a selection or click with the move tool. You'll notice the second layer does NOT disappear.

Between Files
1. After following either of the reproduction steps for keyframes or layers go to File > New 
2. Pick the selection tool or the move tool and click on the canvas. You'll see the figure of the previous file that was prone to disappearing appear on the canvas of the new file.
3. If you double click with the move too, it gets even fixated on the canvas for a while until you click again

### System Information
+ Pencil2D Version:

Version: 0.6.5

commit: 50a0c7c318f38988af85d34e955a5a78d3953474
date: 2020-08-01_01:32:15

Operating System: Windows 10 (10.0)
CPU Architecture: x86_64
Qt Version: 5.12.9

**Comment by CandyFace** [comment]
I can confirm that this will be fixed again when #1471 has been applied
