### ISSUE TITLE
Import layers from PCLX keeping reference to the layer object instead of copying on successive import

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1427]
### Issue Summary
When you use the `Import Layers from PCLX` feature if you want to import a certain layer more than once (for example when importing a walk cycle for looping) your first reflex is that when you open the import dialog and load the reference project file, you can select a layer and press "import layers" as many times as you want. However doing this will load the same object as a reference into new layers and when you move one of them, the others move as well.

While this could be interesting for a future development where we can finally have multiple instances of a file inside another file, in the current workflow it's not ideal as you want to manipulate the layer objects separately even if they are referencing the same resources.

If you import the layer once, close the dialog and invoke the import dialog again this problem will not occur and the layer will be imported as a new layer object..

### Expected Results

Importing the same layer multiple times in a single import action is valid and the layer objects that are created are independent form each other.

### Video or Image Reference

https://youtu.be/0e3CNoYIL3I

### Steps to reproduce

1. Create a file with any given amount of frames and save it as PCLX (PCL doesn't work at the moment)
2. Create a new file
3. Go to File > Import > Import Layers from PCLX...
4. On the dialog load the PCLX you created in step 1
5. The layer section will be populated. Select the layer that has the keyframes
6. Press the import button once but **don't close the dialog**! Notice that the layer has been imported into the Pencil2D project.
7. Now press import layers two more times (this is only to see the effect clearly, you can only import it once more if you want)
8. Close the dialog
9. Now select a keyframe in any of the imported layers, now you'll see that the other layers are selected on the same keyframe. If you select multiple keyframes this will be visible on all imported layers. And if you move them all the layer keyframes will move accordingly.
10. After some time, if you mess up and move the keyframes erroneously, Pencil2D might crash so be careful.

### System Information
+ Pencil2D Version:
Version: 0.6.5

commit: 50a0c7c318f38988af85d34e955a5a78d3953474
date: 2020-08-01_01:32:15

Operating System: Windows 10 (10.0)
CPU Architecture: x86_64
Qt Version: 5.12.9

**Comment by Jose-Moreno** [comment]
I forgot to mention that if you import the same layer various times like in the reproduction steps, so the layer object is instanced multiple times, and you go to `File > New`, Pencil2D will crash consistently.

**Comment by davidlamhauge** [comment]
When I made this, I couldn't see why anyone would want to import the same layer twice. That's why I didn't discover the bug.
I've assigned myself, and will look into it soon.
