### ISSUE TITLE
Implement [Reset Windows to Default] action

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1437]
### Issue Summary

After various reports of people missing their panels and having trouble when they can't get them back after troubleshooting, I think it's time to consider having an action command that resets the window layout to that of the **first time experience** for pencil2d users. While we have one that resets back to the **previous state** having an option to simply start from scratch would be ideal.

**Comment by CandyFace** [comment]
Should be fixed via 4eea365
