### ISSUE TITLE
Expose pending old and new functionality in the shortcut list

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1444]
### Issue Summary

****
|File>Import|File>Export|Edit|Animation|Tools|Layer|Windows|
|---|---|---|---|---|---|---|
|Image Predefined Set|Animated GIF|PegBar Alignment|Range|Reset to Default|Change Line (Pixel) Color|Lock Windows|
|Movie Import|   |   |   |   |   |   |
|Animated GIF|   |   |   |   |   |   |
|Layers from PCLX|   |   |   |   |   |   |
|Movie Audio|   |   |   |   |   |   |
|Append Palette|   |   |   |   |   |   |
|Replace Palette|   |   |   |   |   |   |

_**Note**_ `CmdPreview ALT + P` What is this? It doesn't seem to work, does this exist in preparation for the preview feature that was discussed before?

### System Information
+ Pencil2D Version:
Version: 0.6.5

commit: 50a0c7c318f38988af85d34e955a5a78d3953474
date: 2020-08-01_01:32:15

Operating System: Windows 10 (10.0)
CPU Architecture: x86_64
Qt Version: 5.12.9

**Comment by HeCorr** [comment]
CmdPreview indeed doesn't seem to do anything from what I can tell. it was added by 18ecc6b989df41489383c8081784c847a86ef609 in 2014.

There is [preview.cpp](https://github.com/pencil2d/pencil/blob/eba8d6db44a31ce9574bb76076b90bbbe64b81c9/app/src/preview.cpp) which is from the same year and seems to be abandoned, I assume they are related.

Let's ask @chchwy since he was the one who added it.

**Comment by chchwy** [comment]
> CmdPreview indeed doesn't seem to do anything from what I can tell. it was added by [18ecc6b](https://github.com/pencil2d/pencil/commit/18ecc6b989df41489383c8081784c847a86ef609) in 2014.
> 
> There is [preview.cpp](https://github.com/pencil2d/pencil/blob/eba8d6db44a31ce9574bb76076b90bbbe64b81c9/app/src/preview.cpp) which is from the same year and seems to be abandoned, I assume they are related.
> 
> Let's ask @chchwy since he was the one who added it.

The preview window was made to display the entire canvas when a user zooms in a lot, gives an overview of the whole canvas. As I recall it was once working on my branch but never made it into production.

**Comment by HeCorr** [comment]
> The preview window was made to display the entire canvas when a user zooms in a lot, gives an overview of the whole canvas.

Oh, sort of like a mini-map? That does sound useful!

> As I recall it was once working on my branch but never made it into production.

Then what's the plan for this feature going forward?
Part of what I'm doing in #1866 is removing unused shortcuts, so let me know if I should leave this one alone.
