### ISSUE TITLE
Movie audio import on existing empty keyframe fail under specific conditions

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1448]
### Issue Summary

If you try to import a movie audio on an existing keyframe created by either the sound import feature or by using the `Add Keyframe` actions, will lead the movie audio import to fail.

### Expected Results

Regardless of origin or feature set, it is expected that any kind of sound will be allowed to be imported in a sound layer at any given empty frame.

There seems to be a mismatch between how the Movie Audio and Sound files are treated inside Pencil2D, which should be happening considering those are converted after import AFAIK.

### Video or Image Reference

![image](https://user-images.githubusercontent.com/4912907/91683822-46a3b680-eb1b-11ea-8550-eac58b6e8658.png)
_Movie Audio not loading on empty keyframe created by the sound import / add frame actions_

### Steps to reproduce

1. Open Pencil2D
2. File > Import > Sound > Create a new layer when prompted > Once the file browser opens press **`Cancel`**. Note there's a keyframe created on frame 1
3. File > Import > Movie Audio >Browse for an mp4 or support movie file > Press **`Open`**
4. A loading bar will appear but note that the movie audio will not be loaded into the timeline and the keyframe will remain empty.

**Checking that the movie audio > sound file workflow is possible**

1. Open Pencil2D
2. Create a sound layer (movie audio does not automatically create one)
3. File > Import > Movie Audio >Browse for an mp4 or support movie file > Press **`Open`**
4. Movie audio is loaded. Now press the **`Remove frame`** button
5. File > Import > Sound > Browse for a sound sample > Press **`Open`** . Note that the sound will be correctly loaded into the keyframe container. However.
6. Now press the **`Remove frame`** button again.
7. Try to load the previous Movie Audio, and you will not be able to.

### System Information
+ Pencil2D Version:
Version: 0.6.5

commit: 50a0c7c318f38988af85d34e955a5a78d3953474
date: 2020-08-01_01:32:15

Operating System: Windows 10 (10.0)
CPU Architecture: x86_64
Qt Version: 5.12.9

**Comment by Kaikogf** [comment]
@Jose-Moreno 

Following your initial steps, I found a BUG.

Open Pencil2D
File > Import > Sound > Create a new layer when prompted > Once the file browser opens press Cancel. Pencil2d will close unexpectedly. 
Error showed:
E:\PENCIL2D\pencil-master\pencil2d-Desktop_Qt_5_9_0_MinGW_32bit-Debug\bin\pencil2d.exe exited with code 3 
File > Import > Movie Audio >Br


Using the last development build from 11thSet
Windows 10
