### ISSUE TITLE
Sound import creates unwanted keyframe before importing audio sample

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1449]
### Issue Summary

Whenever you use the **File > Import > Sound** feature a new keyframe will be created before the actual sample is imported (just after the file explorer window appears), there's also inconsistent behavior when using the `Add frame` action on a sound layer, since canceling the file browser without importing a sample, will actually erase the previously created keyframe.

If you press the action by mistake, or you decide to go back without importing a sound, this keyframe will later become a stepping stone for a nastier bug found in issue #1448

This does not happen when using the **File > Import > Movie Audio** feature.

### Expected Results

Do not create a sound keyframe until you have actually decided to import a sound file (after pressing `Open`)

### Video or Image Reference
|**Before Import**|**During Import**|
|---|---|
|![image](https://user-images.githubusercontent.com/4912907/91684032-d47fa180-eb1b-11ea-8df6-ce241df45b90.png)|![image](https://user-images.githubusercontent.com/4912907/91684049-e9f4cb80-eb1b-11ea-9816-39c252267c24.png)|

### Steps to reproduce

**Empty keyframe creation when importing sound**

1. Open Pencil2D
2. File > Import > Sound
3. Create the sound layer you are prompted to
4. When the file explorer opens, note that a single keyframe will be created on the sound layer
5. If you press **`Cancel`** the empty keyframe will remain in the timeline.

---
**Empty keyframe creation when using the `Add Frame` action**
1. Open Pencil2D
2. Create the sound layer you are prompted to
3. Press the `Add frame` button on the timeline widget
4. When the file explorer opens, note that a single keyframe will be created on the sound layer
5. If you press **`Cancel`** the empty keyframe will be erased form the timeline

### System Information
+ Pencil2D Version:
Version: 0.6.5

commit: 50a0c7c318f38988af85d34e955a5a78d3953474
date: 2020-08-01_01:32:15

Operating System: Windows 10 (10.0)
CPU Architecture: x86_64
Qt Version: 5.12.9

**Comment by scribblemaniac** [comment]
Note that empty keyframes created by this technique will causes issues with movie exporting. Although the export bug is technically separate from this, it should be fix along with this, or perhaps even before this bug is fixed so that it can be easily tested.
