### ISSUE TITLE
\pencil-master\core_lib\src\structure\filemanager.cpp:361: error: C4716: "FileManager::writeToWorkingFolder": must return a value

### ISSUE THREAD

**Issue by libaineu2004** [pencil2d/pencil#1460]
### Issue Summary
Compile error!!
\pencil-master\core_lib\src\structure\filemanager.cpp:361: error: C4716: "FileManager::writeToWorkingFolder": must return a value

 

### System Information
+ Pencil2D Version:
master,As of 2020/09/10

 

+ Operating System:
Win10 x64, VS2017, Qt5.12.9 x64

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by chchwy** [comment]
Thanks for reporting. Fixed.
