### ISSUE TITLE
Overlay guides causing visual problems with active selections

### ISSUE THREAD

**Issue by libaineu2004** [pencil2d/pencil#1461]
### Issue Summary
Windows 10, run the program, and then click Menu-Tools-Select to select a rectangle.

There is a docked window called'DisplayOption' with a button overlayCenterButton (Tooltip: Overlay shows field center) inside. When I clicked this button, there was a problem with the selection tool. The position of the rectangle drawn would be abnormal and the coordinates would be incorrect.

If you do not click this button, it is normal.

 

### Steps to reproduce
It's easy to reproduce the problem. You don't need to do anything. 
Just open the software, first click the 'overlayCenterButton',then select the 'select button' on the toolbar, click on it, and drag a rectangle in the main view. The problem appears.The position of the rectangle is incorrect.

 

### System Information
+ Pencil2D Version:
master,As of 2020/09/10

 

+ Operating System:
Win10 x64, VS2017, Qt5.12.9 x64

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by libaineu2004** [comment]
> This works perfect in our official release 0.6.5, so the issue must have been introduced since that release.
> it it the same error with all four overlay buttons.

Yes. The 0.6.5 version is correct, but there is a problem with the master version.

**Comment by Jose-Moreno** [comment]
I tested this with the most recent commit using MinGW 7.3 and Qt 5.14.1. I have the same issue. The selection is getting offset by pressing any of the overlay icons.

I also tested the latest nightly build compiled with commit: 09190a77649b69a7e5497768a1544762bfaf6e23 and this one does not exhibit this problem.

The only commit that stands out as being related to the canvas painter in recent history is fed7e6fa5038b55226d868fd8aa7ee62dad776a3 which was meant to fix your other bug report #1453 

I tested this commit and the the one before to compare, and i'm certain this commit introduces the issue. 

Thanks to this i also discovered another problem related to the overlays as well as the camera size itself when other layers are selected after transforming the camera. I'll report later.

**Comment by Popolon** [comment]
Sorry for the duplicate, I didn't found this one.

Just an information, as this could help. There was a bug similar, but not the same in Mypaint branch few weeks ago, there was a shift (+ a zoom) in selection, perhaps only a zoom then, when vector layers was deleted. CandyFace resolved this issue.

https://discuss.pencil2d.org/t/mypaint-version-pre-alpha-preview/1185/150

**Comment by Popolon** [comment]
I found another one, related to layers, with about the same shift than the previous one, in mypaint branch. In both case there are a shift depending on layers. The shift is about the same distance than the mainline branch, but in this case of this one this is for selection.
https://discuss.pencil2d.org/t/mypaint-version-pre-alpha-preview/1185/174

**Comment by CandyFace** [comment]
Should be fixed via 7a45f975758da14e896518d5f091b0ae4a4c0c50
