### ISSUE TITLE
Polyline draw in Vector mode

### ISSUE THREAD

**Issue by DIane-Kivi** [pencil2d/pencil#1462]
**If you draw a polyline, then draw another, the first line vanishes until the second draw process is complete! This is disconcerting and makes multi line drawings difficult to draw. The problem only occurs with polyline draw function.**

 

During the drawing process only the polyline being draw appears on screen ### Actual Results

 

All previous poly lines to be displayed ### Expected Results

 

Vector ### Video or Image Reference

 

draw more than 1 polyline on a frame

### System Information
0.6.5 + Pencil2D Version:

 

Windows 10 + Operating System:

 

8 GB RAM Size:

 

None + Graphics Tablet:

 

Work around use version 0.6.4 for poly line drawing operations

**Comment by CandyFace** [comment]
This should be fixed via the linked PR that is awaiting.
