### ISSUE TITLE
[BUG] When playing with the MoveTool on vector layers, the strokes will move outside of the selected area

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#1464]
### Issue Summary
When using vector layers and drawing some lines and moving those lines to a different location on the same frame, those lines (or whatever you have draw initially) will start to move away from the selected box when, and only when you hit the pen inside the selected box. And depending how much you move the selection, the strokes will be throw away from the canvas view

### Expected Results
The strokes  should remain inside the selected box
 

### Steps to reproduce
Open Pencil2D
Select vector layer and the PenTool
Draw some lines all to the left side of the canvas
Select those lines using the SelectTool and then select the MoveTool
Move the selection all to your right, 
Hit inside the selection: the lines will disappear. They were actually throwed away to your right the same distance that you move the selection box. Zooming out will check that
 

### System Information
+ Pencil2D Version:

 

+ Operating System:
Win 10
 

+ RAM Size:

 
HUION tablet
+ Graphics Tablet:

**Comment by Jose-Moreno** [comment]
I can confirm this happening also in.

Nightly Build Sep  4 2020

commit: 09190a77649b69a7e5497768a1544762bfaf6e23
date: 2020-09-05_00:07:49

Operating System: Windows 10 (10.0)
CPU Architecture: x86_64
Qt Version: 5.12.9

Some additional comments.

If you click and drag immediately the strokes won't be offset to the right side. However if you click on the selection without moving, they will be offset regardless.

The offset only happens after attempting to reposition the strokes, not before and this offset is proportional to the displacement you applied while moving the vector strokes.

**Comment by J5lx** [comment]
A video recording of this bug was posted in #1541: https://popolon.org/depots/bugs/vokoscreenNG-2020-11-21.vector_objects_move.webm

**Comment by Kaikogf** [comment]
Same issue behaviour after the new improvements [Pencil2d 9thDec2020]

Just recap: After "Move the selection all to your right" (described above), all the lines "disappear".
If "Move the selection a little bit to your right" instead, it will  displace the selection to the right outside of the Select Tool's box.

**Comment by J5lx** [comment]
Have you built Pencil2D yourself from my fixes/vector-move-shift branch (#1547) or are you using a nightly build / build from the master branch? The fix is still pending review, so it hasn’t made its way to the nightly builds yet.

**Comment by Kaikogf** [comment]
That's why, I am using the nightly build here. 👍
