### ISSUE TITLE
[UX] When undocking panels, some are lost with the background 

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#1466]
### Issue Summary
With this image we can see the issue I wanted to explain: After undocking all tool panels into the canvas I noticed just two of them had a well defined outlines, _ColourPallete and OnioSkinPanel_. The rest of them are mixed with the white canvas and had their contour almost lost since their main colour were also white.

It seems very easy to do what I am proposing next: to outline all panels to have a distinctive and clear shape against to any colour or background 

![pencil2d](https://user-images.githubusercontent.com/28032931/93118272-ef274e00-f6b7-11ea-896b-fb98060fa84d.jpg)

**Comment by J5lx** [comment]
That screenshot of yours looks very wrong to me. Distinguishing windows from what’s behind them should be the job of the window manager, not the job of Pencil2D (or any other “classic” application, for that matter). On Windows, those windows should at least have a shadow to distinguish them from what’s behind them, like this:

![Screenshot 2020-12-07 190045](https://user-images.githubusercontent.com/2063777/101387659-0b094d00-38bf-11eb-8f27-2c58be561a5a.png)

Please try opening the Windows settings app and go to System → About. In the “Related settings” section, select Advanced system settings. Then, in the “Performance” section of the window that appears, press the “Settings…” button, which will open another window. In that window, is the “Show shadows under windows” checkbox activated? If not, does activating it and applying the settings fix this issue?

**Comment by J5lx** [comment]
Now that I think about it, it might also be an issue with Qt’s Windows style, since those tool windows do look somewhat different from normal Windows windows. Either way I’m pretty sure this is something that should be fixed by another party.

**Comment by Kaikogf** [comment]
@J5lx 
You were right. Nice!
I always configure my operated system to work with no shadows on windows. So I reverted that function and now the windows got that distinctive separation. 

Closing this issue
