### ISSUE TITLE
After moving/zooming a vector object, click on it will shift it.

### ISSUE THREAD

**Issue by Popolon** [pencil2d/pencil#1541]
# Issue Summary
After moving/zooming a vector object, click on it will shift it.

### Actual Results
On the vector layer, after drawing  a vector shape, when using moving tool (M):
* After the object was moved, click on it move it bottom left
* After the object was zoomed, click on it move it bottom right

### Expected Results
The object should not shift.

### Video or Image Reference

https://popolon.org/depots/bugs/vokoscreenNG-2020-11-21.vector_objects_move.webm

### Steps to reproduce

On the vector layer, after drawing  a vector shape, when using moving tool (M):
* After the object was moved, click on it move it bottom left
* After the object was zoomed, click on it move it bottom right

### System Information
+ Pencil2D Version: today git version 4594.7c4b7591

+ Operating System:
ArchLinux x86_64 updated.

+ RAM Size:
8GB

+ Graphics Tablet:
Huion Kamvas pro 20

**Comment by J5lx** [comment]
Closing as duplicate of #1464.

**Comment by Kaikogf** [comment]
@J5lx 
This issue should be opened. The issue is still there [version 9thDez2020] and it is the same as #1464.

**Comment by J5lx** [comment]
I closed it *because* it is the same as #1464. We like to keep exactly one open report per unfixed bug to make it easier to keep track of them all. As you can see, #1464 is still open, only this issue has been closed.

**Comment by Kaikogf** [comment]
I understand what you mean 👍
