### ISSUE TITLE
Polyline tool glitches

### ISSUE THREAD

**Issue by pragrawal2007** [pencil2d/pencil#1546]
the polyline tool is ultra glitchy and just deform the whole animation. please try to remove the glitch as soon as possible.

 

### System Information
+ Pencil2D Version:0.6.5

 

+ Operating System:windows 10

 

+ RAM Size:4gb

 

+ Graphics Tablet:none

**Comment by J5lx** [comment]
Are you using the vector layer perhaps? There is a known issue in 0.6.5 affecting the polyline tool on vector layers. Could you take a look at #1433 and confirm whether it matches the issue you’re experiencing? That issue has already fixed and will be included in the next version. If you don’t want to wait until the release of the next version, you can try using our [nightly builds](https://www.pencil2d.org/download/#nightly-build-) in the meantime.

If you’re experiencing a different kind of glitch, please try to describe the issue you’re experiencing in more detail, for example the particular actions you performed and in which way the tool deforms the animation. A video recording or at least a screenshot of the issue would also be very helpful.

**Comment by J5lx** [comment]
Report lacks information and reporter hasn’t replied in over two months. Plus, the report most likely relates to a bug fixed in the recent 0.6.6 release. Closing.
