### ISSUE TITLE
[ISSUE] Pencil2D not able to update images on real time when importing them (regardless their extension)

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#1548]
### Issue Summary
When importing an image into a frame, pencil2D will not show it till you click on the canvas or hit another layer

### Steps to reproduce
Open Pencil2D
Go to bitmap layer and draw some lines on the first two frames.
Go to import image (select any kind of images, it also happens with GIF images) and import an image to frame #1
Now if you go to frame #1, the image is not there yet, only the lines you previously draw
Hitting canvas will refresh the content of that frame and will bring the imported image.

### System Information
+ Pencil2D Version: 9th Dec2020

+ Operating System:
WIN10pro

+ RAM Size:
32GB

+ Graphics Tablet:
HUION hd185

**Comment by Kaikogf** [comment]
Can this issue be related to #1496 ?

**Comment by Jose-Moreno** [comment]
Confirmed in Development Build Dec 27 2020, built with code from the master repository just now.

Operating System: Windows 10 Version 1909
CPU Architecture: x86_64
Qt Version: 5.14.1

@Kaikogf Please leave this open as it will be good to track this issue separately from 1496. Also Happy Holidays 😄

**Comment by Kaikogf** [comment]
> @Kaikogf Please leave this open as it will be good to track this issue separately from 1496. Also Happy Holidays 😄

I will close this issue when it is fixed 👍 
I will have holidays when all politicians were put behind bars...  definitely 😂
