### ISSUE TITLE
Travis-CI migration

### ISSUE THREAD

**Issue by chchwy** [pencil2d/pencil#1550]
Hi all, 

Sorry for disappearing for a while, it was an extremely busy October and November for me in both work and family.  Luckily in December, I will get some rest and the time I have been longing for to work on Pencil2D. 

I got a piece of news. `travis-ci.org`, the platform we run Linux/Mac nightly builds, will turn read-only on 31 December 2020. That means we are forced to migrate to their new platform `travis-ci.com`, (.org => .com).

I have done that migration, this is the new link:
https://travis-ci.com/github/pencil2d/pencil

The new .COM platform requires credits to build things (I have 10000 credits for the free plan at the moment), so the good old day of unlimited minutes is over. According to [a post](https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works), it's not as generous as it was. 

We will still use travis-ci.com for now and see if anything needs to be changed.

If it is not going well, we might have to go to AppVeyor as a plan B. A few months ago, I tested and successfully built Mac/Linux builds on AppVeyor. The only issues are the limit of one concurrent job and no Ubuntu 14 support. other things should be fine.

**Comment by J5lx** [comment]
Thanks for the heads-up! For the record, I also experimented with GitHub Actions a while ago – on all platforms including Windows and Ubuntu 14 – and it worked quite well. Best of all, it has unlimited minutes for public repos and is even more generous with concurrent jobs than Travis. If we need to make a switch, this could be another good option.

**Comment by chchwy** [comment]
Github Actions sounds like a better idea. we should probably give it a go.

**Comment by scribblemaniac** [comment]
I fully support moving away from Travis :+1: Appveyor and Github Actions both seem like better alternatives right now. Ubuntu 14 support would be ideal because as a reminder, AppImages cannot be generally be used on distro releases older than the one it is built on because of a lack of backwards compatibility with glibc.
