### ISSUE TITLE
Movie import option filter for "all" filetypes not showing AVI files

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1554]
### Issue Summary

When importing a video the default option is the "Movie formats*.avi *.mpg *.mpeg *.mov *.mp4 *.mkv *.ogv *.swf *.flv *.webm *.wmv"

Using this option will show every filetype except AVI. You have to select AVI manually from the list. I copied verbatin how the text appears, and noticed there's a lack of space before the wildcard (*) could this be the issue?

### Expected Results

The movie formats option should show all file formats available.

### Video or Image Reference
![image](https://user-images.githubusercontent.com/4912907/102678572-708af280-4177-11eb-873e-8449d52a1096.png)

### Steps to reproduce

1. Create a new Pencil2D file
2. go to File > Import > Movie Video
3. Check that you're using the default option for movie format
4. Browse for a folder where you are absolutely sure you have an AVI file.
5. Note that you won't be able to see the file
6. Select the specific AVI file format filter. Now you'll be able to see it.

### System Information
+ Pencil2D Version:
Nightly Build Nov 24 2020

commit: 889f226aaf65ac2b4da00cb3f355b6b29fd5d571
date: 2020-11-24_17:31:44

Operating System: Windows 10 (10.0)
CPU Architecture: x86_64
Qt Version: 5.12.10

**Comment by scribblemaniac** [comment]
There should be a `(` before the first wildcard. That's almost certainly what's causing this issue.
