### ISSUE TITLE
Sound playback is silent

### ISSUE THREAD

**Issue by AndreasMatiwo** [pencil2d/pencil#1566]
### Issue Summary
When I play a sound in pencil2D it is total silent and when I try other sounds and and even restarted my computer the sound is still silent.
 

### System Information
+ Pencil2D Version:

 

+ Operating System:

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by Jose-Moreno** [comment]
@AndreasMatiwo Hi. Can you please download the development version from January 4th and test this again? Here are direct links for each platform.
**Win64** https://drive.google.com/file/d/1hbC5e0B-8rSUI9TfAsX_R1WPOxmzaqAU/view?usp=sharing
**maOSX** https://drive.google.com/file/d/1jwp6Raf81oZub7gyvnN9YAOXZWQT4HqI/view?usp=sharing
**Linux** https://drive.google.com/file/d/1pBE72oLBTVTjC3B3t6aIr-EKlereIoXJ/view?usp=sharing

When you open the development version please delete the previous file and import it again to force Pencil2D to reconvert the audio into a suitable format for internal playback.
