### ISSUE TITLE
Cannot Export in Any File Type.

### ISSUE THREAD

**Issue by mfrex** [pencil2d/pencil#1573]
### Issue Summary

When trying to export to MP4 (or any other file type) the window shows as if itscomplete a fraction of a second after clicking "ok". File cannot be found or searched on my desktop or any other folder I try to save it to. I've made sure software is up to date and manually inputting file type as previous users have tried. still no fix

 

### Actual Results
No results
 

### Expected Results
Saved file.
 

### System Information
+ Pencil2D Version:

 

+ Operating System:
Windows 10
 

+ RAM Size:
16 GB
 

+ Graphics Tablet:
Surface Pro 4

**Comment by Jose-Moreno** [comment]
@mfrex Hi. I know this will sound strange, but can you verify if you are running the software from the ZIP file or from the extracted contents? 

Also please check in the Pencil2D folder in the plugins folder if you have the FFMPEG.exe file. If this file is not present you won't be able to export regardless of method.

Additionally while it may be obvious, please make sure you are using **the File > Export** menu options. 

Using **File > Save** or **File > Save As..** is only meant for Pencil2D project files, it does not convert the result to any other filetype.

We're going to release a new version soon, so please try to use the latest development build to test as well if export works for you. This is the direct download folder for the development version https://drive.google.com/drive/folders/0BxdcdOiOmg-CSVlqc3JNQV9hVGs make sure to get the version with the name format **pencil2d-win64-2021-02-17**

**Comment by mfrex** [comment]
I can't find the ffmpeg.exe file. If I don't have it do I just uninstall and reinstall Pencil2D

**Comment by mfrex** [comment]
UPDATE* 

After Uninstalling and reinstalling problem has been resolved. I believe it was the missing FFMPEG.exe file.


Thanks!
