### ISSUE TITLE
Hi, how can I change the language to english back? Because everything is set in Japanese. Simply when I entered Pencil2D it was set to Japanese. Now I can't understand any text to set the language back, so please help!

### ISSUE THREAD

**Issue by VictorPencil2D** [pencil2d/pencil#1628]
### Video or Image Reference
![image](https://user-images.githubusercontent.com/82094559/113860770-16a64b00-97af-11eb-856d-7da6b537f282.png)

 

### System Information
+ Pencil2D Version:

 

+ Operating System:

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by VictorPencil2D** [comment]
And I'm trying to solve the problem for 3 hours.
I also tried to download it again, but it looks same...

**Comment by davidlamhauge** [comment]
Did you download it from https://www.pencil2d.org/ ? 

If you did, then the standard setting is to use the system language, so either have you yourself set it to Japanese, or your system is set to Japanese.

Another thing is, that this is not an 'issue'. This should have been brought up in the forum: https://discuss.pencil2d.org/c/misc/10

**Comment by VictorPencil2D** [comment]
Thanks but no, my system is to english and I didn't set it to Japanese, yes I downloaded it from there, it's a bug I can't solve because every button is random placed on the screen and I can't read Japanese. I wanna go to languages and set it back but Idk where is the button to go there.

**Comment by davidlamhauge** [comment]
I've just downloaded Pencil2D from the official site, unpacked it, and run it, and it started as expected in my system language, and not Japanese.

You could try to find the preferences. It should be in the menu number two from the right (or maybe from the left), at the bottom. If that triggers the Preferences dialog, it's the top drop down menu, in the first page. Select English.

**Comment by VictorPencil2D** [comment]
Yes it worked, was the menu number 4 (in the middle) finally is in english. Thanks!
