### ISSUE TITLE
Image export options

### ISSUE THREAD

**Issue by mikshaw** [pencil2d/pencil#163]
PNG export is transparent with sequence, flat with single image. This isn't as much a bug report as an idea.
I nearly always save png images with transparency when available, if for no reason other than it leaves more options open for future use of the images. Something that might be useful in the future is to give the user the choice of transparent or not, regardless if exporting a single image or a sequence. Another inconsistency is that an options box appears only if exporting a sequence. Providing options for image exports of any kind is probably something that users will appreciate...giving them more control over not only transparency, but also things like compression level and scale.

I understand this is more a feature for creating static images, which isn't really the focus of pencil development at this time, but i thought i'd write it out just so it would be here for future reference.

**Comment by Kaikogf** [comment]
@CandyFace 
You may close this post since there is already an option for exporting Alpha channel, or not 👍
