### ISSUE TITLE
Lightbox mode wont go away

### ISSUE THREAD

**Issue by FloofyTails** [pencil2d/pencil#1646]
### Issue Summary

 
i made lineart, and added a layer below it to do color, when i did so the lineart layers opacity went down and i cant figure out how to make it full so i can properly color
### Actual Results

 
I expected the lineart layer to stay at full opacity when coloring on a layer below it, it instead grayed out.
### Expected Results

 
The lineart should be full opacity not half
### Steps to reproduce

 
do lineart on one layer, then click the layer below it 
### System Information
+ Pencil2D Version:
0.6.6
 

+ Operating System:
Windows 10 pro
 

+ RAM Size:

 
4GB
+ Graphics Tablet:

 
Ipad+applepencil

**Comment by Jose-Moreno** [comment]
@FloofyTails Hi, Pencil2D has 3 modes for layer visibility:
1. Fully Layer Opacity | All Layers
2. Relative Layer Transparency  | Relative
3. Solo / Isolated Layer Opacity | Current Layer Only

To change this look in the **topbar menu > View > Layer Visibility** 
![image](https://user-images.githubusercontent.com/4912907/125179328-55cfa800-e1b3-11eb-9389-b1120125a63f.png)

Most likely you're currently on the relative option where the active layer will be opaque and the other layers will be semi-transparent, so the farther the layer is from the current layer, the more faint it will look.
