### ISSUE TITLE
To add a way for RESETING the "OPEN RECENT" files

### ISSUE THREAD

**Issue by ghost** [pencil2d/pencil#165]
Last build 04Aug2013
Win7 Ultimate, SP1 64bits

To add a new button/shortcut that allows Pencil to RESET to zero the list of recent files.
When finishing a project/document  there is no need for it to be listed on the OPEN RECENT Menu any more. 

Resetting this list will allow a visual update of the work already in use.

**Comment by J5lx** [comment]
#165 got merged and this feature is now available in master, so shouldn’t this be closed?

**Comment by CandyFace** [comment]
Indeed it should, I just forgot about the issue ;)
