### ISSUE TITLE
Pencil2D crashing after deleting sound layer

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1659]
### Issue Summary
Pencil2D 0.6.6 nightly versions are crashing after deleting a sound layer

### Expected Results
Moving or even touching the playhead shouldn't lead to the app crashing.

### Steps to reproduce

1. File > Import > Sound > Create Layer > Load a sound file (format doesn't matter. I tested WAV & MP3's of different lengths)
2. Once loaded and the layer is created click on the playhead and be sure to move it at least one frame to the right (or any frames as long as it's been moved) _**Note**: It seems even just clicking on the playhead on the first frame will allow the app to crash after the layer has been deleted but to be sure the event is registered move the playhead_
3. Now delete the layer (doesn't matter if you use the buttons on the timeline or the delete layer action menu option)
4. It will crash 100%

### System Information
Nightly Build Aug 12 2021

commit: d2d8907e72dd13de62b9a530f9ad0cda9cc3b226
date: 2021-08-12_16:58:31

Operating System: Windows 10 Version 2009
CPU Architecture: x86_64
Qt Version: 5.15.2

**Comment by davidlamhauge** [comment]
I've downloaded the Nightly build Aug 12 2021, and tried several times. I can't get it to crash. The same goes for the master branch.
Maybe I don't know what the 'playhead' is? I've tried to press on the line with framenumbers, where you can scroll your animation, I've tried the 'PLAY'-button and I've tried the button to turn the speaker on/off. Nothing can make the app crash so far?
What is the 'playhead'?

**Comment by Jose-Moreno** [comment]
@davidlamhauge Hi David. Playhead, scrubber or frame indicator is the vertical red bar on the timeline. I personally can crash it with the reproduction steps everytime and I submitted this ticket mainly because two other users in the discord server complained about the same issue and I began to investigate the problem.

It could be a problem specific to our Windows version, which I just noticed it's wrongly reported in the about panel since I have version 202H and not 2009 🤔

**Comment by davidlamhauge** [comment]
Thanks @Jose-Moreno . I just tested it again, and still no crash. I have Windows 10, version 21H1, so it migth be the version. No matter what, I can't reproduce the crash.

**Comment by J5lx** [comment]
I just realised I still have 2009 (which, for the record, is just another name for 20H2) on my old laptop, so I gave this a try but I still couldn’t make it crash. There must be some other reason this happens.

**Comment by Jose-Moreno** [comment]
I just want to say thank you to everyone that discussed, tested and worked on fixing this. I can confirm that on the current Windows nightly build for November 8th, this issue no longer happens 😄 🎉
