### ISSUE TITLE
Unable to resize docked panels

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1665]
### Issue Summary
Can't resize any docked panel. I can tear them out and resize them as a window, but not as the usually docked versions, I simply don't get the cursor widget once I reach the border of a panel area.

### Expected Results
This was working before. The expectation is that you can resize the panels in a fluid manner.

### Steps to reproduce

1. Open Pencil2D
2. Take the cursor over any of the panel borders that are adjacent to the canvas or internally on each area of the interface
3. Notice the cursor won't change to the usual double arrow icon
4. Try clicking and you won't be able to drag the borders of any panel.

### System Information
+ Pencil2D Version:

Nightly Build Sep 24 2021

commit: f43245b609ce3bbb17be041e4d2db6ea7c71a7ce
date: 2021-09-24_21:00:40

Operating System: Windows 10 Version 2009
CPU Architecture: x86_64
Qt Version: 5.15.2

**Comment by J5lx** [comment]
Whoa, totally didn’t notice that! Anyway, it’s fixed now. Thanks for reporting!

**Comment by CandyFace** [comment]
Oh wow, how have I not noticed that while working on that PR...
I can confirm that commit 887a877 fixed the problem.
