### ISSUE TITLE
add an additional move tool

### ISSUE THREAD

**Issue by Abhinav-ms-903** [pencil2d/pencil#1677]
try to add a rotate tool in selection tool

**Comment by J5lx** [comment]
Rotating a selection is actually already possible, although the feature is somewhat hidden. You can rotate your selection by simply holding down the Ctrl key while clicking and dragging with the move tool. The next version will also display a hint in the status bar to make this feature easier to find.

By the way, when posting issues on this issue tracker, please search for your problem beforehand to make sure it hasn’t already been addressed. If you can’t find what you need and just need help or want to ask questions, you can also post on [our forum](https://discuss.pencil2d.org/) or chat with us on [our Discord server](https://discord.gg/8FxdV2g).
