### ISSUE TITLE
Error exporting movie

### ISSUE THREAD

**Issue by GHoop120856** [pencil2d/pencil#1683]
Error exporting movie

### Issue Summary

When I try to export a project as a movie, I get the following error:

Command: C:/Users/garet/Documents/Pencil2D/plugins/ffmpeg.exe -f rawvideo -pixel_format bgra -video_size 912x513 -framerate 30 -i - -threads 12 -pix_fmt yuv420p -y C:/Users/garet/Videos/Pencil2D Finished Projects 3/G.mp4
ffmpeg version 4.1.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20190212
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, rawvideo, from 'pipe:':
  Duration: N/A, start: 0.000000, bitrate: 449141 kb/s
    Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 912x513, 449141 kb/s, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
[libx264 @ 00000170ca92b3c0] height not divisible by 2 (912x513)
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
Exit status: CrashExit
Exit code: 1
System Info
Pencil2D version: 0.6.6 (stable)
Build ABI: x86_64-little_endian-llp64
Kernel: winnt, 10.0.19042
Operating System: Windows 10 (10.0)
end

This happens almost every time across every project. I'm not a coding wizard, I can't decipher it.

### Actual Results

The green loading bars get to about 60% and then stop. Then, this error pops up.

### Expected Results

I just want to export my movie successfully. I have exported successfully in the past, but it seems to happen randomly.

### Video or Image Reference

![Pencil2D error](https://user-images.githubusercontent.com/96843395/147699385-fe3710ac-5ec1-4601-84db-0e870df38b10.png)

### Steps to reproduce

Try exporting as a movie, I don't know. I guess it just happens to me. Maybe there is a problem that I can't see. User error?

### System Information

+ Pencil2D Version: 0.6.6

+ Operating System: Windows 10

+ RAM Size: 16GB

+ Graphics Tablet: It says this is optional. I don't know what this means

**Comment by Jose-Moreno** [comment]
@GHoop120856 Hi. I believe this is the problem
![image](https://user-images.githubusercontent.com/4912907/147702374-5dcac5ff-8281-4021-b024-279d82885f0d.png)

The MP4 video container **must** have a height and width that's divisible by 2 and the H264 codec must be always less than 2048 x 1080 (2K). So make your camera size 912 x 514 and it will work.

Just in case this isn't a Pencil2D issue but rather a limitation of the video format itself. I think the same resolution size will work in AVI or WEBM formats.

Please try that out and let us know if it worked for you. If it didn't we'll investigate further.

**Comment by GHoop120856** [comment]
Hey Morr,

I changed the Camera to 912x514 and it worked. I'm not particularly good with computers so you were a huge help. I'll keep in mind that the height and width must be divisible by 2. Thanks!

**Comment by Farmanellahi** [comment]
Command: C:/Users/FAC607~1/AppData/Local/Temp/Rar$EXa17316.6176/Pencil2D/plugins/ffmpeg.exe -f rawvideo -pixel_format bgra -video_size 912x514 -framerate 6 -i - -threads 8 -y C:/Users/F A/OneDrive/Desktop/unhealthy lifestyle.pclx
ffmpeg version 4.1.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20190212
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, rawvideo, from 'pipe:':
  Duration: N/A, start: 0.000000, bitrate: 90003 kb/s
    Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 912x514, 90003 kb/s, 6 tbr, 6 tbn, 6 tbc
[NULL @ 000001d0b98fd6c0] Unable to find a suitable output format for 'C:/Users/F A/OneDrive/Desktop/unhealthy lifestyle.pclx'
C:/Users/F A/OneDrive/Desktop/unhealthy lifestyle.pclx: Invalid argument
Exit status: CrashExit
Exit code: 1
System Info
Pencil2D version: 0.6.6 (stable)
Build ABI: x86_64-little_endian-llp64
Kernel: winnt, 10.0.22000
Operating System: Windows 10 (10.0)
end

**Comment by Farmanellahi** [comment]
The above solution cant fix my problem kindly help
