### ISSUE TITLE
Sound layer frame selection displays frame container incorrectly

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1686]
### Issue Summary

There's some issues with the sound frame visualization:
+ When I select the frames in a sound layer, the selected frames will be visualized with an offset all the way to the left of its container.
+ This is happening ever since the sound frame-add preview feature was added. When you double click an empty space you will add a new frame
+ It seems only the first frame container is used as the previsualization model for new frames. In this case I think it's sensible given the variety of sound lengths one can have, but I just want to know if it's intended or not. Please confirm. 
+ Considering audio files will always force a container to change size it might be better to make it a fixed size of one frame 🟥 instead but I'll make this a separate request after we have discussed it internally with the team.

### Video or Image Reference

**Unselected Frame**
![image](https://user-images.githubusercontent.com/4912907/147833433-e2ed4445-7039-4e01-a803-fd86c64381f3.png)

**Selected frame**
_Notice how the frame container shifts towards the left; If I grab the sound in any place that it should exist, I can drag it properly, so it's just a visual glitch when selected_ 

![image](https://user-images.githubusercontent.com/4912907/147833476-ce119dd5-1b65-4cbf-8cd3-39e9d1b11c4c.png)

### Expected Results

Frame container previsualization should accurately depict the position and length of the sound frame or any other frame in any layer.

### Steps to reproduce

1. Add a sound layer
2. Add a sound file
3. Observe the correct position of the frame container
4. Select the the frame container
5. Notice the offset towards the left of its starting point

### System Information
+ Pencil2D Version:
Nightly Build Nov 14 2021

commit: 91b1721baef012d49cffd0d23358524a420af9fd
date: 2021-11-14_16:46:59

Operating System: Windows 10 Version 2009
CPU Architecture: x86_64
Qt Version: 5.15.2

**Comment by MrStevns** [comment]
Fixed via d93dc19cb7c8ad0d2117d7be07e03ea204e4d5f2
