### ISSUE TITLE
Can't export to mp4 on Windows 10

### ISSUE THREAD

**Issue by yellingfrogsie** [pencil2d/pencil#1691]
### Issue Summary

I can't export my animations to mp4. These animations are 3D renders from Blender3D of my own original characters. I have been using Pencil2D to animate my renders for many years and it has always worked in the past.

 

### Actual Results
I get a pop up stating an error (included below) and the mp4 will not export. Previously the mp4 would export with no problem.

 

### Expected Results
My render frames export into an mp4 video seamlessly.

 

### Video or Image Reference
![pencil2dReport](https://user-images.githubusercontent.com/69502986/151463270-1f6d5db3-a522-456a-957a-5ad612d1c9db.PNG)

 

### Steps to reproduce
Import external images/frames by image sequence and export to a movie in mp4 format.

 

### System Information
+ Pencil2D Version:
v0.6.6

 

+ Operating System:
Windows 10 

 

+ RAM Size:
32GB

 

+ Graphics Tablet:
N/A

**Comment by scribblemaniac** [comment]
Please share the full contents of the box at the bottom of the error dialog. Without it we cannot tell what the cause of the error could be.

**Comment by Jose-Moreno** [comment]
This kind of issue can often have widely different root causes, so without further feedback from the user we can't continue to troubleshoot the issue. 

If you continue to have this problem please reopen the ticket.
