### ISSUE TITLE
Canvas appears at bottom right of screen when viewed from a camera layer

### ISSUE THREAD

**Issue by LavenderSnek** [pencil2d/pencil#1692]
### Issue Summary

I compiled the latest version recently and ran into an issue where the canvas shows up in the corner of the screen when the camera layer is selected.

It seems to be an issue with devicePixelRatioF() always returning 2 on retina displays, removing that seemed to fix it for me.

It looks similar to #1685 but it's the canvas instead of the overlays in my case. 

[relevant code](https://github.com/pencil2d/pencil/commit/6e0c24dac40dee3bb20b50bf09e08f3541c8f26f)

### Actual Results

The canvas appears at the bottom right corned of the viewport when the camera layer is selected.

### Expected Results

Camera should appear in the center of the screen when a camera layer is selected.

### Video or Image Reference

![image](https://user-images.githubusercontent.com/81382818/151674129-e7dcd8f6-d824-4dd0-a303-0c65182d5521.png)

### Steps to reproduce

Open a pencil2d with any file or a new file and select the camera layer. Make sure no external displays are connected.

### System Information
+ Pencil2D Version: 2021-11-14 nightly to latest source

+ Operating System: Mac OS 11.6

+ RAM Size: 8GB

+ Graphics Tablet: N/A

**Comment by MrStevns** [comment]
Closed as it's been fixed.
