### ISSUE TITLE
Better onion skin

### ISSUE THREAD

**Issue by chchwy** [pencil2d/pencil#17]
![OnionSkin](http://www.pencil2d.org/wordpress/wp-content/uploads/2013/06/14l53sj.jpg)

**Comment by gordielachance** [comment]
Still would like to see this one !

**Comment by feeef** [comment]
Great idea!

**Comment by feeef** [comment]
Guys, I have implemented this feature! ;)

I didn't have much time to do it so it is a bit ugly in term of interface and I still have to cleanup the code a bit but it works! It will be in my next pull request.

You have to click on the small icon to toggle "absolute" / "relative"

![screenshot from 2015-12-18 17-28-06](https://cloud.githubusercontent.com/assets/383399/11901921/8d4f3c92-a5ae-11e5-80b3-a35bb8a46614.png)

![screenshot from 2015-12-18 17-28-26](https://cloud.githubusercontent.com/assets/383399/11901929/96b181a0-a5ae-11e5-9844-1bf2cbefbac2.png)

Have a happy Christmas animating! ;)

**Comment by gordielachance** [comment]
Feeef, this is amazing :)
Great, great work. 
Really !

**Comment by ManuAros** [comment]
Nice feeef, you make Pencil better and better. Have a very very Merry Christmas :)

**Comment by feeef** [comment]
Thank you guys! :)

**Comment by carlosgf** [comment]
A dream coming true.
The time-line is like the eyes of the animator.

... and now let us start animating :+1:

**Comment by chchwy** [comment]
Implemented by feeef, closed.
