### ISSUE TITLE
Animation Problem

### ISSUE THREAD

**Issue by LooneyFan2008** [pencil2d/pencil#1704]
It won't allow me to put any more frames into my animation. This is really important as I need this to be fixed because of a competition

**Comment by LooneyFan2008** [comment]
Nevermind, its been fixed

**Comment by scribblemaniac** [comment]
@LooneyFan2008 For future reference, these Github issues are intended for reporting bugs or feature request. If you need help using Pencil2D or are having problems that you are not sure if they are bugs or not, the best place to ask is in our forums: https://discuss.pencil2d.org/
