### ISSUE TITLE
My Frames keep getting brighter

### ISSUE THREAD

**Issue by LooneyFan2008** [pencil2d/pencil#1705]
My frames keep getting brighter every time I try to add i a new onw. Its the same as the previous frame, but it keeps getting brighter. Please help me

**Comment by Jose-Moreno** [comment]
@LooneyFan2008 Hi, in these instances when you are reporting an issue please make sure to take a desktop screenshot of the problem when possible. Now by your description it seems that you have the onion skin feature enabled.

Adding a new frame means you are always adding a blank, empty, frame, if onion skin is enabled you will see a semi-transparent or "dimmed" version of a previous frame, which is a behavior that matches your description.

If you're trying to **duplicate** the previous drawing frame look carefully for the **double plus button** on the timeline, you can also use the Animation menu for most of these commands or use the relevant shortcut (F6)

If this isn't what's happening please **post a screenshot of the problem** so we can have more visual cues to provide feedback and triage this problem.

**Note:** As a separate comment, in general unless you are 100% sure it's an error on the software please post your questions in https://discuss.pencil2d.org

**Comment by Jose-Moreno** [comment]
Currently we have two features that could create the visual behavior the OP is describing. Without further feedback we can't continue troubleshooting the issue. 

If you continue to face this problem, please reopen the ticket and make sure to check the original reply that was provided.
