### ISSUE TITLE
Fail to build: src/catch.hpp:8164:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’

### ISSUE THREAD

**Issue by fabiomt** [pencil2d/pencil#1723]
Hello,

pencil2d is failing to build in Debian Unstable in arch amd64.
A bug was filled in Debian Bug Track: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1017329
The full build log, with all info, is here: http://qa-logs.debian.net/2022/08/13/pencil2d_0.6.6-1_unstable.log

The relevant part seen to be here:

> g++ -c -pipe -std=c++11 -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -DGIT_TIMESTAMP=\"2021-02-21\" -Wdate-time -D_FORTIFY_SOURCE=2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DAPP_VERSION=\"0.6.6\" -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050600 -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_XMLPATTERNS_LIB -DQT_NETWORK_LIB -DQT_TESTLIB_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR='"/<<PKGBUILDDIR>>/tests"' -I. -I../core_lib/src/graphics -I../core_lib/src/graphics/bitmap -I../core_lib/src/graphics/vector -I../core_lib/src/interface -I../core_lib/src/structure -I../core_lib/src/tool -I../core_lib/src/util -I../core_lib/ui -I../core_lib/src/managers -I../core_lib/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtXmlPatterns -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I.moc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o .obj/test_viewmanager.o src/test_viewmanager.cpp
In file included from /usr/include/signal.h:328,
                 from src/catch.hpp:5549,
                 from src/main.cpp:18:
src/catch.hpp:8164:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
 8164 |     constexpr static std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/sigstksz.h:24:
/usr/include/unistd.h:640:17: note: ‘long int sysconf(int)’ declared here
  640 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
src/catch.hpp:8223:45: error: size of array ‘altStackMem’ is not an integral constant-expression
 8223 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
      |                                             ^~~~~~~~~~~~
/usr/lib/qt5/bin/rcc -name tests data/tests.qrc -o qrc_tests.cpp
g++ -c -pipe -std=c++11 -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -DGIT_TIMESTAMP=\"2021-02-21\" -Wdate-time -D_FORTIFY_SOURCE=2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DAPP_VERSION=\"0.6.6\" -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050600 -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_XMLPATTERNS_LIB -DQT_NETWORK_LIB -DQT_TESTLIB_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR='"/<<PKGBUILDDIR>>/tests"' -I. -I../core_lib/src/graphics -I../core_lib/src/graphics/bitmap -I../core_lib/src/graphics/vector -I../core_lib/src/interface -I../core_lib/src/structure -I../core_lib/src/tool -I../core_lib/src/util -I../core_lib/ui -I../core_lib/src/managers -I../core_lib/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtXmlPatterns -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I.moc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o .obj/qrc_tests.o qrc_tests.cpp
make[2]: *** [Makefile:417: .obj/main.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/<<PKGBUILDDIR>>/tests'
make[1]: *** [Makefile:135: sub-tests-make_first-ordered] Error 2
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
dh_auto_build: error: make -j8 returned exit code 2
make: *** [debian/rules:16: binary] Error 25
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2`

The bug severity has a _serious_ status, which means the pencil2d could be removed from testing in a near future and, won't make to the next Debian stable release, so it's important to deal with this bug soon as possible.

As a quick workaround I applied the following patch:

```diff
--- pencil2d.orig/tests/src/catch.hpp
+++ pencil2d/tests/src/catch.hpp
@@ -8161,7 +8161,8 @@ namespace Catch {
 
     // 32kb for the alternate stack seems to be sufficient. However, this value
     // is experimentally determined, so that's not guaranteed.
-    constexpr static std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
+   #define sigStackSize 32768
+    //constexpr static std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
 
     static SignalDefs signalDefs[] = {
         { SIGINT,  "SIGINT - Terminal interrupt signal" },
```

But I don't really know the impact in doing this, I did it as a simple test, the build was complete and penclil2d worked, but I ask you guys for an appropriate solution.

Cheers.

**Comment by Jose-Moreno** [comment]
@fabiomt Thanks you Fabio! I'll ask one of the devs with a linux env to check this in case there's something else required. Otherwise if your solution works as it is I think we'll ask you for a PR. Thanks a lot for reporting!

**Comment by scribblemaniac** [comment]
This appears to be the same issue as #1695 and the solution remains the same:
> You can pass CONFIG+=NO_TESTS to the qmake step to skip building the test as a workaround for this issue until the next release, or you can patch catch.hpp with at least Catch2 v2.13.6.

**Comment by fabiomt** [comment]
Thanks @Jose-Moreno and @scribblemaniac for the feedback.

Some how I missed #1695 when searching for a similar issue, I apologize for that.
Yes, it's exact the same issue, and the solution works for me, I guess this issue can be taken as done.

Thanks all.

**Comment by scribblemaniac** [comment]
No worries, thanks for helping to maintain the Debian build

**Comment by chchwy** [comment]
This shouldn't be an issue after releasing a new Pencil2D version as it's been resolved in Catch2
