### ISSUE TITLE
last two seconds of the sound is cut for no reason

### ISSUE THREAD

**Issue by thisaceisdumb** [pencil2d/pencil#1725]
the last two seconds of the sound is cut for no reason

**Comment by MrStevns** [comment]
Hi @thisaceisdumb 

Please fill out the template before making an issue, we can't help nor use an issue with no information whatsoever.

It's very important that you at the very least state which operation system you're using, what version of pencl2D and other things that could be meaningful in investigating your problem.

I will close the issue now, if you update it and fill it out properly, then i'll re-open it.
