### ISSUE TITLE
Bucket tool does not take camera transforming into account when filling

### ISSUE THREAD

**Issue by MrStevns** [pencil2d/pencil#1735]
### Issue Summary

 

When you have moved the camera from its initial position and then switch layer to a bitmap layer and fill, the filled region does not match the new camera position. 

### Actual Results
Fill is happening outside the interpolated frame
<img width="673" alt="image" src="https://user-images.githubusercontent.com/1045397/198682780-b9e1ee89-275c-483e-b5b7-b72ee7748dfc.png">
<img width="632" alt="image" src="https://user-images.githubusercontent.com/1045397/198682830-7c6b7fbb-a63e-4a80-aa34-3cd5758cf1a2.png">

 

### Expected Results
The fill always happens within the camera passpartout.

 

### Steps to reproduce
- Move the camera from its initial position
- Select your bitmap layer
- Select the bucket tool
- Fill on the canvas within the new passpartout.

 

### System Information
+ Pencil2D Version:
Development Build Oct 24 2022
Operating System: macOS 12.6
CPU Architecture: x86_64
Qt Version: 5.15.1

**Comment by AnhuaW** [comment]
Hi, may I attempt this issue?

**Comment by MrStevns** [comment]
Hi AnhuaW, of course 😄
