### ISSUE TITLE
keep the camera fixed and let the bitmap layers move.please help

### ISSUE THREAD

**Issue by morsmordreb** [pencil2d/pencil#1751]
### Issue Summary
I have a question, I don't know where to ask, my question is here to try.
I found that my hand-tool was aimed at the whole camera, and I couldn't keep the camera fixed and let the bitmap layers move. Whenever I use the hand-tool I'm moving the whole camera and the bitmap, I don't know what to set. Please help me

 

### Actual Results
 Whenever I use the hand-tool I'm moving the whole camera and the bitmap, I don't know what to set.

 

### Expected Results
keep the camera fixed and let the bitmap layers move
 

### System Information
+ Pencil2D Version:

 

+ Operating System:

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by Jose-Moreno** [comment]
@morsmordreb Hi. This is a developer focused forum where you are meant to report technical issues the software might have.

For questions or sharing artwork, Pencil2D has a community forum where you can ask questions. You can get there by the main website or by using the Help menu in the software (Pencil2D Forum)

![image](https://user-images.githubusercontent.com/4912907/226475254-81d3d7b4-a890-4de6-b9b6-2030431b2b15.png)

### New Camera Implementation

Anyway. In recent development versions there was a major reimplementation of how the camera worked, which you can check out by downloading a nightly build on the link below. This will change how the camera is used.

https://pencil2d.org/download/nightly

### Old Camera System Controls

- When selecting a drawing layer (bitmap, vector, etc) if you use the hand tool, you would be manipulating the workspace view.
- When selecting the camera layer, using the hand tool will manipulate the camera instead.

### New Camera System Controls

- Using the **Hand tool** will **only** manipulate the workspace view
- Using the **Move tool** when the camera layer is selected will allow you to transform the camera separately.

# Understanding the camera in Pencil2D

It's important to note that regardless of the version you are using, the camera and the canvas are two separate things. The canvas is infinite. The camera is what restricts the output size of the animation.

Basically imagine you have a **cellphone camera** pointing down to a **fixed piece of paper**.
If you keep the camera steady and move your head instead you can see the paper from **different points of view**. 

The camera will still look at the paper from the same place so the picture you take will simply show what the camera sees at any moment in time, not what you necessarily are seeing at that moment.

If you move your camera after that, and take another picture, you will have a different point of view from the camera. This is simply a metaphor on how Pencil2D shows you things.

### Motion Tweening for Layers?

Let me say that currently **you cannot move the canvas or layers automatically**, only the camera has interpolation. To move any layer drawings you NEED to "animate" them frame by frame.

**However** there is a workaround for this. What I always recommend is to animate the motion tweened characters or objects in separate files. This is to use the camera interpolation as a tool to animate them.

Then you should export each character or object as a sequence of transparent PNG's and composite the individual animations in a third party digital compositing program or, if that's too advanced, make a separate Pencil2D document to import all the image sequences on separate layers.

You would need to be very organized to do this, but it's a common skill to be had in professional animation production settings.

### Here's a tutorial I did a long time ago on how to animate an image with the camera

```md
Actual tutorial starts at `3:20` timestamp
Click on the image to visit the tutorial
```

[[VIDEO] Pencil2D - Animating a still image with the camera layer](https://youtu.be/L5ms5GH3FQg?t=200)
[![YT Thumb](https://img.youtube.com/vi/L5ms5GH3FQg/maxresdefault.jpg)](https://youtu.be/L5ms5GH3FQg?t=200)

**Comment by morsmordreb** [comment]
Thank you very much for your reply. Thank you very much.
I have read your tutorial. I have carefully watched your steps of moving the tiger with hand-tool in the camera layer and generating the animation. It is frustrating that I can't achieve it like this. Please take a look at my recording.

https://user-images.githubusercontent.com/88188802/226680513-f7474dbc-fd28-4cf5-8227-08c3d865659f.mp4

**Comment by morsmordreb** [comment]
hi，

    I don't know why the forum has been banned from Posting something, so I don't know how to feedback information。
    Frustratingly, I still couldn't handle hand-tools, even with a recent version of the client.
    I read your tutorial carefully, especially in the camera layer with hand-tools operation, but I can't like you, I don't know whether the mouse needs to be operated at the same time with button assistance.
    Please help me, and I wonder if it is convenient to add your friend. I am a developer, and I have some things I want to develop together.
    I recorded a video on that issue，thanks to check。
thanks

















At 2023-03-21 06:26:34, "Morr" ***@***.***> wrote:

@morsmordreb Hi. This is a developer focused forum where you are meant to report technical issues the software might have.

For questions or sharing artwork, Pencil2D has a community forum where you can ask questions. You can get there by the main website or by using the Help menu in the software (Pencil2D Forum)

New Camera Implementation

Anyway. In recent development versions there was a major reimplementation of how the camera worked, which you can check out by downloading a nightly build on the link below. This will change how the camera is used.

https://pencil2d.org/download/nightly

Old Camera System Controls
When selecting a drawing layer (bitmap, vector, etc) if you use the hand tool, you would be manipulating the workspace view.
When selecting the camera layer, using the hand tool will manipulate the camera instead.
New Camera System Controls
Using the Hand tool will only manipulate the workspace view
Using the Move tool when the camera layer is selected will allow you to transform the camera separately.
Understanding the camera in Pencil2D

It's important to note that regardless of the version you are using, the camera and the canvas are two separate things. The canvas is infinite. The camera is what restricts the output size of the animation.

Basically imagine you have a cellphone camera pointing down to a fixed piece of paper.
If you keep the camera steady and move your head instead you can see the paper from different points of view.

The camera will still look at the paper from the same place so the picture you take will simply show what the camera sees at any moment in time, not what you necessarily are seeing at that moment.

If you move your camera after that, and take another picture, you will have a different point of view from the camera. This is simply a metaphor on how Pencil2D shows you things.

Motion Tweening for Layers?

Let me say that currently you cannot move the canvas or layers automatically, only the camera has interpolation. To move any layer drawings you NEED to "animate" them frame by frame.

However there is a workaround for this. What I always recommend is to animate the motion tweened characters or objects in separate files. This is to use the camera interpolation as a tool to animate them.

Then you should export each character or object as a sequence of transparent PNG's and composite the individual animations in a third party digital compositing program or, if that's too advanced, make a separate Pencil2D document to import all the image sequences on separate layers.

You would need to be very organized to do this, but it's a common skill to be had in professional animation production settings.

Here's a tutorial I did a long time ago on how to animate an image with the camera
Actual tutorial starts at `3:20` timestamp
Click on the image to visit the tutorial

[VIDEO] Pencil2D - Animating a still image with the camera layer
