### ISSUE TITLE
Memory leak when editing Stable Build files with Nightly Build editor.

### ISSUE THREAD

**Issue by RaykoEZ** [pencil2d/pencil#1763]
### Issue Summary
 This may be me lacking critical information, or it may relate to #520 but the project files are saved and edited on the same hardware & OS platform, but with different builds
- work is not lost until the process is killed before saving
- memory leaks are more severe in some actions in the editor, **changing editor panel property (e.g. resizing timeline panel)**, **zooming** and **hand tools** are what I found to be the main contributors in this case, there may be other tools sharing the same problem.
- this bug does not occur when editing Nightly Build files in Stable Build
 

### Actual Results
I didn't expect a file format to affect editor stability and crash my other running processes when I was just viewing frames and zooming in/out. Stable Build takes almost no memory for zooming and moving an empty file, the latest nightly build editor leaks 500MB per drag/zoom edit.
 

### Expected Results
 I would expect a PCLX file to behave the same across different builds/versions, or provide an error when a PCLX file is no longer compatible with a build.  
 

### Video or Image Reference
Link for how I reproduced this bug: 
https://youtu.be/lmbvWBJkdCU
 

### Steps to reproduce
1. Save as a file using the current stable build (v0.6.6)
2. Open Nightly Build Editor (I used 04/22/2023)
3. Open Recent, and select the file saved by v0.6.6
4. Try simple editing, focus on the Resizing UI panels, Zoom and Hand tool footprint
 

### System Information
+ Pencil2D Version: Nightly Build Apr 22 2023

 

+ Operating System: Windows 10 (64-bit)

 

+ RAM Size: 32.0 GB (1GB set as budget)

 

+ Graphics Tablet: WACOM IntuosPro M (this bug affects mouse pointers too)

**Comment by MrStevns** [comment]
Hi Eric

Thanks for reporting this, i've investigated the problem and indeed there's a leak in our painting logic, causing it to create an image of the size of the canvas on every paint operation, when you have a vector layer in your timeline.

The reason you're not seeing the leak in the nightly build initially, only after opening a project file from the stable release is because we've removed the vector layer in the default setup.

The leak however will be fixed together with this PR https://github.com/pencil2d/pencil/pull/1761

**Comment by RaykoEZ** [comment]
Indeed, I reproduced this after adding a vector layer on the Nightly Build.

Thanks!

**Comment by MrStevns** [comment]
Given that the PR hasn't been merged yet, let's keep the issue open. It will be closed automatically when the PR has been merged
