### ISSUE TITLE
app for android

### ISSUE THREAD

**Issue by mesflit** [pencil2d/pencil#1766]
The android version of this application should be released and it should be open source.

On Android we can run this app using termux only. But it is very difficult to use.

**Comment by MrStevns** [comment]
Hi Mesflit

Thanks for the feedback.

An Android version of Pencil2D is not currently planned, nor are any other platforms. There's plenty work for us just supporting Windows, Mac and Linux as it is.

**Comment by chchwy** [comment]
There is no plan to develop an Android app currently due to the shortage of development capacity. We will reconsider it once we find someone who is interested in making one and knows Android development.
