### ISSUE TITLE
Add `qt-gstreamer` as dependency on Linux builds

### ISSUE THREAD

**Issue by timeopochin** [pencil2d/pencil#1768]
Installing `qt-gstreamer` was the solution to #1767. Without it there was no audio playback inside of Pencil2D despite audio files importing and exporting correctly.

I would suggest adding it as an optional dependency at the very least, as it technically isn't required for Pencil2D to be usable.

**Comment by scribblemaniac** [comment]
I see from your previous report that you are using Arch Linux. How are you installing Pencil2D? Dependencies, including gstreamer should be included as part of the appimage releases we create. For any package installations, the package maintainer will need to fix such issues.

**Comment by timeopochin** [comment]
Ah of course, I see, I used both the AUR (development version) and the official arch repositories (v0.6.6)

I will create an issue on there

Thanks

**Comment by scribblemaniac** [comment]
I have updated the documentation for building from source on Arch Linux to include this package.
