### ISSUE TITLE
svg

### ISSUE THREAD

**Issue by dolarfred** [pencil2d/pencil#1769]
### System Information
+ Pencil2D Version:

 

+ Operating System:

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by Jose-Moreno** [comment]
@dolarfred Hi. Please consider filling out the template. Whatever your requirement is, we can't understand if you don't explain it properly. We'll wait for a week for more info. If not provided the ticket will be closed automatically.

FYI if you are asking about having SVG export or import capabilities, this has an existing ticket already and a simple search would have revealed that https://github.com/pencil2d/pencil/issues?q=is%3Aissue+is%3Aopen+svg
