### ISSUE TITLE
Whenever I'm tapping here with my digital pen, it creates ripples around my cursor. 

### ISSUE THREAD

**Issue by dev-ill-hmm** [pencil2d/pencil#1785]
It would have been great to draw without this bug.

**Comment by scribblemaniac** [comment]
Sounds like a Windows Ink issue, but it's impossible to say for sure without more information. I'm assuming you found a solution given that you closed the issue. For future reference, these GitHub issues are meant primarily for the developers to track confirmed bugs. If you need help with doing something in Pencil2D or have some issue using it, posting to [the forum](https://discuss.pencil2d.org/) is preferred. Wherever you post, more information should be provided. What version of Pencil2D are you using? What operating system? What tablet brand? What do you expect to happen vs. what is actually happening? Etc. Sharing screenshots is also helpful for visual issues.

**Comment by Jose-Moreno** [comment]
@dev-ill-hmm Hi, 

From your description it seems you have Windows Ink enabled. This is a software suite that comes with the Windows OS. It usually activate visual aids like the "ripple effect" or "ring effect" near your cursor to signify different pen functionality.

To configure Windows Ink, we have the following guide in our forum https://discuss.pencil2d.org/t/pen-pressure-not-working/4917/4

Following it will hopefully reduce most of the visual elements you have to experience while drawing in Pencil2D or other software like Adobe Photoshop that use the default driver for your PC.

> _Note: FYI Windows Ink, and any associated visual effects that come with it, is developed and handled by Microsoft themselves. It's not something Pencil2D has any control over whatsoever._

Lastly when reporting bugs please consider scribblemaniac's advice written beforehand on this thread. Using the forum is meant to determine if an issue is a bug or not. Using Github is meant for issues that are guaranteed to be Pencil2D problems.

Have a good day,
