### ISSUE TITLE
No escucho el sonido

### ISSUE THREAD

**Issue by juliamaasunovia** [pencil2d/pencil#1805]
La aplicacion a pesar de tener una capa de sonido y que al momento de exportar la  animacion si cuenta con el sonido, al momento de editar ni siquiera aparece en la opcion de ajustar volumen, es decir no suena, ayuda porfavor

**Comment by Jose-Moreno** [comment]
@juliamaasunovia Hola.

Pencil2D es una aplicación para realizar animación, por ende **no cuenta** con la capacidad de **ajustar volumen** o **cortar/editar clips de audio/video** como otros programas especializados.

# Consideración para trabajar audio y video

Se sugiere usualmente que continues el trabajo de creación audiovisual con un programa de edición de video gratuito como **[OpenShot](https://www.openshot.org)** o **[Shotcut](https://www.shotcut.org)**.

En un flujo profesional de trabajo, las pistas de sonido en Pencil2D se deben usar principalmente como **referencia para el animador**. No para inclurise en un video para entregar a un cliente.

Antes de importar el audio de referencia, este se puede grabar o editar en un **programa de edición externo** como [**Audacity**](https://www.audacityteam.org) que es gratuito.

# Importando Video y Audio en Pencil2D

Ahora bien si realmente quieres **importar un video + audio** en Pencil2D, se importa la pista de audio y video por separado. No es automático.

En Pencil2D
1. Archivo > Importar > Video...
2. Archivo > Importar > Audio... (debe decir especificamente **`Audio...`**, para que te permita buscar un archivo de video como AVI o MP4. Si seleciconas la opción **`Sonido...`** solo buscará archivos mp3, wav, etc...)

Pero francamente esto solo sirve como referencia. Si quieres editarlo como clips o poner textos, es mejor usar un software editor de video...

# Problemas y Mejoras de Audio en Pencil2D

Pencil2D tiene problemas de importación de audio en la v0.6.6 que se han arreglado con los años.

Para poder aprovechar estos arreglos en la app recomiendo descargar la versión de desarrollo más reciente en el siguiente enlace https://www.pencil2d.org/download/nightly/

![image](https://github.com/pencil2d/pencil/assets/4912907/05e795d1-997b-4d24-a5c9-27934649d47e)

Una vez abierta la nueva versión (son portables, no hay que instalar) sugiero que pruebes lo siguiente:
1. Abrir tu archivo de animacion
4. Borrar la capa o capas de sonido
5. Reimportar todos los clips de audio para que el programa pueda usar el nuevo algoritmod e importacion de audio.
6. Exportar de nuevo el video con el track de audio que pusiste de referencia. Una vez exportes la animación debes asegurarte de usar un formato MP4 o AVI.
7. Abrir el video exportado en un programa de edición de video y verificar que el audio este incluido. En el programa de edición puedes cambiar el volumen tambien.

Saludos,

**Comment by MrStevns** [comment]
Considering the elaborate answer above and there being no further questioning from the user in at least 30 days, i'm closing the issue.
