### ISSUE TITLE
Update AppStream MetaInfo to meet new Flathub quality quidelines

### ISSUE THREAD

**Issue by J5lx** [pencil2d/pencil#1812]
At the beginning of the year, Flathub [introduced](https://docs.flathub.org/blog/quality-moderation) new [quality guidelines](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines) for app metadata. Pencil2D already conforms to most of the criteria, but there are a few checks that we are currently failing. Fixing that should be fairly simple, so I’d like to get that done for the next release, even though it’s not strictly mandatory. One of the screenshot criteria states that the screenshot should reflect the user interface of the current version, so that’s something I’m simply going to put on the release checklist. That leaves us with:

- [ ] [Has (good) primary brand colors](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines/#brand-colors)
- [ ] [Summary shorter than 35 characters](https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines/#not-too-long-1)

![Screenshot of Pencil2D’s app listing quality review on Flathub. Failing are checks relating to primary brand colors, Summary shorter than 35 characters, and four checks in the Screenshot category: Default settings, Include window shadow and rounded corners, reasonable window size and up to date](https://github.com/pencil2d/pencil/assets/2063777/6b258244-8bed-4190-897f-048891f18991)

**Comment by Jose-Moreno** [comment]
@J5lx Hi, thank you for reporting this. For dark backdrops a white outline version was prepared when the original was made to make it pop from the bg.

I believe I had already shared the editable logo version before, but I'm attaching the SVG so everyone can use it as you consider appropriate for the repo 👍 

_Note: I used Inkscape 1.3 to edit these, and it seems some of the original colors were a bit off so I fixed that prior to upload_

**Pencil2D Square Logo Icon 2024**
![pencil2d_vector_logo_square_2024](https://github.com/pencil2d/pencil/assets/4912907/80480b8b-d194-4823-bd0f-5d47612b4bcf)

**Pencil2D Isologo 2024**
_Note: This one has two alternatives for the typeface. One has outlines, the other one is as shown for full contrast._
![pencil2d_vector_isologo_square_2024](https://github.com/pencil2d/pencil/assets/4912907/218ce831-cac8-4e8c-bf92-9e5c06424eba)

**Pencil2D Branding 2024**
[Pencil2D Branding 2024.zip](https://github.com/pencil2d/pencil/files/14560674/Pencil2D.Branding.2024.zip)

Hope these are useful to fix the requirements mentioned for brand colors and any other use that is required.

**Comment by Jose-Moreno** [comment]
@J5lx I understand. I'll read the specifications carefully to help improve or create alternative icons for FlatPack that align with the branding.

Regarding the folder...if it's the **Pencil2D Branding** google drive folder all of us should have access since it allows anyone with the link to use it 🤔 

But in case I'm mistaken, If you have the direct link handy, please share it here or via discord and I'll look into the permissions issue. Thank you!
