### ISSUE TITLE
Display Options

### ISSUE THREAD

**Issue by marcello257** [pencil2d/pencil#182]
Maybe it’s a good idea to make the activated color of the ‘Display options’ darker, than the light blue it has now.
Because the light color makes it hard to see when the're activated.

**Comment by chchwy** [comment]
Buttons on display option will show black borders when they're activated.
Thanks to @Spark01, implemented in 0001b2c08a.

**Comment by feeef** [comment]
I have slightly modified this update in the latest build to make it even more obvious that things are selected. Also to make the default button states more visually sober. Let me know if you don't like it, I can restore it to the previous state.

**Comment by chchwy** [comment]
Good job, @feeef
