### ISSUE TITLE
Crash on Linux during audio (re)playback

### ISSUE THREAD

**Issue by mikshaw** [pencil2d/pencil#183]
Not sure if this is related to a change in my system, but i don't remember having this problem before...this happens in all linux versions i have, including the 0.5 pre-pencil2D Morevna version.

On the first pass through the timeline the sound works as expected.  The second time through, whether controlled by a click or Enter key, or when the playback is set to loop, the program crashes as soon as the slider reaches the frame where the audio begins. This happens every time, except when you have a combination of loop and a timeline that is shorter than the length of the audio. In that case it will continue to loop over the audio without crashing until you pause and play again (at which point it will crash).

**Comment by Jose-Moreno** [comment]
@mikshaw Sorry to bother you as I'm sure you're no longer invested in Pencil, but could you compile and test the latest repo code to see if this bug is still valid? Matt re-implemented the sound feature with the latest code, and it works on both Win and Mac. Thank you.
