### ISSUE TITLE
app crashes when opening settings

### ISSUE THREAD

**Issue by sfepa** [pencil2d/pencil#1850]
### Issue Summary
Pencil2d crashes when trying to open settings menu 
 

### Actual Results
-
 

### Expected Results
-
 

### Steps to reproduce
Start the program --> Edit --> Settings  -->...

 

### System Information
+ Pencil2D Version: 0.7.0.911

 

+ Operating System: Fedora Linux 40 , KDE Plasma 6.1 (Wayland)

 

+ RAM Size: 16Gb

 

+ Graphics Tablet: HUION GT220 v2

**Comment by MrStevns** [comment]
Thanks for the report sfepa

Would you be able to provide a stacktrace of the crash too?

I don't have a Fedora image running currently but I tested it on another linux distribution and it works as expected for me.

**Comment by sfepa** [comment]
It seems that language is indeed the cause of this problem. The program was launched with a translation into Russian (which is strange, the system language is English), and I just wanted to change the language. Now I downloaded the old version of the program, changed the language in it, and restarted the new one, everything works fine.
