### ISSUE TITLE
sound import error 

### ISSUE THREAD

**Issue by algoscienceacademy** [pencil2d/pencil#1884]
![ffmpeg error](https://github.com/user-attachments/assets/a5d99fd2-21a8-47be-9a5f-54396ed073cd)

How i fix it. i can't see any plugin folder

**Comment by MrStevns** [comment]
Hi algoscienceacademy

Did you compile the application yourself? in that case you have to manually download a static ffmpeg binary and place it in the plugin folder to make it work.

On macOS, you find this folder in `Pencil2d.app/Contents/MacOS/plugins` like this.
<img width="545" alt="image" src="https://github.com/user-attachments/assets/686cb43c-3e1f-40af-9a58-5dee2e7fe388">

You can get the static ffmpeg for mac os here: https://evermeet.cx/ffmpeg/

**Comment by MrStevns** [comment]
Since there hasn't been any update in two weeks, I'm closing the issue.
