### ISSUE TITLE
🐛 [BUG] - Mac build env instructions out of date

### ISSUE THREAD

**Issue by obscurestar** [pencil2d/pencil#1888]
### Description

Low hanging fruit.  The generated docs just need a bit of an update.

qt-creator app now costs and probably shouldn't be the default.

Brew install directions have also changed.

brew install qt5
brew tap homebrew/cask
brew install --cask qt-creator

worked on my machine but your mileage may vary. 

### Expected result

Build instructions should be current

### Actual result

brew tap caskroom/cask  changed to brew tap homebrew/cask
brew cask install   changed to brew install --cask

### Steps to reproduce

```bash
Follow instructions on developer page at https://dev.pencil2d.org/build_macos.html
```

### System Information

```bash
- Pencil2D version: Any
- Operation system: MacOS
- Drawing tablet: n/a
```

**Comment by MrStevns** [comment]
Hi obscurestar

Thanks for notifying us about this.

As far as I know however, Qt Creator is still the de facto IDE to build and run applications made with Qt framework. Given that we all use it, it's unlikely that we will change that part. 

Qt cost money for commercial projects, which we aren't. It is both possible to use Qt and Qt Creator for free, as such that shouldn't be a concern.
