### ISSUE TITLE
Fixed Render Window

### ISSUE THREAD

**Issue by GraphiXS6** [pencil2d/pencil#193]
Instead of having a dynamic camera layer, I think it would be better to have a fixed size window for the camera whose size would be determined on the creation of a file, similar how to an image editor, e.g. GIMP, does it, or flash, which is a good model for reference.  This makes it much easier to render final animations, especially given the fact that, currently, if you have a camera 1920x1080p, for example, you can't actually see your frame.  It extends outside of the border of your view.  Also, bezier curves for vectors would be awesome.

**Comment by Jose-Moreno** [comment]
@GraphiXS6 Hi, I'm parsing old Pencil2D bugs and requests. I understand you might not be interested in this program anymore, but can I ask you to test the lastest build to see if your old request / issue was fixed already? I believe it was partially addressed with these commits: #7 #332 #334 #408 #485 

Here's the link to Windows and MAC OSX Nightly Builds. Thanks!

Oct 10 2016 Nightly Build Download: https://drive.google.com/drive/folders/0BxdcdOiOmg-CcWhLazdKR1oydHM

p.s. In the future we might re-enable the ability to move the camera, but this will be discussed prior to implementation as it is easier to use these kind of feature than to move every individual layer to achieve panning or zooming effects. Thanks again and take care.

**Comment by GraphiXS6** [comment]
Tested on MacOS 10.11.1.  Yes, that is exactly what I wanted.  I'm not sure which commit fixed it, but seeing the camera bounds on all layers is much better, and the ability to zoom out without it also zooming out the camera view improves usability.  Cheers!

**Comment by Jose-Moreno** [comment]
@GraphiXS6 Thanks lot mate! This was fixed progressively I think, either way happy week!
@chchwy We can close this issue as well now :)

**Comment by chchwy** [comment]
Good. Thanks all.
