### ISSUE TITLE
Size adjust bars not actually changing size

### ISSUE THREAD

**Issue by littlebeast** [pencil2d/pencil#232]
When clicking on the size adjust bars on either side of the marker, the marker moves and the displayed number is updated, but the actual size of the tool does not change.  The tool still draws at the previous size, and if you switch to a different tool and back, the displayed size returns to the previous size.
Dragging the marker to a different position works properly.

This is in Windows, beta 0.5.4.

**Comment by Jose-Moreno** [comment]
@chchwy This bug is no longer present in **Nightly Build Jan 15 2016**. There is a similar issue related to how the sliders work, but I will post that later. I think you can confidently close this issue.

**Comment by feeef** [comment]
I closed it!
