### ISSUE TITLE
[REQUEST] Alpha channel with a Slide-Control value

### ISSUE THREAD

**Issue by ghost** [pencil2d/pencil#237]
Last Nightly build December 9 2013
Win7 Ultimate, SP1 64bits

As @mikshaw wrote here #174 
"Also, it kinda feels weird that the alpha returns to 255 when you change an rgb value. Maybe that was intentional, but it's time consuming to adjust the alpha every time you make a color change."
I would like to add that this behaviour (bug) also applies to the HSV mode.

Here a suggestion for improving the way the Alpha-cahnnel works: after fixing this issue mentioned before, to add a slide-control to the Alpha channel for a fast changing value, just like the Slide-controls added to the drawing tools, just click and drag to change its value.
This will only makes sense, my opinion, for people interesting in doing illustration/painting art with Pencil2D. I realized it while working with an image in which I had to change the Alpha value more than often :)

Thank you all.

**Comment by chchwy** [comment]
No longer an issue in 1 Nov 2017 version. Going to close this.
