### ISSUE TITLE
[BUG] Shortcut Key for Toggled-color-palette stops working

### ISSUE THREAD

**Issue by ghost** [pencil2d/pencil#238]
Last Nightly build December 9 2013
Win7 Ultimate, SP1 64bits

When using the toggled-color-palette (shortcut “C”), in RGB or HSV mode, and change any value on the Saturation/Hue/Value/Alpha´s slides, or Red/Green/Blue/Alpha´s slides, it will make the shortcut to stop working. 
It will only close the palette if tapping on the canvas or in the close/toggle(C) button inside it.

**Comment by CandyFace** [comment]
This bug is invalid now, since the popup palette was removed. Closing.
