### ISSUE TITLE
linux build constantly crashing

### ISSUE THREAD

**Issue by philipzae** [pencil2d/pencil#251]
Well i downloaded the last build of pencil for linux and unfortunately it has been crashing constantly.

one simple example, was me opening pencil, drawing a line and then press ctrl+z to undo and it crashes. This happened the first 2 times i ran pencil, then it didnt happen the third time, and then every now and then happens again. Here is the output from the commandline:

```
"/usr/lib/i386-linux-gnu/qt4/plugins" 
"/usr/bin" 
"/usr/lib/i386-linux-gnu" 
Tool Option Widget connect to Editor 
Set Current Tool ""
```

**Comment by feeef** [comment]
@philipzae could you try with the latest nighly build? (16 Jan.)

I am using the Linux version all the time and never had this kind of crash. It may have been a packaging problem that has been fixed. Could you confirm that?

Thanks.

**Comment by feeef** [comment]
Here is the link to the nightly builds : https://drive.google.com/folderview?id=0B-3xNJ86y4WsSmVUWk5rb2VkcXM&usp=sharing#list

**Comment by philipzae** [comment]
Dont mind building it, if there some build instructions.

**Comment by Jose-Moreno** [comment]
@philipzae The google drive link provided by feeef would be a good start since it was compiled by a user that had Ubuntu 14.04 

As far as I know there's only building instructions for Ubuntu 13.10 here, although the dependencies should vary just slightly:
http://www.pencil2d.org/tutorials/advanced/build-pencil2d-linux/

**Comment by feeef** [comment]
@philipzae you should be able to run the builds from this link with no problem : https://drive.google.com/folderview?id=0B-3xNJ86y4WsSmVUWk5rb2VkcXM&usp=sharing#list

Just download the latest.

**Comment by philipzae** [comment]
I previously downloaded pencil2d-Jan162016.zip and it contained source code files in it (*.cpp, *.h, etc) and i didnt find an executable in their, which was why my last comment. Looking a second time, i found ./app/Pencil2D and on first run it gave the following error.

./Pencil2D: error while loading shared libraries: libQt5Multimedia.so.5: cannot open shared object file: No such file or directory

So then i installed libqt5multimedia5 and then got the following error on execution and dont know how to proceed.

./Pencil2D: symbol lookup error: ./Pencil2D: undefined symbol: _ZN6QDebug9putStringEPK5QCharm

Could this be because i'm running a 64-bit build? I tested the november and december builds and got the same error.

**Comment by feeef** [comment]
Well, I don't know where this error can come from. Do you have QT 5.5.1? We will have to work on packaging the Linux build in a better way!

You can also try to build it yourself. Just install QT 5.5.1 and QT Creator, open the file pencil.pro with QT Creator and do a "Build -> Clean All" to make sure no previous build is interfering, make sure that the build environment is set to "Debug" and "App" (just above the green "Run" button) and press the green "Run" button. 

If you get an error message, hopefully, it should give you a clue on what library you are still missing.

Don't hesitate to let me know if you have any problem!

**Comment by philipzae** [comment]
Ubuntu 14.04 doesnt come with QT 5.5.1, so i dont have that version. The version i have is 5.2.1 and even the latest release of Ubuntu, Ubuntu 15.10, only comes with 5.4.2. If there is a means of upgrading the QT libraries with causing conflicts to my system, i wouldnt mind doing so. If pencil is to have a wide usage on linux, it should have a lower barrier of entry when it comes to system library requirements and should be supported by a released Ubuntu LTS.

If you want to package the linux build in a better way, i'd suggest trying http://appimage.org/

**Comment by feeef** [comment]
Thanks for the feedback and for the link @philipzae !

I agree with you anyway, we should support the most common Linux distributions. Making a standalone binary that works everywhere is the way to go indeed. However, I am not an expert in application packaging so I will have to investigate!

I am myself running Debian Stretch and just switched from Fedora 23. In both of them QT 5.5.1 is the main version so I never had to check about backward compatibility.

**Comment by philipzae** [comment]
I installed QT Creator and attempted to build Pencil and here is the compile output.

[compile output.txt](https://github.com/pencil2d/pencil/files/122327/compile.output.txt)

**Comment by chchwy** [comment]
Hi @philipzae if you are still interested in Pencil2D, please try our recent nightly builds:
http://pencil2d.github.io/download/
I believe the stability has been improved.

I'm going to close this issue, thanks.

**Comment by philipzae** [comment]
Thanks for creating appimages. :D
