### ISSUE TITLE
Doesn't duplicate the frame

### ISSUE THREAD

**Issue by chchwy** [pencil2d/pencil#255]
http://www.pencil2d.org/forums/topic/doesnt-duplicate-the-frame/

With the last github version the program doesn’t duplicate the frame. It only create a new “blank frame”.

These are the msg on my terminal (I have tried several time to duplicate the frame)

The image has been saved in the clipboard
to be pasted —> QSize(991, 645)
The image has been saved in the clipboard
to be pasted —> QSize(991, 645)
TimeLineCell: mouse release event.
LayerImage: mouse release.
TimeLineCell: mouse release event.
LayerImage: mouse release.
The image has been saved in the clipboard
to be pasted —> QSize(991, 645)
The image has been saved in the clipboard
to be pasted —> QSize(991, 645)

**Comment by feeef** [comment]
It has been fixed and duplicating frames works well in the 2 Feb. 2016 build. I close this bug.
