### ISSUE TITLE
Info.plist file in the Mac version of Pencil 2D is missing "CFBundle(...)Version" keys

### ISSUE THREAD

**Issue by carlosgf** [pencil2d/pencil#260]
We’d like to deploy Pencil2D to a large number of university lab computers and have run into an issue.

The Info.plist file in the Mac version of Pencil 2D is missing CFBundleVersion, CFBundleShortVersionString and CFBundleIdentifier keys. I understand this file is generated by Qt/QMake and these keys are not essential for the software to function, but having these keys and ensuring they are accurate with each new version that is released is incredibly important for deploying and managing software on Mac OS X. These keys are typically used by software distribution systems in large enterprise or education environments to determine if a piece of software is up-to-date.

CoreFoundationKeys - https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

Thanks,

Matt Hansen

Systems Administrator
Penn State University

**Comment by carlosgf** [comment]
Hi @chchwy 
I was wondering if this issue is already solved, or not. But I presume, since @hansen-m didn't say anything contrary, that it is OK by now

I am going to close this post, but in case it is not OK, just let me know.
Thank you

**Comment by hansen-m** [comment]
Yes, it was fixed in the special build linked provided above. Any idea when this will be included in the official release?

**Comment by carlosgf** [comment]
@hansen-m 
I don't know sorry. Only @chchwy can tell you something
