### ISSUE TITLE
Duplicate keyframe doesn't copy WHOLE picture when zoom in.

### ISSUE THREAD

**Issue by chchwy** [pencil2d/pencil#261]

**Comment by ManuAros** [comment]
This bug is still present in 5 December 2015 nightly. I consider this a serious issue, you might end up doing a  lot of extra work if you forget about this bug when drawing.

**Comment by feeef** [comment]
It has been fixed in one of the latest builds and I just verified that it is working in the 2 Feb. 2016 build. I close it.

**Comment by ManuAros** [comment]
Super ! Thanks
