### ISSUE TITLE
crash while exporting a movie

### ISSUE THREAD

**Issue by mapreri** [pencil2d/pencil#265]
pencil2d crashes while exporting a movie (I've only draw a line and then click the export > movie option).
This is with the b8bd62b33829c04155fb89e62f0a0b764704324c commit.

This is what gdb tells me reading the core dump:
```
Reading symbols from /usr/bin/pencil2d...Reading symbols from /usr/lib/debug/.build-id/a0/536734ffc256321128d0aa5471316f7af01060.debug...done.
done.
[New LWP 17285]
[New LWP 17286]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `pencil2d'.
Program terminated with signal SIGFPE, Arithmetic exception.
#0  0x00007fdcaecab204 in Object::exportFrames1 (this=this@entry=0x7fdcaf226480, par=...) at structure/object.cpp:564
564	structure/object.cpp: No such file or directory.
```

I noted this trying to understand why you closed #257 without a commit (I don't see any commit fixing it).

**Comment by feeef** [comment]
This bug is related to this one https://github.com/pencil2d/pencil/issues/290 and will require a refactoring of the video export feature. I close it.
