### ISSUE TITLE
can't select/drag frames on the timeline

### ISSUE THREAD

**Issue by mikshaw** [pencil2d/pencil#267]
http://www.pencil2d.org/forums/topic/moving-frames-in-the-timeline/

Not sure if this just showed up, or if it's been around since Qt5 has been used. Clicking individual keyframes has no effect.

Debian testing (jessie) 64-bit, Intel HD4000 gpu, Qt 5.3.1

**Comment by Zamarx** [comment]
This is still broken guys.

The issue seems to be in layer.cpp  (or layers.cpp I cant remember),
where all of the interaction functions are literally not written, these being the mouse input functions.

**Comment by carlosgf** [comment]
@chchwy,
You may close this one since it is already fixed/implemented with the last Build (18 Dec 2015)
:+1:

**Comment by feeef** [comment]
It has been implemented indeed! I close it.
