### ISSUE TITLE
Sound Layer never previews or exports in Windows versions of Pencil

### ISSUE THREAD

**Issue by AtsusaKaneytza** [pencil2d/pencil#270]
I'm a Windows 8 user, and I still have yet to find Free or Open Source software that will work seamlessly with Sound files, which is a crucial feature I am desperately looking for. Pencil2D could be that program, but the feature never works in the Windows version of the program. No matter what correct file format I try to import, how short the file is, or how small the file size is, the sound never works.

**Comment by Jose-Moreno** [comment]
@AtsusaKaneytza Hi. I'm sure you're no longer interested in Pencil2D. But we have a new build that implements sounds and videos are exported with sound. Can you confirm this works for you? and if it does please close this issue. Thanks.

You can download the latest Oct 10 2016 Nightly Build here:

https://drive.google.com/drive/folders/0BxdcdOiOmg-CcWhLazdKR1oydHM

**Comment by AtsusaKaneytza** [comment]
will give it a try, thank you for keeping me updated!

**Comment by Jose-Moreno** [comment]
@chchwy @CandyFace We can close this now.
