### ISSUE TITLE
Compile error about Qt

### ISSUE THREAD

**Issue by carldong** [pencil2d/pencil#271]
When I try to compile (both master and dev), I get this error. I will also try to fix it

cd 3rdlib/zlib/ && make -f Makefile 
make[1]: Entering directory `/home/carl/src/Pencil/build/3rdlib/zlib'
make[1]: Nothing to be done for `first'.
make[1]: Leaving directory `/home/carl/src/Pencil/build/3rdlib/zlib'
cd 3rdlib/quazip/ && make -f Makefile 
make[1]: Entering directory `/home/carl/src/Pencil/build/3rdlib/quazip'
make[1]: Nothing to be done for `first'.
make[1]: Leaving directory `/home/carl/src/Pencil/build/3rdlib/quazip'
cd core_lib/ && make -f Makefile 
make[1]: Entering directory `/home/carl/src/Pencil/build/core_lib'
g++ -c -pipe -std=c++11 -O2 -fPIC -D_REENTRANT -Wall -W -DQUAZIP_BUILD -DQUAZIP_STATIC -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_SVG_LIB -DQT_XMLPATTERNS_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../../pencil/core_lib -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtXmlPatterns -I/usr/include/qt4/QtSvg -I/usr/include/qt4/QtMultimedia -I/usr/include/qt4 -I../../pencil/core_lib/graphics -I../../pencil/core_lib/graphics/bitmap -I../../pencil/core_lib/graphics/vector -I../../pencil/core_lib/interface -I../../pencil/core_lib/structure -I../../pencil/core_lib/tool -I../../pencil/core_lib/util -Iui -I../../pencil/core_lib/managers -I../../pencil/core_lib/external/linux -I../../pencil/3rdlib/quazip -I../../pencil/3rdlib/zlib -I.moc -I. -I../../pencil/core_lib -I. -o .obj/colorpalettewidget.o ../../pencil/core_lib/interface/colorpalettewidget.cpp
In file included from /usr/include/qt4/QtGui/QListWidget:1:0,
                 from ../../pencil/core_lib/interface/colorpalettewidget.cpp:17:
/usr/include/qt4/QtGui/qlistwidget.h: In constructor ‘ColorPaletteWidget::ColorPaletteWidget(QString, QWidget*)’:
/usr/include/qt4/QtGui/qlistwidget.h:271:10: error: ‘void QListWidget::currentItemChanged(QListWidgetItem*, QListWidgetItem*)’ is protected
     void currentItemChanged(QListWidgetItem *current, QListWidgetItem *previous);
          ^
../../pencil/core_lib/interface/colorpalettewidget.cpp:41:49: error: within this context
     connect( ui->colorListWidget, &QListWidget::currentItemChanged, 
                                                 ^
../../pencil/core_lib/interface/colorpalettewidget.cpp:42:69: error: no matching function for call to ‘ColorPaletteWidget::connect(QListWidget*&, void (QListWidget::*)(QListWidgetItem*, QListWidgetItem*), ColorPaletteWidget* const, void (ColorPaletteWidget::*)(QListWidgetItem*, QListWidgetItem*))’
              this, &ColorPaletteWidget::colorListCurrentItemChanged );
                                                                     ^
../../pencil/core_lib/interface/colorpalettewidget.cpp:42:69: note: candidates are:
In file included from /usr/include/qt4/QtCore/qiodevice.h:46:0,
                 from /usr/include/qt4/QtCore/qdatastream.h:46,
                 from /usr/include/qt4/QtCore/qpair.h:45,
                 from /usr/include/qt4/QtCore/qhash.h:49,
                 from /usr/include/qt4/QtCore/qdebug.h:46,
                 from /usr/include/qt4/QtCore/QtDebug:1,
                 from ../../pencil/core_lib/interface/colorpalettewidget.cpp:16:
/usr/include/qt4/QtCore/qobject.h:204:17: note: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
     static bool connect(const QObject *sender, const char *signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from ‘void (QListWidget::*)(QListWidgetItem*, QListWidgetItem*)’ to ‘const char*’
/usr/include/qt4/QtCore/qobject.h:217:17: note: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
     static bool connect(const QObject *sender, const QMetaMethod &signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from ‘void (QListWidget::*)(QListWidgetItem*, QListWidgetItem*)’ to ‘const QMetaMethod&’
/usr/include/qt4/QtCore/qobject.h:337:13: note: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
 inline bool QObject::connect(const QObject *asender, const char *asignal,
             ^
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from ‘void (QListWidget::*)(QListWidgetItem*, QListWidgetItem*)’ to ‘const char*’
In file included from /usr/include/qt4/QtGui/qpushbutton.h:45:0,
                 from /usr/include/qt4/QtGui/QPushButton:1,
                 from ./ui_colorpalette.h:19,
                 from ../../pencil/core_lib/interface/colorpalettewidget.cpp:30:
/usr/include/qt4/QtGui/qabstractbutton.h:127:10: error: ‘void QAbstractButton::clicked(bool)’ is protected
     void clicked(bool checked = false);
          ^
../../pencil/core_lib/interface/colorpalettewidget.cpp:50:48: error: within this context
     connect( ui->addColorButton, &QPushButton::clicked, this, &ColorPaletteWidget::clickAddColorButton );
                                                ^
../../pencil/core_lib/interface/colorpalettewidget.cpp:50:104: error: no matching function for call to ‘ColorPaletteWidget::connect(QPushButton*&, void (QAbstractButton::*)(bool), ColorPaletteWidget* const, void (ColorPaletteWidget::*)())’
     connect( ui->addColorButton, &QPushButton::clicked, this, &ColorPaletteWidget::clickAddColorButton );
                                                                                                        ^
../../pencil/core_lib/interface/colorpalettewidget.cpp:50:104: note: candidates are:
In file included from /usr/include/qt4/QtCore/qiodevice.h:46:0,
                 from /usr/include/qt4/QtCore/qdatastream.h:46,
                 from /usr/include/qt4/QtCore/qpair.h:45,
                 from /usr/include/qt4/QtCore/qhash.h:49,
                 from /usr/include/qt4/QtCore/qdebug.h:46,
                 from /usr/include/qt4/QtCore/QtDebug:1,
                 from ../../pencil/core_lib/interface/colorpalettewidget.cpp:16:
/usr/include/qt4/QtCore/qobject.h:204:17: note: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
     static bool connect(const QObject *sender, const char *signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from ‘void (QAbstractButton::*)(bool)’ to ‘const char*’
/usr/include/qt4/QtCore/qobject.h:217:17: note: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
     static bool connect(const QObject *sender, const QMetaMethod &signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from ‘void (QAbstractButton::*)(bool)’ to ‘const QMetaMethod&’
/usr/include/qt4/QtCore/qobject.h:337:13: note: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
 inline bool QObject::connect(const QObject *asender, const char *asignal,
             ^
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from ‘void (QAbstractButton::*)(bool)’ to ‘const char*’
In file included from /usr/include/qt4/QtGui/qpushbutton.h:45:0,
                 from /usr/include/qt4/QtGui/QPushButton:1,
                 from ./ui_colorpalette.h:19,
                 from ../../pencil/core_lib/interface/colorpalettewidget.cpp:30:
/usr/include/qt4/QtGui/qabstractbutton.h:127:10: error: ‘void QAbstractButton::clicked(bool)’ is protected
     void clicked(bool checked = false);
          ^
../../pencil/core_lib/interface/colorpalettewidget.cpp:51:51: error: within this context
     connect( ui->removeColorButton, &QPushButton::clicked, this, &ColorPaletteWidget::clickRemoveColorButton );
                                                   ^
../../pencil/core_lib/interface/colorpalettewidget.cpp:51:110: error: no matching function for call to ‘ColorPaletteWidget::connect(QPushButton*&, void (QAbstractButton::*)(bool), ColorPaletteWidget* const, void (ColorPaletteWidget::*)())’
     connect( ui->removeColorButton, &QPushButton::clicked, this, &ColorPaletteWidget::clickRemoveColorButton );
                                                                                                              ^
../../pencil/core_lib/interface/colorpalettewidget.cpp:51:110: note: candidates are:
In file included from /usr/include/qt4/QtCore/qiodevice.h:46:0,
                 from /usr/include/qt4/QtCore/qdatastream.h:46,
                 from /usr/include/qt4/QtCore/qpair.h:45,
                 from /usr/include/qt4/QtCore/qhash.h:49,
                 from /usr/include/qt4/QtCore/qdebug.h:46,
                 from /usr/include/qt4/QtCore/QtDebug:1,
                 from ../../pencil/core_lib/interface/colorpalettewidget.cpp:16:
/usr/include/qt4/QtCore/qobject.h:204:17: note: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
     static bool connect(const QObject *sender, const char *signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from ‘void (QAbstractButton::*)(bool)’ to ‘const char*’
/usr/include/qt4/QtCore/qobject.h:217:17: note: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
     static bool connect(const QObject *sender, const QMetaMethod &signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from ‘void (QAbstractButton::*)(bool)’ to ‘const QMetaMethod&’
/usr/include/qt4/QtCore/qobject.h:337:13: note: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
 inline bool QObject::connect(const QObject *asender, const char *asignal,
             ^
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from ‘void (QAbstractButton::*)(bool)’ to ‘const char*’
make[1]: *** [.obj/colorpalettewidget.o] Error 1
make[1]: Leaving directory `/home/carl/src/Pencil/build/core_lib'
make: *** [sub-core_lib-make_default] Error 2

**Comment by feeef** [comment]
It is a late reply but I had the same problem on fedora. I just needed to install qt5-qttools-devel. The name should be close on gentoo.

**Comment by mapreri** [comment]
whatever this is not a pencil2d problem

@chchwy maybe close this?

**Comment by chchwy** [comment]
Thanks everybody. :)
