### ISSUE TITLE
[bug] Layers - Pencil Mac 

### ISSUE THREAD

**Issue by Kastellie** [pencil2d/pencil#277]
I am on a mac and I've seen people on mac's create and delete bitmap layers in Pencil. I also cannot delete vector layers. I also have a problem with seeing my previously drawn picture or any of my lines on the 'paper'. I've tried uninstalling and reinstalling to see if there was a break in the download and there wasn't. I've looked for updates and I haven't found any. I would like some help.

**Comment by CandyFace** [comment]
What version of OS X are you using? also.. based on your description, It sounds like you used the 0.5.4 build, available from Pencil2d.org. Is that correct?

What approach do you take when creating layers?
eg. pressing the Layers: (+) (-) or Layer->New Bitmap layer?
