### ISSUE TITLE
[BUG] PENCILtool icon is an arrow

### ISSUE THREAD

**Issue by carlosgf** [pencil2d/pencil#279]
(Nightly Build JAN 13 2015)
WIN8

When opening Pencil for the first time, the PENCILtool CURSOR is showed as an arrow. 
Selecting another tool and going back to the PENCILtool again solves the issue.

**Comment by carlosgf** [comment]
@chchwy 
Thank you. It is working fine

**Comment by chchwy** [comment]
Thank you @carlosgf
