### ISSUE TITLE
Making special canvases for different works/documents

### ISSUE THREAD

**Issue by ghost** [pencil2d/pencil#28]
REQUEST:
Hi,
Having at least two different fixed "Canvas or documents" from which we can select the kind of work we are interested to start pencil.
We can call those new "canvases" by the name of "rooms", which will help the work-flow of Pencil as follow:

One room designed for SKETCHING: It will have ONLY the drawing tools panel (left) and colours tool panel (right)

Another room for ANIMATION: It will have ALL the panels already associated to the standard opening of Pencil, with the addition of the new 3-Pencils (red, blue, black) AND the addition of 2 more FIX LAYERS (background on the top, Rough or In-between on second. After this we have the Cleaning Layer, Vector Layer, Camera Layer.

I believe those rooms will be enough for a faster start of a project (animation) or improving new art concepts (sketches).

The icons related to the rooms can be put following the icon FPS (bottom right)

If all of this is not possible to achieve, at least the "Animation-room" should be implemented on the standard opening of Pencil.

PD: Of course, those panels from the animation and sketching rooms which ar not active (hidden) can be altered as active on the main menu, or something similar

**Comment by Jose-Moreno** [comment]
I think this would make Pencil2D kind of complex. This is a similar notion as what happens in TVPaint or in OpenToonz. I'd like a workspace preset configuration, where the user can rearrange to his liking and save the panel positions, but creating a complex room feature seems unnecesary. This should be discussed further though.

**Comment by chchwy** [comment]
won't implement.
