### ISSUE TITLE
[BUG] PENCIL2D closes without a pop-up message

### ISSUE THREAD

**Issue by ghost** [pencil2d/pencil#282]
(Nightly Build JAN 13 2015)
WIN8

Pencil does not show a message for alerting users to save their work before closing Pencil

**Comment by carlosgf** [comment]
This is kind of important for some users. 
It is not an issue itself since Pencil closes OK, but there is still no pop up window message warning users that Pencil will close before saving any work.

**Comment by chchwy** [comment]
Duplicated of #387
