### ISSUE TITLE
[BUG] EXPORTED Images are saved incompleted

### ISSUE THREAD

**Issue by ghost** [pencil2d/pencil#284]
(Nightly Build JAN 13 2015)
WIN8

Opening Pencil for the first time will show the main window with a vertical and horizontal line joined at the centre (resembling a Cross)
The UPPER-LEFT quarter is the only part of the main window that is rendered as an image. 
So the final exported image will be cut off by ¾.

(it is like the camera view is attached to that particular quarter)

**Comment by feeef** [comment]
I didn't get the time to work on the camera but it is in my to-do list.

Keyframing camera movements is part of the great Pencil2D features I wish to restore as well.

**Comment by carlosgf** [comment]
:+1: 
The work around is easy, but it will be better to have it fixed, of course.

I have read "numerous" complains about the keyfraiming camera movements, but I found it to be a very clever feature.

**Comment by feeef** [comment]
Camera movements should have ease in and ease out to look cool. 

This kind of feature should be developed in a way that is adjustable in the future.

There should be an independent class that handles animated transmations. This way, it will be much easier to implement tweening for any object as well. I would even add animated opacity to this class.

At the end, Pencil2D could integrate  some cool compositing features.

**Comment by aecepoglu** [comment]
Well I primarily care about having the camera work, and not so much about the camera transition animations.

**Comment by feeef** [comment]
I understand that @aecepoglu. What I mean is that I will fix the camera but will do it in a certain way that makes easy to build around it.

I won't be able to fix it before january though.

**Comment by feeef** [comment]
The camera movement feature is not implemented but the problem of the image being cut by 3/4 has been fixed in previous builds so I close this issue.
