### ISSUE TITLE
[BUG] list of SHORTCUTS on the Preference-Panel that DOES NOT WORK

### ISSUE THREAD

**Issue by ghost** [pencil2d/pencil#286]
(Nightly Build JAN 13 2015)
WIN8

Most of the features (listed on the column 1) of the Preference-Panel SHORTCUT-tab work OK
Although it is possible to assign a different shortcut letter to any of the features on the Column 1, some of them will not work at all.

The following shortcut-features do not work
GotoNextframe
GotoPreviousFrame
Ctrl+X (doesn’t work every time)
DeleteCurrentLayer
Exit (Ctrl+Q)
ExportMovie
ExportSvgImage
ExportXsheet

FlipHorizontal (there is an Horizontal-icon on the “DISPLAY OPTIONS” panel, but does not work either)
FlipVertical (there is a Vertical-icon on the “DISPLAY OPTIONS” panel with no effect either)

Importimage (it opens a new window, but none of the file extension I tried were imported successfully)
ImportImageSequence (it opens a new window, but none of the file extension I tried were imported successfully)

MoveFramebackward
NewFile (it works fine, but there is no pop up warning preventing users for saving any changes before closing Pencil)
Alt+P
Ctrl+P

RotateAntiClockWise (by the way, it is written RotateAntiCLOSEwise)
RotateClockWise

ToolHand (it sometimes causes Pencil to crash)

ZoomIn (it makes every content on the main window to disappear)
ZoomOut (it makes every content on the main window to disappear)

**Comment by Kaikogf** [comment]
I have re-checked every bug mentioned here and most of them were already fixed. So I decided to close this and to open a new post with the few remaining issues on this list, but with the same title (numbered 2)

Thank you for keeping this moving
👍

**Comment by Kaikogf** [comment]
Sorry, I forgot that I have lost my ghost login.

@chchwy 
Would you mind to close this post? 

Thank you
