### ISSUE TITLE
Pecil 2d sound don't work

### ISSUE THREAD

**Issue by Pencil2dis** [pencil2d/pencil#289]
When I import sound into pencil2d I don't hear anything.Note this is windows version

**Comment by AtsusaKaneytza** [comment]
There's an old version of pencil (for Windows) where the sound works, which is found here:
http://www.pencil2d.org/forums/topic/fix-the-photon-plugin/#post-25160

The problem with it though is that the playback skips or is choppy and doesn't work correctly.

**Comment by cbradyatinquire** [comment]
the link to the working windows version is now inaccessible.  does anyone have access to the Windows version referenced here where sound works?

**Comment by wintre** [comment]
Try this: http://www.davidefabbri.net/files/pencil/old_code_win_2011-03-22.zip

**Comment by Jose-Moreno** [comment]
@chchwy This needs to be closed, since sound already can be imported in latest Nightly Build.
