### ISSUE TITLE
unable to export as movie

### ISSUE THREAD

**Issue by punpon** [pencil2d/pencil#290]
when i try to export something as a movie it gives me this error: http://i.gyazo.com/fc37eb1a58e40d4ac9ba581424188060.png

it goes as far as opening the file location and options, but it doesn't actually export and just gives me that error instead.

**Comment by hako** [comment]
Pencil needs [ffmpeg](http://www.ffmpeg.org) to export to movies, you can download it [here](http://ffmpeg.zeranoe.com/builds/win32/static/ffmpeg-20150220-git-6c91afe-win32-static.7z) and put it in the plugins directory.

**Comment by hako** [comment]
It doesn't look like the plugins directory exists though as far as I know.

**Comment by mikshaw** [comment]
i'm not sure why mapreri said ffmpeg is dead. It's only been replaced as default in some linux systems, but even in that case the ffmpeg name is still retained as a symlink for compatibility.

Go to http://ffmpeg.zeranoe.com/builds/ for binary versions for Windows (this site is linked from the offficial ffmpeg website). The static versions contain everything necessary to run it as a standalone program. Create a "plugins" directory in the pencil2d installation folder and drop the ffmpeg.exe file into that.

Even after doing this, some types of video still might not work. I seem to remember it failing to make a mov file on windows.  As i understand it, a unified video renderer is planned at some point in the future.

**Comment by markinfo** [comment]
ffmpeg is not dead. For example in Debian is back again.
https://packages.qa.debian.org/f/ffmpeg.html

**Comment by feeef** [comment]
No, ffmpeg is not dead at all and I think that Pencil2D should include MLT, which is based on ffmpeg in future versions.
MLT would add the ability to do much more than import / export.

**Comment by thediamondlion2** [comment]
You Do Know Instead Of Exporting It As A Movie Or Anything You Could Record Your Animation.. Use Microsoft Encoder 4 Pro Screen Capture And Adjust The Size Of The Red Lines.. These Show You What The Screen Recorder Will Record. After That Play Your Animation And Start Recording, Stop Recording If You Need To

**Comment by Jose-Moreno** [comment]
@feeef You commented earlier this year about MLT before. But it seems that movie export was implemented again to work with ffmpeg. Do you think we should discuss this further? or should we stay with ffmpeg?

**Comment by feeef** [comment]
@Jose-Moreno, I think you can close this bug if it is fixed with ffmpeg. We may discuss about MLT later if we need it for required features which is not the case at the moment.

**Comment by feeef** [comment]
Actually, I have closed it myself.
