### ISSUE TITLE
[BUG] fill on bitmap layer only fills 1-pixel lines

### ISSUE THREAD

**Issue by pioggia** [pencil2d/pencil#294]
Whenever I try to use the bucket fill on a second bitmap layer underneath my main bitmap (so I can have one consistent background color through the whole animation), it only fills out a one-pixel-thick line. This happens no matter how many times I click the canvas. Am I doing it wrong, or is there a better way to have a consistent background?

**Comment by carlosgf** [comment]
@pioggia 
Hi
I know it is kind of a bug while filling shapes with the Bucket tool: Not sure which Pencil version you are using but at the moment the Bucket tool doesn't work on Vector layers also. It may be related to your issue.

(there was a trick used with some versions of Pencil _don't recall which, that would allow to fill a shape using the bucket tool: if you wanted to fill a bitmap shape you had to add a Vector layer (try it under or over the bitmap layer). That would do the trick.

Hope this may help you on this

**Comment by pioggia** [comment]
I tried filling a vector layer, but as you said, it's not working (in 0.5.4, it gives an Error: out of bounds). Hmm....I guess I'll just redo the background for every frame then. Thanks for your reply!

**Comment by carlosgf** [comment]
@pioggia 
Sorry but I did not make myself understood.
I was saying that you add a VECTOR layer as following: try to add it firstly above,and than below, the actual BITMAP layer you are using). Next do your things filling the shapes on the BITMAP layer as you pretended to see if it works 
(the vector layer is NOT meant to be touched :) ... I don't recall exactly remember how to do those things :) )

See what you get!

**Comment by pioggia** [comment]
It worked! Thank you so much for your help :D
