### ISSUE TITLE
[request] faster way to use eyedropper

### ISSUE THREAD

**Issue by pioggia** [pencil2d/pencil#295]
While I'm ok with the way it currently works, I would like it if there was a faster way to switch between the eyedropper and the current tool. I use the eyedropper every few seconds, and it's just not intuitive to keep moving my hand across the keyboard for the shortcuts, especially when I use a tablet. So what I would like is something like a "temporary" color select: for instance, the eyedropper only shows when the alt/option key is pressed, and when the key is released it goes back to whatever tool you were using.

**Comment by carlosgf** [comment]
@pioggia 
Hi
Your question is answered here: 
http://www.pencil2d.org/forums/topic/pencil2d-keyboard-shortcuts-and-new-features/

Meanwhile if you see that the eyedropper is working like you pretended, consider to close this issue :+1:
