### ISSUE TITLE
[Improvement] The NEW button needs to be worked out

### ISSUE THREAD

**Issue by carlosgf** [pencil2d/pencil#300]
Pencil2D build with MasterCode 08APRIL2015
WIN8.1

The NEW button (Main Menu FILE -> NEW) works so-so. It will bring an empty new canvas and will delete any new frame or layer added before, but it will NOT Reset the Zoom/Rotate changes. 
It will also do NOT delete immediately the frames added before on the Timeline, they will still be visible till you hit its LAYER on the time line bar (not always happens this way, but mostly yes)

**Comment by carlosgf** [comment]
Tested with the last Nightly Build (14Dec2015)
Win8,1x64bits

I found another "issue" inside this issue, so I am going to keep it open till both of them are fixed.

The new issue is not an Issue but it requires a new label: a REQUEST.
After opening Pencil2D, and selecting FILE > NEW, it will bring the CAMERA First Frame as the active one (the default was always the Bitmap First Frame). 
It is not about what LAYER was selected. It will always bring the Camera First Frame as active while showing a Bitmap (or Vector) Layer selected (you are not going to be able to draw this way)

Hope you understand developers
:)

**Comment by carlosgf** [comment]
Duplicate issue

**Comment by feeef** [comment]
Actually @ghost , this issue was more than just a timeline issue. Zoom/rotate has to be reset as well as having the bitmap layer selected by default. You should re-open this bug and I will close mine as I have not been able to reproduce the broken state of the timeline it.

**Comment by feeef** [comment]
No need to re-open this issue. I have fixed it and it will be on my next pull request
