### ISSUE TITLE
[BUG] Pencil2D doesn't save changes configurations after closing

### ISSUE THREAD

**Issue by carlosgf** [pencil2d/pencil#306]
Pencil2D build with MasterCode 08APRIL2015
WIN8.1

Making any changes over the following tools: 
- SIZE and FEATHER values (TOOLS PANEL)
- PRESSURE ALPHA and INVISIBLE Select-BOXES (OPTIONS PANEL)
- and on any other tools on the DISPLAY OPTIONS PANEL
will make no effect after re-opening Pencil2D

**Comment by feeef** [comment]
It should be fixed after the latest merge from my branch

**Comment by carlosgf** [comment]
@feeef 
I will check it.
Thanks

**Comment by carlosgf** [comment]
UPDATED:
Last build from 01July2015 
Win8.1

The Size and Feather values of the drawing tools are fixed (the changes are correctly saved even when restarting Pencil2D)

Pressure Alpha's Box and Invisible's Box are not there any more, nor in Vector nor in Bitmap layer's tools.

The options on the DISPLAY OPTIONS PANEL on the right bottom works OK and any changes on these values will keep it that way while working with Pencil. But those changes will not be saved after closing Pencil2D, it will be opened with its default settings (the Grid feature is the only one to be saved correctly after closing the program)

Not sure if it is OK to CLOSE this Issue since the main features presented here were already fixed (thanks @feeef)  while the few remaining may not be considered to be an issue at all

**Comment by feeef** [comment]
OK, you should keep it open then!

**Comment by carlosgf** [comment]
Everything OK on the new Nightly Build (14Dec2015)
Win8.1x64bits

Thanks!
