### ISSUE TITLE
[BUG ??] The EYEDROPER-tool doesn't recognize the White Canvas.

### ISSUE THREAD

**Issue by carlosgf** [pencil2d/pencil#311]
Pencil2D build with MasterCode 08APRIL2015
WIN8.1

I have noticed that the white colour of an empty canvas is not detected as a White Colour by the Eyedropper-tool.
When painting several strokes or colour-patches all over the canvas leaving some white areas on the canvas without colouring it, the EYEDROPPER is unable to identify it as White (Is it supposed to behave like this? I don't know)

But if you use white colour while painting the whole canvas, than the eyedropper will allow to pick up the colour on the Colour Wheel

**Comment by 2003cah** [comment]
it's because (apparently) you need to paint the canvas white before you can use the eye dropper to make it white. So to answer your question, yes it's supposed to behave like that

**Comment by carlosgf** [comment]
@2003cah 
If that is the case, then I can close this issue for there is no Bug at all, in order to keep ISSUES clean.
I will wait till @chchwy will say something about.

Thanks!

**Comment by carlosgf** [comment]
Apparently no bug here

Thank you
