### ISSUE TITLE
Buggy Mac Version.

### ISSUE THREAD

**Issue by rooble** [pencil2d/pencil#313]
Attempting to export the movie results in nothing happening; no file can be found anywhere. 
Importing sound crashes the program. 
Despite these problems being addressed for windows, I cannot find a solution for OSX. 
Operating on OSX 10.10.2.

**Comment by BurntMuffin18** [comment]
I am having these problems as well currently. Operating on OSX 10.10.5

**Comment by Jose-Moreno** [comment]
@BurntMuffin18 Both video export and sound import are disabled in current Pencil2D versions meanwhile the developers work to fix it, considering they were broken to begin with. 

Also it is well known that the download version of Pencil2D will not work properly in Mac OSX. Only our Nightly Builds have been reported to work in MAC as of late, however the functionality you are asking for is still in development.

To by pass the video export issue, and make videos please read our FAQ: http://www.pencil2d.org/pencil2d/faq/

To download the latest Nightly  Build please visit this link and pick the most recent version, not that Nightly Builds are experimental and don't represent the final app, it's just a step closer to the finish.

https://drive.google.com/drive/folders/0BxdcdOiOmg-CcWhLazdKR1oydHM#list

**Comment by Jose-Moreno** [comment]
@chchwy we should close this as you've already restored movie export and sound import on MAC OSX.
