### ISSUE TITLE
[BUG] Pen tool in vector layer makes Pencil hang consistently

### ISSUE THREAD

**Issue by tinwelint** [pencil2d/pencil#314]
When sketching with the Pen tool, one or more strokes a second or so, now and then (perhaps every 100 or 200) strokes Pencil just hangs. The window says (Not responding) and the cursor is busy. A force kill of the app is required, and the work is lost.

At the time of this event my task manager says that CPU usage of Pencil.exe is 8%, stable over time, although memory usage rises slowly but steadily, 1M every 10s roughly. It continues like that until the application is killed, no matter how long I wait.

**Comment by JonasThomas** [comment]
@tinwelint

**Comment by JonasThomas** [comment]
@tinwelint  Do you happen to remember if this was happening in vector or bitmap mode.. (How many frames did you have loaded?)  What OS?
I was trying to replicate your problem but couldn't..    I tried testing drew about about a 100 lines in bitmap pencil mode and releasized you said pen.  I think I changed to pen did a file new and got a seg fault..(This is a different issue I think). (I tried repeating and couldn't replicated it)

**Comment by tinwelint** [comment]
Hey, I'm on Windows 10 right now... may have been on Windows 8.1 when it
happened and it was in vector mode. I made the strokes with a Wacom tablet
if that makes a difference. The thing about it was that it was super
consistent and easy to reproduce... probably still is. I'll check back in a
while to try and reproduce this again on all the latest things.

Thanks for taking your time with this. Cheers

On Mon, Jan 25, 2016 at 2:21 AM, Jonas Thomas <notifications@github.com>
wrote:

> @tinwelint <https://github.com/tinwelint> Do you happen to remember if
> this was happening in vector or bitmap mode.. (How many frames did you have
> loaded?) What OS?
> I was trying to replicate your problem but couldn't.. I tried testing drew
> about about a 100 lines in bitmap pencil mode and releasized you said pen.
> I think I changed to pen did a file new and got a seg fault..(This is a
> different issue I think). (I tried repeating and couldn't replicated it)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencil2d/pencil/issues/314#issuecomment-174365765>.
>



-- 
Mattias Persson
Neo4j Hacker at Neo Technology

**Comment by JonasThomas** [comment]
@tinwelint  I give a it a couple a couple of days before you try it out.   There are a few pull requests that haven't been merged into the master that I think address some serious bugs.  At least one of them tinkers with the polyline.  If your going to beat up the polyline, I think it would be better when the latest updates have been incorporated.

**Comment by tinwelint** [comment]
Thanks, I'll await the next round of changes and try again!

On Tue, Jan 26, 2016 at 3:21 AM, Jonas Thomas <notifications@github.com>
wrote:

> @tinwelint <https://github.com/tinwelint> I give a it a couple a couple
> of days before you try it out. There are a few pull requests that haven't
> been merged into the master that I think address some serious bugs. At
> least one of them tinkers with the polyline. If your going to beat up the
> polyline, I think it would be better when the latest updates have been
> incorporated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencil2d/pencil/issues/314#issuecomment-174780732>.
>



-- 
Mattias Persson
Neo4j Hacker at Neo Technology

**Comment by Jose-Moreno** [comment]
@tinwelint Sorry to bother you Mattias, I'm sure you don't use Pencil2D anymore, but if you don't mind could you test the latest Nightly Build for Windows? Latest Windows 64bit version is **Pencil2D-win64-20161102.zip** on the following link:

https://drive.google.com/drive/folders/0BxdcdOiOmg-CSVlqc3JNQV9hVGs

Let us know if this issue has been fixed for you and if possible close it. Thanks!

**Comment by Kaikogf** [comment]
Despite the vector tools (PEN and BRUSH) are far from working OK on VECTOR layers, I tested this Issue and it worked fine, no hang, no crash, no bug.

**Comment by Jose-Moreno** [comment]
@chchwy @CandyFace should we close this one? I'm not having issues with the vector layer performance on the latest version for Windows 7, but if someone can try on Windows 10, and MAC to confirm it would be appreciated.

**Comment by Jose-Moreno** [comment]
@chchwy @CandyFace Although I forgot to mention that someone recently mentioned that they had a slowdown on playback speed while using exclusively vector layers if you want to check out the claim it's on the forum here:
https://www.pencil2d.org/forums/topic/speed-slows-down/

**Comment by CandyFace** [comment]
i think it's safe to assume that this doesn't happen anymore. I haven't experienced a hang using the tools for a very long time, so in my opinion, we should be able to close this.

**Comment by chchwy** [comment]
Hi @tinwelint

Thanks for your interest in Pencil2D.
If you still like to use Pencil2D please try our new version: http://pencil2d.github.io/download/
It has been improved a lot and gotten tons of bug fixes.

Please don't hesitate to contact us if you still get something wrong.
I'm gonna to close this :)
