### ISSUE TITLE
[BUG?] Pressure sensitive is not working

### ISSUE THREAD

**Issue by carlosgf** [pencil2d/pencil#315]
Pencil2D build with MasterCode of 27APRIL2015
WIN8.1

It may not be a Bug since I am using a different driver for my pressure sensitivity tablet. So i will check it later. Meanwhile it is behaving as a Bug.

The pressure sensitive is not working in any of the drawing tools, despite the Size Pressure's box is toggled on

EDITED: refers to the issue #301

**Comment by MattJordan** [comment]
I haven't seen pressure sensitivity working for some time now across several builds and on several different systems.  Main reason I sort of abandoned using Pencil2D.

**Comment by carlosgf** [comment]
@MattJordan 
Last build pressure sensitive was working just fine. And it was not long ago, March 2015.
I@chchwy was working over the Pressure Sensitive check-box's  bug, and that may have interfered with the Pressure itself

**Comment by MattJordan** [comment]
@carlosgf 
Okay, at least by this weekend I'll try that build and the more recent one and see what happens.  (If I can get to it sooner, I will.) Thanks for the update.

**Comment by carlosgf** [comment]
Hi @chchwy 

The pressure sensitivity is working just fine. I tested it right now . The problem was with my tablet drivers (I had to format my PC, extreme way by the way)

I am going to close this issue
