### ISSUE TITLE
Missing components

### ISSUE THREAD

**Issue by 2003cah** [pencil2d/pencil#316]
I realized the zip folder is missing some rather important extensions. these extensions allow the ability to export to any type of file (.mov, avi, gif, etc.) I have the beta edition, is there any way to fix the issue or get an older version?

**Comment by tasaif** [comment]
Does Pencil2D support these extensions?
@chchwy @feeef

**Comment by feeef** [comment]
Yes, Pencil was supporting these extentions but I disabled them a few weeks ago as they were broken and need to be remade.
We may need to get a universal library that handles audio and video input/output. This should be discussed with @chchwy. He will know more than me how these features were developed in previous versions of Pencil.

**Comment by Jose-Moreno** [comment]
@chchwy @feeef we should close this as Matt has already re-implemented mp4, avi, gif export. We don't have mov yet, but mp4 can be used instead pr converted easily.
