### ISSUE TITLE
Crash - Linux build crashing when keyboard commands used

### ISSUE THREAD

**Issue by pinkfoot** [pencil2d/pencil#317]
Brilliant program for teaching children, but immensely frustrating as a variety of keyboard commands can cause crash, with loss of pupils work.  Running on Ubuntu 12.04.5

**Comment by desttinghim** [comment]
I also experienced this error while using. Here's a link to the printout from the terminal when the error occured: http://pastebin.com/knJtwitK

**Comment by tasaif** [comment]
@pinkfoot @desttinghim can you please provide step by step instructions to recreate this bug?

**Comment by JonasThomas** [comment]
Bump @pinkfoot  @desttinghim   I was looking at the pastebin and it looks like you experience a segmentation fault.
These can be really difficult to isolate, but once we can replicate they're not to hard to fix. (There have been many fixes since you documented this issue and it's possible your issue has been fixed)
We really need the exact steps you pupils used to crash the program.  Students can produce keystroke combinations that would never occur to a developer.
If you do manage to find the exact steps that caused the crash, a video with commentary(since you're saying your using keystrokes would really really be helpful)
@tasaif   I think we should keep this open for another couple of weeks,  if we don't get a response I think we should close this issue.

**Comment by pinkfoot** [comment]
Sorry to not be more fulsome, as I appreciate immensely your response, but I
have lesson plans to sort the exact steps?  All they did was hit the
spacebar ­ oomph!

Massively great program, but with caveats which mean that, with great
sadness, we don¹t use it any more.

Best
B


From:  Jonas Thomas <notifications@github.com>
Reply-To:  pencil2d/pencil
<reply+0036da0d466e57ce1ab5ff2943037d7f3109440786df3d5992cf0000000112bd0ba49
2a169ce0497db63@reply.github.com>
Date:  Sunday, 24 January 2016 22:01
To:  pencil2d/pencil <pencil@noreply.github.com>
Cc:  Bill Robinson <bill@billrobinson.com>
Subject:  Re: [pencil] Crash - Linux build crashing when keyboard commands
used (#317)


Bump @pinkfoot <https://github.com/pinkfoot>   @desttinghim
<https://github.com/desttinghim>    I was looking at the pastebin and it
looks like you experience a segmentation fault.
These can be really difficult to isolate, but once we can replicate they're
not to hard to fix. (There have been many fixes since you documented this
issue and it's possible your issue has been fixed)
We really need the exact steps you pupils used to crash the program.
Students can produce keystroke combinations that would never occur to a
developer.
If you do manage to find the exact steps that caused the crash, a video with
commentary(since you're saying your using keystrokes would really really be
helpful)
@tasaif <https://github.com/tasaif>    I think we should keep this open for
another couple of weeks,  if we don't get a response I think we should close
this issue.


Reply to this email directly or view it on GitHub
<https://github.com/pencil2d/pencil/issues/317#issuecomment-174345359> .

**Comment by JonasThomas** [comment]
@pinkfoot  I tried every manner of pressing the space bar and I could not get it to crash.
Still there are many issues that can trip and frustrate a beginner at the moment.   I hoping that in 6 month's or so we'll get those under control.   Hopefully you can put us on your calendar to give it another try.

**Comment by Jose-Moreno** [comment]
@pinkfoot @desttinghim Greetings gentlemen, during the second quarter of the present year 2017, Pencil2D team has been creating APPIMAGES (executable files) to allow for easier ways to run Pencil2D on Linux, particularly Debian-based distributions. The Preference Shortcuts have been fixed almost in their entirety, and quite possibly this older issue you reported has been as well along that.

I'm aware you might not be using the software anymore. But if you could test it out, at least in good faith so we can close this issue, it would be highly appreciated.

We intend to refine the software further, and hopefully soon it can become a very useful tool for students, hobbyists and veterans alike. I wish you all a wonderful evening and thank you for taking the time to consider this request.

**Comment by J5lx** [comment]
@Jose-Moreno Slightly off-topic, but AppImages are (meant to be) completely distribution-agnostic, so there is no bias towards Debian-based systems or anything. It should work equally well on all distributions.

**Comment by Jose-Moreno** [comment]
@J5lx Thanks for the info! I had read before that they were created for Debian based distros, so I kept that in my head. But if they are distribution-agnostic as you said, more the better. The more you know~ Thanks again! :smile:

**Comment by desttinghim** [comment]
@Jose-Moreno I'll give it a look, though it's been a while since I've tried any animating.

**Comment by Jose-Moreno** [comment]
@desttinghim Thanks a lot for testing it out! Hopefully the OP have some spare time to test in order to finally close this. But your confirmation is a huge step forward. Cheers~

**Comment by chchwy** [comment]
Hi @pinkfoot @desttinghim,
Thanks for your interest in Pencil2D.

If you still like to use Pencil2D please try our new version: 
http://pencil2d.github.io/download/
It has been improved a lot and gotten tons of bug fixes.

Please don't hesitate to contact us if you still get something wrong.
I'm gonna to close this :)
