### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by LachlanDS** [pencil2d/pencil#318]
Whenever I add an audio file, the program crashed.

If it helps, I use a Mac, and the audio file was an mp3

**Comment by Jose-Moreno** [comment]
@LachlanDS Hi I'm sure you don't use Pencil2D anymore. Recently sound import has been re-implemented. If you care to try could you let us know if it works for you? and If it does, can you close this issue as resolved? Thanks!

To download the latest Oct 10 2016 Nightly Build, go here: 
https://drive.google.com/drive/folders/0BxdcdOiOmg-CcWhLazdKR1oydHM

**Comment by Jose-Moreno** [comment]
@chchwy @CandyFace This one should be closed since sound has already been implemented and tested ever since the date of this issue.

**Comment by CandyFace** [comment]
Alright, closing.
