### ISSUE TITLE
Internationalization?

### ISSUE THREAD

**Issue by e1th0r** [pencil2d/pencil#321]
Hi,  there are some plans to integrate i18n in this project?

**Comment by mapreri** [comment]
I got pencil2d translated into Italian by PRing the pencil2d_it.ts file.

Please look at d570395207b3bdf6da425e9899d9767262da77e3 for a more simple commit adding a Czech translation.

**Comment by e1th0r** [comment]
Thank you very much, I will try to do for spanish translation

**Comment by chchwy** [comment]
Hi @e1th0r  
The translation work of Pencil2D has moved to OneSky, a online translation collaboration platform.

You could browse all the words used in Pencil2D in this link:
http://osjoq5e.oneskyapp.com/collaboration/project?id=28187
and start to translate online, it’s quite simple, no need to use other tools.
