### ISSUE TITLE
[BUG] - Color is not correctly handled on Vector layers

### ISSUE THREAD

**Issue by feeef** [pencil2d/pencil#328]
On a Vector layer, it is impossible to draw 2 strokes with different colors. The first one is displaying correctly with the first color. When drawing a second stroke with a second color, all other strokes will change to the latest color.

**Comment by feeef** [comment]
This is an issue due to the fact that colors are handled by a color wheel on the user interface but the Pencil core engine is expecting colors to be handled by a palette with clickable color buttons. It may come from a previous version of Pencil. The current color is supposed to be referred to an index on the palette, which doesn't exist anymore. The current color always refers to index 0 and when the vector layer is updated on the screen, all strokes are redrawn based on the index 0 which holds the latest color.

**Comment by feeef** [comment]
I am working on this bug. I don't want to break the way the color manager is working right now because it could be usefull to be able to implement a predefined palette or a palette holding the "latest used colors" a bit like on Flash.

I will just link both systems and make sure that when we select a color, a palette entry is added. As the palette is not implemented on the UI this behaviour should be transparent for the user. The implementation of a palette would be pretty straight forward in the future as the code is present in the engine.

**Comment by feeef** [comment]
Actually, the color palette doesn't even need to be implemented. It already there and just hidden by default. Good! I just need to link everything.

**Comment by carlosgf** [comment]
Good !
[... I didn't realized that you understand coding :+1: ]

Keep the good will

**Comment by feeef** [comment]
Actually, playing more and more with the palette, I don't know if this can be considered as a bug. 

If I use the palette when working on vector layers, the current behavior can even be quite useful. The palette defines the color of each stroke. When selecting a color in the palette and changing its value in the color wheel makes all strokes made with the same color change as well. We just need to refresh the layer as soon as the color changes. This only works with vector layers but it is fine because bitmap drawings handle many more colors and alpha, we don't want to mess with it.

Vector colors depend on the colors in the palette. Bitmap colors only depend on the selected color when the stroke is done.


This behavior is fine for me but I think there is a few things to do :
 
- We must make sure that when on a bitmap drawing palette items are read only, so it doesn't affect vector strokes that use them.

- We must refresh any vector layer as soon as color changes in the palette.

- We must prevent palette colors that are linked to any vector stroke to be removed. (we could actually just disable the remove button in a first step)

- We must also make sure that the palette is visible by default to avoid any confusion.

**Comment by carlosgf** [comment]
I don't really know how a Vector Layer of a different program than Pencil2D works. I assume their lines could be handle as a Bitmap layer-type, just in a Vector-mode.
That is why I considered this behaviour to be a bug. I am not able to just have one specific Layer to have a BLUE colour line, for instance, and the renaming be just in BLACK. 

So, no matter how many LAYERS or FRAMES I have, I will get ALL the lines with the same colour. That doesn't make sense to me :)

My two cents

**Comment by feeef** [comment]
While I left the default behaviour of having each vector stroke linked to one colour in the palette, I made it usable by fixing a couple of bugs. It is not a usual behaviour but I think it is the default Pencil one and when one know how to use it, it can be very useful. I may do a screen cast at some point to explain how to use this feature. I have made a pull request from this fix.

**Comment by feeef** [comment]
This should be fixed by now. I close the issue.
