### ISSUE TITLE
Pencil draw not pressure Bitmap layer

### ISSUE THREAD

**Issue by LynXcode** [pencil2d/pencil#329]
I have wacom bamboo .when I use pencil tool, not pressure. but version 4.4 pencil tool with pressure

**Comment by feeef** [comment]
This bug should have been fixed with the latest source on github. However, I don't know if an "official" nightly build has been released with this fix. If you are using windows, you may try this build of mine : http://freeseedfilms.com/files/pencil.zip

**Comment by chchwy** [comment]
I'll upload a  "official" nightly build recently. :)
