### ISSUE TITLE
Sound Stutters and is glitchy

### ISSUE THREAD

**Issue by oracleofjamie** [pencil2d/pencil#330]
I finally got the sound working, but now the sound's start is delayed and stutters a lot. If there is a solution I would love to know. Thanks

**Comment by chchwy** [comment]
Hi @oracleofjamie, Which version of Pencil2D are you using?

**Comment by oracleofjamie** [comment]
windows 0.5.4b

**Comment by oracleofjamie** [comment]
To get the sound audible I followed the instructions from "a few problem and a few solutions" that got the sound audible but now the sound echos and stutters I am using .wav files.

**Comment by tasaif** [comment]
duplicate
