### ISSUE TITLE
[Improvement] Make it possible to disable the red and green lines in the center of the editor

### ISSUE THREAD

**Issue by Spark01** [pencil2d/pencil#331]

**Comment by Spark01** [comment]
I decided to take some initiative and work on this myself. I've added a button to toggle the axis lines. I have no idea how Github works though, so I don't know how to upload my modifications...

**Comment by carlosgf** [comment]
Hi @Spark01,

I am sure @chchwy is going to give you some help!
:+1: 

Thank you

**Comment by chchwy** [comment]
Hi @Spark01, 
Thank you to help pencil development.

The axis line is just for debug use only, and it will be removed lately, you could just comment it.

**Comment by chchwy** [comment]
Pencil2D use the "Github Workflow":  1. Fork 2. Commit 3. Pull Request.
Did you use git before?

**Comment by Spark01** [comment]
Nope, I've only done solo projects in the past. I'll try not to mess anything up!
