### ISSUE TITLE
[Improvement] Enable viewing of the camera boundaries while other layers are selected

### ISSUE THREAD

**Issue by Spark01** [pencil2d/pencil#332]

**Comment by Spark01** [comment]
Since the Pencil2D code turned out to be relatively easy to make simple modifications to, I've decided to also attempt to add this feature. I'll just add another button for it.

**Comment by chchwy** [comment]
That's a nice idea, Will you make it a preference or a  button on display option?

**Comment by Spark01** [comment]
I made it a display option for the moment.

Of course, if you would prefer it to be a preference, I don't imagine it would be hard for me to change it :)

**Comment by Spark01** [comment]
Hmm.. I've run into a problem. When the program starts, the camera boundary effect is /on/ by default, but the button isn't shown as being on. Could be confusing. How did you get them to "sync" together for the other display options?

**Comment by Spark01** [comment]
I've added this feature in my fork, and submitted a pull request. I suppose I should go ahead and close this :)
