### ISSUE TITLE
Ctrl+Mousewheel causes freezing instead of zooming

### ISSUE THREAD

**Issue by Spark01** [pencil2d/pencil#333]
This issue occurs only in the nightly build, not in 0.5.4.

**Comment by carlosgf** [comment]
This issue is also related to the  #307 issue

**Comment by Spark01** [comment]
This was evidently fixed in the dev branch. Should I go ahead and close it?

**Comment by carlosgf** [comment]
I was not able to reproduce your issue (I am using a Pen-tablet, no-Mousewheel). If you tested it and it was OK, you should close it

Thank you
