### ISSUE TITLE
[Improvement] Increase usefulness of pencil tool

### ISSUE THREAD

**Issue by Spark01** [pencil2d/pencil#335]
At the moment, the pencil tool has limited usefulness. Based on my unscientific observations, it seems to draw an antialiased line at about half of the currently selected alpha. As it stands, there is no reason for it to exist, as the alpha can be changed manually and the brush tool has an adjustable feather/softness parameter.

Therefore, I propose that we turn the pencil tool into a pixel tool, as most programs do. It would use the full alpha set by the user, and have no antialiasing. This would make it much easier to make sprite animations and such in Pencil2D and improve its usability.

I could probably address this myself, or at least start working on it, but I want to make sure it's okay before I start.

**Comment by Spark01** [comment]
Hmm, I took a look at the code just out of curiosity, and the code for "spinsliders" is kind of a mess, unless i'm misunderstanding something. might have to make some changes there

**Comment by feeef** [comment]
I have worked on the bitmap tools a few weeks ago. The code on github should be up to date but the nightly build may not be though.

My goal was to make the pencil tool to behave like a real pencil when using a tablet and the brush tool having a slightly different behavior. For example the pencil tool is always softer than the brush tool. It is true that when playing with the pencil  width, you may end up having a line that looks like a brush but this is not the point. I made the tools settings always remembered so the point here is to define the pencil width the way you like and always go with it for all your sketches and rough animations. then you can use the brush if you want to paint. Your pencil will always keep its settings.

Anyway, here is the post where I describe all my updates : http://www.pencil2d.org/forums/topic/i-fixed-most-of-the-bitmap-brush-engine/

I have started working on fixing the vector tools but I have been very busy since then and had no time to complete that so far.

**Comment by Spark01** [comment]
Hmm, I see what you mean...

I suppose another solution would be to implement presets. That would keep the functionality of what you did while also allowing for pixelart and the like through the pencil tool :D

**Comment by feeef** [comment]
Yes, it is a good idea! 
I tried to implement the mypaint brush engine within Pencil a few months ago. I have made a QT/MyPaint interface for that (which is not complete) https://github.com/feeef/QTMyPaint
But it requires a huge effort as the current code will need some refactoring.

So in a first step, I decided to make the current brush engine usable (even if it is not perfect) and focus on fixing the rest of the bugs for people to start using the application. I think it is a required step if we want to get some interest and some help.
There are so many bugs...

**Comment by Jose-Moreno** [comment]
A Pixel tool or Preset is a great idea, especially for pixel animators. In the future we could pair that with workspace environments or "rooms" suited to fit the workflow for those tools, like what happens in blender.

In my mind though Pencil needs an antialiased tool. I've worked with many animation software both paid and open-source and each one has a different "feel" either close or far from that of a real drawing experience.

At work we've used TVPaint (http://www.tvpaint.com/v2/content/article/home/), a french based raster animation software. It's the closest you can get to that drawing "feeling" in the current animation software market, the next one is Digicel's Flipbook (http://www.digicelinc.com/flipbook.htm) which was the goto app for some of the Disney feature film drafstmen during the 90's and part of the 2000's, including and not limited to Eric Goldberg. When you look at it's interface it features a simple yet efficient way of conveying the animation workflow, especially the historical X-Sheet (which is really a vertical frame-by-frame timeline).

Anyway, I believe Pencil would do well in strenghtening it's raster-based approach while leaving the very much real possibility of vector-based drawing for Clean-up, Inking and possibly sketching purposes (depending on how refined the tool becomes), like what can be seen in new iterations of Toon Boom Harmony )http://www.toonboom.com/products/harmony)

**Comment by Spark01** [comment]
I tried to recode the spinslider class so that it's possible to have a feather of 0 -  effectively eliminating the need for a pixel tool - but now the paintbrush tool's feather is all messed up, so i'm recoding that too. I honestly am pretty unsure if the changes I'm making right now will ever work, but it's worth a shot.

**Comment by Spark01** [comment]
Well, screw this. Instead of messing with brushes and trying to make the feathering look good, I'm gonna start working on the QT/MyPaint thing. Hopefully it won't be /too/ bad.

**Comment by Spark01** [comment]
II've created a thread on the forums for further discussion. I really do think this should be addressed soon, though I'm not really sure how to go about it.
