### ISSUE TITLE
short cut keys bug 

### ISSUE THREAD

**Issue by abhimabi** [pencil2d/pencil#336]
Shortcut keys in ubuntu 15.04  does not work in pencil2d 0.5.4

**Comment by carlosgf** [comment]
@abhimabi,
It is the same issue posted here #280 
(What about if we users keep only one Issue open? just  for saving the developers some reading and keep the total number more accurate)

:+1:

**Comment by abhimabi** [comment]
@carlosgf 
Thanks for pointing out that, it was utterly my mistake apologies, hope the above bug is not mentioned yet.

**Comment by carlosgf** [comment]
Hi @abhimabi 
You don't have to apologize for that :)
About this Open Issue, it is not possible to delete it. But you may close it and it will no longer be available on the Open Issues, but only at the Closed Issues (if you ever want to go there and re-open it again)
:+1: 

Thank you

**Comment by carlosgf** [comment]
EDITED:
I wrote a typo. It is number #286.
