### ISSUE TITLE
[BUG] Vertical Scrollbar for timeline doesn't work

### ISSUE THREAD

**Issue by Spark01** [pencil2d/pencil#337]
It is impossible to scroll up and down in the timeline, meaning that if you have more than 3 layers, some become unusable.

**Comment by carlosgf** [comment]
Everything about the timeline is mess-up, and a lot of its functionalities do not work like in the old version of Pencil. 
In the meantime you can grab and move up the time line (just move the cursor to the top of the timeline and when it changes its cursor just grab it holding your LMB and moving up till you manage to see all the layers)
Hope this help

**Comment by feeef** [comment]
Hello, I may have some time to spend on Pencil next week. I will try to complete my current fix about color handling in the vector layer. Next, I plan to work on the timeline because I feel that it is quite useless at the moment.

**Comment by carlosgf** [comment]
good!....:+1: 
@feeef

**Comment by feeef** [comment]
I said I was going to work on Pencil last week but I unfortunately didn't find the time for it.
@Spark01 if you want to investigate the timeline, just do! I won't have much time for a little while to help you.

Cheers!

**Comment by chchwy** [comment]
This will be fixed on the next build.

**Comment by carlosgf** [comment]
Sam issue here #128 
(I am going to close it. Your explanation is concise) :+1:

**Comment by tasaif** [comment]
@chchwy can this issue be closed?

**Comment by chchwy** [comment]
ok, close.
