### ISSUE TITLE
Build instructions for someone new to the codebase?

### ISSUE THREAD

**Issue by michaeljones** [pencil2d/pencil#341]
Hi,

This looks like a great project. I can't promise much in the way of contributions but I have checked out the code base in an attempt to build it. I'm struggling to find any build instructions though!

There are steps in the `.travis.yml` file which I can follow and will probably work as I'm on Ubuntu 14.04 but I'm hesitant about installing a test ppa if it perhaps isn't completely necessary? It would be great to see a section in the README that covers building and the tools that are required.

Excellent looking project though! Much respect for building it all.
Michael

**Comment by feeef** [comment]
Thanks a lot for your interest Michael! What you need to do is install QT Creator on your Ubuntu box and open the "pencil.pro" file. You should be able to build from there. All the required external libs are included in the main project.
If you have some errors, please let me know, I will try to help.

**Comment by chchwy** [comment]
Hi, @michaeljones 
the .travis.yml was made by trial-and-error. I built Pencil2D... fail, read the error message, add lacked lib, and repeat until build passed. so I guess all the libs in .travis.yml are necessary.

Pencil2D is a Qt-based project, the main idea of build steps is very simple,
1. Install necessary Qt modules.
2. run qamke.
3. run make. 
That's all.

**Comment by tasaif** [comment]
http://www.pencil2d.org/tutorials/advanced/build-pencil2d/
