### ISSUE TITLE
Frame or Keyframe ?

### ISSUE THREAD

**Issue by ManuAros** [pencil2d/pencil#349]
Something is wrong with the frames. If you add a frame they are always filled (black) and you can't step through them with 'Next Frame' instead you will have to use 'Next Key-Frame' so why does Pencil have (two different types) Frame and Key frame? As it seems now every time you add a frame it will be a key-frame that is added, so how do you add regular frames then? Another side effect of this is that you can't move the frames. They are stuck to where they are. 
------------------------------------
Pencil2D Build 21.11.2015
Windows 10 - 32 Bit

**Comment by carlosgf** [comment]
@ManuAros 
If I understood correctly, this is a Bug already reported here: #280 

At the moment you are not allow to move frames on the time line. Not allowing to move frames you will always end up with a "filled (black) and you can't step through them with 'Next Frame" (as you said)
(hope this is it)

**Comment by feeef** [comment]
I am going to fix this bug this week.

**Comment by carlosgf** [comment]
@feeef  :+1:

**Comment by ManuAros** [comment]
Duplicate frame doesn't work either, maybe that's related to this issue?
Tested on Dec. 12 build.

**Comment by ManuAros** [comment]
This is fixed in the 19 December 2015 build. BIG Thank you developers !!
