### ISSUE TITLE
Hand tool doesn't move

### ISSUE THREAD

**Issue by ManuAros** [pencil2d/pencil#350]
I can't get Hand tool to move the screen? Is this just my build ?
------------------------------------
Pencil2D Build 21.11.2015
Windows 10 - 32 Bit

**Comment by Jose-Moreno** [comment]
If you press & hold the middle mouse button while dragging, that should activate the translation behaviour from the hand tool, can you confirm if it works independently from the hand tool or is it broken as well?

**Comment by carlosgf** [comment]
@ManuAros @Jose-Moreno 

That is a bug already reported here: #307

**Comment by aecepoglu** [comment]
@carlosgf No it's more htan #307 . Regardless of clicking once or twice, the tools won't work.

I cannot see where the view is in comparison to the canvas so I'm not sure whether it's just not rendering or whether the moving around action is just jumping to random locations.

I had 5 drawings in a project and I lost them. I kept zooming in and out and I would sometimes be able to see my drawings but I couldn't move them into the view fully because the tools didn't work.

This is happening on the build right now (nov 23rd)

**Comment by carlosgf** [comment]
You say that the tool doesn't work. So let me ask you. 
Does the HAND Tool icon appear as an icon on the tip of the Pen?
If Yes, what really happens when you just try to use the Hand tool? Does the whole drawings disappear? or nothing really happens when you release the Hand tool or hit the canvas?

**Comment by aecepoglu** [comment]
The icon appears. Once I stop using the tool the drawings disappear. Search around for my drawing and sometimes they will appear while I'm zooming in and out but they'll disappear afterwards

**Comment by carlosgf** [comment]
OK. So, this is what is happening to me also. The Hand tool is not working properly I know but If I want to move an object from the right to left of the canvas I will apply the trick I showed you before (it is still working for me), that is: draw your object. Hold the SPACEBAR (shortcut for Hand Tool) and place the tip of the cursor on the canvas and just move it ONE MILLIMETRE to your right, and release it: your object will be placed more to its right.
Make sure before doing anything that you have not changed the zoom of the canvas. To be sure just close Pencil and open it again (I have just found another bug that will bring back the last zoom I made and that made things worst)
And remember: zooming doesn't work as intended, well at least here with me in my tablet: if you try to zoom something that is centralized with the centre of the canvas, it will not bring your drawings centred towards you (when you zoom in) but instead it will zoom them to the sides (I lack English words to explain this) 

It is a Bug of course.

**Comment by aecepoglu** [comment]
I know why the translation is broken.

In the translation code it always translates by the amount of difference between current cursor position and the first mouse-down-position. This means if you mouse-down and move your mose about 100 px it means the translation amount will be 1 + 2 + 3 ... + 99 + 100.

I'll send a pull request for this.

**Comment by carlosgf** [comment]
@aecepoglu  :+1:

**Comment by aecepoglu** [comment]
Seems to be fixed as of the latest merge.

**Comment by carlosgf** [comment]
Yes, It is already fixed with the last build (23Nov2015).

[@ManuAros, You may close this issue] :)

**Comment by ManuAros** [comment]
Very good. :) Thanks to everyone involved.
