### ISSUE TITLE
When drawing with a Wacom Intuos on Pencil Version 0.5.4 dev (Mac) the lines will drag behind the cursor.

### ISSUE THREAD

**Issue by scaryslender18** [pencil2d/pencil#351]
I've just recently started using pencil to animate, or at least trying to. You see, the problem is that whenever I plug in my Wacom Intuos Pen Small (model CTL-480) and try to draw, the lines move around 2-3 times slower than my cursor is actually going.

Here is a demonstration: https://www.youtube.com/watch?v=p_MneDdu9hI

Meanwhile, when I simply use my mouse, the lines are just fine, and move at the same speed as my mouse. I am quite sure that this is a bug, because I was troubleshooting with my Intuos for about 45 minutes. Any bug fixes/help would be much appreciated!

Link to this thread on pencil2d.org: http://www.pencil2d.org/forums/topic/disappearing-lines/#post-27256

**Comment by mcsblanc** [comment]
Bonjour
J'ai constaté exactement le meme probleme avec ma tablette graphique et la souris.
I found exactly the same problem with my graphics tablet and mouse.

**Comment by CandyFace** [comment]
This issue is related to #345

**Comment by tasaif** [comment]
I tried with a Bamboo tablet and it works fine. If someone wants to send me a Wacom CTL-480, I can debug this.

**Comment by feeef** [comment]
Isn't this bug fixed by commit https://github.com/pencil2d/pencil/commit/6cfe0cbd43e16a8fcb2659932d805a6c4d0ec21d ?

**Comment by CandyFace** [comment]
Yes to my knowledge it has been fixed, and both this and #345 should be closed.

**Comment by feeef** [comment]
Ok! Closed it!
