### ISSUE TITLE
Line bug

### ISSUE THREAD

**Issue by Reaper10** [pencil2d/pencil#352]
Not all my lines are black on camera layer, why is that?
<img width="840" alt="capture" src="https://cloud.githubusercontent.com/assets/8137561/11321128/36bc01e4-9078-11e5-89f7-64a17c6257ed.PNG">

**Comment by feeef** [comment]
It looks like a bug I have fixed in the nightly build. It was due to onion skin interfering with the current frame. If you wait a week or 2, we should be able to make a build with many bug fixed.

**Comment by carlosgf** [comment]
That is what I thought.
The Onion Skin also interfere with the colour of the brushes when it is activated...
(no need to open a New Issue since I have done it before, just wanted to point it out)

**Comment by feeef** [comment]
This bug should be fixed in the last nightly build. Can you confirm that @Reaper10 ?

**Comment by tasaif** [comment]
feeef what are the steps to recreate this so that I can verify instead of Reaper10?

**Comment by feeef** [comment]
The steps were : 

- Draw a black line on an empty frame.
- Switch on onion skin on both sides (previous & next)
- Switch on onion skin colours on both sides (red & blue)
- The line became purple.

**Comment by Jose-Moreno** [comment]
@feeef This has indeed already been fixed. Is there a way we can close this now?

**Comment by feeef** [comment]
Done! :)
