### ISSUE TITLE
Bug when switching tools while still drawing

### ISSUE THREAD

**Issue by Jabst** [pencil2d/pencil#353]
Hey this might be somewhat complicated to explain but I will try my best to be the most concise.

When I draw a line using brush and I hotkey to the pen and continue to draw that line but when I switch back to the brush I notice that there is a straight line that links the last coordinate on the first use of the brush(x,y position on the canvas) and the first coordinate of the other use of the brush.

I will attach an image of the resulting canvas.
![bug](https://cloud.githubusercontent.com/assets/9280778/11325757/f1c3e8a0-914d-11e5-92e7-83c7043affb5.png)

**Comment by carlosgf** [comment]
Same thing here. 
(drawing a path like a Serpent, you will get that new issue line between curves)

Win8.1x 64bits
