### ISSUE TITLE
tool will not stay on the tool I want to use

### ISSUE THREAD

**Issue by Reaper10** [pencil2d/pencil#354]
When I try to go from one tool to another tool then I go to use on the canvas it goes back to the first tool. Example 1: I tried to use the Brush tool then I tried to use the Fill tool on the canvas the tool stays on  Brush tool. OS Windows 10

**Comment by carlosgf** [comment]
Inform the developers what OS you are using. It will be easier for them to check the issue.
Thanks

**Comment by Reaper10** [comment]
OS Windows 10
