### ISSUE TITLE
launch error

### ISSUE THREAD

**Issue by Reaper10** [pencil2d/pencil#355]
launch error windows 10 Pencil2D-dev-20151123
<img width="840" alt="capture" src="https://cloud.githubusercontent.com/assets/8137561/11349219/8f9cc176-91f0-11e5-861f-161d082f6c4b.PNG">

**Comment by carlosgf** [comment]
This error is related to your OS. 
Do a search for MSVCP120.dll, and download the missing file (careful to download it from a reliable site (there are lots of Brazilian fake sites promoting the file as saved to download from their pages)

To be easier for you, just follow the following steps on youtube:
https://www.youtube.com/watch?v=tmmypFGgs98

**Comment by chchwy** [comment]
MSVCP120.dll and MSVCR120.dll are included in Nightly build since Dec 5. No more need to download from other source.
