### ISSUE TITLE
no grid

### ISSUE THREAD

**Issue by Reaper10** [pencil2d/pencil#357]
What happened to the grid on off button in the news encil2d?
<img width="166" alt="36bc01e4-9078-11e5-89f7-64a17c6257ed" src="https://cloud.githubusercontent.com/assets/8137561/11461037/385fad1c-96c1-11e5-8d61-91457f65343d.png">

**Comment by chchwy** [comment]
@Reaper10, You could show/hide Grid via Menu->View->Grid, or press the hotkey "G".

I removed Grid button because there are too many buttons on display options panel, but it can be discussed. What do you think?

**Comment by feeef** [comment]
I fixed the grid output that was not always behaving correctly. As @chchwy suggested, I didn't put the button back as it is in the menu but the display is fixed (in the next build)
