### ISSUE TITLE
An UNDO option for "frames deleted"

### ISSUE THREAD

**Issue by ghost** [pencil2d/pencil#36]
REQUEST
Last build
When a group of frames are deleted (or just one frame) they are deleted for good, and lost. 

The request, if possible, is to bring the "undo" function, under the EDIT MENU, to do that same behaviour now with the time-line frames.

Thanks

**Comment by carlosgf** [comment]
As we are taking the time to refine the Timeline, it will be desirable to fix this issue, since there is no chance of deleting a frame, and trying to bring it back, without messing all around the timeline with disastrous end behaviours (deleting content of adjacent frames, etc)

**Comment by Kaikogf** [comment]
@chchwy 

This was closed but I have checked (build 31Dec2017) and there is an issue related to the UNDO feature when applied to the Vector frames (not sure if it is already duplicated). I will open a new issue
