### ISSUE TITLE
Onion skin (previous frame)

### ISSUE THREAD

**Issue by ManuAros** [pencil2d/pencil#363]
The Pencil2D nightly from 5 December doesn't show previous frame when onion skin is turned on.
If you increase the previous frames to show to 2 frames, it shows two previous correctly but not if you only leave it at 1 frame then none previous is shown,

Windows 10, 64 bit.

**Comment by carlosgf** [comment]
@ManuAros ,
Good one!

I have the same behaviour here
Win8.1x64bits

**Comment by feeef** [comment]
I fixed this in my branch. It should work on the next build.

**Comment by carlosgf** [comment]
@feeef :+1:

**Comment by ManuAros** [comment]
Confirmed and working :+1:
