### ISSUE TITLE
Pan doesn't show movement

### ISSUE THREAD

**Issue by ManuAros** [pencil2d/pencil#364]
When using the Hand tool to pan the image you won't see the image moving only after releasing the image you will see where it got moved to. This is not the behavior Pencil used to have.0.5.4b always showed the "floating" image when moving.

**Comment by carlosgf** [comment]
The Hand feature is broken again. I believe this is your #350 issue.

**Comment by feeef** [comment]
@chchwy I will need some help on this if you have time. I am struggling to find out why the ScribbleArea is not updated while dragging? The mouse release event is not calling anything after moving so why is the area only updated at that point? Thanks for your help! :)

**Comment by ManuAros** [comment]
Just verified the same behavior on Windows 7 64-bit as on Windows 10 64-bit. I pick the hand tool press left mouse button, drag (and the window stays where it was before) and I release mouse button and I the window updates to the new location.

**Comment by feeef** [comment]
I have found a solution and fixed this! :) There was a condition on the ScribbleArea that defined not repaint it when the mouse was in use. I let it go through this condition when the selected tool is the move tool or hand tool. It seems to work perfectly! :)

**Comment by ManuAros** [comment]
Good Job ! That sound nice, thank you !

**Comment by ManuAros** [comment]
Tested and works in latest nightly. :)
