### ISSUE TITLE
[BUG] Horizontal Flip issue on VECTOR LAYERS

### ISSUE THREAD

**Issue by carlosgf** [pencil2d/pencil#365]
Last build (05Dec2015)
Win8.1x64bits

Steps: 
-Open Pencil2D
-Select the VECTOR layer, and draw some lines NEAR the centre of the canvas (just to be more accurate)
-Go to the DISPLAY Panel, to the right, and click the HORIZONTAL FLIP icon. 
Result: all the lines will disappear. Clicking it again will bring them back.

NOTE:  the V making Zoom Out will not bring the images to the canvas.
Vertical Flip is working fine on both Vector and Bitmap layers

**Comment by feeef** [comment]
I can't reproduce this bug. Is there something you are missing in the procedure?

**Comment by carlosgf** [comment]
Hi
The procedure is spot on in Win8.1x64bits... It seems that I explained it quite badly :)

So here new explanation: 
-Open Pencil2D
-Select the VECTOR layer, and draw a line at the very TOP CENTRE of the canvas (just to be more accurate).
if you select to flip the image VERTICALLY (clicking the FlipVertically's icon at the right on the Display Panel), the image will be flipped OK and it will be showed at the BOTTOM CENTRE of the canvas, right?
Doing the same thing with the FlipHorizontally's feature (Select a VECTOR Layer, Draw a line at the very RIGHT CENTRE of the canvas, and now selecting the Horizontal flip feature) doesn't work: the line that it was supposed to be flipped to the other side (Left Centre) of the canvas, doesn't show up. There is no trace of it on the canvas :(

It seems to me that the lines were flipped outside the canvas, that is why I mentioned above that zooming-out will not bring back the lines :)

Hope this help

**Comment by feeef** [comment]
Strange, it is working fine on my side. I can't manage to make to line disappear. I am testing on my branch where I have made other fixes on the canvas rendering so maybe this bug was related to something I fixed... 

I will leave it at the moment and I suggest that you tell me if you still have it on the next build.

**Comment by carlosgf** [comment]
OK!

**Comment by chchwy** [comment]
I can't reproduce this bug either. :(

**Comment by carlosgf** [comment]
Everything is OK now with the new Nightly Build (14Dec2015)
Win8.1x64bits

@feeef , I think one of your fixes turn it OK.

Thanks!
