### ISSUE TITLE
[BUG] Using 2 layers (vector AND bitmap), hidden one of them doesn't prevent it to show their frames

### ISSUE THREAD

**Issue by carlosgf** [pencil2d/pencil#366]
Last build (05Dec2015)
Win8.1x64bits

Steps:
-Open Pencil2D
-Go to the Bitmap Layer and ADD two more frames to it. Draw B1 for the first frame, B2, for the second, and B3 for the last frame (this will help you to see what is really happening)
-Now select the Vector Layer and ADD two more frames. Do the same as before drawing V1, V2 and V3 for the respective frames

Layers can be activated or deactivated by clicking the circle at the very left of their icon layer (well, that is if no Bug/Issue is presented)
By default when opening Pencil2D the active layer is the Bitmap Layer while the remaining (Vector and Camera) are showed as semi-transparent, reduced-opacity (the circle dot at its very right is showed as grey). Layers are deactivated when the circle dot is showed with no colour.

-Select the first frame of the BITMAP LAYER: all drawings from "frame 1", of each Layer, will be showed on the canvas.
-Go and click on the Main Circle Dot that controls all layers transparency (just above the first layer) and hit it twice (first one will give full opacity to all layers,next one will hide all layers but the selected one)
-Result: the drawings of the hidden Vector Layer still shows up. Checking all other frames shows the same result. Going now and selecting the Vector Layer will bring the same result when checking its frames.

A QUICK solution: 
Select the Bitmap Layer. After hitting the main circle dot twice go now to the Vector layer and click on its circle dot ONCE. That will hide that particular Layer (note that the circle dot remains the same, with no colour in both cases)

**Comment by feeef** [comment]
I fixed this on my branch. It should be working on the next build!

**Comment by carlosgf** [comment]
@feeef  :+1:

**Comment by carlosgf** [comment]
(I thought nobody would understand what I have wrote in the first place LOL)

**Comment by feeef** [comment]
I didn't! :) So I followed your exact instructions and saw that something wasn't working! ;)
Thanks for testing and reporting bugs anyway!

**Comment by carlosgf** [comment]
@feeef 

jejeje, your firsts line made my day!  :) 
Glad to have helped... 

[you are working fast!... Imagine three more developers like you working at the same time over Pencil2D!... that would definitely surpass Blender3D with their new version releases every three month or so...]

**Comment by carlosgf** [comment]
I will close this issue once I check it on the new build

**Comment by carlosgf** [comment]
FIXED with the last Nightly Build (14Dec2015)
Win 8,1x64bits

You nailed it @feeef :+1: 

Thanks
