### ISSUE TITLE
Not a BUG: The Control Slide Bar (Size,Feather) from all drawing tools doesn't updated with the size of the tools applied

### ISSUE THREAD

**Issue by carlosgf** [pencil2d/pencil#367]
Last build (05Dec2015)
Win8.1x64bits

It is not an issue by itself. As the title says the Slider Position Control Bar doesn't move at all when using the Dynamic Resize Shortcut key (when using Pencil, Pen or the Brush tools) but the changes made by applying the Dynamic Shortcut are correctly applied to the strokes of the tools.

Changing the size manually instead of using the shortcut, works OK, meaning the Slider Control Bar moves and it update the size of the tool accordingly.
If closing Pencil2D with the Control Size Bar at "200" at each drawing tool, and open Pencil2D again it will bring all the drawing tools with a size of 200, BUT with the Size Position Bar moved all to the left

**Comment by ManuAros** [comment]
I can only add to this that I also experience lots of bug with resizing brush and feather. The normal Pencli behaviour was to hold down SHIFT only brush size changed as you moved the pen on the tablet   surface, and while hollding CTRL only feather slze changed. Now depending on tool both feather and size move no matter if it's CTRL or SHIFT you hold down.

**Comment by carlosgf** [comment]
The new Nightly Build (14Dec2015) FIXED the Slider Position of the Control Bar
Win8.1x64bits

@ManuAros , you explained that issue very well. I am going to copy your comment and paste it on my other issue. 
Here it is the same issue posted long ago #310 

Thank you @chchwy

**Comment by carlosgf** [comment]
(I thought this issue was duplicated!)
