### ISSUE TITLE
Select Tool doesn't always react

### ISSUE THREAD

**Issue by ManuAros** [pencil2d/pencil#368]
This has been the case with Pencil2D for a long time I think. Sometimes when dragging a box with the select tool, nothing happens. When trying to select 3-5 times repeatedly it suddenly start working again.

**Comment by feeef** [comment]
I have been working on this yesterday. I fixed the move and resize feature on vector layers. It will be included in the next build. I will check about bitmap layers now. I will try to add rotate and flip if it is not too complicated at this stage.

I will keep you updated in this thread.

Cheers!

**Comment by ManuAros** [comment]
Thanks, love to hear that. Proportional re-size is the biggest problem for me atm.

**Comment by ManuAros** [comment]
Select tool now works. Proportional resize, rotation etc. also works. Nice job!
