### ISSUE TITLE
[Improvement] - Select / Move frames in timeline

### ISSUE THREAD

**Issue by feeef** [pencil2d/pencil#376]
The ability to select one or multiple frames and moving them around is required.

I would get inspired from Krita new animation feature : https://www.youtube.com/watch?v=9uvju6sUNJA

Making it just a bit simpler than in Krita (without click-drag to box select and click-hold to select) :

Select
- click : to select a single frame
- shift -> click : to select range
- ctrl -> click : to select individual frames

Move
- click -> drag : to move a single frame
- alt -> click -> drag : to move a frame and all the frames at its right
- ctrl -> click -> drag : to move a duplicate of a frame or range of frames

**Comment by gordielachance** [comment]
Seems great.
There is a good idea in the ALT>CLICK>DRAG thing (I remember that it was annoying in Flash to have to zoom out to select all the frames).  
Maybe this could also be approached as : 
* CLICK + RIGHT ARROW KEY (select current key and all keys to the right) + DRAG (move them)
* CLICK + LEFT ARROW KEY (select current key and all keys to the left) + DRAG (move them)

I don't know if you use Blender, but it could be useful too to have a look at their workflow, which is quite smart and really fast to work with.  Meanwhile, you've got to get used to it.
eg : the "G" key (for "grab") moves a "thing".  If you're in the viewport, it will move an object.  In the timeline, it will move a key.  In the graph editor, it will move a curve, etc...  Really nice to use.

**Comment by feeef** [comment]
I have implemented this feature and it will be on my next pull request.

What I have implemented so far :

Select

    click : to select/deselect a single frame
    shift -> click : to select range
    ctrl -> click : to select/deselect individual frames
    alt -> click : to select a frame and all the frames after it
    click -> drag : to box select

Move

    click selected -> drag : to move a single frame
    alt -> click -> drag : to move a frame and all the frames at its right

I will try to do a screencast to show it work when I get some time.

**Comment by carlosgf** [comment]
With this working fine Pencil2D will be such a nice software for doing our little 2D animations

Congratulations @feeef . I am deeply surprised by your develop expertise.
Please, take also your time to take a good rest :+1: ..

**Comment by feeef** [comment]
Thanks @carlosgf !

I think it is working fine for anyone who knows how it works. Especially when you move frames over others existing frames. Their positions are swaped and it can be a bit confusing at first. It is why I would like to do a screencast to show the capabilities. They are quite good really.

The main missing features of the timeline now are the possibility to undo and the possibility to copy/paste the selected frames.

Apart from that, I agree that Pencil2D is starting to be a very usable application. It is at the state I wanted it to be at the end of this week and now I am going to take some holiday! :)

**Comment by feeef** [comment]
This is fixed in the 19 December 2015 build.
