### ISSUE TITLE
Could we change the Hand tool behaviour a bit

### ISSUE THREAD

**Issue by ManuAros** [pencil2d/pencil#380]
I noticed in the latest release a tiny issue that have a huge impact on how fluently you can work. 

Before in 0.5.4b you could have hand tool assigned to for example "space key" and while sketching you could pan your work area super fast just by holding down "space" and move the pen.

Since the new implementation with the hand tool I can no longer use it like this because when I select hand tool with the shortcutkeys the hand tool stays on forever until I select another tool.
I don't know what would be a smart way of implementing both ways, or could Pencil be configured that when you pick Hand tool from the Icon on Tools, the hand tool stays on, and when you use hand tool with shortcut key, the hand tool is only active as long as key is pressed. (Maybe this was the behaviour with 0.5.4b, i don't remember I would have to check).

**Comment by feeef** [comment]
In my understanding of how things work in Pencil, the tool shortucts are only used to permanently switch tool (to avoid clicking on the toobox).
Temporary switch are handled by other keys and I would also suggest that the space key could be used for that.

It is not a difficult task to do and I will add it to my to-do list.

**Comment by carlosgf** [comment]
@ManuAros  @feeef 
I also noticed that. 
There is still a way to use the temporary HandTool: Just use the shortcutkey  "LMB + DRAG". 
It is working fine!

**Comment by feeef** [comment]
I fixed this! The space key shortcut will be working on the next build

**Comment by ManuAros** [comment]
Tested and working fine, excellent!
