### ISSUE TITLE
Onion skin when rotating

### ISSUE THREAD

**Issue by ManuAros** [pencil2d/pencil#382]
If you have onion skin on and rotate, you can't make use of the previous next frames because rotating a selection hides the onion skin while you're rotating. It's not a bug I guess but rather a feature that could be implemented. It would make knowing where to rotate to easier.

**Comment by ManuAros** [comment]
I will close this. @feeef said it better in #390

**Comment by feeef** [comment]
Sorry @ManuAros , I didn't notice you already mentioned it.
