### ISSUE TITLE
Export does not export from current position

### ISSUE THREAD

**Issue by aecepoglu** [pencil2d/pencil#383]
When I try to export image or image sequence, pencil2d always exports from the same position.

I try to move the canvas around using mouse middle button, the hand button or mouse right button but none seem to have an effect

**Comment by carlosgf** [comment]
it is a bug. It was also reported here #284

**Comment by carlosgf** [comment]
A turn around to this situation is to go to the Display panel and select the icon "Camera border". It will give you a different situation now: everything done inside the borders will be also exported

**Comment by aecepoglu** [comment]
Closing in favour of #284 

IT would mean a lot if this was resolved

**Comment by carlosgf** [comment]
Good idea to keep just one open :+1:
