### ISSUE TITLE
Behaviour when colouring on a bitmap layer is slightly changed now

### ISSUE THREAD

**Issue by ManuAros** [pencil2d/pencil#386]
ISSUE 1:
You have two bitmap layers. Layer 1 where you have your line drawing and Layer 2 which is going to be your colouring layer. When you start colouring on Layer 2 the view is not updated automatically when you release the pen meaning the colour you added will show as if it was placed on-top of your line drawing. You will have to switch focus to layer 1 and back to layer 2 before you can see your line work again because of course it's important to know where you are colouring relative to your line work. This is not a problem when making flood fills because you do that on Layer 1 and the colour goes automatically to the bitmap layer beneath. 

In version 0.5.4b the behaviour was the colouring seemed as it painted on top of the line work (ok) but as soon as you released the pen the view updated automatically and your line work shows as the front most layer as it should be (because its on top of the coloring layer)

ISSUE 2: (related)
Make Two bitmap layer, Layer 1 = line work, Layer 2 = colours
Draw a circle on Layer 1 and fill it with a colour (e.g skin colour)
Draw two small black circles inside the big circle = eyes
Go to colouring layer (2) and you will see that the "eyes" disappears because Pencil doesn't allow you to "see trhough" the colouring so that you actually know where you put the eyes

This worked well in 0.5.4b

**Comment by carlosgf** [comment]
I haven't tested your step-process, but I just want to ask you: which layer is the one you named LAYER1?
Is is the Layer at the top of all the others? 

I am asking this because Pencil2D handles Layers in a different way: the FIRST Layer is the one at the BOTTOM.

**Comment by feeef** [comment]
Sorry, I didn't know one could draw on one layer through another one. I didn't work on this feature.

Is there any documentation about it for me to understand the right behaviour?

**Comment by ManuAros** [comment]
@feef, after reading carlos question I realized I need to go trough this again. I must say I always considered the layer on top to be the first layer. Let me check and comment on this matter as soon as I  tested some more.

**Comment by ManuAros** [comment]
@feeef 

I thought the best way to explain this behavior was to show  the old version of Pencil. This is what I think the new Pencil should be able to do also. It's awesome :)

https://www.youtube.com/watch?v=xRumVB2jf7c

**Comment by feeef** [comment]
Thank you @ManuAros this is an interesting feature. It made me understand that in the current version of Pencil, the top layer is actually on top of the timeline. I guess it was the case before. It is a good behaviour in my opinion. However, I agree, the colouring behaviour in the bitmap layer should be fixed.

While this is not working correctly you can also do your clean up and colouring in a vector layer. I have implemented some cool features in the vector engine for that : https://goblinrefuge.com/mediagoblin/u/feeef/m/pencil-dev-update-colours-on-vector-engine/

**Comment by carlosgf** [comment]
Sorry about the confusion. 

I was trying to remember when I read that thing of the layers working differently for Pencil2D. But it was like 3 or more years ago. But I have no clue, only I did remember about an issue on a vector layer

My English is not good for that kind of technical words so this was my last comment on issues.

**Comment by feeef** [comment]
I would like to be assigned to this bug. I want to improve the bucket tool on the bitamp layer while fixing this bug. Improvements will include : 

- The ability to expand the painted area to go behind the drawing lines (brush feather makes an ugly separation between the line and the painted area)
- The ability to feather the painted area. (Not as essential)

This is essential in order to have good quality painting.

**Comment by tasaif** [comment]
Bug fixes and improvements belong in separate branches/pull requests

**Comment by feeef** [comment]
Ok! I have only been sending pull requests on master so far but it's ok for me to work on separate branches. I will open an issue for the improvements.
What are the branches you are working on for bug fixes and improvements?

**Comment by feeef** [comment]
I have forwarded the improvement part of this issue : https://github.com/pencil2d/pencil/issues/438
and I set the primary issue as a bug that I am fixing now.

**Comment by ManuAros** [comment]
@feeef 

This is so great, my biggest THANK YOU! for fixing this. I now feel 'at home' again.  :)

**Comment by ManuAros** [comment]
tested an worked !
