### ISSUE TITLE
pencil2d - latest from github - segfault / doesnt start

### ISSUE THREAD

**Issue by blurymind** [pencil2d/pencil#388]
Not much to this bug. after compiling it from github via AUR (1866.9b954a0-1)- I am on manjaro linux 64 btw,
Pencil2d just crashes upon start. I get this error:

[tai@tai ~]$ pencil2d
Segmentation fault (core dumped)

**Comment by blurymind** [comment]
Also tried it on pencil2d-git-1869.3d8b703-1

Same error message. pencil2d wont start at all. :(

**Comment by chchwy** [comment]
@blurymind, sorry i don't have a linux machine available around me, but I'll help as much as i can. 
Could you provide more details?
How did you compile pencil?  and how did you run the executable?

**Comment by blurymind** [comment]
I compiled it via AUR. Ran it via terminal.
On 23 Dec 2015 15:31, "Matt" <notifications@github.com> wrote:
>
> @blurymind, sorry i don't have a linux machine available around me, but
I'll help as much as i can.

**Comment by blurymind** [comment]
This is the build script:
https://aur.archlinux.org/packages/pencil2d-git/
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pencil2d-git

I think that the segfault is going to affect all linux users, as the build process is fairly standard

**Comment by chchwy** [comment]
I didn't see anything strange in the build script.

**Comment by JonasThomas** [comment]
I was having some issues also in Ubuntu 14.04   I made a few changes that got merged to master.  Can you pull down the latest and give it another try?

**Comment by blurymind** [comment]
Thank you! I will give it a try tonight. :)

**Comment by blurymind** [comment]
I tested it and it works now! Thank you. Btw the bucket tool no longer seems to function on  vector layers

**Comment by feeef** [comment]
Bucket tool still don't work well on vector layer. Especially if the shape is not a simple one. However, you can draw the shape of what you want to fill with the bucket tool. This should work.

**Comment by blurymind** [comment]
Drawing the shape no longer works for me. It used to in previous versions

**Comment by tasaif** [comment]
Original issue is resolved. Bucket tool issue moved to #415
