### ISSUE TITLE
[BUG] - Move / Rotate selection breaks the onion skin

### ISSUE THREAD

**Issue by feeef** [pencil2d/pencil#390]
When moving or rotating a selection, the onion skin where the selection was defined is not visible anymore.
This can be a problem when trying to adjust the current drawing based on previous or next drawings.

**Comment by ManuAros** [comment]
I also reported kind of the same thing here #382, I closed that because your explanation is better.

**Comment by tasaif** [comment]
core_lib/canvasrenderer.cpp:328 is part of the problem
still working on it
