### ISSUE TITLE
Conflicting package name

### ISSUE THREAD

**Issue by hellocatfood** [pencil2d/pencil#396]
There is another well known package that uses the Pencil name:

Pencil http://pencil.evolus.vn/ | https://github.com/prikhi/pencil/
Pencil is built for the purpose of providing a free and open-source GUI prototyping tool that people can easily install and use to create mockups in popular desktop platforms.

Both packages are unable to be installed at the same time as they both are called Pencil. A bug report on that Pencil has already been reported https://github.com/prikhi/pencil/issues/748

Could the package name be renamed to pencil2d to avoid conflicts in the future?

**Comment by chchwy** [comment]
I believe the package name has been chaning to pencil2d now.
