### ISSUE TITLE
scrubbing with arrow keys doesn't work

### ISSUE THREAD

**Issue by tasaif** [pencil2d/pencil#402]
looking at the code, it looks like you're supposed to be able to scrub with the arrow keys, but trying it out doesn't work
~~
further digging shows that the keyboard keys are tool specific, so if a certain key you press is not applicable to the current tool, it's supposed to fallback to a default behavior.
~~
I'm currently using the brush tool which doesn't have keyPressEvent overloaded and so should return false, but for some reason seems to be returning true
~~
I've defined a keyPressEvent on the brushtool and returned false and got the desired behaviour. I've also confirmed that keyPressEvent is not being called on the base tool when it's not defined. I'm not sure what's happening.
~~
For some reason it's calling stroketool's keyPressEvent instead of the basetool's.

**Comment by Jose-Moreno** [comment]
Actually I've been having this bug as well ever since a few nightly builds, somewhere along the line this behaviour was broken, but I'm not sure if any other dev was trying to fix this silently perhaps refactoring the behaviour or what. Hopefully any other dev can give us word on this.

**Comment by tasaif** [comment]
are stroke tool and brush tool supposed to be the same?
