### ISSUE TITLE
[BUG] - Custom palette first colour is always black

### ISSUE THREAD

**Issue by feeef** [pencil2d/pencil#411]
After customizing the first colour of the palette (Black), saving the project, closing and re-opening the project, the first colour in the palette is back to black.

**Comment by feeef** [comment]
I am fixing this issue right now

**Comment by feeef** [comment]
It is fixed and in my latest pull request

**Comment by tasaif** [comment]
Has this been merged?

**Comment by feeef** [comment]
Yes! It was on my last pull request. I close it!
