### ISSUE TITLE
Canvas-size save

### ISSUE THREAD

**Issue by tasaif** [pencil2d/pencil#422]
Pencil2D always opens with the Camera size at 640/480 (default)
Adding a save-canvas-size feature as enhancement.
- Kaiko

**Comment by Kaikogf** [comment]
What I meant with my initial post was that I am not found of that camera size, besides it is an outdated dimensions now-a-days.

We have already discussed it on Pencil2D forum about implementing a new default camera resolution for Pencil.
http://www.pencil2d.org/forums/topic/pencil2d-nightly-builds-2015/#post-28715
and a camera resolution of 1280x720 mentioned by @chchwy gives Pencil2D a better face!
;)

If implementing a new camera resolution I think there is no need for implementing a new camera-size's save mode 

Thank you

**Comment by Jose-Moreno** [comment]
[2018] The default camera resolution has been updated to 800 x 600, however this is insufficient to cover most user cases. A new proposal for a preset manager has been made #981
