### ISSUE TITLE
Grabbing Layer crashes Pencil2D

### ISSUE THREAD

**Issue by tasaif** [pencil2d/pencil#424]
Grabbing any layer (bitmap, vector, camera, sound) to the bottom of the Layers panel crashes Pencil2D

- Kaiko

**Comment by JonasThomas** [comment]
@taslf   I'm having trouble verify this bug.  I'm working if it's been fixed, or it's occuring when other weird things are happening.

**Comment by JonasThomas** [comment]
@tasif http://www.pencil2d.org/forums/topic/bug-grabing-a-layer-crashes-pencil2d/#post-27788
Posted to the originator for futher info

**Comment by JonasThomas** [comment]
Bug confirmed.   There is a segmentation fault that's occurring during a drag and drop event.   The seg fault occurs when a layer is grabbed and dropped outside of the frame of the application.    @chchwy  I don't think I have privileges to assign myself  this bug.. I'll take a look at this.

**Comment by JonasThomas** [comment]
The segmentation fault occurs here:
void TimeLineCells::mouseReleaseEvent( QMouseEvent* event )

specifically in this section
 if ( m_eType == TIMELINE_CELL_TYPE::Layers && layerNumber != startLayerNumber && startLayerNumber != -1 && layerNumber != -1 )
    {
        mEditor->moveLayer( startLayerNumber, layerNumber );
    }
When I set up a break point of and drag the layer off the screen I get a layerNumber = -4
@feeef @tasaif     quick fix would be to change  !=-1  to >=0   although I suppose @chchwy would probably want the layerNumber set to -1

**Comment by JonasThomas** [comment]
The real critter is in int layerNumber = getLayerNumber( event->pos().y() );

**Comment by tasaif** [comment]
@JonasThomas should this be closed now?

**Comment by JonasThomas** [comment]
Yes
