### ISSUE TITLE
Not able to delete new camera layer

### ISSUE THREAD

**Issue by tasaif** [pencil2d/pencil#425]
When adding a New Camera Layer, it is not possible to delete it. Bitmap, Vector and Sound Layers can be deleted.
- Kaiko

**Comment by tasaif** [comment]
It looks like this was done intentionally?
@chchwy 
```bool LayerManager::deleteCurrentLayer()
{
    if ( currentLayer()->type() == Layer::CAMERA )
    {   
        return false;
    }

    editor()->object()->deleteLayer( currentLayerIndex() );

    if ( currentLayerIndex() == editor()->object()->getLayerCount() )
    {
        setCurrentLayer( currentLayerIndex() - 1 );
    }   

    Q_EMIT layerCountChanged( count() );

    return true;
}
```

**Comment by chchwy** [comment]
The function is not implemented correctly.
There must be at least one camera layer in project, but it doesn't make sense to let user create new camera layer but can't delete it.
