### ISSUE TITLE
Move tool should be enabled/disabled based on whether a selection is made

### ISSUE THREAD

**Issue by JonasThomas** [pencil2d/pencil#429]
Unless there is a valid use case that I'm missing, the move tool should be enabled when the selection box is visible for bitmap and vector and otherwise disabled when no selection is made
(I haven't played enough with the camera layer enough to determine if  behavior would make sense there as well)
I feel this will reduce selections have no function and add to the potential of buggy behavior.
Mentioned here https://github.com/pencil2d/pencil/issues/412

**Comment by tasaif** [comment]
I would imagine the move tool would effect everything in the current frame and layer almost like if there was a select box on the entire screen. I believe this is the most common behavior in image editing software.

**Comment by feeef** [comment]
I agree with that @tasaif. In that case, the move tool's icon shouldn't be an arrow but a move icon. There is one in the icon resources. The select tool could be the arrow. The select tool would be the one able to select areas of the picture.

**Comment by JonasThomas** [comment]
I was playing around with inkscape so how it compares..  Inkscape seems behave as you guys discuss above.  @tasaif  I noticed the messaging for invalid  or options for completion in inkscape vs the popup I was suggesting a few days back, seeing it in action, I see you point..   I'm closing the request.
