### ISSUE TITLE
QUESTION: is it possible to see scrooll bars when we "zoomed in" too much?

### ISSUE THREAD

**Issue by carlosgf** [pencil2d/pencil#43]
It is just a question. Not sure if someone can benefit from that.

**Comment by chchwy** [comment]
It's almost impossible to add scroll bars to Pencil2D currently. Pencil only paint the visible part of canvas to screen, it didn't paint the whole canvas, so there is really nothing to "scroll".

However, if preview window is implemented, it will be more easy to locate the working area of whole canvas.

**Comment by carlosgf** [comment]
it has been more than two (2) years since I first posted that comment, but now (Dec2015) I can't help but thinking that I was completely drunk at that time  :) ..... it really doesn't make any sense to me now. 

So, I am going to close it now
