### ISSUE TITLE
Color wheel UI enhancement

### ISSUE THREAD

**Issue by CandyFace** [pencil2d/pencil#430]
I've been playing with positioning of the color wheel and the color inspector, as the screen is much wider than it is tall, i think it would be ideal to move the color wheel next to the color inspector instead of having the them underneath each other. Although i'm not entire sure on that that yet... Maybe we could just split the color wheel and the inspector into separate windows, then people would be able to customize that themselves. 

I have so far made it possible to resize the color wheel, to fill less if needed. What i have achieved looks like the second/right image.. but my goal is to have the wheel aligned in center and also make the wheel thinner when resizing.

![Color wheel]
(http://i.imgbox.com/u98OxvBz.png) ![Resizing color wheel]
(http://i.imgbox.com/Rcs84hPL.png)

I'm not much of a math person, so i'll try to keep my boundaries within UI and interface and use my knowledge to develop those parts.

**Comment by Jose-Moreno** [comment]
@CandyFace Hey man, just wanted to say THANK YOU for the tools size sliders in a previous PR!

This looks great too and It's really needed to be able to change from HSV / RGB / HEX particularly if you're working with other software without having a palette file to export. Keep up the great work!

**Comment by tasaif** [comment]
@CandyFace should this be closed now?

**Comment by CandyFace** [comment]
Yes please close it
