### ISSUE TITLE
Add functionality to about window to show latest build Hash and User OS to improve quality of bug reporting

### ISSUE THREAD

**Issue by JonasThomas** [pencil2d/pencil#434]
![freecadabout](https://cloud.githubusercontent.com/assets/935641/12374747/956dae4e-bc6b-11e5-947a-af144684d001.png)
I hope my screen shot works here.  What do you guys things about enhancing the about box to what freecad has.
There is a command button that copies the following information into the clipboard.

OS: Ubuntu 14.04.3 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.16.6225 (Git)
Build type: None
Branch: master
Hash: 1027801be6e68f29659b6da624a1489588ba455b
Python version: 2.7.6
Qt version: 4.8.6
Coin version: 4.0.0a
It seems like if we did that we could get some better info on our bug reports.

**Comment by chchwy** [comment]
Now in the about dialog we can see
1. Version number
2. Git hash and commit date
3. Operating system name and version
4. build architecture like x86_64
