### ISSUE TITLE
[Improvement] Zoom Info

### ISSUE THREAD

**Issue by Spark01** [pencil2d/pencil#435]
Okay, I can't be the only one who's noticed how annoying it is that you can't tell what your current zoom is, right? It'd be nice to have a little notice somewhere saying what your current zoom is, like paint.net and gimp and basically every other image editor have. 

I can start working on this if that's okay, but I wanted to run it by the community before I do too much with it. :)

**Comment by tasaif** [comment]
I would just go for it. I don't think that's something that's liable to break anything. It should be pretty straightforward.

**Comment by CandyFace** [comment]
Yes do please add it! i too have been getting quite annoyed by the fact that i don't know how far i've zoomed in or out.

**Comment by feeef** [comment]
+1

**Comment by Spark01** [comment]
I've done it! It's added to my branch.
https://github.com/Spark01/pencil
