### ISSUE TITLE
Resizing of timelinecell seems to break moving of timeline rows.

### ISSUE THREAD

**Issue by JonasThomas** [pencil2d/pencil#436]
I noticed this when I was testing for  https://github.com/pencil2d/pencil/issues/425

I'm a little bit ahead of the master fb383338957955f5ccafe3afb884e3660749e2b4  my pull request hasn't been  merged yet. 
I really don't think my bug fix caused, so if some could confirm they're seeing this as well before https://github.com/pencil2d/pencil/pull/433 gets merged, I would appreciate that.

**Comment by Jose-Moreno** [comment]
@JonasThomas I was trying out this, but I'm not getting any kind of weird behaviour from the Nightly Build from yesterday (JAN 15 2016) Should I use the latest code from trunk?

How are you resizing the timeline "cells" are you using the preferences "frame in pixels" box? I tried also resizing the timeline window but nothing like that happened. I'll try with the trunk code built in Qt tomorrow. :+1:

**Comment by JonasThomas** [comment]
I don't think there should be a difference. This was my point about have the hash code in the about box.
The last commit was 1-13   
I think I narrowed this down a bit..  I inserted a layer and then I increased the size of the timeframe grid so there was a airgap between the bottom row of layer frames and the container .  It seems I can move freshly inserted  layer row except to the end (which was the first thing I tried.)   I still don't think my fix caused this(although I'm less certain since I suspect the issue resides in the same routine I was poking around in..   I need to  figure out some git magic to back up one commit and run a test.  Mental batteries are drained.  Time for bed.

**Comment by JonasThomas** [comment]
ok.. totally tired so this might not make sense.
If I grab a row-layer and drop it on the last row it work fine.
If I drop it past the last row it has problems with that...
The reason I'm having this issue is that the rows don't auto resize when a row is inserted which caused me to manually resize the row.
Question 
A)Should the grid automatically resize when a row is inserted? 
A.1 how crazy do animators get with the amount of layers.
B) Should we limit the resize not to exceed the amount of rows that are present?

**Comment by JonasThomas** [comment]
So I tested without https://github.com/pencil2d/pencil/pull/433  if you move the layer button to the bottom, you get a seg fault. (I posted a picture on the pull request).   There seems to be many tiny non-critical bugs that reveal themselves after the pull request is incorporated.   
Basically if you want to move a layer on the end you have to drop it on the end layer not past the end layer.
Also if you do drop it past the end layer the colored frame doesn't bounce back with the button.  I think the simplest solution is to throttle the max resize to the maximum rows present. 
To insure this happens we need to do a resize also after a frame insertion/deletion event..
(There may come a time where someone will want vertical scroll bars  because someone has put in 100 frame rows...  I think that goes beyond stabilization.

**Comment by JonasThomas** [comment]
@mor I just tested and it's still there.  It's pretty minor but its annoying me.  I see if I can post a video of it on saturday.

**Comment by Jose-Moreno** [comment]
I think you tagged the wrong dude, but I still got your message on my email due to Github notifications haha. Anyway, indeed, I think a video would deffinitely help other devs to see what's up. Sometimes it is rather difficult to describe very complex bugs even with a screenshot.

**Comment by JonasThomas** [comment]
so what is your tag

**Comment by Jose-Moreno** [comment]
I think it's the username that is displayed in our replies, but it should be easy to know just by using the @ symbol and waiting a moment for a list of participants to populate :)

"@morr" is how you tag me in the forum though.

**Comment by JonasThomas** [comment]
@Jose-Moreno   Here you go.  
https://youtu.be/INAsUcpywL8

**Comment by tasaif** [comment]
Thanks for making a video. It's much easier to understand the bug now.

When you add a new layer, the scrollbar to scroll down is way off to the right. The scroll wheel should also allow you to scroll down.

With regards to the bug, I think the proper behavior should be the expected behavior. We should have it to where when you drag it to the bottom, it gets moved to the bottom.

**Comment by JonasThomas** [comment]
@tasaif  @Jose-Moreno 
Drop down behavior is now correct.   I experience a gotcha btw... It took me a while to realize that the last row represents layer 0..  I had it my head that the first row was layer 0 event though that's not what the code said..    
I've been using a marble mouse and I don't have the scroll wheel mapped.  When I switched to a mouse I noticed that the scroll down works properly but the scroll up appears to be broken.  I just a soon deal with this on this issue for the moment.

**Comment by JonasThomas** [comment]
The scroll bar bug is very strange and I don't fully understand it yet.
It existed prior to Bug Fix #454  but is didn't test to see if I created it before #433 (But I don't think I did)
I think the issue is somewhere between
void TimeLineCells::vScrollChange( int x )
and 
void TimeLine::wheelEvent(QWheelEvent* event)
As near as I can tell pixelDelta() is returning 0 all the time (maybe...)
(I'll figure it out ;)  )

**Comment by JonasThomas** [comment]
@chchwy  I added two changes pull request to my bugfix branch which should be in sync with the current master.
One deals with the drag and drop in the timeiine
The other fixes the scroll bar.
My git stills are not as good as I would like them to be..  Hopefully my pull request makes sense.. (If not please let me know what your preference how I should submit a pull request.
JT.

**Comment by JonasThomas** [comment]
#456   Previous pull request was sort of screwed up, I think this one should be better.
