### ISSUE TITLE
Add a shortcut key for making straight lines with the polyline tool

### ISSUE THREAD

**Issue by ghost** [pencil2d/pencil#44]
Hi,

That will allow to work on drawings/paintings with organic look (like characters, nature landscapes) and inorganic things (buildings, cars) just pressing a hot key will enable to draw straight lines without changing to another tool, more specific to the Polyline tool.

So with a shorcut key there is no need to change tools. Maybe applying an extra function to the "POLYLINE TOOL" (under the TOOLS MENU)?

Thanks

**Comment by carlosgf** [comment]
What I was intending in my first comment was to Request another keyboard shortcut for FAST/TEMPORARY use of the PolylineTool.

Thanks

**Comment by Kaikogf** [comment]
Closing this as there is another post [#1248] with more detailed idea about an implementation of a feature similar to this one

**Comment by Kaikogf** [comment]
Upss.. I am not able to close this post...

**Comment by chchwy** [comment]
Closing :D
