### ISSUE TITLE
[BUG] Zoom Reset with every click through Key Shortcut

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#442]
**--Video Demo--**
https://youtu.be/dku9M_V-pq0

**--Steps to reproduce--**
1) Press Ctrl + Spacebard to enter Zooming Mode
2) Click & Drag to either Zoom-In or Zoom-Out
3) Release your Mouse button
4) Click & Drag again
5) Zoom resets to 100%

**--Expected Results--**
Users should be able to zoom in and out from the last known "zoom distance percentage" (%) they left their image at. 

For example: If you zoomed the image by 300%, that is the image is scaled 3 times it's current size, when you use the Zoom function again you should be able to move away, say to 100% or closer to a particular region (i.e 600%) from the current image scaling factor (300%), instead of always going back to 100% effectively resetting your zoom.

**--System Information--**
Pencil2D Nightly Build 15 Jan 2016
Windows 7 64bits SP1
ATI Radeon HD 6770 1GB
AMD Phenom II X4 965 BE 3.4 GHZ
4 GB RAM

**Comment by tasaif** [comment]
@feeef can this be closed?
