### ISSUE TITLE
[BUG] Polyline & Pen Tool Sharing Size Property

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#443]
**--Video Demo--**
https://youtu.be/cafRCJ3cHQA

**--Steps to reproduce--**
1) Select the Polyline tool
2) Draw a polyline with it's current width
3) Change the polyline size slider or use the number arrow box
4) Draw a new polyline to compare the lack of size change
5) Select the Pen tool
6) Change the pen tool size
7) Select the polyline tool
8) Draw a polyline; compare the new size with the previous lines on canvas.

**--Expected Results--**
Users should be able to change the polyline tool stroke size independently from the pen tool, and viceversa.

**--Notes--**
I think that revieweing the variables that hold the stroke size for each tool would be the most direct approach, and if by chance this variable is being shared (used as a unique placeholder), I'd suggest that each tool gets an individual variable for it's stroke size.

**--System Information--**
Pencil2D Nightly Build 15 Jan 2016
Windows 7 64bits SP1
ATI Radeon HD 6770 1GB
AMD Phenom II X4 965 BE 3.4 GHZ
4 GB RAM

**Comment by linganesan** [comment]
I guess I fixed this bug on my machine. How do I sent those changes to review? Can I make a commit in dev branch or send a patch?

**Comment by tasaif** [comment]
1) Fork the repo
2) Clone it locally
3) Create a new branch for the fix (e.g. polypen_size_443)
4) Put all of your changes into this branch and push it to github

You should be able to click open pull request from github at that point. If you need me to go into more detail, please let me know.

**Comment by linganesan** [comment]
Should I sent a pull request to master branch or dev branch?
![screenshot from 2016-01-26 01-55-16](https://cloud.githubusercontent.com/assets/8380786/12563443/66948ae0-c3d0-11e5-9760-1e9721b51882.png)

**Comment by tasaif** [comment]
master
