### ISSUE TITLE
[BUG] Polyline Display & Drawing Bug During Creation Phase

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#445]
**--Video Demo--**
[14 JAN 2016 Build: Video Demo - Ghost Polyline Bug](https://youtu.be/UN9oXSxU6-E)

[27 JAN 2016 Build: Video Demo - Polyline erases "Ghost" Polyline, contributed by @JonasThomas ](https://www.youtube.com/watch?v=0DyrH3E-clg)

**--Steps to reproduce--**
1) Select the Polyline tool
2) Create a reference line that is drawn on the canvas
3) With the polyline tool selected, begin creating a new stroke.
4) You just need to click once for the first point to become "fixed" on the canvas
5) When the second point becomes dragabble, Press ESC.
6) Your "Ghost" line will appear to be drawn.
7) Select the eraser tool and click anywhere on canvas.
8) The second polyline will dissapear.
9) Repeat Steps 3 to 6, and go to 10
10) Use any other tool, except the polyline tool and draw a minimum of two strokes.
11) Press Ctrl+Z until the last stroke is undone. You'll notice that the "Ghost" Polyline will dissapear as well.

**--Expected Results--**
Polyline creation process should either be canceled or line should be drawn up to the last point  that was "fixed" on the canvas

**--Notes--**
I think actually when you enter the "polyline creation" state, pressing esc should just undo any "fixed" points that have been placed on the canvas, while pressing enter should terminate the creation process and ultimately draw the line, which is the same as double clicking to finish the polyline. I'll propose this on a separate issue later on.

**--System Information--**
Pencil2D Nightly Build 15 Jan 2016
Windows 7 64bits SP1
ATI Radeon HD 6770 1GB
AMD Phenom II X4 965 BE 3.4 GHZ
4 GB RAM

**Comment by linganesan** [comment]
So you need to cancel that ghost polyline when ESC is pressed? Then 'ESC' and 'ENTER' buttons have the same functionality! I just checked krita's polyline tool, in there if I press 'ESC' then it cancel the polyline and Pressing 'ENTER' fixed the current state of polyline on the canvas. Shall we do it like that or what?

**Comment by linganesan** [comment]
Sorry about the previous comment. I thought Pressing Enter will cancel the current polyline state on canvas but it is not. It seems like another issue! :/

**Comment by CandyFace** [comment]
This has been fixed for a while now, i'm closing this.

**Comment by aprekates** [comment]
I get the polyline ghost areas in build 2-Nov-16  in windows 10.
Has the bug get fixed in linux maybe?

**Comment by CandyFace** [comment]
The bug is fixed universally, not in Nov 16 build though, you need to at least get something from Feb 2017 but using the latest Nightly build would be the best.
