### ISSUE TITLE
[BUG] Selection Tool Behaviour Duplicates Canvas Content Display

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#446]
**--Video Demo--**
https://youtu.be/k_dV3KqbV6s

**--Steps to reproduce--**
1) Create a line stroke with any tool
2) Select the "Selection" Tool (Marquee)
3) Click & Release Once without dragging the selection marquee.
4) Move your cursor to a different position and Click & release a second time without dragging the selection marquee
5) You will see that the created stroke(s) become duplicate
6) If you repeat steps 3 to 5, the duplicate stroke will change position relative to where you clicked during the new steps

__*To Undo the duplicates*__
1) With the selection tool selected, click & drag a slection marquee
2) Click outside or inside the selection marquee to make it dissapear
3) The duplicate strokes will dissapear as well

**--Expected Results--**
When "failing" to create a selection marquee, we should NOT see a duplicate version of the current strokes on canvas.

**--System Information--**
Pencil2D Nightly Build 15 Jan 2016
Windows 7 64bits SP1
ATI Radeon HD 6770 1GB
AMD Phenom II X4 965 BE 3.4 GHZ
4 GB RAM

**Comment by feeef** [comment]
Thanks for the great bug reports @Jose-Moreno ! :) 
I know where this one comes from. I will handle that!

**Comment by feeef** [comment]
Should be fixed with my latest pull request.

**Comment by tasaif** [comment]
@feeef Can this be closed?

**Comment by feeef** [comment]
Yep, I close it! :)
