### ISSUE TITLE
[BUG] Onion Skin does not show non-contiguous keyframes

### ISSUE THREAD

**Issue by MicSc** [pencil2d/pencil#449]
**--Pictures--**
![pencil_bug1](https://cloud.githubusercontent.com/assets/16787308/12468248/1532dbb2-bfe2-11e5-83a6-cacda2ba28aa.png)
![pencil_bug2](https://cloud.githubusercontent.com/assets/16787308/12468249/18373a74-bfe2-11e5-87c1-dd051f7afc86.png)
![pencil_bug3](https://cloud.githubusercontent.com/assets/16787308/12468251/1a4d4498-bfe2-11e5-97d1-8a2d752bbcc3.png)
**--Steps to reproduce--**
1)Activate Onion Skinning
2)Create keyframe(s) and draw something in it
3)Create or move a keyframe so that there is a gap of one or more frames between keyframes.

If the gap is two frames or longer, the onion skin of the previous keyframes will not be visible, if it is one frame only the second-level onion skin will be faintly visible.

The reason appears to be that the onion skin counts and displays absolute (global) frames instead of keyframes.

**--Expected Results--**
The default behaviour of Pencil2D 0.5.4b, onion skin displays previous/following keyframes regardless of any gaps.

**--System Information--**
Pencil2D Nightly Build 15 Jan 2016
Windows 10 64bit
Intel Mobile Core 2 Duo P8600 @2.40GHz
Intel GMA 4500MHD (GM45)
4 GB RAM

**Comment by feeef** [comment]
There is a button (maybe not obvious enough) to switch from absolute to relative keyframe onion skin positions. If you over it with your mouse, it says "Toggle match keyframes".

![screenshot from 2016-01-21 08-58-55](https://cloud.githubusercontent.com/assets/383399/12474734/a5fd3fe4-c01d-11e5-9a66-255c2cb6832e.png)

The feature is there and maybe we should improve the UI to make it more obvious.

**Comment by CandyFace** [comment]
Yea i have been thinking about ways to make this more obvious, because it's current UI doesn't say much when you press it, unless you have one of the "show onion skin" displays enabled and look at the timeline. Maybe it should have two different images, one for relative and another for absolute.

**Comment by feeef** [comment]
Feel free to update this UI as you wish @CandyFace . I am not very good in UI design and you seem to be pretty good in this area. I like what you have done with the colour wheel.

**Comment by tasaif** [comment]
@MicSc is this resolved then?

**Comment by MicSc** [comment]
Well now I feel stupid, but yes, I guess this resolves it.
Not sure if it should be left up for the suggested UI change or if that should be a new issue?

**Comment by MicSc** [comment]
Well now I feel stupid, but yes, I guess this resolves it.
Not sure if it should be left up for the suggested UI change or if that should be a new issue?

**Comment by MicSc** [comment]
Well now I feel stupid, but yes, I guess this resolves it.
Not sure if it should be left up for the suggested UI change or if that should be a new issue?

**Comment by MicSc** [comment]
Well now I feel stupid, but yes, I guess this resolves it.
Not sure if it should be left up for the suggested UI change or if that should be a new issue?

**Comment by MicSc** [comment]
Well now I feel stupid, but yes, I guess this resolves it.
Not sure if it should be left up for the suggested UI change or if that should be a new issue?

**Comment by MicSc** [comment]
Well now I feel stupid, but yes, I guess this resolves it.
Not sure if it should be left up for the suggested UI change or if that should be a new issue?

**Comment by MicSc** [comment]
Well now I feel stupid, but yes, I guess this resolves it.
Not sure if it should be left up for the suggested UI change or if that should be a new issue?

**Comment by MicSc** [comment]
Well now I feel stupid, but yes, I guess this resolves it.
Not sure if it should be left up for the suggested UI change or if that should be a new issue?

**Comment by tasaif** [comment]
Don't worry about it.
Please put it in a new issue.
