### ISSUE TITLE
when i import sound it wont play??

### ISSUE THREAD

**Issue by kitkat549** [pencil2d/pencil#453]
i make a sound layer, i import the music in, but it doesnt play when i hit play?

**Comment by Jose-Moreno** [comment]
@kitkat549 Hey, yes, sadly this has been a known bug for a long time. Right now developers are working on fixing stability before messing with sound or video, but I can assure you they are already looking for a solution.

In the future please use the search function to find if there are similar reports. You can do so on the issues tab, next to filters and use the search bar. Please refer to our dedicated FAQ on the Pencil2D website here for more information on how to make sound work for Windows 7 here: http://www.pencil2d.org/pencil2d/faq/

For any other OS, you'll have to be patient for a new release with a sound fix.

**Comment by Jose-Moreno** [comment]
@tasaif As far as I can tell this bug is related or is the same as #233 #289 and #330 (User "oracleofjamie" followed the troubleshooting guide that is outlined on the FAQ & Forums) Just leaving this here so you guys can keep track of those duplicate reports.

**Comment by tasaif** [comment]
thanks @Jose-Moreno for putting the duplicates in one spot
thanks @kitkat549 for showing initiative and reporting a bug when you saw one
