### ISSUE TITLE
Opacity slider for Layers

### ISSUE THREAD

**Issue by alexandervrs** [pencil2d/pencil#459]
There was a case that I wanted to add a new bitmap layer and import my character sheet PNG so I could reference some of her poses. 

Problem is that Pencil2D does not have an opacity setting for each layer so that I can make the reference sheet more dim and draw over on another layer. So an opacity slider for each layer would be useful.

**Comment by feeef** [comment]
That's a very good feature indeed!
Thanks @alexandervrs

**Comment by Spark01** [comment]
Crap, I self-assigned this months ago and never did it. I'm so sorry folks, I'm gonna start working on this ASAP!
