### ISSUE TITLE
Grid cell size settings in Preferences

### ISSUE THREAD

**Issue by alexandervrs** [pencil2d/pencil#460]
There is a Grid feature but it seems fixed to a specific cell size. It would be useful if we had settings for it in Preferences like Grid width & height in the format of like:

Grid Cell Size 
[ 32] x [ 32]

Additional grid settings could be Grid Color and a slider for Grid Opacity.

**Comment by Spark01** [comment]
This is in the development version, unless it's been removed for some reason. Is it okay for me to go ahead and close this?
