### ISSUE TITLE
Invert mouse wheel zoom Preference

### ISSUE THREAD

**Issue by ghost** [pencil2d/pencil#462]
It would be useful, perhaps in the Preferences > Shortcuts section, to have an option to invert the mousewheel zoom. Some drawing apps, especially Japanese ones, use wheeldown to zoom in and wheelup to zoom out so it would be helpful for those users -myself included.

**Comment by curtisbowden** [comment]
@alexandervrs has been waiting a long time!  I would like to be assigned this issue if it hasn't been closed by another PR elsewhere.

**Comment by scribblemaniac** [comment]
@curtisbowden Go for it!
