### ISSUE TITLE
[BUG] Quick width/feather adjustment misbehaving

### ISSUE THREAD

**Issue by 4423Q** [pencil2d/pencil#464]
Running the latest sources in Ubuntu 14.04.
Bug arises when using the CTRL or SHIFT modifiers and left clicking and dragging.
Width/feather size indicator appears and follows mouse, indicator gradually changes size but doesn't go away when the mouse is released. Can't make any LMB input while this is happening. Eventually the indicator disappears and the new size updates in the tool window.

While the indicator is visible the ScribbleArea::mouseMoveEvent function in core_lib/interface/scribblearea.cpp gets repeatedly called which then calls currentTool()->adjustCursor. The ScribbleArea::mouseReleaseEvent doesn't get called until the indicator goes away. 

It seems to be that the indicator changes are in some way preventing the mouseReleaseEvent getting called for ScribbleArea, I'll have a look and see if I can figure out what's causing this, but it'd be helpful to know whether this bug exists on Windows/OSX.

**Comment by 4423Q** [comment]
I think it's something to do with how X11 handles mouse events

**Comment by Jose-Moreno** [comment]
@4423Q I was actually going to report this first in the forum as well. But first I reported related issues that arise when the eraser tool is invoked through the keyboard shortcut CTRL + SHIFT

http://www.pencil2d.org/forums/topic/bug-invoked-eraser-behaviour-through-key-shortcut/

**Comment by feeef** [comment]
I reopened! ;)

**Comment by Jose-Moreno** [comment]
@feeef I opened the 2 bug reports as you suggested this bug should then be linked to #466  and #467

**Comment by 4423Q** [comment]
This bug in particular isn't actually present if you build using Qt5.6.0 beta, AFAIK the Nightly build zips are built using 5.5.1 which I think still has the bug. The bug is related to Qt's compression of the events queue under certain configurations, so it means each event has to be processed in turn. Qt5.6.0 fixes this and skips events in the queue. I think it's related to this Qt bug: https://codereview.qt-project.org/#/c/115531/

so it's not a Pencil bug, it's a build environment problem.

**Comment by scribblemaniac** [comment]
Close this as it does not appear to be an issue anymore and we've been using Qt 5.6+ for a long time now (in fact I think the code depends on it in some places).
