### ISSUE TITLE
[BUG] Eraser Tool Toggle - Tool Size Behaviour

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#466]
### **--Issue Overview--**

When you press CTRL+SHIFT the eraser tool changes it’s size to **adjust to the size of the current tool** you are using. I initially thought it was a great idea, but we have the following problem:

**--Steps to reproduce--**
1) Select the eraser tool
2) Write down it's current size (e.g 5 pixels)
3) Select any drawing tool (i.e Pencil Tool)
4) Take notice of it's current size (e.g 58 pixels)
5) Press & hold CTRL + SHIFT and notice the eraser pixel size which varies according to this table:

**Eraser Vs Active (Drawing) Tool Size Offset**
![Eraser Vs Active Tool Size Offset ](http://www.pencil2d.org/wordpress/wp-content/uploads/2016/02/offset_table.jpg)

6) Press & hold CTRL+SHIFT and notice the feather size which varies according to the selected tool, so the eraser too adjusts it's feathering to absolute values:

**Eraser Tool Vs Active Tool: Size & Feather Values**
![Eraser Vs Active Tool Feather Values](http://www.pencil2d.org/wordpress/wp-content/uploads/2016/02/tool-size-feather-toggle-values.jpg)

**--Expected Results--**
Size adjustment should occur at the same ratio i.e if my pencil is 1 pixel my eraser should be 1 pixel. When using non-drawing tools eraser should be left with the previously used size & feathering (look proposal below)

**--Behaviour Change Proposal--**
For ease of use we should just leave the eraser tool size & feathering to have an individual size that does not change to match the original drawing tool you're using when toggling.

This is actually sometimes preferred in other drawing applications because you can configure the eraser tool separately as if you had either a kneaded eraser or a Rubber eraser for different tasks when drawing.

**Comment by feeef** [comment]
I fixed that, it is here : https://github.com/pencil2d/pencil/pull/470
