### ISSUE TITLE
[Improvement] Make it possible to turn off sizing with ctrl/shift

### ISSUE THREAD

**Issue by Spark01** [pencil2d/pencil#468]
Okay this is pretty minor but personally it really irks me, sometimes when I'm doing a keyboard shortcut I accidentally change the size of the brush or feathering. It's be nice to have a simple on/off button for this feature, since it is potentially undesirable. (This would also open up the door to the user making a shortcut for picking a color that uses ctrl, like in gimp)

**Comment by 4423Q** [comment]
This was annoying me too so I had a quick go at implementing it. I've not done open source stuff before, but I've made a pull request and hopefully not broken something. #469

**Comment by Spark01** [comment]
Alright, cool, I'll add an option in preferences.

**Comment by Spark01** [comment]
Okay, this is done by my latest commit. Is working fine.
