### ISSUE TITLE
Brush tool draws on top of grid and higher layers until mouse is released

### ISSUE THREAD

**Issue by Spark01** [pencil2d/pencil#473]
While you're drawing, it shows the stroke on top of everything else. I've tried to fix this but I'm not familiar enough with the drawing mechanics and I couldn't figure out how.

**Comment by feeef** [comment]
I guess we should leave this behavior as it is now because it is fast and you always see what you draw.
It would be possible to render every stroke live but it would cost in term of hardware resources and make Pencil2D almost useless on slower computers.

**Comment by Spark01** [comment]
True. Most programs don't have this problem though, so there's definitely a way to do it without slowing things down drastically - I'll try and figure that out, I guess

**Comment by Spark01** [comment]
Hm, I made a function that re-renders only the specified area and it seems to fix this bug without any notable performance drop. Hooray!

**Comment by CandyFace** [comment]
That sounds promising, so it's only doing the doing the re-render inside a ROI? that's indeed a lot less painful. I imagine that it would have to be tested though on a laptop with somewhat below average specs before it can be concluded that it's not too performance heavy. It does sound like a very plausible solution though. Is the bug-fix available on your repo, because then i'll take a look and see if i can see and notable difference on my Macbook air.

**Comment by Spark01** [comment]
It is not yet - I've noticed that it complicates the process of making a constant-opacity brush that can't overlap itself, so I'm trying to work out how to fix that before I upload it to github.

**Comment by Spark01** [comment]
Okay I just uploaded it to Github. #477

**Comment by Spark01** [comment]
@CandyFace were you able to test this yet? No rush, but it'd be good to know if it's okay to merge the PR

**Comment by CandyFace** [comment]
@Spark01 No sorry, i haven't had the time to do a proper test yet. I'm a bit busy atm. though i'll try to see if i can make it happen before the end of the week.

**Comment by CandyFace** [comment]
@Spark01 Okay so given that the brush engine is still a bit slow on OS X 10.11 when using a pen, causing a bit of delay, doesn't make it easier to test.. however i tried a few things and compared the performance with an older build, and concluded in all my tests that the bugfix seemed to make it a bit faster, not by much though. I would say it should be okay to merge, but wouldn't it be better if this was applied to all the tools, for consistency, before merging?

**Comment by feeef** [comment]
I have just checked your code @Spark01 . It seems that it is done the correct way. You repaint the bitmap image just were the stroke is done so it shouldn't make anything slower.

For me the feature can be merged. If I understand the code one can just disable this behaviour by commenting out the call to paintBitmapBufferRect() in ScribbleArea? It could even be a setting if things are indeed slow on slow computers.

**Comment by CandyFace** [comment]
Closing this as it's been implemented a long time ago.
