### ISSUE TITLE
Linux Binary Packaging

### ISSUE THREAD

**Issue by feeef** [pencil2d/pencil#480]
We need to provide a binary package for Linux, that works on all the main distributions.

**Comment by mapreri** [comment]
@feeef OOI, how are you doing it?
(Debian maintainer of pencil2d here (and indirectly of Ubuntu too))

**Comment by feeef** [comment]
Hi @mapreri ! Nice to meet you! :) 
I am myself a Debian user (on all my machines). Thanks a lot for your help with pencil2d. Thank you very much for adding one of the latest builds to Debian Stretch!

**Comment by feeef** [comment]
Sorry @mapreri,  I send my previous message too quickly without answering your question. 

Actually, I don't know how to do it. I will have to find out.

**Comment by mapreri** [comment]
yeah, "problem" right now is to choose when to take a given random commit to upload…  (waiting on 0.6 :wink:)

**Comment by CandyFace** [comment]
The recently implemented travis integration with google drive has added binary releases for linux and mac, see #627 and #617.

**Comment by J5lx** [comment]
Can this be closed now that we have AppImages?

**Comment by J5lx** [comment]
Umm… anyone here? Can this be closed now that we have AppImages?

**Comment by chchwy** [comment]
Give it a shout if any linux guy here.... (I'm not a linux guy :p)

**Comment by Jose-Moreno** [comment]
@mapreri @feeef Since you guys were interested in this particular issue, we're wondering if this can be marked as resolved. Now that Appimages have been implemented for linux distros we'd like to know what is your take on this?

**Comment by J5lx** [comment]
In that regard I could try to get it into the Arch repos (unless there is some other Arch user here who already has connections to the TUs). The initial report was about a package “that works on all the main distributions” though, and that kind of cross-distro packages is what AppImages are all about.

**Comment by mapreri** [comment]
yeah, the initial repo is about those common packaging format like appimages, which I don't particularly care, and I think that is done now, so this bug can probably be closed.
