### ISSUE TITLE
[BUG] Camera Border dissapears by layer re-order

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#481]
**--Issue Overview--**

The Camera border becomes either missing or re-positioned after changing the layer order upwards. This does not happen when the layer is moved to the bottom of the layer stack. This bug appears differently in both Nightly Builds from January 15th and February 16th.

**--Video Demo--**
https://www.youtube.com/watch?v=8PeVbXl0BJ4&feature=youtu.be

--Steps to reproduce--
1) Open Pencil2D
2) Activate the Camera Border
3) Move the camera layer to the top of the layer stack
4) The camera border dissapears
5) Select the camera layer to make the camera border re-appear
6) Move the camera layer back to it's default position downwards
7) Camera border remains intact.

**--Expected Results--**
The camera border should be unaffected by it's position in the layer stack or any other behaviour related to how layers are ordered.

**--System Information--**
Pencil2D Nightly Build 15 Jan 2016 / Nightly Build 16 Feb 2016 (Run & built with Qt Creator 3.4.2 based on Qt 5.5.0)
Windows 7 64bits SP1
ATI Radeon HD 6770 1GB
AMD Phenom II X4 965 BE 3.4 GHZ
4 GB RAM

**Comment by feeef** [comment]
I fixed this issue in my latest pull request. I merged it so you can test it @Jose-Moreno

**Comment by Jose-Moreno** [comment]
@feeef Just tested this and it's fixed, you have magic fingers man! :+1: I'll close the issue now :)
