### ISSUE TITLE
[BUG] - Camera border size and position not updated when zooming and panning

### ISSUE THREAD

**Issue by feeef** [pencil2d/pencil#484]
The camera border should be updated when zooming in or out and when panning with the hand tool. Otherwise, if the frame is larger than the screen, we don't see any border and it is impossible to know what we are framing.

**Comment by feeef** [comment]
This has been in my todo list for a long time so I plan to fix this problem for my next PR.

**Comment by Jose-Moreno** [comment]
@feeef could this issue be related to #481 ? If you plan on checking the camera border code as a whole, would mind including that report into your next PR?

**Comment by feeef** [comment]
Sorry, I didn't see you already added this issue! I close this one!

**Comment by Jose-Moreno** [comment]
@feeef Oh, but the other issue was only related to how ordering layers would break the camera border, not how the zoom or pan didn't update the border. Although if you think it stems from the same problem in the code you can keep either issue open. I don't see a problem with that :+1:

**Comment by feeef** [comment]
Ok, I didn't fully read the other issue and you are right, they are different issues. I re-opened! ;)

**Comment by feeef** [comment]
Ok, I fixed this issue and merged my pull request straight away. I close it.
