### ISSUE TITLE
Pencil2D - Czech localization file

### ISSUE THREAD

**Issue by pafri** [pencil2d/pencil#49]
Hi,

I took and translated .ts file. Could you provide e-mail for me to be able to send it to you? My is: pavelfric [sour fisch] yahoo dot com

**Comment by Jose-Moreno** [comment]
@pafri Hi! it's been a while. We wanted to let you know that Pencil2D has moved the translation databases to Transifex. If you'd like please take a look at it on this URL: https://www.transifex.com/pencil2d/pencil2d/

Thanks!
