### ISSUE TITLE
Have an option for a preview circle around the cross cursor

### ISSUE THREAD

**Issue by alexandervrs** [pencil2d/pencil#490]
There should be an option in the Preferences to display a circle around the cross cursor so you can preview better the brush thickness. 

Examples: 
http://pe-images.s3.amazonaws.com/photo-editing/color-replacement-tool/color-replacement-tool-cursor.gif
https://media-mediatemple.netdna-ssl.com/wp-content/uploads/images/photoshop-brushes/cursor-changing.gif

**Comment by alexandervrs** [comment]
I just noticed there is a Preference for a dotted cursor, but the circle does not scale correctly as you zoom.

**Comment by Kaikogf** [comment]
@alexandervrs 

I played a little bit with the dotted circle and it worked OK with me when I zoomed it.
What I noticed is that the dots are actually TOO big when you zoom in (not sure if you were referring to this?)

Not sure if it is possible to do it but I would suggest to have the dotted circle's thickness independent of the value of the canvas (dimension/zooms)

Opening a new issue with the suggestion and closing this one?

**Comment by CandyFace** [comment]
There has been a circle cursor available for some time now.

@Kaikogf Yeah I think that opening a new issue would be ideal, then i'll close this one.
