### ISSUE TITLE
Help us host pencil2d.org !

### ISSUE THREAD

**Issue by gordielachance** [pencil2d/pencil#494]
Hi guys,

Since there seems to have a problem with pencil2d.org (I don't know what yet), my host asked me to remove it from my web space or they would delete my account.
I cannot thus host it there, I need a separate place to host pencil2d.org. 
I open this ticket so people that maybe have a solution (free web space, etc) could tell us here !

The minimum requirements are :
- php > 5.3
- mySQL databases
- ability to run Wordpress on it

Thanks

**Comment by hako** [comment]
@gordielachance  Have you thought about hosting pencil2d.org using [Heroku](https://www.heroku.com)?

They support [PHP](https://www.heroku.com/php) and [MySQL](https://elements.heroku.com/addons/jawsdb)

**Comment by gordielachance** [comment]
No, I don't know that, but [this guy does not recommand it](https://www.wphuman.com/hosting-wordpress-on-heroku-8-things-i-wish-i-knew/).  (We need to run Wordpress on it)

**Comment by feeef** [comment]
@gordielachance do you have a spare computer at home (doesn't need to have big specs)? Do you know how to setup a debian box with apache and mysql? You could just forward port 80 to this machine from your internet box.

This is a solution that requires some technical skills but it could work while we find a good host for pencil2d.org

**Comment by DarckCrystale** [comment]
Copy of my facebook post:

> Try Kimsufi : https://www.kimsufi.com/uk/ and https://www.kimsufi.com/uk/servers.xml
> (usa available, I suppose)
> 
> I have one kimsufi for personal purposes, it's nice and have an anti-ddos protection.
> If you know how to manage a dedicated server, this one could be great AND affordable, no? If you don't, I can maybe help you to install and configure it.

Or, maybe, I can try to host the website on my personal kimsufi, but it seems not really safe.

**Comment by mzilikazi** [comment]
https://wordpress.com/ 

https://wordpress.org/hosting/

**Comment by gordielachance** [comment]
Hi guys,
Just had a message from my host saying that now that pencil2D is disabled, I don't surcharge the server anymore.
I have made various checks to clean it (they say it had probably a virus); and i'll probably try to restore it monday.  Then, we'll see if the problem comes back or if it's OK...

**Comment by feeef** [comment]
Great news @gordielachance ! Maybe you should backup the database, erase everything on your server, do a fresh, clean install and restore the database.

**Comment by DarckCrystale** [comment]
Hi. This is really great @gordielachance!
I agree with @feeef, you could try an entire reinstall, if you have the time/motivation.

**I add some information:**
If you want to try Kimsufi, I would be glad to share mine ^^ My dedicated server has a management screen with graphes and a table with the 5 process using the more RAM, this could be useful for your investigations ([see a screenshot here for the graphes](http://arnaudbertrand.io/images/2014/12/kimsufi-monitoring-portal.png)).
If the money is the problem to change of host, I can pay for you an host, it's not so big (17,99€ per month for me, maybe less for yours, depending of the ressources you need).

One question @gordielachance, I see you use spaces between words and punctuations like '?', english is not your native language?

**Comment by alexandervrs** [comment]
For paid hosting, I could recommend [servergrove.com](servergrove.com), their support is awesome.

Otherwise for free hosting, you could go to [awardspace.com](awardspace.com) for now, their free plan allows 1 MySQL DB and they have PHP 5 I believe. No ads also. Only limitation would be that you can't upload mp3 files and cannot send emails.

**Comment by Brad-Le** [comment]
Did you ask your host why they wanted you out such as causing high, disk, network, or bandwidth usage?

If you are still looking for a home, I can happily sponsor you a server and have a LAMP stack set up on it if you please.

**Comment by gordielachance** [comment]
Hi guys, I did restore the website with a fresh install, added plugins for malwares and spammers; and cleaned the database.  Quite some work...
I was working on a new theme, but it's taking too long.  I'll do that slowly, when I have some time.
The website is online at http://www.pencil2d.org/wordpress but I didn't remove the redirection page yet at http://www.pencil2d.org coz I would like to check with my host if everything is OK.  Meanwhile, you can login and edit stuff (if you are an editor).

**Comment by chchwy** [comment]
@gordielachance Good job!

**Comment by Jose-Moreno** [comment]
@gordielachance Nice. Hopefully things will go well. however I must tell you that just today we've had a lot of spam bots registered. I've already confirmed my suspicions with a +96% of accuracy that the spambots always have a username that consists of a: name + (Optional: Numbers) + 2 CAPITAL letters at the ends of their username. If you see others who have registered previously they have never submitted anything other than spam (those who managed to bypass akismet).

We need to create a filtering rule for the registration process somewhow to prevent these spammers to overload the server. Is there a way we can like filter them all and ban them? You can check the activity log for today and see for yourself.

http://www.pencil2d.org/activity/

**Comment by Jose-Moreno** [comment]
@gordielachance We're also having an increased number of "single name" spammers that promise you stuff and ask you to contact them on their email via private messages. I've been contacted by 3 of those in the same day already.

You can see other people who are reporting that here: http://www.pencil2d.org/forums/topic/spam-messsages/

**Comment by chchwy** [comment]
Anything about website please go to #558
I'm closing this.
