### ISSUE TITLE
No sound?

### ISSUE THREAD

**Issue by Purplescrib** [pencil2d/pencil#497]
I'm using Pencil ver 0.5.4 and the sound layer wont work. I've tried converting it to a .wav file, but it still wont work. Please help!!

**Comment by Jose-Moreno** [comment]
@Purplescrib This is a well known issue that won't get fixed until the next release. Please read the FAQ for possible solutions depending on your OS, thanks.

https://pencil2d.github.io/doc/faq/#when-i-import-sounds-i-can-see-it-on-the-layer-but-i-cant-hear-anything-windows-only
