### ISSUE TITLE
MacOSX build crashes when played with an audio layer

### ISSUE THREAD

**Issue by gunCannon** [pencil2d/pencil#508]
-

**Comment by Jose-Moreno** [comment]
@gunCannon Our lead dev is working on finally fixing the audio layers. Hopefully nearing July we can have some development towards fixing these problems. For now don't try to use the audio as it is unusable in any working version you can download from the webpage.

p.s. Next time please give details as well as to which version you have if it is a more specific bug, thanks!

**Comment by chchwy** [comment]
The crash issue is fixed, close.
