### ISSUE TITLE
[Suggestion] Show unsaved sign on the program title

### ISSUE THREAD

**Issue by hankofficer** [pencil2d/pencil#511]
I think it would be nice to have a star sign after filename if the file haven't saved. e.g.
`C:/user/mybox/myartwork.pclx* - Pencil2D`

**Comment by Jose-Moreno** [comment]
@hankofficer I like this idea, similar to Blender and other software, although maybe we should be even bolder about it and display a <not saved> message haha, thee are a lot of kids using this software and they have short attention span :stuck_out_tongue_closed_eyes:

**Comment by lordadamson** [comment]
I'm working on it :D
