### ISSUE TITLE
[Suggestion] Exporting animation as Animated GIF and APNG.

### ISSUE THREAD

**Issue by hankofficer** [pencil2d/pencil#513]
It'd be super convenient for me. I usually draw short animation. :)

Not sure if anyone is working on this, I might try to implement it myself first.

**Comment by scribblemaniac** [comment]
This is pretty much #69, except with the addition of APNGs. That issue is assigned to @chchwy, so presumably he is doing/has done some work on it. Personally I would love to see APNG support.

**Comment by walkerka** [comment]
For reference, here's a very easy to use GIF library.
[https://github.com/ginsweater/gif-h](https://github.com/ginsweater/gif-h)

**Comment by chchwy** [comment]
GIF exporting is supported on Win/Mac, but not yet on linux.
