### ISSUE TITLE
Command prompt opening when launched

### ISSUE THREAD

**Issue by sacksquid** [pencil2d/pencil#517]
I recently downloaded Pencil for my windows 10 laptop, and upon launch I am greeted with the program, and command prompt opening and saying; "Initialize win32: <nothing, for now>
WARNING: bool __thiscall Phonon::FactoryPrivate::createBackend(void) phonon backend plugin could not be loaded
"C:\Qt\4.8.5-VC2010\plugins"
"C:\Qt\4.8.5-VC2010\bin"
"C:\Qt\4.8.5-VC2010\lib"
Tool Option Widget connect to Editor
"
I am quite confused about this, and it's quite annoying,
Any Help?

**Comment by Jose-Moreno** [comment]
@sacksquid Hi, thank you for taking the time to report your experience with Pencil2D, however this has been reported in the past. Overall this was a leftover problem from when the original developer worked to develop the original Pencil, the command prompt was just useful for development. 

I'll have you know that we have a FAQ where you can try to solve or workaround the most common issues in Pencil. This particular problem is related to a missing sound library, if you'd like to fix that you can visit this link: https://pencil2d.github.io/doc/faq/#when-i-import-sounds-i-can-see-it-on-the-layer-but-i-cant-hear-anything-windows-only

However in the newest Nightly Builds (a.k.a development snapshots of the software progress), both the sound library and the command prompt have been removed so people won't have a hard time manipulating Pencil. However don't worry we do plan on having sound import in the future release of Pencil2D.

Thank you once more for your time, hope this can help you to sort certain issues that are more than documented in that version of Pencil2D.

**Comment by ocarneiro** [comment]
I guess this issue should be closed, then, since it's fixed, right? (just trying to help keep things organized so that developers can find issues to solve)

**Comment by chchwy** [comment]
OK, close issue.
