### ISSUE TITLE
I'm having trouble when downloading, it just stops

### ISSUE THREAD

**Issue by MoonDawgAnimations** [pencil2d/pencil#523]
Hello i'm wondering if you can help me. When I try to download this half way it just stops and does not continue and then after a while on the bottom left of my screen where it is downloading it says Failed - Network error I don't know if its my internet or what?

**Comment by MoonDawgAnimations** [comment]
never mind after 5 tries it downloaded

**Comment by chchwy** [comment]
I'm glad to hear that :D
