### ISSUE TITLE
Bucket tool paints to wrong layer

### ISSUE THREAD

**Issue by ocarneiro** [pencil2d/pencil#524]
When drawing on bitmap layers, the bucket tool paints the wrong layer. 

See video or gif below:
[![https://youtu.be/ddLbv48fZow](https://ibin.co/2odDHUfgxT1O.gif)](https://youtu.be/ddLbv48fZow)

**Comment by Jose-Moreno** [comment]
@ocarneiro This is not exactly a bug, it's bad design. Originally the tool was thought to mimic what happens in the animation production process so you can have the lineart independent from the color as if they were separate entities, however Pencil has never been too good to communicate these small details to the user...

I believe It would  be more effective if we as users could choose whether to fill the current layer or a different layer (below or above the current one) similar to how TVPaint does. But this is more a feature request than anything.

The way to bypass this impediment is just to move the current layer that you want to fill to the bottom of the stack, below any other bitmap layer and then use the fill tool. Then it will correctly fill a closed outline.

**Comment by CandyFace** [comment]
fixed in #687
