### ISSUE TITLE
[BUG] Selected drawing not rotating!

### ISSUE THREAD

**Issue by nicholasopuni31** [pencil2d/pencil#526]
In my drawing selection, the feature, selection rotation, is not found in this software. When I was doing my animation, I was thinking about rotating the selected drawing, but it's not here. The selection rotation feature should be from Flip-a-Clip to Pencil2D.

**Comment by Jose-Moreno** [comment]
Go to View > Rotate Clockwise & Rotate Anti-Clockwise, shortcut is R & Z

**Comment by Jose-Moreno** [comment]
@nicholasopuni31 If you want to rotate the selection, you have to use a newer version of Pencil, download a Nightly Build here: https://pencil2d.github.io/download/

Once you have one of the newer versions do the following:
1) Create a marquee selection around the drawing (Marquee: V)
2) Then pick the black arrow (Move Tool: Q) 
3) Inside the marquee, press CTRL + Click and drag left or right inside the selection. 

Note: If you click anywhere else but inside the selection you will undo the marquee.

Cheers.

p.s. Before you report a bug please try to test it out in the newer versions, which are less stable but often times superior to the download version posted in the website.

**Comment by CandyFace** [comment]
I'm closing this. 

If you still experience this problem in the newest nightly build, then please create a new issue, stating as much relevant information as possible.
