### ISSUE TITLE
[temporary solved] few bugs here [u need to adjust pencil2d]

### ISSUE THREAD

**Issue by P0RC0DI0** [pencil2d/pencil#534]
Im running ubuntu gnome 16.04. ive installed pencil2d 0.5.4 beta version.
what ive found really bad are 2 things:
- when i click on exit button the program quits without even opening the saving project window.
- there is no way to save a project as a movie
  the second issue is what makes me angry because it is supposed to be a program for making movie out of drawing, but projects cannot be saved as movies.
  a lot of programs asks wether to save or not the project/file. why p2d is not doing it?
  im very sad

**Comment by P0RC0DI0** [comment]
I'm sorry jose. I just wrote what i wrote in furiosity.
I understand that p2d is stil a beta. I m sorry.
I really thank you for your answer.

**Comment by CandyFace** [comment]
I'm closing this as the issue was targeted towards 0.5.4. 
Both issues should have been resolved. If the problem persists, please create a new issue, stating as much relevant information as possible.
