### ISSUE TITLE
[SOLVED]request for developers

### ISSUE THREAD

**Issue by P0RC0DI0** [pencil2d/pencil#537]
Hello,
I noticed that in nightly builds there is no way to have a really helpfull feature as in the beta. I'm talking about the shadow of the previous frame. In beta 0.5 the shadow allow to draw more naturally. With the nightly build, on the other hand, there isn't this feature, so the drawing of something in motion is more difficult.
I dont know if you understood what i wrote.
Thanks for the help.
Pencil2d is a very helpful program for people who love handmade animation instead of flash animation.
Thanks again

**Comment by Jose-Moreno** [comment]
@P0RC0DI0 Hello! Is this what you mean?

![Onion Skin](http://imgur.com/a/rnEAt)

You have to activate the buttons on the Tool Panel, the ones on the left activate the previous / next onion skin feature. The ones on the right allows the keyframes to be tinted.

There is one last feature which is the little diamond above the timeline. It was created to allow onion skin of separated keyframes when they are not close to each other like in this example.

If this isn't what you mean, would you mind to show us an example of what you want to do, and in which software we can find a similar feature? Thanks! :smiley:
