### ISSUE TITLE
Change the website layout

### ISSUE THREAD

**Issue by gordielachance** [pencil2d/pencil#542]
It's time that we think to upgrade the design layout, as Jose-Moreno said.
I already worked on it a few months ago, I'll post screen captures here.
But anyway, if you have ideas (structure, design, Wordpress themes references, ...) post it here.

**Comment by Jose-Moreno** [comment]
@gordielachance Thanks man!

I recall oinkystudio suggested some months back this website: http://www.zeptolab.com/

There was also another thread in the forum were I recall we all discussed this but I can't find it. You even showed us some hints of how the layout was looking, and it was really good too!.

Let us know if you require assistance with anything. And don't forget to post the link so we can donate to you for maintaining the website :smile: .

**Comment by chchwy** [comment]
Since we'are moving to a new website, I'm closing this :)
