### ISSUE TITLE
[BUG] Imported sounds are deleted from layer when re-opening a file with PCL extension.

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#546]
### --Issue Summary--

Sound(s) imported to a Pencil file get removed from file when saved with PCL extension. This does not happen with PCLX since the sound is embedded instead.
### --Actual Results

I imported one sound file to the sound layer. saved as PCL and when I reopened the file, the sound layer was empty and the folder didn't contain any sounds.
### --Expected Results--

The PCL file should properly keep track and maintain the reference link to the sound file.
### --Steps to reproduce--
1. Create a new file
2. Create a sound layer
3. Import any sound file with wav or mp3 extension.
4. Save the file as PCL
5. Re-open the PCL file
6. Notice the sound is gone, yet the sound layer is still there.
### --System Information--
- Pencil2D Version:
  Nightly Build Oct 10 2016
- Operating System:
  Windows 7 Ultimate 64bits
- RAM Size:
  4 GB
- CPU:
  AMD Phenom II x4 965 BE

**Comment by Kaikogf** [comment]
@Jose-Moreno 
I have tested this Issue with a PCL file, and Pencil2D crash and close after a message window appear:
This application has requested the Runtime to terminate it in an unusual way

**Comment by Kaikogf** [comment]
Not a single Issue from the last build 31August2017

**Comment by chchwy** [comment]
I can replicate it with 31 Oct version, i'm on it.

**Comment by chchwy** [comment]
Fixed in 1 Nov 2017 version
