### ISSUE TITLE
[BUG] Layer transparency while camera/sound layer is selected

### ISSUE THREAD

**Issue by scribblemaniac** [pencil2d/pencil#552]
### --Issue Summary--

Upon selecting the camera or sound layer, all other layers have a slight transparency, but this is not desirable behavior.
### --Actual Results

When the camera layer or a sound layer is active, all layers get a slight transparency applied to them.
### --Expected Results--

The expected behavior when the camera or sound layer is selected is no transparency or filtering of any kind within the render area. It should display _exactly_ what the camera would render (esp. for the camera layer). This transparency is normally applied to all other layers so you can focus on the strokes in the selected layer, which makes sense for bitmap and vector layers but not for sound or camera layers. When the user selects the camera they are conveying that they want to focus on what the camera would render, which is all of the layers not none of the layers.
### --Video or Image Reference--

|  | Current Behavior | Expected Behavior |
| --- | --- | --- |
| **Viewport<br>(Camera/<br>sound<br>layer<br>selected)** | ![viewport screenshot](https://cloud.githubusercontent.com/assets/3461051/19427197/b2952fd0-93ff-11e6-8406-cf75be10e9db.png)Red value: #FF3936 | ![rendered result](https://cloud.githubusercontent.com/assets/3461051/19427218/cc1df78e-93ff-11e6-974f-e90feaaef058.png)Red value: #FF0000 |
| **Render** | ![rendered result](https://cloud.githubusercontent.com/assets/3461051/19427218/cc1df78e-93ff-11e6-974f-e90feaaef058.png)Red value: #FF0000 | ![rendered result](https://cloud.githubusercontent.com/assets/3461051/19427218/cc1df78e-93ff-11e6-974f-e90feaaef058.png)Red value: #FF0000 |
### --Steps to reproduce--
1. Open a new project
2. Draw or import something that is not white onto the bitmap or vector layer
3. Select the camera layer
### --System Information--
- Pencil2D Version:
  Nightly Build October 11 2016
- Operating System:
  macOS Sierra

**Comment by Jose-Moreno** [comment]
@scribblemaniac Ah. I somehow knew this was going to be brought up after re-reading my own comments on the other issue. 

This is not a bug. It's the relative transparency system in effect. I talk about it here: 

https://www.youtube.com/watch?v=GJFW9hzny_M

To make it render "fully opaque" you just have to press the top timeline circle and make it tint black, instead of grey.

I would totally agree that this is not an obvious feature. At all. But it is a working system and in the near future we would need to mix this with individual layer opacity sliders to get the most out of simulating transparency while drawing for animation.

**Comment by scribblemaniac** [comment]
Yeah your absolutely right. Hopefully the timeline rewrite will make some of this a bit more obvious.

**Comment by scribblemaniac** [comment]
Just watched your video and it changed my mind. The very first thing you do is go to a camera layer and it shows 'how it would look if it was rendered'. I don't see why this feature was removed, it seems quite intuitive to me.

**Comment by Jose-Moreno** [comment]
@scribblemaniac Now that you mention it, I can see now what you mean. Just testing it though I noticed something. When you click on the first bitmap layer that comes with the file, it exhibits the same behaviour as if you clicked the camera before. Making other layers fully opaque "as if rendered". Sigh, I think when they rewrote the camera layer rendering order they erroneously changed the layer index properties.

I was going to make a request later on about changing this to a relative thing, but after investigating the old PCL files, it seems Pencil has an inner system where each layer gets an absolute numbered index. So no matter what you do it's always the same layer index for each individual layer, and if you delete a layer it will just continue counting. So my really vague guess is that the first bitmap layer has the index that was associated with the "make fully opaque when clicking" function. I have no clue about the code involved tho.

You can try it too: open a new file, draw something on the first bitmap layer, then create a new bitmap layer, and draw anything else. Then click on the new layer, and the first bitmap layer back and forth and also on the camera layer. Can you see what I mean?

If you want to check the index I'm talking about, save the file with PCL extension, which is a glorified XML file, and look at the properties. Anyway I'm out, it's past bedtime for me and I gotta work tomorrow. Talk to all of you soon!

**Comment by CandyFace** [comment]
Am I correct when I say that the issue that persists, is that when you select a camera layer, all layers are rendered translucent instead of fully opaque? 

If so, then an upcoming PR should fix that ;)
![opacity](https://cloud.githubusercontent.com/assets/1045397/25532274/1f7aa452-2c2d-11e7-8e42-a73a16829dbd.gif)

**Comment by scribblemaniac** [comment]
Closing, this issue was fixed with #660.
