### ISSUE TITLE
[Request] Use Github "release tag" feature to communicate new major (stable) and minor (Nightly build) versions

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#560]
Hey, I've been thinking ever since we have talked about making the Github repo a bit more dev centered, I think we should start using the release tags to version the nightly builds and the upcoming stable release(s). 

https://github.com/pencil2d/pencil/releases
https://git-scm.com/book/en/v2/Git-Basics-Tagging

@chchwy Matt was using a forum thread to upload links to the Nightly Builds along the release notes, however since we have no idea what will happen with the forum, It would make more sense and make the Nightly Build access with release notes more open to the community. 

Also there are people who sometimes can't access the google drive link, so this would make an excellent "standard" way to share progress with the community. I've seen good use of the release tag in OpenToonz  and Superpowers (game engine) repo in case you want to have a look.

**Comment by chchwy** [comment]
Good suggestion, I will do it soon.

**Comment by chchwy** [comment]
Done. Going to close this.
