### ISSUE TITLE
[Request] Restore camera layer keyframe interpolation or 'tweening'

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#567]
**Camera Layer Keyframe Interpolation (tweening)**
I never quite understood why this was removed. I think @feeef mentioned that it was necessary to allow his solution for the persistent camera layer to always be seen on the canvas, but I'm not sure.
A few other users said it was a "bad" feature, just because they never used it properly (and now they're not using pencil2D anymore lol) so I have to strongly suggest it to be restored. 

I mean has anyone tried to translate multiple elements to "fake" a camera pan in pencil? It's a pain in the arse. I get that people were unaware of the fact that using the pan tool and the zoom would inadvertently put keyframes on the camera layer and since they used the camera layer to work before the persistent frame being implemented, when they ended up exporting their animation it would destroy the framing they thought they had. But this is a really powerful and existing feature in any animation software I know of.

In the past we could animate pans (translation) and zooms (scale) via interpolation, I would also suggest that could also allow for a camera roll (rotation) feature to allow animators to animate things like "screen shakes" or to allow use of camera tricks like "the dutch angle" which in film-making is basically a tilted angle to create psychological unrest. Without having to change the whole artwork in multiple layers.

What you guys think?

**Comment by doryfor** [comment]
hi jose, hi mr developers.
i have just downloaded the new nightly build, and i have no idea what happened to the camera layers. at first, i thought it was a bug. when i try moving the bacgrnd around (with the camera staying still) like you used to be able to, everything moves around (so the camera layer does not move relative to the actual bg, just everything swings around) is that actually an intended new feature? anyway, i agree that the camera motion tweening was great. it would be a shame if it was removed. i think the persistent camera isnt a bad thing, but doesnt add much anyway. 
anyway, keep up the good work!

**Comment by Jose-Moreno** [comment]
@doryfor Actually the persistent "frame" was very much requested because people couldn't deal with having a lot of space to draw. However a by-product of that was that the keyframe interpolation for that layer had to be removed. Right now you can think of it as a "render view area" and whatever is seen through it is what will be exported in your final animation.

Pan and zoom are now independent of the camera, similar to other software, so you are now effectively panning and zooming the canvas, and not the camera. Well have to wait and see how to bring back that feature because to be honest It really needed in my eyes as well.

As an extra, If you want to turn off the camera just left click on the small dot near the layer name. :smile:

**Comment by chchwy** [comment]
I believe no one remove the camera interpolation on purpose, I have a look at this issue.

**Comment by chchwy** [comment]
Done. I'm going to close this.
