### ISSUE TITLE
Pencil2d Conflict with Pencil Prototyping Tool

### ISSUE THREAD

**Issue by merclabs** [pencil2d/pencil#580]
### --Issue Summary--
Installed Pencil (Prototyping Software: http://pencil.evolus.vn/ ) on Fedora 25, with standard command (dnf install pencil), later tried to install Pencil2d after downloading RPM, got error message of conflict with pencil.desktop icon in Pencil package installed pencil.desktop. Had to pick which one I wanted to use, not use other. 
Fedora 25. 

### --Actual Results
RPM would not install both packages... shows transaction conflict. Request you add "2d" to the name of your desktop icons and Mime Type. 

ex: pencil2d.desktop instead of pencil.desktop which causes the conflict. 

### --Expected Results--
Install both packages with no errors.

### --Steps to reproduce--
Try installing pencil2d-0.5.4-20130728.1.x86_64.rpm and pencil-2.0.5-1.fc19.noarch.rpm from http://pencil.evolus.vn/

### --System Information--
+ Pencil2D Version: 0.5.4

+ Operating System:
Fedora 25

+ RAM Size:
8GB
+ CPU:

**Comment by J5lx** [comment]
FWIW, the suggested naming scheme is [currently already used in the Arch Linux package of Pencil](https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=pencil2d-git&id=cc034b0c4aa61ff666cce34b5b7788a776f0f123) (in AUR). Before they did it that way Pencil 2D and Evolus’s Pencil conflicted on Arch Linux as well.

**Comment by mapreri** [comment]
FWIW, also [in the Debian package](https://packages.debian.org/sid/amd64/pencil2d/filelist) ([the renames](https://anonscm.debian.org/git/collab-maint/pencil2d.git/tree/debian/pencil2d.install)).
Reason was just to be clearer, even if we had no conficts (but there were in ubuntu, there was a package for the original pencil)

**Comment by LukeVideo** [comment]
The other way around it fails to. I tried to install pencil after pencil2D and it failed because of the conflict.
```
whereis pencil2d
pencil2d: /usr/bin/pencil2d
```

and

```
sudo dnf install pencil
Last metadata expiration check: 2:17:48 ago on Wed Mar 29 12:20:16 2017.
Dependencies resolved.
================================================================================
 Package           Arch           Version                 Repository       Size
================================================================================
Installing:
 pencil            noarch         2.0.18-1.fc25           fedora          4.4 M
 xulrunner         x86_64         44.0-9.fc25             updates          32 M

Transaction Summary
================================================================================
Install  2 Packages

Total download size: 36 M
Installed size: 91 M
Is this ok [y/N]: y
Downloading Packages:
(1/2): pencil-2.0.18-1.fc25.noarch.rpm          1.4 MB/s | 4.4 MB     00:03    
(2/2): xulrunner-44.0-9.fc25.x86_64.rpm         1.7 MB/s |  32 MB     00:18    
--------------------------------------------------------------------------------
Total                                           1.7 MB/s |  36 MB     00:20     
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction check error:
  file /usr/share/applications/pencil.desktop from install of pencil-2.0.18-1.fc25.noarch conflicts with file from package pencil2d-0.5.3-20130717.1.x86_64

Error Summary
-------------
```

**Comment by chchwy** [comment]
I'm closing this since we are not providing rpm package.
And the new pencil2d.desktop has updated the app name, it should be no longer an issue.
