### ISSUE TITLE
Saving as movie

### ISSUE THREAD

**Issue by newtopencil** [pencil2d/pencil#583]
### --System Information--
+ Pencil2D Version:

+ Operating System:

+ RAM Size:

+ CPU:

+ Graphics Tablet:

---

**Comment by Jose-Moreno** [comment]
@newtopencil Hi please download the latest development build which has movie export on the following link: https://drive.google.com/drive/folders/0BxdcdOiOmg-CcWhLazdKR1oydHM#list

In the future please search the repository for similar bugs before submitting already existing cases. It is really hard to keep track of every issue and we're trying to minimize the amount of duplicate reports. Thanks!

**Comment by newtopencil** [comment]
Sorry I am rubbish at this but thank you for taking the time to reply, 
and yes it now works fine

newtopencil
