### ISSUE TITLE
[Website Request] Allow mod muting or temporal ban due to spammer increase.

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#585]
@gordielachance Hey man, Just wanted to let you know there's been an unpleasant increase in "profile spammers" They somehow manage to bypass the site security, change their profile pictures and then go on to post "update" comments on other's profiles. here's a few examples from this week: 

http://www.pencil2d.org/members/debbie120/
http://www.pencil2d.org/members/jessica0004/

There are also others which don't have profile pictures but post spam on their updates:

http://www.pencil2d.org/members/belindadowns/
http://www.pencil2d.org/members/malamani493/
http://www.pencil2d.org/members/samuelgreg82/
http://www.pencil2d.org/members/stephen147geo/
http://www.pencil2d.org/members/frankcurtis04/

Please make it possible to flag these "users" again, or at least allow me to mute them. It is getting really bad these days, like the site activity feed only shows spammers nowadays.

**Comment by gordielachance** [comment]
Hi !
Merry Christmas !
Thanks for the feedback.
I marked them as spammers.
Of course we all know there will be other ones, I don't know why now.
Let's see what's happening and i'll try to find a solution.

Thanks !

2016-12-24 15:51 GMT+01:00 Morr <notifications@github.com>:

**Comment by Jose-Moreno** [comment]
@gordielachance Happy New Year as well now! I wanted to ask you if there's a way to at least mute these spammers. Today We got a new one which posted a lot of pirated series on different threads. I already flagged those as spam but they remain on the site-wide activity, is there a way to clear those with mod powers?

Here's the offender:
http://www.pencil2d.org/members/mangoled/

Anyway, hope you and your family had a great time, let's hope this year is better for everyone!

**Comment by gordielachance** [comment]
Ok, I'm not sure...
But can you access this URL ?
http://www.pencil2d.org/members/mangoled/settings/capabilities/
If yes, you can (I just did it) mark that user as a spammer.

Thanks,

G

2017-01-10 0:47 GMT+01:00 Morr <notifications@github.com>:

**Comment by Jose-Moreno** [comment]
@gordielachance No it seems I can't access that URL hehe. It's ok, i'll just keep flagging their posts as spam and post their profile here.

A new one registered today: http://www.pencil2d.org/members/tyvonzack/

**Comment by Jose-Moreno** [comment]
@gordielachance Hey, it also seems the page was hacked

**Comment by scribblemaniac** [comment]
@gordielachance The hack was probably done with the [Unauthenticated Privilege Escalation Vulnerability](https://make.wordpress.org/core/2017/02/01/disclosure-of-additional-security-fix-in-wordpress-4-7-2/) which is in the version of WordPress you are currently using. Please upgrade immediately and check for users that have privileges they shouldn't.

**Comment by gordielachance** [comment]
This is so boring.
Anyway, thanks, I updated WP, the plugins, checked the users privileges (no weird stuff there) and i'm currently running an anti-malware tool.
Also did restore the two hacked posts (using archive.org).
Thanks !

**Comment by chchwy** [comment]
Since we'are moving to a new website. I'm closing this. :)
