### ISSUE TITLE
incomplete dependency list for the rpm package

### ISSUE THREAD

**Issue by Maninbeartrap** [pencil2d/pencil#586]
### --Issue Summary--

i tried to install pencil 2d through the rpm packages and it didn't install all the needed librarys. The fallowing library were missing
- libpng12 -
### --Video or Image Reference--

![selection_001](https://cloud.githubusercontent.com/assets/24769306/21473917/855972b4-cadd-11e6-9241-7a3672c32f3f.png)

### --Steps to reproduce--

a fedora installation that does does not have libpng12 installed but has the official pencil 2d rpms installed 
### --System Information--
+ Pencil2D Version:

0.5.4
+ Operating System:

fedora 25
+ RAM Size:

+ CPU:

+ Graphics Tablet:

---

**Comment by Jose-Moreno** [comment]
@Maninbeartrap Sorry it took me long to answer. I'm not a dev, but meanwhile this is solved, there's a guide to build from source that scribblemaniac wrote here:

https://github.com/pencil2d/pencil/blob/master/docs/build_linux.md

Hope it helps meanwhile. Happy Holidays!

**Comment by chchwy** [comment]
At the moment, we're not officially providing an rpm package. 
But you can find an AppImage here:
http://pencil2d.github.io/download/

I'm closing this.
