### ISSUE TITLE
[BUG] Pencil tool pressure sensitivity issue, stroke not drawn with minimal stylus pressure.

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#595]
### --Issue Summary--

When using Pencil tool, you can only achieve faint strokes after putting about 45~50% pressure on your stylus.

### --Actual Results

Quite literally when you try to draw with a stylus pressure under 45~50% the Pencil tool will not draw a single pixel. It only begins to count after pushing really hard.

### --Expected Results--

Pressure sensitivity opacity should work from 0 to 100 pressure similar to how the Pen tool works with size only. It should draw a stroke with the faintest of pressure put on the stylus.

### --Video or Image Reference--

![image](https://cloud.githubusercontent.com/assets/4912907/22513819/59accf02-e86b-11e6-91c0-976d53d67539.png)

### --Steps to reproduce--

1. Select Pen tool
2. Check Pressure checkbox []
3. Try to draw a faint line.
4. Press harder until you see a line.

### --System Information--
+ Pencil2D Version:

Pencil2D Nightly Build Nov 2 2016
+ Operating System:

Windows 7 Ultimate
+ RAM Size:

4GB
+ CPU:

+ Graphics Tablet:

Wacom Intuos Pro 5 PTH-450
Driver: 6.3.15-3

---

**Comment by CandyFace** [comment]
This was fixed with #599, so i'm closing this issue.
