### ISSUE TITLE
Importing the same sound twice causes Pencil to crash

### ISSUE THREAD

**Issue by martinvanzijl** [pencil2d/pencil#604]
### --Issue Summary--
Importing the same sound twice causes Pencil to crash.

### --Expected Results--
You should be able to import the same sound twice.

### --Steps to reproduce--

1. Create a new file.
2. Create a new sound layer.
3. Import a (short) sound.
4. Import the same sound again. Pencil will crash.
	
### --System Information--
+ Pencil2D Version:
Nightly Build Feb 13 2017

+ Operating System:
Windows 7 64-bit

+ RAM Size:
4 GB

+ CPU:
Intel i5-2410M @ 2.30 GHz

+ Graphics Tablet:
Wacom Intuos 4

### --Code Snippets--
The second time I imported the sound, the remove() call below does not actually remove the file in the data folder (AppData\Local\Temp\Pencil2D\Default.Y2xD\data):

```C++
QString Object::copyFileToDataFolder( QString strFilePath )
{
...
    if ( QFile::exists( destFile ) )
    {
        QFile::remove( destFile );
    }
```

That means the function returns an empty string. That causes the Q_ASSERT call below to fail, leading to the crash:

```C++
Status SoundManager::loadSound( Layer* soundLayer, int frameNumber, QString strSoundFile )
{
...
    QString strCopyFile = soundLayer->object()->copyFileToDataFolder( strSoundFile );
    Q_ASSERT( !strCopyFile.isEmpty() );
```

**Comment by CandyFace** [comment]
I can't replicate this on OS X. I tested using a wav file, imported the same track multiple times without problem. What is the format of the file you are importing?

**Comment by Kaikogf** [comment]
I tested this Issue with wav and mp3 files, creating even a third sound layer and everting was working fine, no bug

Maybe this post can be closed now?

**Comment by chchwy** [comment]
I believe it has been fixed. I'm closing this.
