### ISSUE TITLE
Strings to be translated (localized) or not

### ISSUE THREAD

**Issue by ptrg** [pencil2d/pencil#605]
I did some review of the source codes of Pencil2D while I was hunting for the strings still displayed in English in a localized environment.
I found some issues that need to be fixed as below (in my opinion):
- Some debug messages are able to be localized ( _enclosed in tr()_ ) and some others not. Suggested fix: debug messages not to be localized, because in a bug report the developers will not understand the meaning of localized messages.
- Some backup() related messages seems to be command identifiers (list of command to undo/redo) and they are able to be localized. Suggested fix: backup related command identifiers not to be translated. Examples: "DeleteImg", "ImportImg", "Paste" (~~not the item caption of edit menu, but a reference for the action itself~~ these strings appear in the menu and are extending the caption of the Undo item)
- There are some other messages that may be displayed on the GUI in some special conditions and cannot be localized at the moment. Suggested fix: enclose in tr() to allow localization of them.

I will make the above changes (and create a pull request) if you agree with my suggestions.

**Comment by CandyFace** [comment]
Good work, i'm closing this.
