### ISSUE TITLE
Selection rectangle not shown when dragging up or left from original point

### ISSUE THREAD

**Issue by martinvanzijl** [pencil2d/pencil#609]
### --Issue Summary--
Using the select tool, if drag up or left from the original point where I clicked, the selection rectangle is not shown. It works fine when I drag down and right.

### --Actual Results
The selection rectangle is only shown when dragging down and right.

### --Expected Results--
The selection rectangle should be shown no matter which direction you drag in.

### --Video or Image Reference--
Video (zipped):
[Selection_Rectangle_Bug.zip](https://github.com/pencil2d/pencil/files/697173/Selection_Rectangle_Bug.zip)

NOTE: The yellow and red circles around the mouse cursor are added by my screen capture software - just to show where I am clicking/releasing the mouse.

### --Steps to reproduce--
1. Open new animation.
2. Choose the select tool.
3. Click and drag up and left on the canvas. The selection rectangle will not be shown.

### --System Information--
+ Pencil2D Version:
Nightly Build Dec 16 2016
(Still occurs in Feb 13 Nightly Build)

+ Operating System:
Windows 7 64-bit

+ RAM Size:
4 GB

+ CPU:
Intel i5-2410M @ 2.30 GHz

+ Graphics Tablet:
N/A - Was using the mouse.

### --Code Snippets--
Looks like the code below needs changing. I've been developing a fix, and I'm hoping to make a pull request soon.

```C++
        case ScribbleArea::NONE:
            mScribbleArea->mySelection.setBottomRight( getCurrentPoint() );
            break;
```

**Comment by CandyFace** [comment]
Tested, it works great. Good job :)

**Comment by CandyFace** [comment]
As mentioned, tested and works. Closing.
