### ISSUE TITLE
Exporting images with no camera layer crashes Pencil (.PCL files only)

### ISSUE THREAD

**Issue by martinvanzijl** [pencil2d/pencil#612]
### --Issue Summary--
When I open a .PCL (old) animation, if I use _File --> Export --> Image..._ Pencil crashes if there is no camera layer. 

This is only applicable for animations made with older versions of Pencil. With the new version of Pencil, you can't delete the last camera layer.

(NOTE: I'm working on a fix. Will be useful for people like me who still have a lot of .PCL animations.)

### --Actual Results
Pencil crashes with a segmentation fault warning.

### --Expected Results--
Pencil should export the image using a default size.

### --Video or Image Reference--
Video and sample file (zipped):
[Export_Image_Bug_Video_And_Files.zip](https://github.com/pencil2d/pencil/files/792163/Export_Image_Bug_Video_And_Files.zip)

### --Steps to reproduce--
1. Create a new animation using an old version of Pencil. (e.g. 0.5.4b).
2. Delete the camera layer.
3. Save the animation (as a .PCL file).
4. Close the old version of Pencil.
5. Open the animation with the new version of Pencil.
6. Choose "File --> Export --> Image...".
7. The program crashes.

### --System Information--
+ Pencil2D Version:
Nightly Build Feb 16 2017

+ Operating System:
Windows 7 64-bit

+ RAM Size:
4 GB

+ CPU:
Intel i5-2410M @ 2.30 GHz

+ Graphics Tablet:
N/A - Was using the mouse.

The debugger shows the error occurred here.

```C++
QRect LayerCamera::getViewRect()
{
    return viewRect;
}
```

Called from here:

```C++
    int cameraLayerId = mEditor->layers()->getLastCameraLayer();

    LayerCamera *cameraLayer = dynamic_cast< LayerCamera* >(mEditor->object()->getLayer(cameraLayerId));


    // Options
    auto dialog =  new ExportImageSeqDialog( this );
    OnScopeExit( dialog->deleteLater() );

    dialog->setExportSize( cameraLayer->getViewRect().size() );
```

I suspect cameraLayer is NULL. I'm working on a fix and hope to make a pull request soon.

**Comment by CandyFace** [comment]
Can someone confirm that it's been fixed, so we can close this issue :)

**Comment by Jose-Moreno** [comment]
@martinvanzijl @CandyFace I just updated with latest repo source and I tested this succesfully. The image was exported with the original size form the deleted camera (640 x 480) and didn't crash. 

I tested this with both bitmap and vector layers. Funny thing is that when I made an additional stroke outside of the "perceived" camera bounding box, the exported image became larger, but when I deleted the vector stroke, and re-exported the image It continued to have the last "recorded" area size from the last exported image bounding box.

Anyway, this is good to prevent issues from original active users of the old version. Good work.

p.s. I'm noticing the pen strokes are a bit less "smooth" and the pressure influence is more direct than in November 2 2016 Nightly Build, anyone know what happened in between these two nightly builds?

**Comment by CandyFace** [comment]
@Jose-Moreno  I removed an operation that caused the mouse position to be smoothed in one of my previous PR, that's probably why it's more direct now. I'm working on getting it implemented again, with new types of  interpolation and other things though. It will be possible to select interpolation strength now.

**Comment by CandyFace** [comment]
Closing this as it's been fixed.
