### ISSUE TITLE
[Request] Allow to import image sequences with adjustable frame spacing

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#620]
### --Issue Summary--

Right now importing an image sequence of any length **will import each image for every 2 frames**. This means it is imported on two's. This is useful on some cases when bringing frames drawn by hand, however the user should have the ability to choose if they want to import it on one's, two's, three's or a custom frame spacing between images.

### --Expected Results--

There should be a window dialog that allows the user to specify the amount of separation between each image. We could use a window dialog similar to the one used when exporting, I think those are made with QT widgets.

Edit: The caption could say something like "Import an image every **[X]** frames"

![image](https://cloud.githubusercontent.com/assets/4912907/23493645/4ce7acac-fedb-11e6-9d2b-76ecc6f8be9a.png)

### --Video or Image Reference--

![image](https://cloud.githubusercontent.com/assets/4912907/23493257/6cd934b6-fed8-11e6-9948-1f2e9d9ba4cb.png)

### --Steps to reproduce--

1) Go to File > Import > Image Sequence.
2) Choose your images
3) You'll get an even amount of frames similar to the image reference above.

### --System Information--
+ Pencil2D Version:

Pencil2D Nightly Build November 2 2016

+ Operating System:

Windows 7

**Comment by CandyFace** [comment]
Sounds like a good request, I'm going to work on this :)

**Comment by Jose-Moreno** [comment]
@CandyFace Thanks a lot! Other animators had asked me for this but I was trying to put up a decent request before submitting.

**Comment by CandyFace** [comment]
![test](https://cloud.githubusercontent.com/assets/1045397/23554591/139cbb58-0026-11e7-922a-6952329c320d.gif)

Alright should be done now. PR to be comitted soon :)

**Comment by Jose-Moreno** [comment]
@CandyFace Awesome! also that hand icon looks quite great!

**Comment by CandyFace** [comment]
I'm closing this since it has been implemented.
