### ISSUE TITLE
Draw lag when using wacom tablet on mac

### ISSUE THREAD

**Issue by MFRS** [pencil2d/pencil#640]
### --System Information--
+ Pencil2D Version:
0.5.4 dev

+ Operating System:

+ RAM Size:

+ CPU:

+ Graphics Tablet:

---

**Comment by CandyFace** [comment]
Hi MFRS

You've written 0.5.4 dev, would you mind clarifying whether that's the latest nightly build from google drive? https://drive.google.com/drive/u/0/folders/0BxdcdOiOmg-CeVpTY294cXdLZ2c.

How much lag are you experiencing? leaving no information makes it rather difficult to figure out what you mean

**Comment by MFRS** [comment]
Ok I apologize. Its the latest version I download that shows in the pencil2d main page that is available for mac.

About a 1 second lag when drawing. Any other questions?

**Comment by Jose-Moreno** [comment]
@MFRS Thanks for taking the time to answer :smiley:  Actually, would you mind testing this version? The following is a direct link to download one of the latest MAC versions, could you test if it's still happening on that particular version or not? If you have the time of course. Thanks a lot!

https://drive.google.com/open?id=0BxdcdOiOmg-CZUctazFtbmk5MGM

**Comment by MFRS** [comment]
Awesome, it works in this one. Thanks!
