### ISSUE TITLE
Version numbering and more relevant dev info in about

### ISSUE THREAD

**Issue by CandyFace** [pencil2d/pencil#642]
### --Issue Summary--
With the current setup, a lot of manual information has to be added, to make an issue useful to us developers. This often leads to a problem, because only few takes the time to do that. For our own sakes, we could automate some of this process by adding the info to the about dialog, making it possible to copy/paste.

This should be in the about dialog: 
Pencil2D version: 0.5.5.x, 
git commit: "52b31cafcd9038b14e5eabd489e3be29c3aa2e8a"
commit: date and time

I'm already working on refactoring the about button, changing it from a html QMessageBox into a QDialog. I'm not sure how to incorporate git hash or anything yet but i've researched a bit:
http://stackoverflow.com/questions/1704907/how-can-i-get-my-c-code-to-automatically-print-out-its-git-version-hash.

### --Video or Image Reference--
For reference, here's a setup, which is used in a game development program i'm using. 
![screen shot 2017-04-13 at 09 47 53](https://cloud.githubusercontent.com/assets/1045397/24995218/4e198220-202e-11e7-9459-89024f10dc26.png)

**Comment by scribblemaniac** [comment]
This would definitely be useful 👍

**Comment by mapreri** [comment]
> and time when the build was compiled.

Please **no**.

The time the build was done carries _no information_ whatsoever, and it just makes the build unreproducible  out of the box.

The rest of the information you are suggesting is cool, instead, and way more useful than the build date.

**Comment by CandyFace** [comment]
Hmm it specifies exactly how old the build is, without looking up the git hash on the website, I think that's somewhat useful. However It's true that we can't use the info for better debugging.

**Comment by mapreri** [comment]
Probably the build system can detect if the build is being done from a git repository, and if so define COMMIT_HASH and COMMIT_DATE (or whatever) and embed those?  That could probably be more useful than a clueless build date.

**Comment by CandyFace** [comment]
Ah yes, my mistake, I meant commit date when I said build time and date.

**Comment by CandyFace** [comment]
PR up #644
