### ISSUE TITLE
Clicking the remove frame button when there is no frame, crashes the application

### ISSUE THREAD

**Issue by CandyFace** [pencil2d/pencil#643]
### --Issue Summary--
if you move the red bar to an empty space on the timeline and hit the remove button, the program will crash

### --Actual Results
Program crashes.

### --Expected Results--
Nothing should happen, because there is no frame to be deleted.

### --Steps to reproduce--

1. Move red bar to an empty space
2. Press remove keyframe

### --System Information--

Pencil2D Version:
Pencil2D nightly build April 11 2016.

Operating System:
Mac OS X 10.11.6

RAM Size:
8 GB 1600 MHz DDR3

CPU:
Processor: 1.7 GHz Intel Core i7

Graphics Tablet:
Intel HD 5000

---

The issue happens around here.

```C++
void Editor::removeKey()
{
	Layer* layer = layers()->currentLayer();
    if ( layer != NULL)
    {
        layer->removeKeyFrame( currentFrame() );
		
        //scrubBackward();
        mScribbleArea->updateCurrentFrame();
	}
    Q_EMIT layers()->currentLayerChanged( layers()->currentLayerIndex() ); // trigger timeline repaint.
}
```

**Comment by Jose-Moreno** [comment]
@CandyFace I Can't reproduce this in Windows 7. When I press the remove keyframe button the header goes back to the previous frame unharmed,

Could this issue be MAC OS specific? Can anyone on Linux confirm this problem?

**Comment by CandyFace** [comment]
Hmm weird, neither can I atm. I was able to consistently do it yesterday but now it's not happening. I'll try to provoke it a bit, if I still can't reproduce it, then I'll close it.
