### ISSUE TITLE
Move tool shouldn't be able to make selection area

### ISSUE THREAD

**Issue by CandyFace** [pencil2d/pencil#662]
### --Issue Summary--
If you select the move tool, then drag on the canvas, the tool turns into the selection tool. If try to drag the selection, the selection will disappear and nothing will happen.

### --Actual Results
The move tool turns into the selection tool.

### --Expected Results--
nothing should happen. Only the selection tool should be able to make a selection. The move tool should ideally make a selection automatically of the area which has been drawn on and move it. 

### --Video or Image Reference--
![selection](https://cloud.githubusercontent.com/assets/1045397/25541093/a66913ac-2c4d-11e7-8e54-e71c775ced6c.gif)

### --Steps to reproduce--
1. Select the move tool
2. click and drag
3. drag again

### --System Information--
+ Pencil2D Version:
commit: 41505e32bf83e9e8d6248de5112378bdb91ef2a9
date: 2017-04-26_10:10:51

**Comment by CandyFace** [comment]
I've been working on implemented my ideal solution for a while now, but i've hit a dead end... I've implemented such that when you drag anywhere on the canvas, the bitmap region will be searched through, and make a selection based on the non alpha region. My problem atm. is that the transformation is wrong and that it only works after you've dragged once (somewhat). I'm going to lay it off for now but i'm leaving the code here in case someone has an idea.

The code works as such:
it takes the size of the bitmap image at the current layer and looks through each row using scanline.
Then it set the top left and bottom right corner to whatever the first and last opaque pixel is.
Afterwards I map the rect to the coordinate system and returns the rectangle.
```c++
QRectF MoveTool::findBoundingRect(BitmapImage* bitmapImage)
{
    QImage* img = bitmapImage->image();
    int q = img->width(), e = img->height(), w = 0, h = 0;
    for (int y = 0; y < img->height(); ++y)
    {
        QRgb *row = (QRgb*)img->scanLine(y);
        bool rowFilled = false;
        for (int x = 0; x < img->width(); ++x)
        {
            if (qAlpha(row[x]))
            {
                qDebug() << qAlpha(row[x]);
                rowFilled = true;
                w = std::max(w, x);
                if (q > x)
                {
                    q = x;
                    x = w; // shortcut to only search for new right bound from here
                }
            }
        }
        if (rowFilled)
        {
            e = std::min(e, y);
            h = y;
        }
    }
    //float scale = mEditor->view()->scaling();

    // TODO: figure out the correct view transformation.
    QRectF rect = QRectF(QPointF(q,e), QPointF((w+1),(h+1)));
    rect = mEditor->view()->getView().inverted().mapRect(rect).toRect();
//    qDebug() << t2;
//    qDebug() << "mouse " << getCurrentPoint();
//    qDebug() << test;

    return QRectF(rect);
}
```

then to call the new function I have a conditional that asks if nothing is selected and is bitmap inside the moveEvent, find the bounding box and set the selection true.
```c++
        if (layer->type() == Layer::BITMAP && !mScribbleArea->somethingSelected)
        {
            bitmapImage->setSelected( true );
//            if (!chosen)
//            {
//                chosen = true;
//            }

            QRectF test = findBoundingRect(bitmapImage);

            mScribbleArea->setSelection(test, true);
        }
```

but as you can see here, there has issues...
It only works atm. if you:
* haven't zoomed.
* haven't translated the view
* haven't rotated the view
* haven't moved the selection (from the initial (0,0) position)

other issues:
sometimes it doesn't make the rect big enough, leaving 1 pixel lines around.
![selection](https://cloud.githubusercontent.com/assets/1045397/25741047/5be0497c-3189-11e7-8429-a690c33e5821.gif)

**Comment by Jose-Moreno** [comment]
@CandyFace I think this bug is already fixed thanks to some of your own commits :slightly_smiling_face:   as for the other comment with the search algorithm for non-alpha values, that would be an interesting feature on it's own, what do you think?

**Comment by CandyFace** [comment]
Indeed it would be nice if you could move the canvas by just dragging with the move tool instead of having to select something.

I believe there's a much easier way though than what i'm trying to do above... silly me :3

I'll close the issue
