### ISSUE TITLE
Import/Export file chooser field instead of dialog

### ISSUE THREAD

**Issue by J5lx** [pencil2d/pencil#673]
Currently the file dialogs for import and export are handled slightly differently depending on the type of media. Exporting images and image sequences shows an options dialog first and a file chooser second, exporting movies and importing image sequences does it in the opposite order. But instead of figuring out the One True Dialog Order it might be a good idea to just turn the file path into another option like this:

![screenshot from 2017-05-16 03-14-01](https://cloud.githubusercontent.com/assets/2063777/26085583/bcc00494-39e5-11e7-9621-0c7f09aaaf13.png)

If others are okay with this, I can come up with a proper widget and adjust the dialogs. Thoughts?

**Comment by CandyFace** [comment]
I support this, it sounds like a good solution and it makes it easier to understand what to expect when you click the export or import button.

**Comment by chchwy** [comment]
agree, would be good to have these dialogs to work in the same way.

**Comment by Jose-Moreno** [comment]
@J5lx I think it would be for the better. As long as each function (import / export) is consistent with this proposal I see no issue, this way people can expect to always define the path for a file to be imported and to be exported as such. Thanks a lot! :smile:

**Comment by J5lx** [comment]
I’ll work on it then.
