### ISSUE TITLE
Missing DLLs MSVCP120.dll and MSVCR120.dll

### ISSUE THREAD

**Issue by Qwerp-Derp** [pencil2d/pencil#676]
### --Issue Summary--
I'm trying to run Pencil2D on Windows 10, but apparently I'm missing DLLs. When I run Pencil2D, it comes up with four errors in succession - one for MSVCP120.dll, one for MSVCR120.dll, one for MSVCP120 again and one for MSVCR again.

### --Steps to reproduce--

1. Download the latest nightly build (2017-05-20) from the Google Drive
2. Run Pencil2D.exe

### --System Information--
+ Pencil2D Version: Nightly build 2017-05-20

+ Operating System: Windows 10

+ RAM Size: 4GB

+ CPU: Intel i5

+ Graphics Tablet: Gaomon 1060

**Comment by Jose-Moreno** [comment]
@Qwerp-Derp Usually this is a Windows issue, that's why if you notice the Pencil2D download file is bundled with a vcredist_x86.exe file, which is a run-time redistributable for visual studio components which many developers use. Try that out and see if it works for you.

**Comment by Qwerp-Derp** [comment]
@Jose-Moreno I fixed this issue another way, by installing Visual C++ 2013 (x64) on my laptop - turns out I don't have it installed. Also, is there a way to extend a keyframe?

**Comment by Jose-Moreno** [comment]
@Qwerp-Derp Good to hear, if you can please close this issue as it was resolved already. 

Regarding your second question, you mean Extend a frame as in extending it's duration? It should be done automatically. Basically you have to control how long your drawings are exposed by inserting other keyframes. 

For example, If you create a drawing in frame 1 and a drawing in frame 24. The first drawing will be held for every frame until frame 23.
