### ISSUE TITLE
[BUG] Pressure sensitivity checkboxes are disabled / misplaced

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#678]
### --Issue Summary--

Pressure sensitivity is working by default with graphic tablets. However attempting to disable the pressure using the appropriate checkbox doesn't have any result. This happens on every tool.

### --Actual Results

Using the pressure checkbox doesn't do anything. On Paint tool the pressure checkbox does not do anything BUT the feather checkbox is enabling and disabling the pressure.

### --Expected Results--

Pressure sensitivity checkbox should allow the user to enable or disable the pressure sensivitity to achieve different effects.

### --Steps to reproduce--

1. Open Pencil2D
2. Select a drawing tool (i.e. Pen tool)
3. Draw. Notice you have pressure enabled.
4. Press the checkbox to disable pressure.
5. Draw again. Notice you still have pressure sensitivity enabled.
6. Select Brush tool.
7. Draw. Notice you might not have pressure on.
8. Disable Pressure and Enable Feather.
9. Draw. Notice you now have pressure enabled for the Brush tool.

### --System Information--
+ Pencil2D Version:

Pencil2D Nightly Build May 20 2017

+ Operating System:

Windows 7 Ultimate

+ RAM Size:

+ CPU:

+ Graphics Tablet:

Wacom Intuos Pro 5
---

**Comment by CandyFace** [comment]
Posting this (slightly edited) comment I made on the PR^ here, as it's relevant to the issue.

Pressure doesn't do anything for brush unless feather is on. I recall it was discussed whether Brush should have size pressure or not and I believe that it concluded that pressure should only affect feather at the time.

Because of that and the fact that there's no constant control for feather blending yet, makes it feel a bit broken. 
Therefore whenever you need feather, set pressure on too, otherwise it won't work. I want to add more customisation for the tools but I don't want to make changes before we've implemented the MyPaint library as such change might become obsolete.

**Comment by ryyharris** [comment]
[2019 Review] I downloaded the Pencil2D v0.6.3 version for MacOS and the pressure sensitivity works for me. I tried to reproduce the bug using the steps above, but nothing went wrong. 
However, I fond that wen I ran the Pencil2D v0.6.3 in the virtual box ubuntu emulator, the pressure sensitivity did not work at all, whether or not the pressure checkbox was marked.

**Comment by scribblemaniac** [comment]
@ryyharris How exactly did you use virtualbox? By default it will just emulate the mouse, which of course has no pressure sensitivity. You have to add a new usb device filter for the tablet, and then install the appropriate drivers in your virtual machine for pressure to work properly on any application, including Pencil2D.

**Comment by Jose-Moreno** [comment]
I'm closing this as the offending problems mentioned in the original message are no longer present. I believe this was fixed recently by 42bf7684b8a500e9abcea4de264d66327ef9ff01 but i'm not entirely sure as this other commit c9fc9a7b9de95ee1fb239090cc3ec32c6b524347 removed the feather and AA checkboxes on the brush tool.

Thanks to @ryyharris for also filing an updated report for macOS and Ubuntu (VM), if possible could you test the latest dev build with similar conditions and comment back if you had the same problems? If you can't that's fine though, either way thanks everyone.
