### ISSUE TITLE
Changing default bahavior in 'paste' command.

### ISSUE THREAD

**Issue by aprekates** [pencil2d/pencil#680]
### --Issue Summary--
When pasting in a bitmap layer i cant move it but i must select it again.
The problem is that the layer has already changed!.

### --System Information--
+ Pencil2D Version:
0.5.4

(ps: i tried for 10 minutes to make an account and login in the forum, https://www.pencil2d.org/forums
with no success. )

**Comment by CandyFace** [comment]
Hi aprekates

What do you mean that the layer has changed? It sounds like you mean that when you import a new image, you're being moved to the next empty frame, thus you have to first select the previous keyframe again then use selection and move tool to drag your image? if that's not correct, please elaborate.

Also, would you mind telling the specific version of Pencil you're using, you can find this information from the menu: About->"About Pencil2D" 
If you are using the latest nightly build copy/paste the info from the white box here.
The info should look like this:
"commit: xxxxxxxxxxxxxxxxxxxxxxxx"
"date: 2017-xx-xx_xx:xx:x"

**Comment by aprekates** [comment]
I'm using 0.5.4(26 July 2013) and occasionaly Nigthy Build 23 2015 
The 'issue' i submit i think is a feature request . 

1.In a bitmap layer i have drawn sth. 
2.I select a part of it (or all of it) and the rectangular select line will be displayed as a border of my selection.
3. I give Edit->Copy command
4. I Edit->Paste either in the same layer in the current frame or in the same layer in the next frame
5. In either case by default i will not see the selection bound-box in order to move or resize my pasted-selection but the pasted-selection will get pasted on the same spot with not being able to move it or change it before i  'embed it' in the layer.

**Comment by CandyFace** [comment]
Ah I see, well the old 0.5.4 version is not supported anymore. Anyhow, this is still an issue which is present in the newest nightly build, so it's a fair request.

**Comment by Jose-Moreno** [comment]
@aprekates Meanwhile this gets worked upon, a workaround for this you can do is the following:

1. Select the portion you want to copy
2. Edit > Copy or Ctrl+C
3. Now use the marquee tool and create a bounding box on the place you want to paste. The marquee must be bigger than the content you want to paste (you have to gauge this visually) or else the pasted content will become distorted (the proportions don't matter as long as it's bigger)
4. Edit > Paste or Ctrl + V
5. Press Q or Select Arrow tool and move the pasted content to the place you need.

Also please use the latest Nightly Build from May 2017 for your preferred Operating System. November 2015 is full of bugs that have already been fixed, as well as version 0.5.4.

https://drive.google.com/drive/folders/0BxdcdOiOmg-CcWhLazdKR1oydHM#list

**Comment by aprekates** [comment]
Thanks . i'm aware of the workaround and it's difficult to make precision copies.

**Comment by aprekates** [comment]
Hi from greece. I've just tested Nightly 2017-09-23 on ubuntu 16.04.

The issue seems resolved.

Thanks to the programmer(s)

**Comment by chchwy** [comment]
Happy to hear that @aprekates, hope you enjoy using Pencil2D  :)
