### ISSUE TITLE
[BUG] Can't open a previously saved .PCLX file with imported data

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#682]
### --Issue Summary--

Disclaimer: I'm posting this issue in behalf of a Pencil2D forum user.
Related: We had a similar bug in the past which @chchwy fixed via this [commit](https://github.com/pencil2d/pencil/commit/20891445508a9e238f67fd3491ec8a409684f9fa)

### --Actual Results

Trying to load a .pclx file pops up an error (screenshot below) 
The file doesn't seem to have been wiped as reported in previous issues since the file size is about 48mb. I opened the .pclx file with a text editor and among the encrypted data I could spot a few mp3 and wav files on the data path, which must be the reason for the file size.

The user tells me she used Nightly Build Nov 2nd 2016 to create and save these files, however I asked her to use latest May 28th 2017 Nightly Build, and I'm also using it to test the file, however we both still can't open the file. 

### --Expected Results--

The file should open without issue, regardless of imported data.
### --Video or Image Reference--

![image](https://cloud.githubusercontent.com/assets/4912907/26709896/c47a7348-471b-11e7-8a66-0ec6156844ef.png)

**Test File** provided by the user: http://www.mediafire.com/file/6w1e9od6l0bj22c/what.pclx

**Forum Thread**: http://www.pencil2d.org/forums/topic/i-cant-open-any-saved-animations/

### --System Information--
+ Pencil2D Version:

Nightly Build Nov 2nd 2016
Nightly Build May 28th 2017

+ Operating System:

User: Windows OS (it's either 8 or 10)
Me: Windows 7 Ultimate

+ RAM Size:

User: Unknown
Me: 4GB
+ CPU:

+ Graphics Tablet:

---

**Comment by J5lx** [comment]
I couldn’t reproduce the error here on Linux and the file does seem to be fine to me. There are no sound layers so the MP3 and WAV files are not actually used, but that’s all. However I see that there are question marks in some of the sound file names and I wonder if there might be some kind of encoding problem. At some point I had those in the past with ZIP files and Linux programs seemed to cope with it better than Windows ones.

Also, for the record, pclx files are basically ZIP files, so you might be able to figure something out by extracting them (via Windows Explorer, 7-Zip etc.).

**Comment by CandyFace** [comment]
I too have tried and can't reproduce this. It seems it's an Windows related error. Perhaps as J5lx says, an encoding problem because of the filename with certain characters. 

@Jose-Moreno does it work if you extract the content, rename the audio files, zip, change to .pclx again and import?

**Comment by chchwy** [comment]
Has confirmed it happened on Windows. The main.xml doesn't be unzipped properly, so pencil2d couldn't open the xml file. Looking into the Quazip source code at the moment.

**Comment by chchwy** [comment]
Here is the PCLX file that I fixed, should be loaded without problems:
https://www.dropbox.com/s/3mhdts1rckevj0g/what.pclx?dl=0

I'm fairly certain it's a filename issue. There are 2 files which have non-ASCII filename in the PCLX. Obviously zlib doesn't handle it properly on Windows. It results in a sudden interruption of unzip process before the most important file `main.xml` is unzipped. 

I'll fix it later.

**Comment by Jose-Moreno** [comment]
@chchwy I figured as much, I already warned the user to rename any sound file with alphanumeric latin characters for the time being as I was suspecting this issue could be either due to an encoding issue or due to the imported data filesize, considering all the files that weren't able to be opened in the initial report had a similar file size.

I'll close this once you've pushed the fix, thanks a lot everyone!

Thanks a lot everyone!

**Comment by CandyFace** [comment]
@chchwy you updated zlib some time ago, did you fix this problem or is it still ongoing?

**Comment by chchwy** [comment]
No, new zlib doesn't solve this issue.
What I plan to do is rename sound files to a simple number like 0001.mp3 on importing.

**Comment by CandyFace** [comment]
Ah I see, yeah that sounds like a good solution.
