### ISSUE TITLE
[Translation] Request to add an European Portuguese (pt-PT) translation slot

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#697]
@chchwy It seems Brazilian Portuguese and European Portuguese (Portugal) are very different despite their roots. So a user has requested this in our forums:

http://www.pencil2d.org/forums/topic/translation-language-request/

**Comment by chchwy** [comment]
Portuguese has been added.

**Comment by Jose-Moreno** [comment]
@chchwy Thanks Matt. I'll let the user know so he can contribute right away :)
