### ISSUE TITLE
Clearing recent files menu then saving animation crashes Pencil

### ISSUE THREAD

**Issue by martinvanzijl** [pencil2d/pencil#706]
### --Issue Summary--

When I clear the recent files menu, then save the animation, Pencil crashes.

### --Actual Results
Pencil crashes with a segmentation fault warning.

### --Expected Results--
Pencil should save the animation as usual.

### --Video or Image Reference--

Video:

[clear-menu-defect_edit.zip](https://github.com/pencil2d/pencil/files/1151330/clear-menu-defect_edit.zip)

Image:

![crash-2](https://user-images.githubusercontent.com/24422213/28193838-0b78f618-6894-11e7-988c-e0d87a59d383.png)

### --Steps to reproduce--

1. Select "File --> Open Recent --> Clear".
2. Save the animation using "File --> Save".
3. Pencil will crash. 

OR

1. Select "File --> Open Recent --> Clear".
2. Open an existing animation using "File --> Open".
3. Pencil will crash. 

### --System Information--
+ Pencil2D Version:

Git master as of 17 July 2017 (fd59758).

+ Operating System:

Windows 7 64-bit

+ RAM Size:

4GB

+ Graphics Tablet:

N/A - Using the mouse

### --Code Snippets--
The debugger stops at the"addAction" line below:

```C++
void RecentFileMenu::addRecentFile( QString filename )
{
   ...
        addAction( mClearSeparator );
```

It's probably to do with the re-adding of the separator and "Clear" item to the menu.

**Comment by J5lx** [comment]
From the documentation of QMenu::clear():

> Removes all the menu's actions. Actions owned by the menu and not shown in any other widget are deleted.

My guess is that this is the problem. I’ll look into a proper solution.

**Comment by CandyFace** [comment]
While we are at it, is there a reason why the clear button in the preferences window that I implemented some time ago has been kept? I don't see a reason why both should exist.
