### ISSUE TITLE
Being able to drag layers without swapping

### ISSUE THREAD

**Issue by CandyFace** [pencil2d/pencil#714]
### --Issue Summary--
When you drag a layer beneath another or in-between two, the layers will get swapped. This makes it difficult to organize layers when you have a lot of them.

As you add more layers and want them in-between, the problem grows.

### --Actual Results
The layers are swapped, putting layer 2.5 at 2 spot and 2 and 2.5 spot.

### --Expected Results--
The layer is moved between 2 and 3

### --Video or Image Reference--
Example: move 2.5 between 2 and 3:
![moving layers](https://user-images.githubusercontent.com/1045397/28693892-444994c8-7327-11e7-83dc-4e4441dd9071.gif)

### --Steps to reproduce--
Follow the gif above:

### --System Information--
+ Pencil2D Version:
date: 2017-07-24_11:03:18

**Comment by scribblemaniac** [comment]
This will definitely be fixed in #533.

**Comment by Jose-Moreno** [comment]
@CandyFace This is related to this issue #436 which was brought up by JonasThomas he even did a video where he explained this and other stuff. https://www.youtube.com/watch?v=INAsUcpywL8&feature=youtu.be  He did fixed a few other problems around that issues, but this particular layer behavior got stuck. Could be worth taking a look at all that thread to understand what was implemented too.

**Comment by davidlamhauge** [comment]
This issue should be closed. Fixed long ago.

**Comment by Jose-Moreno** [comment]
@davidlamhauge You're right. This was fixed by #1147 
Closing.
