### ISSUE TITLE
Introduce API documentation

### ISSUE THREAD

**Issue by J5lx** [pencil2d/pencil#716]
Since our current codebase is rather scarcely documented, it seems that all agree that we should introduce some actual, structured internal API documentation. As of now, Doxygen seems to be the means of choice as documentation generator, and @scribblemaniac is working on a configuration for Pencil on [his add-doxygen branch](https://github.com/scribblemaniac/pencil/tree/add-doxygen). Until it is done, we should discuss remaining issues such as automated deployment of generated documentation here.

References: #540 (particularly https://github.com/pencil2d/pencil/issues/540#issuecomment-255045764)

Related: #683 (regarding formatting of documentation comments)

**Comment by CandyFace** [comment]
This too is regarding @scribblemaniac comment in #683 
> I would like to modify the styling a bit more because it is ugly right now I my opinion, but I might just leave it if don't have enough time.

Imo. that can wait until later. I agree it's ugly and we should definitely change it, but it can wait.
As for auto deploying to gh-pages using travis, I found this guide: https://gist.github.com/vidavidorra/548ffbcdae99d752da02
