### ISSUE TITLE
[Feature/UI Improvement] Ability to display the palette as a table of color swatches instead of "named list"

### ISSUE THREAD

**Issue by darkhog** [pencil2d/pencil#718]
### --Issue Summary--
This feature would be useful, because current way the palette is displayed when you get to larger projects with many different colors or really detailed coloring you need to go through the list to find the color you need. Something like GIMP's or Photoshop swatches with color name displayed after hovering would be preferred.

### --Actual Results
not a bug

### --Expected Results--
not a bug

### --Video or Image Reference--
Any graphics editor with color swatches/"color grid" for palettes. GraphicsGale and Photoshop are good examples. Just google it.

### --System Information--
+ Pencil2D Version:
not a bug, stable 0.5.4

+ Operating System:
not a bug, doesn't matter

+ RAM Size:
not a bug, doesn't matter

+ Graphics Tablet:
not a bug, doesn't matter

---

**Comment by J5lx** [comment]
Actually Pencil has supported a grid view in the colour palette for some time, though I’m not sure whether there are tooltips for the colour names. However this feature is not available in the ancient version 0.5.4 which you are using. At the moment our nightly builds are probably actually more stable than that “stable” version from four years ago. We are hoping to release a new version soon™, but until then it’s recommended to use the official nightly builds for Linux, macOS and Windows from  <https://drive.google.com/open?id=0BxdcdOiOmg-CcWhLazdKR1oydHM>.

**Comment by CandyFace** [comment]
As @J5lx  mentioned, this has been available for quite some time now in the nightly build. I'm closing this.
