### ISSUE TITLE
Import animated gif

### ISSUE THREAD

**Issue by hellocatfood** [pencil2d/pencil#72]
Can there be an option to import an animated gif and split its frames into Pencil frames at their specified frame rate?

**Comment by Jose-Moreno** [comment]
@chchwy You can close this. GIF Import works as of Oct 10 2016 Nightly Build. I can succesfully import animated gifs that are correctly split in the timeline. I've tested it with animated GIF's from 18 frames to 480 frames long.

**Comment by chchwy** [comment]
Good job! @Jose-Moreno
