### ISSUE TITLE
Selection Flip x/y executing same function as View H/V Flip

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#723]
### --Actual Results

Edit > Selection > Flip is flipping the VIEW, when it should only flip the content of the selection.

### --Expected Results--

The Selection Flip function should flip only the contents of the marquee, and not the whole view. That's what Flip View function is for.

### --Steps to reproduce--

1. Create an arrow pointing to the right.
2. Create another arrow below pointing to the right
3. Use marquee selection tool to select the first arrow
4. Go to Edit > Selection > Flip X or Flip Y
5. You'll notice both arrows were flipped

Bonus: Another way to notice that the view has been flipped is, for example when you have flipped the "selection" horizontally (x), the marquee tool won't allow you to start the selection box from usual left to right, but form right to left, because the view is what have actually been flipped.

Go to View > Horizontal Flip or Vertical Flip to counter and you'll notice it's the same behaviour with the select tool.

### --System Information--
+ Pencil2D Version:

Pencil2D Nightly Build
commit: 6bf33191e153c47933e37a91415968d4867468e4
date: 2017-08-04_10:18:40

+ Operating System:

Windows 7 Ultimate
+ RAM Size:

4GB
+ Graphics Tablet:

---

**Comment by chchwy** [comment]
Fixed by @CandyFace
