### ISSUE TITLE
Movie Export broken in August Builds

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#724]
### --Actual Results

Exporting a movie no matter it's file extension (mp4, avi, gif) results in no file being exported
### --Expected Results--

Export functionality should render a video or gif.

### --Steps to reproduce--

1. Create an animation
2. File > Export > Movie
3. Browse for destination folder and press [OK]
4. Rendering bar appears as expected
5. No resulting file is found inside the folder

Please review if this is a windows only problem or a global problem.
Also this does not happen with July 19th version, it only happens with August versions.

### --System Information--
+ Pencil2D Version:

date: 2017-08-09_16:41:04
commit: 8eab59e0ea17864c4baf12b0e74a3b360873031b

+ Operating System:

+ RAM Size:

+ Graphics Tablet:

---

**Comment by CandyFace** [comment]
Can confirm it doesn't work on mac too.

**Comment by chchwy** [comment]
Looking at this.

**Comment by chchwy** [comment]
Same here, it doesn't happen in my local build, that's weird :/

**Comment by chchwy** [comment]
I found the reason. 

In `movieexporter.cpp`, the code to write a key frame image to disk
```
bSave = imageToExport.save( strImgPath );
Q_ASSERT( bSave );
```
was changed to this
```
Q_ASSERT( imageToExport.save( strImgPath ) );
```
According to [Qt's document](http://doc.qt.io/qt-5/qtglobal.html#Q_ASSERT), `Q_ASSERT` does nothing if QT_NO_DEBUG was defined during compilation.

@J5lx Just a kind reminder the code in Q_ASSERT() or assert() usually won't be executed in release builds :)

**Comment by chchwy** [comment]
Fixed, please check the Aug 11 build.

**Comment by J5lx** [comment]
Ah yes, that was quite an oversight on my part. I knew that assertions wouldn’t do anything in release mode, but since `Q_ASSERT()` looks so much like a regular function I forgot that that also applied to the condition.
