### ISSUE TITLE
Please consider to use GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [pencil2d/pencil#730]
Please consider to use GitHub Releases rather than Google Drive for the downloads. It is more standardized and made for this purpose.

**Comment by CandyFace** [comment]
This has been discussed before (see #582). We made the conclusion back then that Google Drive would suit better for nightly builds. Github Releases will be used for future stable releases.

**Comment by probonopd** [comment]
OK thanks.

**Comment by probonopd** [comment]
Would still make life _much_ easier for https://github.com/AppImage/AppImageHub...
