### ISSUE TITLE
Extreme Zooming transitions when using mouse or stylus

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#731]
### --Actual Results

The smooth transition we used to have when zooming in or out is now replaced with extreme zoom in or zoom out by just moving the mouse or stylus when using CTRL + Right Click functionality.
### --Expected Results--

Transition should be smooth and relative to mouse / stylus pointer displacement

### --Steps to reproduce--

1. Just try out zooming in or out with your mouse.
### --System Information--
+ Pencil2D Version:

commit: 20fc432d55bf7f6d9ea4ad34de069518b1040769
date: 2017-08-20_22:58:34
+ Operating System:

Windows 7
+ RAM Size:

8GB
+ Graphics Tablet:

Wacom Intuos Pro 5 Model: PTH-450
---

**Comment by chchwy** [comment]
Fixed in Aug 22 version
