### ISSUE TITLE
[ISSUE] When using the PEN/BRUSH TOOL a large stroke preview will not allow sketching on VECTOR Layers

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#734]
### --Issue Summary--
When dragging continuously with the PEN TOOL on a VECTOR layer it shows a _too large_ stroke that will cover eventually the whole canvas, particularly if you got a value size (Options Panel slide) bigger than (for instance) "10".
After releasing the pressure of the pen tablet the final stroke will be showed correctly.

With the BRUSH tool things are most similar: the _too large_  initial stroke also appears but after releasing it the final stroke will show only a _thin line_ (like the PENCIL tool does) independently of the value of its size

I am lacking technical words to describe it better

### --Actual Results
If you got the BRUSH size of "**_10_**" or more and start dragging the canvas, an initial "large stroke" will cover the canvas. After releasing the pressure the canvas will show its correct size

### --Expected Results--
If you got the BRUSH size of "**_10_**" or more and start dragging the canvas, an initial stroke should have the same thickness as the final stroke. After releasing the pressure the canvas will show the correct size again.

### --Steps to reproduce--
- Open Pencil2D
- Go to VECTOR layer and pick the PEN tool and make its size value to "10"
- Draw some lines
For the BRUSH tool follow the same steps. 

### --System Information--
+ Pencil2D Version:
Last Build 23August2017

+ Operating System:

+ RAM Size:
32GB

+ Graphics Tablet:
HUION GT185 HD

---

**Comment by Kaikogf** [comment]
NOTE:

I am not sure what have just happened with this ISSUE but today everything since to work rather OK...
I will check it once more

**Comment by CandyFace** [comment]
I believe this is related to some recent changes @chchwy made while working on view and zoom. I don't know how to reproduce it myself entirely, I just know it can happen if you zoom very fast into 10.000% and back to 100%. I think it has something to do with the view not being updated properly under certain conditions.

**Comment by Kaikogf** [comment]
I tried to zoom very fast and I noticed that the canvas not always matched the initial zoom, meaning that when zooming in and then out the canvas will stuck somewhere in the middle. The more I tried to bring the canvas back to its position the more it got stuck far away.

Has nothing to do with this post, but just wanted to comment it 👍

**Comment by Kaikogf** [comment]
I have followed the steps and now things are working OK. I am closing this post.
