### ISSUE TITLE
[BUG] list of SHORTCUTS on the Preference-Panel that DOESN'T WORK [related to #286]

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#735]
### --Issue Summary--
The following Shortcut keys from the Preference Panel doesn't work:
- EXIT (CTRL + Q)
- Export SvgImage
- Export Xsheet (Ctrl+Alt+X)
- ImportimageSequence (**TIFF**, **PNG**, **JPG**, **BMP** with UperCase. **GIF** with Lower/UperCase)
- PREVIEW (ALT+P)
- PRINT (CTRL+P)

### --Actual Results
Shortcuts doesn't work at all

### --Expected Results--
In relation with the ImportingImageSequence, the dialogue window for importing images shows Upper/Lower case for any of the extensions to be saved. So I assume that every extension should be working with those variants

### --Steps to reproduce--
Easy:
Go to Edit > Preference panel > Shortcuts > and check the shortcuts with their default behaviour

### --System Information--
+ Pencil2D Version:
Last build 23August2017

+ Operating System:
Windows 8.1 x 64bits

+ RAM Size:
32GB

+ Graphics Tablet:
HUON GT185 HD

---

**Comment by Kaikogf** [comment]
Following the previous issue #286

**Comment by chchwy** [comment]
Considering to remove these items since there are not used at the moment.

**Comment by Kaikogf** [comment]
@chchwy 
The ImportImageSequence is working rather well, with the exceptions mentioned above [TIFF, PNG, JPG and BMP only import with UperCase extension. GIF only import with Lower/UperCase extension], so in order to remember you developers of those exceptions, it would be better to open a "new" issue?

**Comment by Jose-Moreno** [comment]
@chchwy @Kaikogf I honestly think, we should leave them considering they are part of our future targets. Things like SVG support for import/export, X-Sheet export, Live / Cache Preview have been very much requested features for a number of years.

**Comment by scribblemaniac** [comment]
@Jose-Moreno However, if they're in the menu then people might think that they have already been implemented and would expect the shortcuts to work.

**Comment by CandyFace** [comment]
I agree with @scribblemaniac we should hide these shortcuts for now. Something like not implemented shortcuts and the like is not something you want to have lying around in a stable release.

**Comment by Jose-Moreno** [comment]
@CandyFace @scribblemaniac That is true. Since I'm not aware of the difficulties of implementing these features, I assumed it would be a wasted effort to remove these now only to re-activate them later along with the full feature. But I guess it's better to just leave the specific working features to avoid confusion.

**Comment by Kaikogf** [comment]
@chchwy 
Everything is working fine with the ImportingImageSequence, with the only exception of the GIF extension (lower/upper, doesn't import yet)

**Comment by Kaikogf** [comment]
@chchwy 
The GIF extension (lower/uppercase) is working when Importing a single Image. 
_So the only issue left here is the GIF extension when Importing ImageSequences_
:+1:

**Comment by Kaikogf** [comment]
### Updating the list of Shortcut keys from the Preference Panel that doesn't work, initially presented here.

I believe some of the initial shortcut keys mentioned in my first comment were hidden, so the only one that remains to be fixed is:

- ImportimageSequence (**GIF**). Doesn't work with **_uppercase_** extension

**Comment by Jose-Moreno** [comment]
@Kaikogf That's because the animated GIF option was separated from the Export movie functionality. As such it is currently not exposed.

I'll open a new issue to present which actions are pending exposure in the shortcuts list including that one.

**Comment by Kaikogf** [comment]
@Jose-Moreno 

Not sure if I understood your words correctly as I think you missed my words. I am saying that the GIF importing feature does not work with uppercase extension, while all the other extensions works OK with uppercase or lowercase characters. In another words, when trying to import a GIF image with a uppercase extension (**GIF** instead of **gif**) pencil2D does not load its content….

**Comment by Jose-Moreno** [comment]
@Kaikogf I see. I certainly had not understood the specific comment sorry. 

Since it is an unrelated issue to this (shortcuts list). Please open a new bug report for the filetype case mismatch. 

If it is possible for you before reporting, please also test if the other filetypes have the same problem (i.e JPEG, JPG, PNG, as opposed to jpeg, jpg, png, etc) in case your tests show that the issue only affects the gif format, then just report that.

**Comment by Kaikogf** [comment]
@Jose-Moreno 
tested every other file extension and everything was OK. Already opened a new post about GIF
