### ISSUE TITLE
[ISSUE ?] PREFERENCES PANEL is opening with a new window everytime you select it on the Menubar

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#736]
### --Issue Summary--
Going to EDIT > and clicking on PREFERENCES will open the Preferences panel. 
And while it is open, go and repeat the same process. it will open a new window every time you select it....
:O

### --Expected Results--
Should be open only one Preferences window

```
-->

**Comment by chchwy** [comment]
Fixed in 30 Oct version
