### ISSUE TITLE
[ISSUE] The AntiAliasing feature on the BRUSH Options Panel is hidden when the FEATHER checkBox is selected

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#743]
### --Actual Results
Selecting the checkingBox _USE FEATHER_ on the Brush Options panel will hide the checkingbox of the Anti-Aliasing feature

### --Expected Results--
The Anti-Aliasing feature should be always visible

### --Steps to reproduce--
. Open Pendil2D
. Select Brush tool
. Uncheck the _**Use Feather**_'s checkbox to unhide the _Antialiasing_ feature

### --System Information--
+ Pencil2D Version:
Las build 23August2017)

+ Operating System:
Windows 8.1 x 64bits

+ RAM Size:
32GB

+ Graphics Tablet:
HUION GT185 HD

---

**Comment by CandyFace** [comment]
This is intentional, as I explained here in #705, the way feather works makes anti-aliasing redundant when it's enabled and it is therefore being hidden whenever feather is on.

**Comment by Kaikogf** [comment]
I see ! 👍 

Well, and here it is just a simple question, thinking about it, would it be easier to have implemented just a _grey-out Antialiasing checkbox_ feature while keeping it visible to all?. Right now it was a bit confusing, not now, for me and it may be for others. But honestly I understand your way of thinking.

**Comment by CandyFace** [comment]
I've recently been talking about removing the "feather" toggle for brush and just have it on always, as I think it makes sense for the brush type it's supposed to behave like, so i'll probably remove anti-aliasing from brush completely. If you want a finer stroke type, use pen, if you want a pencil like type, use the pencil.

**Comment by chchwy** [comment]
Agree with removing the feather and AA toggles of the brush tool.

**Comment by Kaikogf** [comment]
Just to let you know I also noticed today (Pencil2D build 12SET2017) that the ERASER tool also hides the _Anti-Aliasing_ feature if the _Use Feather's box_ is selected.

**Comment by nickbetsworth** [comment]
I'd like to pick this up if it's still up for grabs!

**Comment by davidlamhauge** [comment]
Go ahead @nickbetsworth !

**Comment by CandyFace** [comment]
Has been addressed in #1284
