### ISSUE TITLE
Opening the same recent project, causes incomplete sound loading 

### ISSUE THREAD

**Issue by CandyFace** [pencil2d/pencil#752]
### --Issue Summary--
If you open a project, import a few sounds files, save it and open it from recent again, then the sound files will not be loaded and inserting a new sound file will crash the program with:
```
[Object] couldn't copy sound file to data folder:  "/Users/CandyFace/Documents/Polycode/Asteroid/Sfx/pew.wav"
ASSERT: "!strCopyFile.isEmpty()" in file ../../pencil-mychanges/core_lib/managers/soundmanager.cpp, line 132
```

### --Actual Results
Recent file is loaded again but sound files are not imported correctly. Also, adding new sounds again will crash the program with the error above.

### --Expected Results--
Recent file is loaded again with sound files imported correctly

### --Video or Image Reference--
![recent-bug](https://user-images.githubusercontent.com/1045397/30211195-49f68e04-94a0-11e7-8905-f368dabe0be3.gif)

### --Steps to reproduce--
1. open a new project
2. import a few sound files
3. save it
4. open it again from recent opened files

### --System Information--
+ Pencil2D Version:
commit: b661883877266fa96080ff58359453d74812e464
date: 2017-08-26_16:01:16

+ Operating System:
Mac OS 10.12.6

**Comment by Jose-Moreno** [comment]
[2018] This issue still happens in the latest Nightly Build for:

Version: 0.6.1.1
commit: 999c05af9544706a9df72b39766704f30b378954
date: 2018-06-13_15:28:41
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

The current work around is to load a new file and the re-load the file with sound again and it will load properly.

**Comment by chchwy** [comment]
Closed as it's fixed in #1043

**Comment by CandyFace** [comment]
I can confirm it has been fixed on Mac os 👍

**Comment by chchwy** [comment]
Thanks @CandyFace
