### ISSUE TITLE
[BUG] Still Image and Img Sequence export not applying camera motion

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#765]
### --Actual Results

When Exporting either an Image Still or an Image sequence when there is a camera interpolation / keyframe motion, it will result in a static frame across the exported frames. Even if you move the camera in the first frame, and export a still image, the camera "animation" it will not be applied.
### --Expected Results--

Camera motion, regardless of export method should be applied and represented in the final result.

### --Steps to reproduce--

1) Import an image that's bigger than the camera frame size. Or reduce the camera size.
2) Select camera layer.
2) go to any frame after the first and create a keyframe for the camera.
3) Move the camera so the image is visibly "out of bounds"
4) Go to File > Export > Image (position playback on any frame) or Image Sequence
5) Review result form either method and confirm that the image has the same placement from when the image was first imported.

### --System Information--
+ Pencil2D Version:

commit: 8fd508104389c097a83e7bc9d9a1ed32a85f9f9a
date: 2017-09-23_13:05:14
+ Operating System:

Windows 7 Ultimate
+ RAM Size:

+ Graphics Tablet:

**Comment by chchwy** [comment]
Hi @Jose-Moreno 
This issue should be fixed in 28 Oct version, could you please confirm?

**Comment by Jose-Moreno** [comment]
@chchwy alright I'll give it a try throughout the day. I'll report approximately at 20:00 pm GMT -5 thank you for your work!

**Comment by Jose-Moreno** [comment]
![came_interp_test](https://user-images.githubusercontent.com/4912907/32136059-6de3ad38-bbce-11e7-92e4-2b201c43ba0f.gif)

I had time early, so I gave it a quick try. Exporting image sequence works well even when rotating the camera :smile: 

I exported a still frame from the file with camera interpolation and it worked well.

**However** I have found a consistent crash when exporting still images that is related to the camera layer keyframes, I created an issue here #770

**Comment by chchwy** [comment]
@Jose-Moreno Thanks for your time :) I'm going to close this.
