### ISSUE TITLE
[Bug] Changing to Russian Language, switches to Japanese instead

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#769]
### --Issue Summary--

This is a report that was posted on the forum. I'm posting on behalf of the original user. You can visit the thread here: https://www.pencil2d.org/forums/topic/select-japanese-language-instead-russian/

### --Actual Results

I select Preferences > Language > Russian, then restart Pencil and see Japanese instead Russian. So can’t select Russian 🙂

### --Expected Results--

Switching to any language should switch to the exact language the user expects.

### --System Information--
+ Pencil2D Version:

commit: 8fd508104389c097a83e7bc9d9a1ed32a85f9f9a
date: 2017-09-23_13:05:14

+ Operating System:

Debian Stretch
Linux AppImage

**Comment by Jose-Moreno** [comment]
Can confirm, it happens on windows September 23rd RC as well.

**Comment by chchwy** [comment]
Should be fixed in Daily build 23 Oct 2017
