### ISSUE TITLE
[BUG] Exporting Still Image Frame without Camera Layer Keyframe Crashes Pencil2D

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#770]
### --Issue Summary--

It seems that exporting still images of any frame that doesn't have a camera interpolation keyframe directly below will crash pencil2D.
### --Actual Results

Exporting a still image of any frame of an imported image sequence / frame drawn inside pencil2d different from frame 1 crashes Pencil 2D
### --Expected Results--

Pencil2D should not crash from exporting still images from any frame regardless of camera interpolation
### --Video or Image Reference--

![image](https://user-images.githubusercontent.com/4912907/32136335-8feffe74-bbd1-11e7-93c5-2de899b91994.png)
Example: Exporting frame No. 4 on this timeline will crash Pencil2D
### --Steps to reproduce--

want I can create a new issue on this). 
Here are the steps:
1) Create a new file without camera interpolation 
2) Import an image sequence of any length (for tests I used 8 frames and 12 frames sequences) 
3) Once imported, position the playback bar on the last frame of the sequence
4) File > Export > Still Image...
5) Leave options at default and browse any location to save
6) Instant Crash (attached log for windows)

> Faulting application name: Pencil2D.exe, versión: 0.0.0.0, marca de tiempo: 0x59f44d5d
> Faulting module name: Pencil2D.exe, versión: 0.0.0.0, marca de tiempo: 0x59f44d5d
> Exception code: 0xc0000005
> Fault offset: 0x000000000004bf6a
> Faulting process Id: 0x1b54
> Faulting application start time: 0x01d350040d454256
> Faulting application path: C:\Users\MORE\Downloads\pencil2d-win64-2017-10-28\Pencil2D\Pencil2D.exe
> Faulting module path: C:\Users\MORE\Downloads\pencil2d-win64-2017-10-28\Pencil2D\Pencil2D.exe
> Report Id: 820d545d-bbf8-11e7-989b-f46d048fe04e

### --System Information--
+ Pencil2D Version:

commit: b5c3d28f519c30a5f356c8547bebd4dcb883f5a6
date: 2017-10-28_20:14:12
+ Operating System:

Windows 7 Ultimate
+ RAM Size:

8 GB
+ Graphics Tablet:

**Comment by chchwy** [comment]
Fixed in 29 Oct version
