### ISSUE TITLE
[BUG] Vector Layer strokes not saving pressure data or line width.

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#772]
### --Issue Summary--
Today I provided support for a user who's been using old Pencil versions and wanted to upgrade and use the newest ones. 

However after saving some copies they swiftly told me that they had an issue where all the vector artwork line weight had been lost (all lines had a uniform line width). 

I can confirm this issue exists in every version from 2017 I've tested so far (from May 4th version) up until the latest versions. Those versions can still open files made with "ancient" versions such as 0.4.4b or 0.5.4 while displaying the vector artwork correctly, for my own testing I used 0.5.4 dev

### --Expected Results--
Vector artwork line width should stay consistent with what the user draws and sees after saving the file. And such artwork should be able to be displayed without issue.

### --Steps to reproduce--
1) Create a New file
2) Draw a pressure sensitive stroke on vector layer
3) save the file as PCL and/or PCLX (test both types)
4) close and re-open the file on the same version.
5) The vector strokes will get the line width of the widest point that was drawn before saving and closing.

### --System Information--
+ Pencil2D Version:

commit: 33f202d86039e84d4764a574eb356cda23543fd5
date: 2017-10-29_22:07:20

Additional Testing Versions: 
Version May 4th 2017 (Has same issue as reference)
Version 0.5.4 (26 July 2013) (Vector Line width working as expected)

+ Operating System:

Windows 7
+ RAM Size:

8GB

**Comment by chchwy** [comment]
Fixed in 1 Nov version
