### ISSUE TITLE
[BUG] Autosave feature disabled

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#773]
### --Issue Summary--
After some reports where people have been losing work after unexpected black outs or computer malfunction, yet it seemed they lost work from the last time the "manually saved" I decided to investigate this issue.

As it turns out despite the auto save feature being turned on by default, nothing you do on Pencil2D will trigger it.

I tried creating layers, frames, drawing on both layer types, importing sound and images. Nothing will work to activate the autosave.

### --Expected Results--
Any of the following functions should trigger the auto save after the specified amount of steps found in preferences:

+ Drawing / Erasing on Bitmap Layer (after stroke has been placed with any tool)
+ Drawing / Erasing on Vector Layer (placed stroke)
+ Transforming strokes on Bitmap layer (on confirmation / release) (move tool + finger tool)
+ Transforming strokes on Vector layer (on confirmation / release) (move tool + finger tool)
+ Adding / Removing /Duplicating key-frames
+ Adding / Removing Layers
+ Creating / Deleting colors on color Palette.
+ Importing Files (Bitmap, Vector, Sounds)

### --Steps to reproduce--
1) Open a new pencil file
2) Saves As... your new file for the first time.
3) Go to Edit > Preferences > Files > Disable or Re-Enable Autosave Checkbox. 
4) Reduce Number of modifications to a suitable number (I used 15 first then moved to 1 modification for testing)
5) On your OS file browser / finder check the modification date for your file (the time you just saved it as a file). No matter what you do it will not change. Also there will be a perpetual star (*) next to the pencil2D filename.

### --System Information--
+ Pencil2D Version:
commit: da990cc5126488ac29d3f971bd05b9164b79fa2e
date: 2017-11-01_13:13:19

+ Operating System:
Windows 7

+ RAM Size:
8GB

**Comment by chchwy** [comment]
Fixed in 6 Nov 2017 version
