### ISSUE TITLE
[BUG] Scrolling affects camera layer when new file created

### ISSUE THREAD

**Issue by scribblemaniac** [pencil2d/pencil#775]
### --Issue Summary--
Whenever a new file is created from the menu (not at startup), then scrolling the mouse wheel zooms the camera, even though the bitmap layer, not the camera layer, is selected in the timeline. Selecting another layer, then reselecting the bitmap layer fixes this issue.

### --Actual Results--
The camera zooms in/out when the mouse is scrolled, as if the camera layer was selected.

### --Expected Results--
The view should zoom in/out when the mouse is scrolled because the bitmap layer is selected.

### --Steps to reproduce--
1. Start Pencil2D
2. Draw something
3. Scroll up and down with the mouse over the canvas. Take note of how it scales the entire viewport.
4. Go to File > New... (Don't save changes)
5. Draw something again
5. Scroll up and down with the mouse over the canvas again. Now only the drawing scales.

### --System Information--
+ Pencil2D Version:
Nightly Build 2017-11-01_13:13:19

+ Operating System:
macOS 10.13.1

+ RAM Size:
16 GB

**Comment by chchwy** [comment]
Fixed in 3 Nov 2017 version.
