### ISSUE TITLE
allow to link against system zlib

### ISSUE THREAD

**Issue by mapreri** [pencil2d/pencil#784]
I'd like to link against the system-wide zlib instead of using the embedded code copy.

In Debian we repack pencil2d to remove the embedded library (because it's very discouraged by policy, for good reason if I might add).
I came up with [a patch](https://anonscm.debian.org/git/collab-maint/pencil2d.git/tree/debian/patches/remove-zlib.patch?h=debian/0.5.4%2bgit20171107.7e7aff7%2bds-1) (yes, I know it's way broader than needed, I just removed everything blindly…) to link *only* against the system zlib, but I can see how that might not be good for you, as you might want to keep linking against the local library if available.

It seems that I'm unable to come up with enough time/motivation to work on an appropriate patch myself, so I'm looking if anybody else could do it — write something to allow linking with either system or local/embedded zlib.

A particular gotcha: it would be best if the inclusion of the zlib subdir was done only after checking whether we are going to use the system one or not, so the zlib directory can be removed without any further patch to the build system.

### --System Information--
+ Pencil2D Version:
anything up to 2017-11-07 sources.

+ Operating System:
I care only about linux (well, Debian) and friends, but probably affects everything.

**Comment by scribblemaniac** [comment]
Déjà vu: #530. Still relevant though.

**Comment by chchwy** [comment]
I have a plan to replace the zlib+Quazip with a more lite-weight compression lib called [miniz](https://github.com/richgel999/miniz) in the near future. The lib has only 2 files so that we can easily embed it into our project. Then we don't have to worry about this issue anymore

**Comment by mapreri** [comment]
> Déjà vu: #530. Still relevant though.

oops. Yeah, that. It felt odd that I've never forwarded it, I've now added a note with that bug.

mhhh, please feel free to close this one as a duplicate then :\

**Comment by mapreri** [comment]
> I have a plan to replace the zlib+Quazip with a more lite-weight compression lib called miniz in the near future. The lib has only 2 files so that we can easily embed it into our project. Then we don't have to worry about this issue anymore

That might be good enough indeed.
I still wouldn't particularly like embedding sources from other projects, but that would be better than the whole zlib and (a patched!) quazip.

**Comment by J5lx** [comment]
> I have a plan to replace the zlib+Quazip with a more lite-weight compression lib called [miniz](https://github.com/richgel999/miniz) in the near future. The lib has only 2 files so that we can easily embed it into our project. Then we don't have to worry about this issue anymore

And there I started experimenting with using system libs just two days ago :) @chchwy How near is “near future”? Would it make sense to work on a patch for system-wide quazip+zlib in the meantime or would that just be a waste of effort?

**Comment by chchwy** [comment]
@J5lx I will do that as soon as 0.6 is out.
