### ISSUE TITLE
Can't save file

### ISSUE THREAD

**Issue by MarcelWeijenberg** [pencil2d/pencil#785]
Even in admin mode (windows10) i get
Invalid Save Path
The file path you have specified ("D:/1.pcl") cannot be written to, so the file cannot be saved. Please make sure.......

**Comment by CandyFace** [comment]
Hi Marcel

Have you tried writing to other folders? Do you get the same message if you save to your desktop?

**Comment by chchwy** [comment]
Hi @MarcelWeijenberg 
Please make sure you are using the nightly build 7th Nov 2017 version. The file saving was accidentally broken in the 6th Nov 2017 version but has been fixed now.

**Comment by MarcelWeijenberg** [comment]
Hi chchwy. That could be the solution but now the file is blocked bij AVG so i can't check it.

**Comment by Jose-Moreno** [comment]
@MarcelWeijenberg Normally both Windows and AVG are very paranoid with ZIP files. If you download the ZIP files from the the Google Drive you can tell AVG to make an exception of that file as described in the following article:

https://support.avg.com/SupportArticleView?l=en&urlName=How-to-exclude-file-folder-or-website-from-AVG-scanning

For Windows part, right click on the file properties to "unblock" the file as explained here:
https://youtu.be/S8nS7aeBD04?t=184

**Comment by MarcelWeijenberg** [comment]
It took about 20 minutes for AVG to trust the file but all works fine now.
Thx!

**Comment by chchwy** [comment]
Happy to hear that!
