### ISSUE TITLE
[BUG] Autosave cannot be turned off in preferences

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#786]
### --Issue Summary--
Autosave Is working as expected, but after experiencing the behavior referenced in #782 I tried to turn the autosave feature off. However when I unchecked the box it would continue to bring the autosave function regardless of being turned off. Even in the regedit key the program recognized it was turned off, but it kept working as if it was turned on.

### --Expected Results--
Autosave checkbox should allow for the user to turn the feature ON or OFF .

### --Video or Image Reference--
Regedit Key Values
![image](https://user-images.githubusercontent.com/4912907/32508413-3c50add8-c3b8-11e7-8246-1e8618d609e3.png)

Autosave checkbox OFF in preferences
![image](https://user-images.githubusercontent.com/4912907/32508525-9f6a2d04-c3b8-11e7-802c-8aad757c46be.png)

Autosave invoked after 10 strokes (according to the number defined in preferences)
![image](https://user-images.githubusercontent.com/4912907/32508554-b42c3124-c3b8-11e7-9fee-91af953f456d.png)

### --Steps to reproduce--
1) Open Pencil2D
2) Go to Edit > Preferences
3) Define a low amount of strokes to activate the feature (I used 10 for the test)
4) Turn off the "enable autosave" checkbox
5) Draw the specified number of strokes
6) Save window will pop-up

### --System Information--
+ Pencil2D Version:
commit: 83e0e6c11487bc48c006e341360125c52333b4dc
date: 2017-11-07_10:15:49

+ Operating System:
Windows 7

**Comment by chchwy** [comment]
What a shame when I said it's an option that can turn off but it is not really off :p
I'm going to work on this.

**Comment by chchwy** [comment]
Please test this in the 8th Nov 2017 version.

**Comment by Jose-Moreno** [comment]
@chchwy Confirmed working on case scenario. Thanks a lot!, I didn't know about it either until I wanted to turn it off haha :smile:
