### ISSUE TITLE
[BUG] Move tool autosave modifications requirements change after using vector tools.

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#789]
### --Issue Summary--
I honestly don't understand why the move tool / black arrow tool "click" event on the empty canvas is considered a "modification" but, if there's any odd behaviour to be reported is that after using a vector tool on a vector layer, clicking is not following the modifications number set in the preferences. This happens on both bitmap and vector layers after using the vector tools.

### --Expected Results--
Clicking on empty space should trigger after the appropriate amount of modifications set in the preferences dialog regardless of the tools that have been used before or after.

### --Steps to reproduce--
1) Create a new file
2) go to Edit > Preferences > Files > Set the amount of modifications to your test number (I used 10, and 20 on separate sessions)
3) Select the Move tool and first test that the number of modifications you set is correct. e.g. Click X times on your empty canvas.
4) Now, select the vector layer. And pick any drawing vector tool (pencil, pen, brush). Draw a single stroke.
5) Now repeat the test from step 3 and you'll notice it now takes less than a half of the required steps to trigger the autosave with the move tool.

### --System Information--
+ Pencil2D Version:
commit: 83e0e6c11487bc48c006e341360125c52333b4dc
date: 2017-11-07_10:15:49

+ Operating System:
Windows 7

**Comment by chchwy** [comment]
Two changes:
1. Using move tool on vector layers now counts only one autosave step.
2. Clicking on an empty canvas doesn't increase autosave steps anymore.

**Comment by chchwy** [comment]
Please test this in 8th Nov 2017 version.

**Comment by Jose-Moreno** [comment]
@chchwy I can confirm the following:

1.  Change no. 1 is working exactly as described. That is when moving the artwork visually it counts as one autosave step.

Notes:
- When you click inside the selection zone without moving the selection, it executes the "move" command as well. This is not bad, and I'm sure it's needed for the function to work.

2. I can also confirm No.2 works as described on Bitmap and Vectors Layers.

Notes:
- This change seems to also have solved the case where pressing ESC to clear a selection in bitmap or vector layers counted as executing the move command.
- When making a selection, clicking outside the selection zone still executes the move command, as seen on the undo stack.

Thanks a lot!
