### ISSUE TITLE
[BUG] Clear Image command affecting Undo for previous drawing function

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#790]
### --Issue Summary--
The Clear Image command (invoked via CTRL+D , using paper button) or Delete Selection command (pressing backspace inside a selection) does not allow for UNDO operations on the bitmap and vector layers despite being added to the undo stack.

However, this seems to affect only the previous stroke. If you create many strokes and Clear the Image in any way, and you navigate through the undo stack (pressing ctrl+z) you will notice that only the stroke drawn BEFORE the Clear Image command is the only one that does not appear.

### --Expected Results--
Clear Image or Delete Selection commands should allow the user to undo such operations.

### --Steps to reproduce--
1-Stroke test
1) Open Pencil2D
2) Draw a stroke on bitmap or vector layers (test both separately, just in case)
3) Use the Clear Image Command OR draw a selection and use the Delete selection command
4) Go to Edit > Undo > Clear Image OR Delete Selection (this is just so you can see that the previous command "1 Pen" is on the stack, but the pen stroke is not appearing on the canvas.

Multi-Stroke Test
1) Open Pencil2D
2) Draw more than one stroke on either bitmap or vector layers (test both separately, just in case)
3) Use the Clear Image Command OR draw a selection and use the Delete selection command
4) Go to Edit > Undo > Clear Image OR Delete Selection (this is just so you can see that the previous commands on the stack). 
5) Notice that after the first CTRL +Z / Undo command the last pen stroke is not appearing on the canvas. However the others will appear.

Note: If you try to draw a stroke, clear image, draw a new stroke, clear image again, and so forth. You won't be able to see any stroke. The main issue stems from the Clear Image command affecting the undo operation from bringing the previous stroke into the canvas.

### --System Information--
+ Pencil2D Version:
commit: 83e0e6c11487bc48c006e341360125c52333b4dc
date: 2017-11-07_10:15:49

+ Operating System:
Windows 7

**Comment by chchwy** [comment]
Please test this in 8th Nov 2017 version.

**Comment by Jose-Moreno** [comment]
@chchwy Confirmed working on case scenario.
