### ISSUE TITLE
Qt version for 0.6 release

### ISSUE THREAD

**Issue by chchwy** [pencil2d/pencil#793]
This is a follow-up of #776

The supported platforms of all Qt 5 versions.
https://doc.qt.io/qt-5/supported-platforms-and-configurations.html

And here a list of platforms which are supported in 5.6 but **not** supported in 5.9:
- Windows XP & Vista
- Mac OS 10.8 10.9
- openSUSE 13.1, Ubuntu 14.04

I believe the user groups of these platforms are relatively small but still there, especially like Ubuntu 14.04 LTS is still officially supported until April 2019. (but I can't find an actual market share though)

So in my opinion, we can use Qt 5.9 for official releases to get benefits from the latest Qt SDK, but keep the code backwards compatible to 5.6 so we can provide old binaries on demand.

5.6 binaries could be compiled manually only once when a new official version is out. No need to do it in the nightly builds.

Any thoughts?

**Comment by mapreri** [comment]
I agree.  As long as it keeps compiling with Qt 5.6 (even with extra flags disable extra features) that's cool.

I'm not providing binaries for e.g. ubuntu 14.04, but I do for other projects and it's very bothersome when a project drops support for a (not so) old Qt.

**Comment by Jose-Moreno** [comment]
@chchwy @mapreri I agree as well. As someone else said, the complaints about compatibility are sparse. I'll share as well the preliminary result to the survey we pushed through the social networks. I'would leave it run for a few more weeks, but it is clear the users with older systems are on the fringe as we had thought initially.

https://docs.google.com/spreadsheets/d/1omMhI8ofMRBaxCnJkY8kZZHzF5FPRN1rGsH6UhTcVIc/edit?usp=sharing

**Comment by CandyFace** [comment]
Sounds good to me 👍

**Comment by scribblemaniac** [comment]
I do agree that we should try to support 5.6, at least for the moment, however one important thing to consider is testing. If we advertise that we support these older platforms, then we should have a way to test the application on those platforms and debug any issues specific to those platforms. The linux versions are not an issue as we can easily virtualize them, but Mac OS X and Windows will be trickier as they are non-free and Mac OS X is difficult to run on a virtual machine. I've personally still got an XP machine, but someone else will have to test/debug on Mac OS X 10.8 and 10.9, and Vista.

The compatibility of the libraries we use also have to be considered. For example, the FFmpeg builds we are currently using are for Windows 7+ and macOS 10.9+.

**Comment by chchwy** [comment]
FFmpeg is definitely a problem. (sign

Since pencil2d is an open source project with 100% volunteers, I'm afraid we can't guarantee it will work on these older platforms. I think we can provide a tentative binary along with 0.6 and ask for people's help. To see If any xp/vista or macOS 10.9 users want to help.

**Comment by CandyFace** [comment]
If we ever get to a point where a bug is certain to only appear on an older platform, then we can setup a virtual machine. I've done that with OS X so it's possible, it's just fiddly to get up and running.

When that's said though, having builds available for legacy users is one thing but supporting them is another. Given that we're open source, and a small team, I don't think it's realistic to say that we can support these operation systems. I however still think we should make builds available, just still make them loosely or not supported at all.

**Comment by chchwy** [comment]
Will follow the rule until the end of Qt5.6 LTS (I think it's 2019 Q1).
