### ISSUE TITLE
[BUG] Creating new file while selecting newly created color on palette crashes Pencil

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#795]
### --Issue Summary--
Pencil2D crashes consistently after creating a new file when creating a new color in the color palette.

### --Steps to reproduce--
1) Open Pencil2D
2) Create a new color, it doesn't matter if it has the same name, or a different name, or the same color. This is irrelevant to the bug. KEEP the color selected i.e don't select anything else.
3) Immediately after creating the color go to File > New and Pencil2D will crash automatically.
### --Crash Log--

6th crash report
Faulting application name: Pencil2D.exe, versión: 0.0.0.0, time stamp: 0x5a027afb
Faulting module name: Qt5Core.dll, versión: 5.6.2.0, time stamp: 0x57e77601
Exception code: 0xc0000005
Fault offset: 0x00000000000a98ff
Faulting process Id: 0x2590
Faulting application start time: 0x01d358d7a348557e
Faulting application path: C:\Users\MORE\Downloads\pencil2d-win64-2017-11-08\Pencil2D\Pencil2D.exe
Faulting module path: C:\Users\MORE\Downloads\pencil2d-win64-2017-11-08\Pencil2D\Qt5Core.dll
Report Id: f19eedbe-c4ca-11e7-aeb9-f46d048fe04e

### --Pencil2D Version--
commit: 5bafbb1791808cfc03b4a8e10c90934ebeb0ae77
date: 2017-11-08_14:09:46

### --OS Version--
Windows 7

**Comment by Jose-Moreno** [comment]
It seems any color created beyond the default palette will crash Pencil2D if they are selected while either a) creating a **new file** or b) opening a file via the **open file** OR **open recent file** commands.

However if you select the offending custom colors the file will save normally. (Save operations do not crash, but might be worth taking a look)

Additional test case:

1) Create a new color.
2) Select the previous color
3) Save the file normally.
4) Reload the saved file
5) Create an additional new color below the previous one.
6) Select the previous new color (second to last)
7) Create a new file
OR
7) Open a new a previous file via File > Open... or File > Open Recent ...
8) Pencil2D will crash.

**Comment by chchwy** [comment]
Fixed in 10th Nov 2017 version.
