### ISSUE TITLE
[BUG] Pencil2D does not save color palette alpha values on file.

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#796]
### --Issue Summary--
Alpha value of any color, even default, is not saved in the file, and will be reset everytime you open the file again.

### --Expected Results--
Saving RGBA information should be done properly since the user expects to have the same transparency values on custom colors the next time they are operating the software.

### --Steps to reproduce--
**Note**: Due to the recent changes in code you now have to select the vector layer prior to be able to change the color palette via the color wheel.
1) Open Pencil2D
2) Select the vector layer.
2) Create a new color on color palette or select an existing one. Change it to your preferred RGB+A values to test.
3) Save the file.
4) Reload the file
5) Notice that the Alpha values of the customized colors are now reset to 255.

### --System Information--
+ Pencil2D Version:
This is an old bug I forgot to report, but it's still present on the latest version
commit: 5bafbb1791808cfc03b4a8e10c90934ebeb0ae77
date: 2017-11-08_14:09:46

+ Operating System:
Windows 7

**Comment by chchwy** [comment]
Fixed in 10th Nov 2017 version.
