### ISSUE TITLE
[BUG] Importing sound on first keyframe after deleting previous sound pops warning

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#802]
### --Issue Summary--
I think this has to do with the issue that was closed before #768 considering the warning is the same. However the issue is different. Before we argued that it was a fair warning so you couldn't overwrite an existing sound, but the problem now is that even if you delete the previous sound Pencil2D still thinks the empty keyframe has a sound, which in turn doesn't allow to import the sound on the first keyframe. However If you create a new keyframe it will allow you to import correctly the new sound, and you can delete the previous keyframe container. However although it is not a critical issue, nor does it cash the software, it'ss bad for the user experience, and should be fixed in the future. (For now when I create the intro tutorials I'll try to mention the shortcomings of the app after talking about specific features)

### --Expected Results--
Just as with bitmap layers, when you erase the contents of the first frame, for a sound layer you should be allowed to delete the sound sample, and reimport it without Pencil2D telling you there's a sound that doesn's actually exists.

### --Video or Image Reference--
![image](https://user-images.githubusercontent.com/4912907/32921305-20a37ae4-cafb-11e7-983b-cd22230fcf14.png)

### --Steps to reproduce--
1) Open Pencil2D
2) File > Impor  > Sound ... > Select a wav or mp3 sample (Pencil2D will ask to create a sound layer, and give it a name)
3) Delete the sound
4) [optional] Select the first frame that was left and press the delete button to make SURE, you emptied the frame
5) File > Import > Sound...
6) Pencil2D will prompt the warning and won't allow to import the sound on that frame number.
7) Create a new keyframe on the next frame. You will be able to import it without issues
8) Delete the first frame.

### --System Information--
+ Pencil2D Version:
(it's the same for RC No, 4 (Nov 15 2017)
commit: e9aeb1a1cf711a5b36c9d4734181ee525ccacd84
date: 2017-11-14_23:22:11

+ Operating System:
Windows 7

**Comment by Jose-Moreno** [comment]
Additional Info: I kept working on the file, just doodling to test Pencil2D. When I wanted to save the drawing I did, Pencil2D had an internal crash (nice job on the crash report!) and it gave me the following output:

![image](https://user-images.githubusercontent.com/4912907/32925680-32b7733c-cb11-11e7-8eb8-e63619ae53bc.png)

FileManager::save
strFileName = C:/Users/MORE/Downloads/Pencil2D Showcase/cuphead.pclx
strTempWorkingFolder = C:/Users/MORE/AppData/Local/Temp/Pencil2D/Default.Y2xD/
layerCount = 4
layer[0] = Layer[id=1, name=Camera Layer, type=5]
layer[1] = Layer[id=2, name=Vector Layer, type=2]
layer[2] = Layer[id=3, name=Bitmap Layer, type=1]
layer[3] = Layer[id=4, name=Sound Layer, type=4]
- Layer[3] failed to save
Layer::save
strDataFolder = C:/Users/MORE/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
- Keyframe[1] failed to save

Error Display
Title: Internal Error
Description: An internal error occurred while trying to save the file. Some or all of your file may not have saved.

System Info
Pencil version: 0.5.4
Build ABI: x86_64-little_endian-llp64
Kernel: winnt 6.1.7601
Product name: Windows 7

So apparently, IF you follow the steps outlined above, and try to save the file, your save manage will crash and you will be unable to save the work. I think this information makes this bug a bit more critical than I initially suggested.

**Comment by Jose-Moreno** [comment]
I just tested again: Taking the steps for reproducing this bug, allow the filemanager to crash everytime. The problem lies in the sound layer and this bug is higly likely to get sprung by a user since I only deleted the sound once. 

Current workaround is to delete the layer and create a new layer with a new sound, everytime you want to change sound samples.

**Comment by chchwy** [comment]
Should be fixed in 21 Nov 2017 version
