### ISSUE TITLE
won't save

### ISSUE THREAD

**Issue by Pickering1853** [pencil2d/pencil#805]
Error Display
Title: 
Description: 

System Info
Pencil version: 0.5.4
Build ABI: i386-little_endian-ilp32
Kernel: winnt 10.0.15063
Product name: Windows 10

### --System Information--
+ Pencil2D Version:

+ Operating System:

+ RAM Size:

+ Graphics Tablet:

---

**Comment by CandyFace** [comment]
Hi @Pickering1853 

You're using a very old version of pencil2D, please try the 0.6 release candidate instead:
http://pencil2d.github.io/download/

**Comment by Pickering1853** [comment]
Thank you

**Comment by CandyFace** [comment]
if you can reproduce this in 0.6, please make a new issue.
I'm closing this.
