### ISSUE TITLE
[UX] Zooming In/out with menu, keyboard shortcuts and scroll-wheel input is not precise.

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#807]
### --Issue Summary--
This is a User Experience "issue" which i'll tag as [UX] whenever I report (hopefully someone can create a UX label too). I'ts not a critical issue, but it does affect how users interact with our application. This is something we should also begin considering for any release beyond 0.7 and closer to 1.0

For this comparison I used Nov 23rd 2017 and Nov 02 2016 nightly builds.
On the newer builds the zooming operation is never precise and after taking any amount of steps you cannot return to a previous value and to get to 100% you have to reset the view zoom, which is not ideal for an efficient animation workflow.

The current way that Pencil2D handles the zoom operation makes it difficult to predict and the bitmap workflow suffers as compared to an older version.

### --Expected Results--
Normally when working you are expected to take incremental steps. For example If you press the shortcut or use the scroll-wheel these should allow you to have discrete increments. 

In the older version apparently it was handled by divisors and multipliers like 1.5, 2, 2.5, 3 and so on etc. Of course it would never get to 0% and the maximum was 10,000%

However the only time you want floating point increments like what we have now is when you are zooming in by hand using the mouse or a stylus.

I also think we could implement "zoom snapping" so when using the freehand zoom we could snap to certain zoom values determined by those discrete values.

### --Video or Image Reference--
RIGHT: Discrete Zoom (300%)
LEFT: Uneven Zoom (301.5%) this was achieved by painstakingly getting close to the value by moving the mouse freehand.
![image](https://user-images.githubusercontent.com/4912907/33243667-b0bdf068-d2b8-11e7-8028-983efc4328d7.png)

### --Steps to reproduce--
Note: Please repeat these same steps on both versions to understand the difference thoroughly
1) open pencil2D
2) Press CTRL + H to reset the zoom view
3) Press CTRL + UP ARROW / CTRL + DOWN ARROW / Scroll wheel UP / Scroll Wheel Down
4) notice that everytime you use the shortcuts it will go further up or down than the previous value, so you will never get the same zoom value that you previously worked on.

### --System Information--
+ Pencil2D Version:
++ Version: 0.6.0 (Nov 23rd 2017 Nightly Build from Google Drive)
++ November 2nd 2016 Nightly Build
+ Operating System:
Windows 7 (64 bits)

**Comment by J5lx** [comment]
I think caring about UX should be a no-brainer, so I went ahead and made a label for that. Also, valid points you raised there, the zoom in Pencil really is kind of odd.

**Comment by chchwy** [comment]
Now Pencil2D uses fixed zoom levels except high-res scrolling (for example MacOS trackpad)
