### ISSUE TITLE
[Issue] Sound layer isn't working.

### ISSUE THREAD

**Issue by Nicole-Fuzbrain** [pencil2d/pencil#817]
--Issue Summary--
Sound layer isn't working.
 
 --Video or Image Reference--
https://vid.me/3CrGS

--Steps to reproduce--
Pretty sure it's been like this since I downloaded it, so it should do this for everyone.
 
 --System Information--
 Pencil2D Version:
commit: bc68a99ff28373076280a70641da5b8b865c7c61
date: 2017-11-16_11:39:51
 
Operating System:
ubuntu 16.04 lts  32bit
 
RAM Size:
1GB or 1753MB
 
 Graphics Tablet:
Wacom intuos small, CTL-480

**Comment by scribblemaniac** [comment]
FFmpeg information for the version embedded in the 32-bit linux AppImages:
```
ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/i386-linux-gnu --incdir=/usr/include/i386-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv --disable-i686
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Hyper fast Audio and Video encoder
```

**Comment by scribblemaniac** [comment]
Found the issue. Needed to install the `libqt5multimedia5-plugins` package or else the mediaplayer would not load.

@chchwy How do you want to handle this fix? Do we wait until 0.6.1 or create a second version of 0.6.0 for 32-bit linux?

**Comment by chchwy** [comment]
Let's re-upload a new 0.6.0 since the Linux-32bit binary is not really officially out.

**Comment by mapreri** [comment]
wait, you are not going to re-issue a new tag changing the code or the released tarball, right?

**Comment by chchwy** [comment]
According to what @scribblemaniac said, it's not a code issue. so no code change will be made. Just recompile a new binary with a correct package installed.

**Comment by chchwy** [comment]
Hey @Nicole-Fuzbrain 
I've re-uploaded the linux 32bit appimage at
https://github.com/pencil2d/pencil/releases/download/0.6.0/pencil2d-linux-i386-0.6.0.AppImage

Can you confirm whether the sound layer is working or not in this version?

**Comment by chchwy** [comment]
Thanks @scribblemaniac, I'm closing this.
