### ISSUE TITLE
Segmentation fault when quitting after duplicating a sound frame

### ISSUE THREAD

**Issue by scribblemaniac** [pencil2d/pencil#831]
### --Steps to reproduce--
1. Start Pencil2d
2. Import a sound
3. Duplicate the sound on a different frame
4. Quit Pencil2d (doesn't matter if you save)

### --System Information--
+ Pencil2D Version: 0.6.0

+ Operating System: macOS 10.13.1

+ RAM Size: 16 GB

### --For Code Contributors--
The issue appears to have something to do with `~QMediaPlayer()` based off of Apple's crash report, but that's all the useful information I can get from it. The command line output just says that it is a segmentation fault. Currently GDB isn't properly set up on my computer, but if we can't find the issue just by looking at that code then I'll get that working and run a proper backtrace.

**Comment by chchwy** [comment]
Can't replicate on Windows 10

**Comment by scribblemaniac** [comment]
I can't seem to replicate it either on Windows 10 or Ubuntu 16.04. I guess it's a macOS specific issue.

**Comment by CandyFace** [comment]
I can't seem to replicate this either on Mac OS 10.12.6

does it happen consistently?

**Comment by scribblemaniac** [comment]
I can replicate it consistently in 0.6.0, but it seems to be "fixed" in nightly. Probably the change how frames are duplicated either fixed this or hid it.
