### ISSUE TITLE
great job love the new pencil the issues ive noticed are-the fill bucket leaves areas unpainted.the auto save saves constantly.the export doesnt size the animation right.and how do you get the grey bars to go from the drawing area cheers

### ISSUE THREAD

**Issue by fairz01** [pencil2d/pencil#842]
### --System Information--
+ Pencil2D Version:

+ Operating System:

+ RAM Size:

+ Graphics Tablet:

---

**Comment by Jose-Moreno** [comment]
@fairz01 Hi. First of all next time please put the issues on the description not on the title of the report...

Now. Let me answer in order:

1) Fill Bucket is currently a work in progress. Even in comercial software it filling algorithms will leave spaces open. You have to either a) use lines without antialias (soft outlines) or b) use the threshold slider to fill inside out.

2) The autosave works as expected, if you want to change the frequency in which your file is autosaved go to edit > preferences > files > autosave documents > Number of modifications, and put a high number like 96. Or conversely disable the autosave.

3) The export size is provided by the camera size. To change the camera size you have to double click on the camera layer and input the "viewfinder" size which will be the same as the video output

4) I don't understand what you mean about "the grey bars", but I suppose you mean the camera "passepartout" or out-of-field grey area. If you don't want to see it, just turn the camera layer OFF, byt clicking on the radial button next to the camera layer name.

Make sure you are using the latest version of Pencil2D. Hope this helps. Cheers.

**Comment by fairz01** [comment]
great help thanks and love the software  

    On Saturday, 30 December 2017 7:55 PM, Morr <notifications@github.com> wrote:
 

 @fairz01 Hi. First of all next time please put the issues on the description not on the title of the report...Now. Let me answer in order:   
   - Fill Bucket is currently a work in progress. Even in comercial software it filling algorithms will leave spaces open. You have to either a) use lines without antialias (soft outlines) or b) use the threshold slider to fill inside out.
   - The autosave works as expected, if you want to change the frequency in which your file is autosaved go to edit > preferences > files > autosave documents > Number of modifications, and put a high number like 96. Or conversely disable the autosave.
   - The export size is provided by the camera size. To change the camera size you have to double click on the camera layer and input the "viewfinder" size which will be the same as the video output
   - I don't understand what you mean about "the grey bars", but I suppose you mean the camera "passepartout" or out-of-field grey area. If you don't want to see it, just turn the camera layer OFF, byt clicking on the radial button next to the camera layer name.
Make sure you are using the latest version of Pencil2D. Hope this helps. Cheers.—

**Comment by chchwy** [comment]
Happy to know you like it @fairz01
