### ISSUE TITLE
Timeline Too Short

### ISSUE THREAD

**Issue by infinityglitches** [pencil2d/pencil#846]
The timeline only goes up to 240 frames and wont let me go any further, by that I mean I cant drag that little gray thing past 240 frames, it ends there, please fix this. I have been looking for hours and DAYS trying to find a good 2d animating software and when I found this I was so happy, but now I'm getting a bit angry, please fix ASAP.

Thank You,
infinityglitches

**Comment by chchwy** [comment]
Hey @infinityglitches 

We will add the ability to auto extend timeline in the future.
At the moment, you can change it in preference -> Timeline -> give a number e.g., 999 to resize the timeline length.

**Comment by chchwy** [comment]
Fixed. Please test this in Nightly build 24 Jan 2018
http://pencil2d.github.io/download/#nightlybuild
