### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by richardcookie3232** [pencil2d/pencil#854]
![ezgif-5-0a855d2fef](https://user-images.githubusercontent.com/35379683/34889704-a164d518-f794-11e7-954b-d865ca188444.gif)
Hello:

I am using Pencil2D for the first time, and I just found out that when I press the loop button, it only loops until the penultimate frame, how do I loop it until its entirety?
```
-->

**Comment by scribblemaniac** [comment]
This seems like the same issue as #838, which has been fixed recently. Please try downloading the latest nightly build and let us know if that fixes the issue.

**Comment by richardcookie3232** [comment]
Nevermind, I just activated the range and is already solved, thank you for the suggestion anyway.

**Comment by Jose-Moreno** [comment]
@richardcookie3232 Hi! Just in case you want to download the latest build you can do so by visiting http://pencil2d.github.io/download and in the "Nightly Build" section at the bottom of the page you can pick and choose the most recent development version.

If you need anything else let us know, also we have a discord server in case you require help and are not necessarily reporting a bug:

https://discord.gg/wP7Zdz
