### ISSUE TITLE
[ISSUE] Importing Sequence Images, they are bigger and out of the camera boundareis

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#856]
Self explanatory.

I imported Sequence PGN images from an animation made with Pencil2D some time ago. All images shows to be bigger than the first time I saved them, and they are showed down out of the camera/canvas boundaries

It works OK when Importing the .pclx animation of the same animation

Last build 12JAN2018) win8.1x64bits

**Comment by Jose-Moreno** [comment]
@Kaikogf I'm not exactly sure I understand the issue. Is the camera resolution the same on both files? Or does it change when you import the sequence?

Also when you say you are importing the .pclx you mean you are opening the file?

**Comment by Kaikogf** [comment]
@Jose-Moreno 
You must be the Portal Angel 👍 . You guessed it! I have checked the camera size and it is way bigger than the standard. That alone explains the increase in size of the PNG Images.

I am going to close this comment. Thank you
