### ISSUE TITLE
[BUG] Timeline: Playback head is freezing and lagging after stopping and resuming play

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#860]
### --Issue Summary--
After kaiko reported an issue on this comment https://github.com/pencil2d/pencil/issues/747#issuecomment-357407263 l I tested the second case and managed to reproduce it consistently when using Nightly Build Jan 12th 2018. 

In this report I'll be using a sound track so it's obvious but this behaviour is affecting the animation playback in general with or without sounds. Basically when you play the animation, stop playback and attempt to resume at a later frame, the playback head will freeze for the amount of time you actually skipped forward counted from the first frame (in my test case it was about 4 seconds at 12fps, i stopped roughly at frame 12 and resumed at frame 48 and the lag summed up the whole 48 frames in time before moving again to resume it's playing speed, however since I was using a sound sample I noticed that the sound kept playing in the background but once the sound stops playing since the playback lagged behind it will continue in silence until it reaches the end of the timeline and only then it will stop.

This happens even if you start playing at a later frame for the first time, without playing back form the first frame. It seems also this behaviour resets when the timeline is played back from the beginning.

For some reason the playback broke between december 20th nightly build and Jan 1st nightly, as it is working correctly on the former.

_**Addendum**_: It's also worth mentioning that when you skip forward a few frames or resume the the sound playback the sample will skip a bit, however this seems to come from before release so I'll see If I can make a different bug report for that

### --Expected Results--
Timeline playback should stop and resume without noticeable lag or without enumerating ellapsed time up to the point of resumed playback.

### --Video or Image Reference--
![pencil2d_timeline_error](https://user-images.githubusercontent.com/4912907/34918114-20c6c798-f91c-11e7-9e70-2c01b55f458b.gif)

_props to CandyFace for letting me know about LICEcap!_ :smile: 

### --Steps to reproduce--
Note: Please use an audio sample to fully understand this issue.
1) Open Pencil2D
2) Import a sound sample longer than 100 frames (the bug exists without sound, this is just to help determine where the bug is being produced at)
3) Playback from the first frame; it will play normally
4) Stop and move the playback head to a frame above 50.
5) Press the play button again. Notice the sound will resume but the playback will get stuck and delayed until it moves again looking to reach the end of the sound or timeline, whichever comes first. 

_**Note**_: If you use a chronometer to count how much the head lags behind, you'll notice that the time is equal to the total amount of frames up to the place where you moved the playback. So at 12 FPS, if you moved the playback to resume on frame 60, it will take 5 seconds for the playback to move again, on frame 72, 6 seconds, and so on.

### --System Information--
+ Pencil2D Version:
Version: 0.6.0
Development build (Jan 12th 2018) _Note: we should include the release date as well in this about box, because it's not showing_
Operating System: Windows 7 SP 1 (6.1)
Cpu Architecture: x86_64

**Comment by CandyFace** [comment]
probable regression:
https://github.com/pencil2d/pencil/commit/84304fee1917327c0c59b59fb89d2e5a00f46c0a and https://github.com/pencil2d/pencil/commit/8319cb5e4cb8677a338917b749615544701b0447

**Comment by chchwy** [comment]
Will look at this soon.

**Comment by chchwy** [comment]
Please check this in the 17 Jan 2018 nightly build.
