### ISSUE TITLE
Sound not working.

### ISSUE THREAD

**Issue by infinityglitches** [pencil2d/pencil#861]
I use this animating program for my YouTube Channel I will be making, I know I've already posted 2 bugs, and I don't wanna be that guy who finds bugs in everything but, this is a actual bug.

When i record my voice, and save it to a file, the program cant find the file, like it doesn't exist.

**Comment by Jose-Moreno** [comment]
@infinityglitches It's ok if bugs are found it's best to report them. Thank you for taking the time to do that. Pencil2D only recognizes either .wav or .mp3 sound files. So if your sound file is not of either type P2D won't read it.

**Comment by infinityglitches** [comment]
OK, I will try that, do you have any apps i can use to record, because it doesn't work with Windows Voice Recorder.

**Comment by CandyFace** [comment]
You can use Audacity http://www.audacityteam.org to convert your file to mp3

**Comment by infinityglitches** [comment]
O thx

**Comment by scribblemaniac** [comment]
Actually it's probably easier to convert to a wav with Audacity, since it doesn't come with LAME by default (the library needed to read/write mp3s).

**Comment by infinityglitches** [comment]
Ok

**Comment by infinityglitches** [comment]
Ok, i was messing around with the files and I found a way to convert the file into a mp3, so I'm probably dumb for starting this topic lol.

**Comment by CandyFace** [comment]
No worries. 
Just to be sure, are you able to import the sound file after you've converted to either .wav or mp3?

It would be nice to know, so we can close this issue :)

**Comment by infinityglitches** [comment]
sorry for taking lots of time, uhh yeah the sound works.

**Comment by chchwy** [comment]
Cool @infinityglitches. I'm closing this issue.
