### ISSUE TITLE
help..

### ISSUE THREAD

**Issue by infinityglitches** [pencil2d/pencil#865]
yeah so i just loaded up my animation, its all gone, like when you load up the animation its just like if it were a brand new one.

**Comment by chchwy** [comment]
Hi @infinityglitches 
1. Please upload the project so we can have a look at it. I can't do anything if you just said "help".
2. Go to `C:\Users\YOUR_NAME\AppData\Local\Temp\Pencil2D`, a couple of folders `[PROJECT].Y2xD` should be there, go into one of these folders and open the `data` folder, if you're lucky you will find your works.

**Comment by infinityglitches** [comment]
Hello @chchwy 

I cant find my project.

**Comment by CandyFace** [comment]
If your project doesn't exist or you've overwritten it or anything similar to navigating in windows, then it's not an issue about pencil2d anymore. Unless you find the project and upload it for further investigation (if it's broken), it's pretty much impossible for us to help you properly.

**Comment by infinityglitches** [comment]
@CandyFace Ok thanks.

**Comment by chchwy** [comment]
Closing due to lack of information
