### ISSUE TITLE
Infinate Timeline

### ISSUE THREAD

**Issue by TurbsUP** [pencil2d/pencil#868]
So the timeline is infinate, but i cant see it all i can make frames but i cant move the bar far enough to see my animation. i just wanna  make a long one

**Comment by CandyFace** [comment]
Hi TurbsUP

You can change the timeline length by going to preferences -> timeline and set timeline size in frames.

**Comment by Jose-Moreno** [comment]
@TurbsUP Hey. Well honestly the timeline is not infinite. I can have up to 9999 frames. However the more frames you have the more RAM your computer will demand. Having up to 1000 frames is actually a stressful task for any computer, so if you really want to make a long animation I suggest you read these woe prevention tips on our FAQ when working on Pencil2D with longer animation:

http://pencil2d.github.io/doc/faq.html#pencil-crashed-and-my-files-are-unusable--corrupted

Also the answer below that will tell you how to extend the timeline.

**Comment by chchwy** [comment]
Please test this issue in Nightly build 24 Jan 2018
http://pencil2d.github.io/download/#nightlybuild
