### ISSUE TITLE
Losing all of an animation data while saving.

### ISSUE THREAD

**Issue by oliveirafre** [pencil2d/pencil#873]
I don't know why this append but recently i saved an animation I just drew 500 frames on it when I tried saving it stoped responding...then when it finally started to respond again and finished saving I closed it I tough everything was fine and that it was just windows 10 fucking with me.
Today I tried opening the file every layers were there,every frames were there but everything was empty just empty all white...
Is their any way to fix this or is this new...

**Comment by chchwy** [comment]
Hi @oliveirafre 

Sorry to hear that.
Here are some ways you can try to recover your work:

First, a pencil2d project is actually a zip file. So rename the file from `XXX.pclx` to `XXX.zip` and unzip it, and take a look at what's left inside (most of the frames should be in `data` folder after you unzip it).

Second, recovering from the temporary workspace:

1. Open File Explorer, in the Folder Address Bar, enter: `%temp%` to go to the temporary files folder.
2. Look for a `Pencil2D` folder. Enter the Folder.
3. A couple of folders name `[PROJECT].Y2xD` should be there, go into one of the folders and open the `data` folder, see what's left inside.

And the last step, upload your file (via Dropbox or Google drive etc.) so our developers can take a look at it.

I would recommend you to backup your project next time. Although we try our best to make it more stable, the software will not be always 100% crash-free. Good luck!

**Comment by Jose-Moreno** [comment]
Depending on the circumstances of the OP, this issue should have been fixed by https://github.com/pencil2d/pencil/pull/1012 or the repercussions of a crash should be addressed by the recent https://github.com/pencil2d/pencil/pull/1436 however we never got additional feedback after 2 years. Closing.
