### ISSUE TITLE
Not working well after saving file

### ISSUE THREAD

**Issue by Lnoj** [pencil2d/pencil#884]
### --Issue Summary--
The program was working fine until after I saved it. Then every so often, when I tried to do simple things (like duplicating a slide) it would stop me from working and act like it was trying to process what I was doing. If I tried to do anything, it would crash with my unsaved work, so I have to wait for it. It still works it just takes a lot longer.

### --Actual Results--
 Sometimes it takes a minute to process what I did for some reason, and won't let me do anything else until it's done.

### --Expected Results--
When I try to do something like duplicate a slide, it should work the same every time.

### --Steps to reproduce--
It only started happening after I saved my work for the first time. Usually it happens when I do things like saving, and duplicating a bunch of slides 

### --System Information--
+ Pencil2D Version:
 v0.6

+ Operating System:
 Windows10

+ RAM Size:
 43.7MB

+ Graphics Tablet:
 I don't think it matters, but I have a huion 

---

**Comment by chchwy** [comment]
Hi @Lnoj 

I guessed the **processing things** is a feature called auto-saving.
It will save the file every 25 strokes by default to prevent users losing their works.

You can change the settings in **Preference->Files**, increase the auto-saving steps to a larger number like 100, or just disable it if you don't like it.
