### ISSUE TITLE
Missing Toolbar

### ISSUE THREAD

**Issue by Matt697799** [pencil2d/pencil#897]
My toolbar went missing and I dont know how to get it back

**Comment by Jose-Moreno** [comment]
@Matt697799 Please try the following:

1) Go to menu **Windows > Tools** to enable it. Or press Ctrl + 1 on your keyboard.
2) If the previous doesn't work make sure you have all of them enabled and then go to menu **View > Reset Windows**

If this still brings not solution we might be able to try something else depending on your current Operating System, so make sure to try those options first and let us know later on which OS you are using to see if we can attempt to reset the windows in a different way.

**Comment by Matt697799** [comment]
Thanks That helped
