### ISSUE TITLE
A quite annoying crash issue.

### ISSUE THREAD

**Issue by JmeBoo** [pencil2d/pencil#902]
### --Issue Summary--

Pencil2D crashes without an error report and without saving literally out of the blue.
### --Actual Results--

Pencil2D is literally the best animation thing I have ever found. the only thing I dislike about it is this random crash it has been doing every time I use it.
I would have posted this issue report a few years ago if I knew how to post one back then. (sorry)
### --Expected Results--

basically I draw the frames and everything looks like its going well and then I click on a tool instead of using the shortcut for it and it just closes the whole thing as if it thought I clicked the X or something.
### --Steps to reproduce--

go about drawing the frames.  have about 3 bitmap layers open and the other default layers. use only shortcuts for a while and then when you're about 10 or 20 minutes into making something use your mouse or pen to click on one or two of the tools. for me it usually crashes on the pencil and brush tools.
also I dont really know if this will even repeat the issue successfully I just know thats what causes it for me.
### --System Information--
+ Pencil2D Version:

v0.6.0
+ Operating System:

Windows7
+ RAM Size:

8GB
+ Graphics Tablet:

HuionWH1409 wireless

**Comment by Kaikogf** [comment]
Pencil version 28March2018

I have tried to catch this bug following the indications given by @JmeBoo, but Pencil2D worked fine.

Since this post has a months, I think the bug is no longer present. 
@JmeBoo you may download the last version of Pencil2D to check if everything is working fine with no crash. Last build version (28March)

**Comment by Jose-Moreno** [comment]
@JmeBoo Sorry to hear about your issue, it's been a while and Pencil2D has been updated a few times, so I've come to ask you if you can use the latest development build and confirm if this still happens for you or not so we can continue to investigate this problem. I personally also have Windows 7 and I'm not having crashes so If possible please test it out http://pencil2d.org/download#nightlybuild

**Comment by JmeBoo** [comment]
I just spent about half an hour testing the newest nightlybuild of it and it hasnt had the crash happen yet, so Epicness! :D 
thanks a bunch!

**Comment by Jose-Moreno** [comment]
**Closing**
---
_**Reason**_
OP hasn't reported abnormalities with the provided nightly build for 20+ days.
