### ISSUE TITLE
Can't open saved animation

### ISSUE THREAD

**Issue by PessimistDoggo** [pencil2d/pencil#906]
### --Issue Summary--
I'm trying to open an animation that I made in Pencil, but it won't open.

### --Actual Results--
Every time I attempt to open the file it comes up with the message "Pencil cannot read this file. If you want to import images, use the import command." The animation is about 80-90 frames long with a 9 MB sound file. I only have two layers, one for sound and one for the drawings. I'm about to cry because I need to finish that ASAP but then I basically just lost it all.

### --Steps to reproduce--
I've tried opening the file in the 'Open Recent' thing and trying to open it manually, but the same thing happens every time. It should be noted that immediately after saving the animation, Pencil crashed. But I did make a second super short test animation afterward, and it opened just fine.

### --System Information--
+ Pencil2D Version: 0.6.0

+ Operating System: Windows 10

+ Graphics Tablet: Wacom Intuos Pen & Touch Tablet

**Comment by chchwy** [comment]
Hi @PessimistDoggo 
Could you please upload your project so that we can take a look at it?

**Comment by PessimistDoggo** [comment]
The file saved as a .pclx file, and I tried uploading it, but I got the message 'We don't support that file type.'

**Comment by chchwy** [comment]
Please zip it before uploading it, or use other online storages like Google
drive, Dropbox and put the link here.

**Comment by PessimistDoggo** [comment]
https://drive.google.com/file/d/1I1sqvUs4Waei1ff9ZpB_2HVLGMEIH4Nh/view?usp=sharing
Here you go!

**Comment by chchwy** [comment]
Hi @PessimistDoggo 
Please find you project here:
https://www.dropbox.com/s/3dj1pwtwdqvnlbs/politics%20S%20U%20C%20K.pclx?dl=0

The frames are more or less off-center due to information lost but most of your work are still there.

**Comment by PessimistDoggo** [comment]
Thank you so much!!
