### ISSUE TITLE
File Leaking

### ISSUE THREAD

**Issue by scribblemaniac** [pencil2d/pencil#907]
### --Issue Summary--
Sometimes, data from other projects is found inside pclx files.

### --Actual Results--
When investigating the contents of some pclx files, I have found images and sounds from unrelated projects. Normally I would think this is just a case of something not getting cleaned up when loading or creating a new project, however these files are from projects that were not even loaded during the same instance of the Pencil2D process in which the problem file was created! This is not super high priority because these files don't actually appear in loaded animation, but it could slow down saving, increase file sizes, and has minor privacy concerns when sharing pclx files. Given the many saving issues lately, perhaps tracking this issue down might solve a bigger problem as well.

### --Expected Results--
A pclx file should only contain images from its own project obviously.

### --Steps to reproduce--
This is how to reproduce the issue with sound. I have not figured out a way to reproduce this issue with image sequences, although it is possible since it has happened to me before.
1. Open Pencil2D
2. Import a sound on a new layer (wav or mp3)
3. Quit Pencil2D without saving
4. Open Pencil2D again
5. Save the new project as a pclx

If you then unzip that pclx, you will find the sound you imported in the data folder.

### --System Information--
+ Pencil2D Version: 0.6.0 and Nightly Build Febuary 28th (a1825f75a5af6ac273af7c9794d6ffc66b5f12d5)

+ Operating System:
macOS 10.13

+ RAM Size:
16 GB

+ Graphics Tablet:
N/A

**Comment by chchwy** [comment]
I've been aware of this issue for a while because we don't delete audio files when removing a sound key.
But removing the file right after deleting a key may not a good thing for undo.

I'm thinking to make a whitelist of the files that must be included in zip instead of zipping the whole working folder.

**Comment by CandyFace** [comment]
Can't we just clean the work folder when exiting pencil2D and make sure a the work folder is clean when making a new project? I agree that deleting the audio file might not be good a good idea since the undo/redo system depends on the file being in the work folder.

**Comment by chchwy** [comment]
Now I'm making a whitelist for zipping rather than zip the whole temp working folder. It will zip only the files which are used in the current project. It should fix the file leaking issue.
