### ISSUE TITLE
Value of stabiliser option is not preserved across program restarts

### ISSUE THREAD

**Issue by J5lx** [pencil2d/pencil#908]
### --Issue Summary--
Unlike other tool options such as brush size or pressure, the value of the stabiliser setting is not preserved across program restarts.

### --Actual Results--
The stabiliser option is always set to “None” when the program starts.

### --Expected Results--
The value of the stabiliser option is saved when quitting the program and restored to its previous value when the program is started again.

### --Steps to reproduce--
1. While a tool with the stabiliser option is selected, change the value of that option to “Simple” or “Strong”.
2. Quit the program and start it again.
3. Observe that the value of the stabiliser option has returned to “None”

### --System Information--
+ Pencil2D Version: Applies to both 0.6.0 and d939c885233addc4b79392bf5783d54876864309
+ Operating System: Arch Linux

---

As reported [on the forum](https://discuss.pencil2d.org/t/notes-from-my-drawing-animation-sessions/2482?u=j5lx)

**Comment by scribblemaniac** [comment]
Related #744

**Comment by CandyFace** [comment]
Fixed in https://github.com/pencil2d/pencil/commit/f1e93c375877f71df6314602989f1df5ba1b0f7b
