### ISSUE TITLE
blank pop up?

### ISSUE THREAD

**Issue by chiara198** [pencil2d/pencil#910]
### --System Information--
+ Pencil2D Version:

+ Operating System:

+ RAM Size:

+ Graphics Tablet:

---

**Comment by chiara198** [comment]
I still don't know how this works so I am submitting a separate comment, basically, this blank popup comes up every few seconds and I don't even have time to draw 6 or 7 lines! it is a lot like the one that tells you to save, but that one has a button that allows you to stop it from popping up again, this one doesn't. it only started after I saved a second project. now that I think about it, I did have to reinstall pencil2d like three times because it "couldn't start properly", or "(insert file name here) couldn't be located)"

**Comment by chchwy** [comment]
Hi @chiara198 
This is a feature called "auto-save", it will save your project every certain number of actions and probably will save your work if pencil2d crashes unexpectedly.

You can increase the number of actions in Preferences or disable it if it annoys you.
The blank pop-up has been fixed, you will see a proper progress bar for saving in the nightly build.

**Comment by Jose-Moreno** [comment]
@chiara198 Hey, don't worry. It's probably the autosave feature. Go to Edit > Preferences > Files > And in the autosave documents section, increase the number of modifications to something above 80.

This means that you will require about 80 actions before the autosave is triggered so it won't bother you.

Let us know if this solves this particular issue, if not please let us know which version of Pencil2d you downloaded and which operating system you are using.

**Comment by chchwy** [comment]
Closing this because the auto-saving progress bar is working.
