### ISSUE TITLE
[ISSUE] Bitmap layer doesn't refresh after deleting the layer

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#920]
### --Actual Results--
Two issues when using bitmap layers

### --Steps to reproduce--
1. Open Pencil2D
2. Use the default bitmap layer already selected and draw some lines with any tool you like, use a red color (just for visualization)
3. **Add** a new bitmap layer
4. Add again another bitmap layer (this step is not necessary though
5. Now **delete** one layer (which means that you are going to delete the first layer with the red lines lines since no other layer was selected). _Use no shortcut keys_
6. **_Result:_** The red lines are still there on the canvas

7. Select another color (blue) and draw some lines on the canvas. When you release the pen the red lines will be covered by a white square surrounding the blue lines and eventually will disappeared in just a few seconds leaving the canvas with blue lines only (not always happens this way)

### --System Information--
+ Pencil2D Version:
Last build 11March2018

+ Operating System:
Windows 8.1 x 64bits

+ RAM Size:
32GB

+ Graphics Tablet:
HUION GT185HD

**Comment by Kaikogf** [comment]
EDITED:

In step "6", if you select another **layer** all the lines on the canvas will disappear. If selecting a **Tool** instead of a layer, all lines will be on the canvas

**Comment by Jose-Moreno** [comment]
Can confirm this issue is still happening in the latest nightly build for June 13th.
