### ISSUE TITLE
Unable to select layer or frame underneath long scrubber

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#921]
I have just noticed that while the scrub indicator on the timeline is long, it will not allow to select a layer or a frame underneath it. 
You just have to make it short or select the frame besides it (for selecting another layer, or just move it else where for selecting a frame

Last build 11March2018

**Comment by Jose-Moreno** [comment]
@Kaikogf If you double click on the scrub indicator, you can shorten it to only display on the frame numbers above the timeline in order to avoid this issue. This works ever since 0.5.4.

**Comment by Kaikogf** [comment]
@Jose-Moreno 
My intention was to give to all here another perceptive of the scrub/timeline thing. 
The point that I wanted to make was that I pictured myself having lots of layers and frames while doing an animation, and the only way I wanted to be precised picking a specific frame was to go directly to it because it was already highlighted by the _Long Scrub Indicator_, and them I would clicked on it, but I realized that that doesn't work. I was just letting developers know if there was an easy way to have the same indicator highlighting all frames along the layers and still being able to allow clicking over it, instead of shorten it
:+1: 

Just a though. Everything is just fine the way it is.

**Comment by Kaikogf** [comment]
I will just wait before I close this issue

**Comment by CandyFace** [comment]
There are couple of ways we could go about this:

a: 
if you select a frame which is behind the scrubber, dragging the frame will also drag the scrubber

b: 
if you select a frame which is behind the scrubber, only move the frame.

c:
Only move the scrubber from the top of the timeline, ie. where the frames indicator is.

**Comment by Kaikogf** [comment]
@CandyFace 
I tested what you mentioned and I wasn't able to do that.

a. b.
Having the long scrub, If selecting a frame and dragging it, it wouldn't drag the frame, just the scrub no matter what. 
Having the scrub long and trying to move/drag a frame behind it it will only affect the scrub. 

By the way, testing this I found a bug, a Runtime Error and Pencil2D crashed. Open a new comment.

I will close this one since everything is working fine. What I presented here was just an idea :+1:

**Comment by CandyFace** [comment]
@Kaikogf I think you've misunderstood my post, what I mentioned were possible solutions of what could be implemented not what is possible currently.

**Comment by Kaikogf** [comment]
Ohhhh... I see.. I am re-opening it

Sorry, didn't understand your comment
:+1:

**Comment by Kaikogf** [comment]
I would get the **_b_** way. 
The scrubber can stay still like working as a reference point, since moving a frame behind it will give us a help of to where it was before (I mean it is of a great help when the timeline is already full with several layers and frames)

**Comment by Jose-Moreno** [comment]
@Kaikogf A method to select the frames under the playhead / scrubber was implemented in https://github.com/pencil2d/pencil/pull/1343 

Now the playhead will become "hollow" when you hover the cursor over it to allow you to select the layers or keyframes below. 
If you click and hold over the playhead and try to drag it on the frame rule or an empty space (no frames or layers below) you can move it normally as usual.

![timeline_hollow_playhead](https://user-images.githubusercontent.com/4912907/146689528-2fd4adb4-8440-4ce7-89e9-8f095ca2f45c.gif)

Closing :v:

**Comment by Kaikogf** [comment]
Well done developers!
