### ISSUE TITLE
[ISSUE] When loading some animations, the translation on the Layers will change to Spanish

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#923]
Having Pencil2D with English language and loading two small sketch animations, it will change their default layers's name (bitmap layer, vector layer, camera layer) to Spanish (capa de bits, capa vectorial, capa de cámara) while the remaining Pencil2D will be unchanged (English)

A very nice catch 
lol

Pencil2D v. 15March2018
Win 8.1 x 64bits/ 32GB/ HUION GT185HD

**Comment by scribblemaniac** [comment]
Thanks for reporting! Can you please tell us what your system language is (what language is used by default for Microsoft applications, menus etc.) and what you have set for the Language preference in the Pencil2D Preferences > General window?

**Comment by chchwy** [comment]
This might not be a bug.

When you save a project, the layer names are saved to `.pclx`, too. And the layer names are in the words of the current UI language.

For example:
1. Launch Pencil2D in Spanish
2. Save the project file (now the Spanish layer names are saved into the pclx)
3. Switch the UI language to English and relaunch Pencil2D.
4. Open the file from step 2. You will see the layer names in Spanish.

If it is the case, it's not a bug.

**Comment by Kaikogf** [comment]
I tested it again and @chchwy is right. It is not a bug and all other different UI language will launch the animation with layers in Spanish
:+1:
