### ISSUE TITLE
Bucket fill tool fills off stage

### ISSUE THREAD

**Issue by TacocaTYT** [pencil2d/pencil#924]
### --Issue Summary--
the bucket tool fills past the white and therefore ignores lines 

### --Actual Results--
I expected the paint bucket to not leave the area in the white box but it does and fills the whole page and i would expect a bucket tool to be constrained by the white canvas section and lines in it. 

### --Expected Results--
I expected it to not leave the white section and also be blocked by my line and not need to be fully boxed in. 

### --Steps to reproduce--
 draw a line through the white part then use the bucket tool on one side of the line 

### --System Information--
+ Pencil2D Version:

+ Operating System:
 windows 10 

+ RAM Size:

+ Graphics Tablet:

---

**Comment by scribblemaniac** [comment]
This issue was fixed in #837, but has not been merged due to some other blocking changes in that PR (and admittedly some bad planning on my part). This should be fixed by the time v0.6.2 is released.

**Comment by Jose-Moreno** [comment]
@TacocaTYT Hi, if you would be so kind, can you test the most recent development build to see if this issue is solved for you now? Thanks

http://www.pencil2d.org/download#nightlybuild

**Comment by TacocaTYT** [comment]
sry I haven't used pencil in like a long time

**Comment by Jose-Moreno** [comment]
**Closing**
--
**Reason**: This no longer happens in the latest versions of Pencil2D as fill has been confined to the camera view boundary. If you'd like to test it out please download the latest version at http://pencil2d.org
