### ISSUE TITLE
Can't export video

### ISSUE THREAD

**Issue by MoMoChan1126** [pencil2d/pencil#927]
### --Issue Summary--
 My Pencil2d doesn't export MP4 or AVI video. Whenever I export my work I still see it works but in the end I can't find the movie in neither destination folder nor the whole computer using search. 

### --System Information--
+ Pencil2D Version:
 0.6.0

+ Operating System:
 Windows10

+ RAM Size:
 4GB

+ Graphics Tablet:
none

---

**Comment by Jose-Moreno** [comment]
@MoMoChan1126 Hi please try to use the latest development version to check if it's an ongoing problem or if it has been fixed already. You can download a suitable version in this link:

http://pencil2d.org/download#nightlybuild

**Comment by MoMoChan1126** [comment]
Oh thank you! The lastest version worked. The camera layer seemed didn't work though but for me it isn't a big deal.

**Comment by Jose-Moreno** [comment]
@MoMoChan1126 Would you mind letting us know how exactly did the camera layer stop working? Im using the latest version and I can move and animate the camera just fine, so we0d like to learn if you have different behaviour to prevent others from having similar problems.

**Comment by MoMoChan1126** [comment]
well at some frames the camera is supposed to move but in the exported video all those frames stay still. Weird thing is that when I ran the demo in the software before exporting everything was completely normal

**Comment by CandyFace** [comment]
@MoMoChan1126 I haven't been able to replicate that behaviour, would you mind uploading your project so we can take a look?

**Comment by Kaikogf** [comment]
Pencil2D v. 28March2018, Win8.1 x64bits

@CandyFace 
I experienced the same behavior _"...the camera is supposed to move but in the exported video all those frames stay still. "_  I commented this issue in our community site [https://github.com/pencil2d/pencil/issues/840]

**Comment by chchwy** [comment]
Closing because the issue has been fixed in the latest nightly build.

**Comment by Jose-Moreno** [comment]
@Kaikogf the problem you mentioned in your last comment for this thread has been solved in the latest nightly build. The camera motion should be preserved now during video and gif export.
