### ISSUE TITLE
[BUG] Pencil2D will show Runtime Error and close

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#930]
Just do as following:

Open Pencil2D
Select the Polyline tool
Check the Bezier box > Pencil will show the error and close

[I checked the nightly build from 15Mar2018 and pencil showed no error]

Pencil v. 28Mar2018

Win8.1 x 64bits
32Gb
Huion tablet

**Comment by Jose-Moreno** [comment]
According to the repro steps, this is a possible duplicate of #885

**Comment by chchwy** [comment]
Fixed in 708d418
