### ISSUE TITLE
[ISSUE] When selecting some of the tools on Tools Panel, the mouse-over effect on the Options Panel will bring the same windows-text

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#931]
**_This issue is only applied when the System-Language is selected to Portuguese-Portugal_**. I haven't tested it with English language

Here is a list of the situations found on the Options Panel [_"Opções"_]:

- There is no mouseover effect on _"Pressão", "Estabilizador", "Bézier", "Anti-serrilamento"_.

- When selecting the Hand, Brush, Polyline, Pen, Eraser and Pencil tools, the mouseover effect will show the same text: _"Ajustar largura da Caneta..."_

- Selecting any tool its size-bar will show the text _"Pencil"_ instead of the name of the tool selected
(I am going to close an issue that I opened recently with this situation and the Eraser tool)

**Comment by Kaikogf** [comment]
@J5lx 
I noticed that in Portuguese (Portugal), those mouse-over texts are in English. 
A think it is all about update the translations

All the rest is OK

**Comment by J5lx** [comment]
Yeah, we’ll just have to wait for those new strings to go through the translation process.
