### ISSUE TITLE
Pencil2D crashes when using SAVE or SAVE AS

### ISSUE THREAD

**Issue by MilesPrunier** [pencil2d/pencil#933]
![error](https://user-images.githubusercontent.com/37989851/38179850-ac491134-35f5-11e8-88af-c51b1d51878c.jpg)
![error](https://user-images.githubusercontent.com/37989851/38179857-be590a96-35f5-11e8-968e-d4b1290148e6.jpg)

### --Issue Summary--

The moment I try to SAVE or SAVE AS, I get a popup informing me "pencil2d.exe has stopped working" and the program crashes.

### --Actual Results--
The program crashes.

### --Expected Results--
I expected to be able to save my project to disk.

### --Steps to reproduce--
I open the program then choose FILE-->SAVE or FILE-->SAVE AS.

### --System Information--
Version:  0.6.0  and "pencil2d-win64-2018-03-15" give the same result.

+ Operating System:
Windows 7 Professional Service Pack 1

+ RAM Size: 8GB

+ Graphics Tablet:

---

**Comment by chchwy** [comment]
Hi @MilesPrunier, If you a DELL laptop or PC, please uninstall the "Dell backup and recovery".

It's a known issue:
https://www.dell.com/community/Productivity-Software/Backup-and-Recovery-causing-applications-using-Qt5-DLLs-to-crash/td-p/4590325

**Comment by MilesPrunier** [comment]
Matt,

That did the trick!

Thanks very much!

-Miles

**Comment by chchwy** [comment]
Happy to know that. :)
