### ISSUE TITLE
[BUG] Runtime Error and crash when dragging a frame and hitting the timeline

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#934]
### --Actual Results--
Pencil2D will crash when selecting and moving/dragging a frame and then hitting the timeline (where the number of frames are)

### --Steps to reproduce--
Open Pencil2D
Open an animation. It must have several frames. I tested with around 100 frames
Go to the middle of the frames and selecting one drag it to another place and leave it there
Now click the timeline. If nothing happens hit it again in a different place. The runtime error will crash Pencil2D

### --System Information--
+ Pencil2D Version: 28Mar2018

+ Operating System:
win 8.1 pro x64bits 32Gb Huion graphic tablet

**Comment by chchwy** [comment]
@Kaikogf I'm not able to replicate this bug in the latest version. mm..

**Comment by Kaikogf** [comment]
@chchwy 

I tested it again and the issue is consistent. But found out that the real issue is related to Pencil2D not being able to load/import all frames on the timeline

Here what I realized. The issue is applied when importing a PCLX animation with more than 33 frames, in my case 37. 
When importing the same animation in PNG ImageSequence (37) the issue is different: all frames/images imported shows to be empty.

I tested build 28Marc2018.


(haven't tested with other formats)

**Comment by Kaikogf** [comment]
![pencil-crashing-dragging-frame](https://user-images.githubusercontent.com/28032931/38769830-253dd4e8-4001-11e8-9a1d-5358aed95ebd.gif)

**Comment by Jose-Moreno** [comment]
@Kaikogf can you test if you still have this issue with the latest nightly build from June 13th? try not to build from QT but download it from the web.

**Comment by Kaikogf** [comment]
@Jose-Moreno 

Tested with version 20Jun2018 and it is working fine!
:+1:
