### ISSUE TITLE
Display frame counter on canvas

### ISSUE THREAD

**Issue by CandyFace** [pencil2d/pencil#935]
Something like maybe:

![counter](https://user-images.githubusercontent.com/1045397/38203799-b484de9a-36a0-11e8-88c3-51552eff4824.gif)

although I have no idea what the two other counters are... it seemingly looks like seconds and milliseconds but it restarts at 30...

edit: as clarified by @Jose-Moreno below:
> It stands for: total frames [per cut] ( seconds : frames every second)

**Comment by Jose-Moreno** [comment]
It stands for: total frames [per cut] ( seconds : frames every second)

This looks cool. Normally this is used in japan and sometimes in france (when co-producing with asia) but normally timecode is more universal in the way after effects handles it which is akin to video production: hh:mm:ss:ff (hours, minutes, seconds, frames every second) vs total elapsed frames 0000.

I think the suggestion you propose could be a toggle displayed on the canvas, while the other one could be always visible on the timeline as is traditional for video compositing and editing software.

**Comment by CandyFace** [comment]
@Jose-Moreno Ah riiight.. yes of course!

Yes it would indeed be a toggle.

**Comment by Jose-Moreno** [comment]
I'd like to add that this should be an on-screen time counter, preferably having adjustable display templates according to different systems i.e SMPTE timecode (HH:MM:SS:FF) as well as animation production time counters such as the one displayed in the original message.

Ideally the system should only count in frames and convert that to the specific display template such as:
- [ ] Pure frame counter
- [ ] Animation SS:FF frame counter
- [ ] SMPTE time counter
- [ ] Other

For more info please take a look at these links: 
- https://blog.frame.io/2017/07/17/timecode-and-frame-rates/

If anyone knows about more display templates please comment, but ideally whoever implements this please allow for an easy way to expand the visualization while using the same underlying system.

**Comment by scribblemaniac** [comment]
Additionally, this feature should be optional and easily disabled/enabled in the preferences (and possibly modified for the format as previously discussed).

**Comment by Jose-Moreno** [comment]
Implemented via #1423
