### ISSUE TITLE
[ISSUE] When Importing PNG ImageSequence the last frames are not imported

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#941]
When Importing a specific number of PNG images (37 to be precised), the last three images are not imported into the timeline. This is a consistence issue

If the number of images is bellow 30 (more or less) all images are imported correctly. When the total is above 32 (more or less) all images are imported empty (blank frames)

(haven't tested with other format files)

Pencil2D version 28Marc2018

Win8.1x64bits

**Comment by Kaikogf** [comment]
![pencil-not-loading-all-images](https://user-images.githubusercontent.com/28032931/38769651-433f2a6c-3ffe-11e8-8819-fa758d565bb4.gif)

**Comment by Kaikogf** [comment]
The issue is from last build 11Apr2018

**Comment by CandyFace** [comment]
Hmm I can't replicate this behaviour.. although it's likely that some of your last files have different extension or something. I looked at the code and we check for extensions when importing but don't fire an error if it doesn't exist, we just continue. Looking at your gif the bar stops before it completes, making me suspicious that some files are simply being ignored.

@Kaikogf could you please try to compile this branch and see if it fixes the problem?
https://github.com/pencil2d/pencil/pull/948

**Comment by Kaikogf** [comment]
@Jose-Moreno 
The issue remains doing what you suggested. I even selected the same images but randomly to check the result and it showed that Pencil behaves the same when doing so. What is of importance is the total number of images selected.

@CandyFace 
Since you are not able to replicate this issue (nor @Jose-Moreno) I am starting to think that the real problem might be the build I got from Qt Creator ?, if that could be possible ... 
Anyway, I compiled the new code (15Apr2018) but the same issue remains. It is consistence though in the way that the import ImageSequence is limited to around 30 images...

**Comment by Kaikogf** [comment]
A note: 
I played a lot with this thing of importing 37 sequence images...

Sometimes Pencil would import 34 images and the animation was playing OK. Sometimes it would import only 32 images with no animation (blank frames). At the end Pencil2D will consistently allow to import correctly around 30 images as a total.

**Comment by scribblemaniac** [comment]
@Kaikogf I can't replicate this issue either with images the same size and type as you describe. Is it possible for you to upload a zip of the image sequence you are using to reproduce this to mega.nz, dropbox, google drive or any other service you consider and post the direct link in a reply? If you want you can send it privately to pencil2danimation (at) gmail.com. This might help us replicate your issue and eventually fix it.

**Comment by Kaikogf** [comment]
@scribblemaniac 

I tested the same animation with the last version (20Jun2018) and everything is working fine. All frames are imported to the timeline and the animation is playing OK.

Sorry for the late reply.

I am closing this. Thank you
