### ISSUE TITLE
[UI] Show a "Remove Color Swatch" Button on the Color Palette UI

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#942]
### --Issue Summary--
Currently there's only an "add swatch button", so organizing custom palettes for different projects is really cumbersome.

### --Video or Image Reference--
![image](https://user-images.githubusercontent.com/4912907/38764370-194775ec-3f73-11e8-97bd-791e890a1312.png)

**Comment by CandyFace** [comment]
So i've started working on this: the implementation will be as following:

One can:
* delete a color using the delete button
* Select multiple colors to be deleted, by dragging or holding the equivalent button on the keyboard to select multiple 
![soon](https://user-images.githubusercontent.com/1045397/39959245-323f1700-560f-11e8-864a-58d9f9188842.gif)

* right-click where as a context-menu will appear with three options:
![screen shot 2018-05-12 at 18 05 40](https://user-images.githubusercontent.com/1045397/39959233-1d41f57a-560f-11e8-87d3-e1c576603cb4.png)

This goes into a bigger implementation of making the color palette static, as in not connected to strokes or anything, and adding a new window to keep track of "connected" colors for the vector layer. 
You can read more about my proposal here #962

**Comment by Kaikogf** [comment]
Very must have implementation
:+1:

**Comment by CandyFace** [comment]
Implemented and available in latest nightly build, closing.

**Comment by Jose-Moreno** [comment]
It's working well. Good job! :slightly_smiling_face:
