### ISSUE TITLE
[BUG] First color swatch not updating properly on different scenarios

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#943]
### --Issue Summary--
First swatch of color palette does not update when changing the color while using the color wheel.
### --Actual Results--
On a vector layer, the first color swatch updates on the canvas when you click a different swatch, or if you change the color first and draw a new stroke with the same swatch, it will update only after you draw again, however the thumbnail does not update in either case.

**25-SEP-2018**: There was an issue that I failed to report at first. When you use another swatch and then switch back to the first swatch in the list, the color value from the previous swatch is assigned to the first swatch.

**Note**: Considering the new palette workflow that has been implemented through the "replace" command allowing the swatches to be replaced only by user choice, a few scenarios for this issue were removed from description.

### --Expected Results--
The first swatch and any other swatch should update properly after being selected and changing the color through the wheel.

**Bitmap Layer: First swatch**
- [x] Fix: Swatch color value update (Replace only) (_03/06/2019 - The fix is only partial, the replace command only changes the swatch thumbnail but not the RGB value_)
- [x] Fix: Swatch is assigned color value from last selected swatch

**Vector Layer: First swatch**
- [x] Fix: Swatch color value update (Replace only)
- [x] Fix: Swatch is assigned color value from last selected swatch
- [x] Fix: Swatch color should not update on canvas drawing (Replace only)
- [x] Fix: Swatch color should not update after using the color wheel (Replace only)

### --Video or Image Reference--
_Note: The video outlines the original issue for the vector layer before the palette workflow changed. This issue has been reviewed with 0.6.2 and thus the checkboxes above have been updated to consider this new workflow_
https://www.youtube.com/watch?v=i3MagndT1P8&feature=youtu.be

### --Steps to reproduce--
Please take a look at the video for one of the main tests and it's steps.

### --System Information--
+ Pencil2D Version:
Version: 0.6.1
commit: 708d418f7982b95bd553add78882ac565c636e59
date: 2018-04-02_20:38:44
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by Jose-Moreno** [comment]
_**Update 03/06/2019**_

With 0.6.4 one of the tasks for this bug was fixed for the bitmap layer. Switching between swatches It no longer brings the color value from the last selected swatch.

However in the first task, the fix is only partial, the replace command only changes the swatch thumbnail but not the RGB value, so after you switch the old value remains)

**Comment by J5lx** [comment]
@Jose-Moreno Can this be closed now that #1265 has been merged? As far as I can tell all the scenarios have now been addressed, but I’m also not quite sure if I understand all of them correctly.

**Comment by Jose-Moreno** [comment]
@J5lx I'll test the issues and reproduction steps again and close accordingly depending on the expected results. Thank you for your reminder.

**Comment by Jose-Moreno** [comment]
Alright this has been tested on 

```
Nightly Build Aug 18 2022

commit: 8a2feec15536175c4f656743d794aa8c609953e3
date: 2022-08-18_17:26:43

Operating System: Windows 10 Version 2009
CPU Architecture: x86_64
Qt Version: 5.15.2

```

It's working as expected and the 6 tasks have been solved from what I can see, great work! I'm closing this now as solved.
