### ISSUE TITLE
[Request] Allow to re-order color swatches in either list or grid mode

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#944]
### --Issue Summary--
With the idea of customizing swatches to export them later and be re-used by other project members in any production, this is another important behavior for creating custom palettes from your color model.

Ideally you should just be able to click select & drag any swatch to change it's default order.

If the color palette has some sort of absolute index (similar to what layers had) it might be wise to think ahead and also re-issue the index once the move / re-order operation is completed.

**Comment by Jose-Moreno** [comment]
@davidlamhauge Weren't you working on this as well? if you were can you please assign yourself to it? thanks in advance :slightly_smiling_face:

**Comment by davidlamhauge** [comment]
Done.
I think it was talking to @CandyFace one day, that made me aware that the swatches could become draggable. How it escaped my mind that there was an open issue, I don't know. 
Thanks for pointing it out @Jose-Moreno . The PR is on it's way...
