### ISSUE TITLE
[Request] Implement Range Export Feature for Image Sequences

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#951]
### --Issue Summary--
Currently only the movie export has the "range" feature that allows you to export from and to a specific frame. It would make sense to have the ability to export a certain range of frames as an image sequence for people that can't seem to export the whole timeline as a video or as individual images.

**Comment by CandyFace** [comment]
Implemented in PR #997

**Comment by CandyFace** [comment]
Will be available in next nightly build.
