### ISSUE TITLE
it gives me an error while i try to save

### ISSUE THREAD

**Issue by Stefan1233456** [pencil2d/pencil#956]
it loads normally and when its at 100% it says:"an internal error accured your file may not be saved

**Comment by CandyFace** [comment]
Hi @Stefan1233456 

Sorry to hear you're having problems, we'll need more information than that though if we are to help you or get anything from this report.

Please fill out the template if possible next time as it makes everything easier on our side.

- What version of Pencil2D are you using? 
  + you can find this information by starting pencil2D and going to help -> about us or Pencil2D ->about us on mac.

- How big is your project? ie. frames, camera size etc...
- What operation system are you using?
- did you download the 32bit or 64bit?

It sounds like a problem we've seen before though, the main xml file which stores all information about your project might have been deleted for some reason... 
You can verify this by going to the temp folder mentioned below and try to find your project, then look for a main.xml file, if it's not there, then you'll have to setup the project again. Your frames may still be there though.

> WINDOWS:
> a) In the Start Menu, go to System, or open a folder
> b) In the Folder Address Bar enter: %temp% to go to the temporary files folder
> c) Look for a Pencil2D folder. Enter the Folder. Organize the files by “last modified”
> d) Look for a folder with the name of your saved file and Y2XD extension. e.g MyFile.Y2xD
> d-2) If you hadn’t saved, look for a folder called “Default.Y2XD”
> e) enter the data folder and verify if there is any image inside.
> f) make a copy of this folder on your desktop or a preferred folder to at least save some of your images.
> 
> MACOSX
> 
> a) In the Finder Menu, under GO choose “Go to Folder” you can also use the shortcut: Shift + CMD + G.
> b) In the Go To Folder dialog box enter: ~/Library/Caches.
> c) Look for a Pencil2D folder. Enter the Folder. Organize the files by “last modified”
> d) Look for a folder with the name of your saved file.
> d2) If you hadn’t saved, look for a folder called “Default”
> e) make a copy of this folder on your desktop or a preferred folder.

**Comment by Alinuxnorway** [comment]
Guys, github is something i dont have time to learn. But issue is with PENCIL program, where Importing .mp3 file to pencil = deletes it from your hard-disk =( 
If that mentioned, can be saved as a issue on github. Please do so. Because deleting files is a big issue.

Good luck

**Comment by chchwy** [comment]
Hi @Alinuxnorway Please at least tell us what version you are using and your operating system.

Pencil2D has heaps of fixes in the past a few months, I believe deleting audio files is one of these. So your information could help us to identify it's a new issue or not, cheers.

**Comment by Jose-Moreno** [comment]
@Stefan1233456 Hey. Today a new development build was made with a fix for this problem. If you don't mind could you test it out with a disposable file and let us know if this has been fixed for you or not? Visit http://pencil2d.org/download#nightlybuild and look for the June 5th 2018 nightly build.

**Comment by KaeAnimates** [comment]
I have the same problem as Stefan. Please help me I don't want to lose my project. My version of Pencil2D is 0.6.1.1 but I don't know how big my project is. I'm pretty new to Pencil2D. My Edition is Windows 10 Home and my Version is 1803. My operating system is 64-bit and that is the one I downloaded. Do you need more information than that?

**Comment by chchwy** [comment]
Hey @KaeAnimates 
Please download the nightly build 3 July 2018 and try again:
https://www.pencil2d.org/download/#nightlybuild

**Comment by Jose-Moreno** [comment]
@KaeAnimates Along with what chchwy suggested, if your pencil2d file is still open try to go to the windows 10 temp folder and look for the pencil2d folder in there, then look for a folder called Default.Y2xD and copy the "main.xml" file and the data folder to a different location before closing the program.

![image](https://user-images.githubusercontent.com/4912907/42251389-a3e5eeea-7efc-11e8-8e24-58116b4f227b.png)

If you managed to salvage those files after trying to save do the following:
1) Take the data folder and the xml file and zip them together with WinZip or other zip file manager you use.
2) On the newly created ZIP file, change the .zip file extension to a .pclx extension 
3) Try to open the newly created pclx with the newer development version chchwy linked in the previous comment. 

If you had already closed your file after the error then I'm afraid any changes you made during the work session have been lost, but hopefully this new version will fix this saveing bug for any future issues. If it doesn't PLEASE report back and let us know so developers can continue to look for a solution.

**Comment by KaeAnimates** [comment]
Thanks! I downloaded and opened the Nightly Build July 3, 2018 version, then copied the main and data files and zipped them, but how do I change the zipped folder to a .pclx instead of a .zip?

**Comment by Jose-Moreno** [comment]
@KaeAnimates Please follow this guide to show file extensions in windows. After that it's just a matter of changing the file extension to that of pclx.

https://www.thewindowsclub.com/show-file-extensions-in-windows

**Comment by KaeAnimates** [comment]
I changed the file extension and saving works perfectly now! Thanks so much! You two were really helpful. I appreciate it!

**Comment by Jose-Moreno** [comment]
@Stefan1233456 Hi, there's been a new fix implemented for the save file bug, if you can please test it and if the problem has been solved for you please let us know and close this issue:

Download the nightly build for July 3rd 2018 here:
https://www.pencil2d.org/download/#nightlybuild

**Comment by Jose-Moreno** [comment]
While this is a duplicate issue of what was an ongoing problem at that time, the original user never replied with feedback after a potential fix was issued 2 years ago. Closing.
