### ISSUE TITLE
[Bug] Bundled FFMPEG version causing issues for video export in OSX

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#959]
### --Issue Summary--
A fellow user had this issue while exporting a GIF. He was using v0.6.1.1 from the downloads page. Upon our suggestion he also used the latest Nightly Build available, bearing the same results.

It seems from version 0.6.1 onwards there's an issue where FFMPEG stops processing / outputting frames after a while. As @CandyFace investigated it seems the bunbled version of FFMPEG is too old (3.2.4). After some testing the problem was fixed with a newer version of FFMPEG.

It also seems this is an OS specific issue with that version since testing on Windows 7 didn't produce the error.

### --Steps to reproduce-- 
1) Get an animation with more than 100 frames to see the problem clearly
2) Export it as a GIF
3) Notice how the animation output stops around 2 seconds.

### --System Information--
+ Pencil2D Version:
Version: 0.6.1.1 Stable + 2018-04-27_13:17:37 Development Build
+ Operating System:
MAC OSX 10.13
+ RAM Size:
4GB

**Comment by chchwy** [comment]
Please test with nightly build 5 June 2018

**Comment by Jose-Moreno** [comment]
@CandyFace could you test if this continues to happen? I don't have a mac so I can't test it :slightly_frowning_face:
