### ISSUE TITLE
[Bug] Camera motion not working on exported video in latest version

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#960]
### --Issue Summary--
Thanks to a user report we found that the current stable maintenance release is having problems when exporting camera motion interpolation. Apparently neither VIDEO (MP4, AVI) nor GIF filetypes are getting the camera motion into the final file. However exporting an image sequence will treat the camera motion correctly.

Also tried updating the FFMPEG build, but it behaved the same.

### --Expected Results--
Camera motion should appear seamlessly in any filetype the user choose to export as.

### --Video or Image Reference--
(Artwork by Imperaxum)
**Normal GIF exported from Pencil2D project **
![image](https://user-images.githubusercontent.com/4912907/39849840-f6a986b8-53d3-11e8-825e-9242b3e74ed7.png)

**Image Sequence exported from and turned into GIF inside Pencil2D**
![image](https://user-images.githubusercontent.com/4912907/39849878-260b75ce-53d4-11e8-9abf-89337846f378.png)

### --Steps to reproduce--
1) Open an animation with camera motion
2) Export a movie with any filetype. For my test I used MP4 and GIF
3) Notice that the camera motion is not there
4) Export an image sequence and put it together either in Pencil2D or a video editor of your choice
5) The camera motion is exported with Image sequences.

### --System Information--
+ Pencil2D Version:
Version: 0.6.1.1
commit: 827cddb1d1bf59378d65629dfeae0487f79cddcd
date: 2018-04-27_13:17:37
Development build
Operating System: Windows 7 SP 1 (6.1) / Original User Report OS: Windows 10
CPU Architecture: x86_64

**Comment by chchwy** [comment]
Fixed in nightly build 21 May
