### ISSUE TITLE
PCL import file bug?

### ISSUE THREAD

**Issue by marcello257** [pencil2d/pencil#97]
The PCL file of my storyboard animation, is not recognized by pencil . when i want to import it again?

I tried many options, but nothing works?..

By the way:

GREAT that Matt chchwy is put so much effort and time to make Pencil a great freeware animation tool!

You make the world a little bit better!

Thanks for it!

**Comment by Jose-Moreno** [comment]
@chchwy Was this a bug then? I don't know the details, but judging by the words "broken file" and how the OP described the file size makes me think this might have been related to the fact that PCL files MUST be accompanied by a folder that holds the images. 

I've given support to other users on tumblr with similar claims and It all relates to how they don't know that when you create a pencil .PCL file, it also creates a folder with the name "_folderName.pcl.data_" that holds the actual individual images that pencil requires to reconstruct the animation in the timeline.

If this was never possible to investigate, or if it was fixed I suggest we close it. :+1:

**Comment by Jose-Moreno** [comment]
@chchwy @CandyFace Bump. We should close this as it's impossible to know what was the problem to start with. It must be related to the elusive crash-wipe bug from 0.5.4 dev

**Comment by CandyFace** [comment]
Since we never got the source file, I agree. Closing.

If it's still a problem in the newest nightly build, please make a new issue and fill out as much relevant information as possible.
