### ISSUE TITLE
[BUG] Selection transform proportional re-size not working with modifier [shift] key(s)

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#973]
### --Issue Summary--
Hey so, yeah, basically the title. When showing the resizing function I tried to constraint it and it didn't work in the latest Nightly Build. I assume there has to be a regression implemented for it to work since it was working before (0.6.1 at least). Currently using the shift key only affects it's positioning to be constrained to the X or Y axis.

### --Expected Results--
Pressing Shift should allow for proportional resizing as well as constrained / discreet displacement and rotation (the latter has not been implemented, ever but maybe we can use this bug as an excuse :smile: )

### --Steps to reproduce--
1) Draw something
2) Select it with CTRL + A or the selection tool
3) Select the black arrow tool
4) Press the SHIFT key
5) Try to resize from a single corner and move it on different axis to notice that it fails to constraint the proportional edit.

### --System Information--
+ Pencil2D Version:
Version: 0.6.1.1
commit: 81f8da7d4105c579b480c5793abeba953311a3b2
date: 2018-05-18_22:58:16
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by scribblemaniac** [comment]
This bug appears to have been introduced in ed3c4ec/#949.

@CandyFace can you please take a look at this when you get a chance?
