### ISSUE TITLE
Implement canvas properties "preset" manager

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#981]
### --Issue Summary--
A few people, and another one today (on discord) have asked for the possibility to change the default camera resolution that comes "hard coded" with every new file in Pencil2D. 

I'm not talking about making a "new file" dialog, but rather to expose the camera layer default size and any other feasible constants, as a preference option and take it from there.

Normally this implementation would ideally come with a way to have "presets" for TV, Web and other platforms which would become an ordered list of different configurations that can modify and replace the "default" editor settings for Pencil2D on the current and each new file. 

For reference in other animation software when you create a new file you can:

1. Setup the measurement Units (P2D works with pixels but in the future we might want to support other measurements due to the relationship between field size / inches for animation paper and camera work in traditional animation so at least the imported paper can have their "real" size recognized by the software.
2. Setup the canvas size (Width x Height)
3. Setup the duration of the shot (timeline frame length)
4. Setup the FPS
5. Setup the Bakground Solid Color / Texture / Transparency Channel
6. Setup pixel ratio / aspect ratio (in different media and video specifications the pixel changes it's ratio, i.e 1.0 are called Square Pixels, because they have a 1:1 ratio, same with the screen, 1.33:1 is the pixel size for the famous 4:3 aspect ratio, 1.375:1 is the aspect ratio for film from the MPAA, and so on. This is also a key aspect you need to be compliant of when submitting video to film festivals or government institutions, they ask for this stuff literally)

In Pencil2D most of these elements are already present in the preferences option dialog except No.1 (uninplemented), No. 2, No. 4, and No.6 (unimplemented)

Most of these properties also already modify the software globally and are remembered when opening the software or creating a new file (timeline length, background color / texture) Ideally all of these options should be modifiable.

I know we don't want to over complicate things, but still a preset manager for projects would be nice. 

For the preset idea we could use a dropdown box that is populate with the list of presets along an <add> and <remove> button to add and remove custom presets. Also when creating a new preset we would need to enter the required values into a form or options dialog similar to the one for the video exporter.

When selected these presets would immediately change the current file values, and would maintain the same values for any new files that are created after that choice.

This is a quality of life (QoL) request, since I acknowledge that changing these parameters doesn't take long, but if you're working with many files (shots / cuts) with the same parameters that differ form P2D's defaults, it becomes a chore. Let me know what you think about this :slightly_smiling_face:

**Comment by J5lx** [comment]
For the record, Blender takes default project options from its [startup file](https://docs.blender.org/manual/en/dev/data_system/files/startup_file.html).

**Comment by CandyFace** [comment]
We could do something similar to blender startup file, just launching a startup.pcxl and be able to save and edit values.

**Comment by Jose-Moreno** [comment]
@J5lx So perhaps as @scribblemaniac suggested on Discord a template / startup file would be a viable solution then? Like you can configure your stuff save your startup file and then be done with it. He also mentioned it would be relatively simple to implement this sort of behavior.

On the other hand from a professional perspective I would still miss having a preset list for commonly used resolutions and film settings, mainly because movie settings differ a lot between countries and media. (e.g. NTSC vs PAL vs WEB vs FILM) Again, this is more of a quality of life thing. The easiest path is to have the user have their own list with those settings or to "google" or "duckduckgo" those results and input them every time they want a different "setting"  ... but that feels a bit counter-productive particularly for hobbyists and beginners which make a fair chunk of Pencil2D's user base and that have no clue as to what "standard" settings are used in the first place for the aforementioned media.

**Comment by CandyFace** [comment]
> On the other hand from a professional perspective I would still miss having a preset list for commonly used resolutions and film settings, mainly because movie settings differ a lot between countries and media. (e.g. NTSC vs PAL vs WEB vs FILM) Again, this is more of a quality of life thing. The easiest path is to have the user have their own list with those settings or to "google" or "duckduckgo" those results and input them every time they want a different "setting" ... but that feels a bit counter-productive particularly for hobbyists and beginners which make a fair chunk of Pencil2D's user base and that have no clue as to what "standard" settings are used in the first place for the aforementioned media.

@Jose-Moreno These are imo. things that belongs to a "new file dialog", like how CSP does it
![image](https://user-images.githubusercontent.com/1045397/40553540-456f8fc4-6043-11e8-8ac6-49b24de03ad3.png)

**Comment by J5lx** [comment]
@Jose-Moreno Blender has presets like that in its render dimension settings, alongside its startup file mechanism:

![screenshot from 2018-05-26 00-00-00](https://user-images.githubusercontent.com/2063777/40567952-082c5f18-6078-11e8-8aca-30b9df390625.png)

So in our case we could put them into the camera layer settings or something, I guess. Of course a new file dialog would also be an option, but personally I kinda like it when you can just start a new project without thinking too much about it beforehand, especially for a tool like Pencil2D that is mostly aimed at hobbyists and beginners who usually don’t have specific requirements.

**Comment by Jose-Moreno** [comment]
@J5lx @CandyFace To be honest I like the blender route a bit more for both things, the "startup file" and the "preset manager", but well I guess we'd have to mockup the thing and see if it's actually worth the effort since I also considered that...well it's not actually "difficult" to change the settings when you create your new file, it's just convenient and it's been requested a lot, but I know we're trying to also maintain simplicity not only from the user perspective but from the development side as well. Thank you for discussing this thing again :slightly_smiling_face:

**Comment by CandyFace** [comment]
Well to be honest I too like not having to worry about project settings when I start a new project.

Given that we already have some properties in the camera properties dialog, I see no reason why we couldn't add the rest there too.
