### ISSUE TITLE
[BUG] Exporting a movie any size lower than camera resolution exports single image

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#982]
### --Issue Summary--
Today it was reported and confirmed that exporting a video using the movie export options dialog, to  reduce or increase the movie resolution to a different size than what is set in the camera layer will provide wrong results during playback for any export format.

Note this does not happen while exporting to image sequences.

### --Actual Results--
Lower or Increasing the resolution seems to affect the offset of the images. When you lower the res, the images move offset horizontally, and when you increase the resolution the images are offset vertically.

Note that when you lower the resolution by half the current size and there's less than 7 frames, the exporter outputs a single image containing all the frames. If there's more than 7 Frames it will output enough "images" to portray the rest of the frames on a single page.

### --Expected Results--
Lowering or Increasing the size output using the export options dialog, should adequately scale the output to the desired resolution regardless of the entered size or even if the screen ratio is not the same, the image should be able to accomodate the output in a sensible manner.

### --Video or Image Reference--
**Original GIF export with output size set equal to camera size (800 x 600)**

![spritesheet_test_1](https://user-images.githubusercontent.com/4912907/40554984-255476e0-600d-11e8-9dc9-6819821d3430.gif)

**GIF export scaled down on output to half it's size (400 x 300)**

![spritesheet_test_2](https://user-images.githubusercontent.com/4912907/40555006-36cf96d4-600d-11e8-957e-36155d862166.gif)

**GIF export scaled up on output to twice it's size (1600 x 1200)**
![spritesheet_test_2b](https://user-images.githubusercontent.com/4912907/40555025-4a1fbe26-600d-11e8-8535-93f3ab4282bf.gif)

### --Steps to reproduce--
1) Draw a few frames of animation
2) File > Export > Movie
3) Press Browse, set any file format and give it a name
4) Export a reference file with default size
5) Change the width and height output and export again. (Go crazy, if you use extreme values you better can notice the problem)

### --System Information--
+ Pencil2D Version:
Version: 0.6.1.1
commit: 1977b4a627a73945621adaf73309c2441b85035e
date: 2018-05-21_22:38:11
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by scribblemaniac** [comment]
Fixed, thanks for reporting!

**Comment by Jose-Moreno** [comment]
@scribblemaniac Thanks to you for fixing it!
