### ISSUE TITLE
Camera Layer

### ISSUE THREAD

**Issue by Padorey** [pencil2d/pencil#985]
### --Issue Summary--
When I set 2 key frames in order for the camera to go from one place of the background to another, it works fine in pencil (pressing "play") but the mp4 exported plays the animation only from the first keyframe´s point of view.

### --Actual Results--
The camera view doesn't go from the first to the second keyframe in the exported MP4 animation.

### --Expected Results--
In the exported animation (MP4) the background would go from one point to the other as it does in Pencil when playing it
![keyframe1](https://user-images.githubusercontent.com/39774418/40769149-8bb63578-64b7-11e8-8814-fd32109eb45a.png)
![keyframe2](https://user-images.githubusercontent.com/39774418/40769150-8bdd5f2c-64b7-11e8-85ee-88df0ff19d97.png)

### --Steps to reproduce--
Export the animation in Mp4 and open in VLC player (Version 2.2.8 Weatherwax (Intel 64bit)).

### --System Information--
+ Pencil2D Version:
Version: 0.6.1.1

+ Operating System:
Operating System: macOS High Sierra (10.13.4)

+ RAM Size:

+ Graphics Tablet:

---

**Comment by chchwy** [comment]
Hi @Padorey Thanks for raising this issue.

Please download the latest nightly build version:
https://www.pencil2d.org/download/#nightlybuild

The camera layer issue has just been fixed.

**Comment by Jose-Moreno** [comment]
@Padorey If you are on a rush, you can also export an image sequence which will correctly display the camera motion, and you could re-import the images into pencil2D and then make the video. 
But as chchwy mentioned this issue has been fixed on the latest development build (nightly build).

**Comment by CandyFace** [comment]
Closing issue as it's been fixed.

**Comment by Padorey** [comment]
Beeing a rookie I'm impressed by all your kind answers, thank You all very much. I was already looking for an alternative by testing Synfigstudio. I'm glad to read that the nightlybuild latest version corrects my problem as I like the look of the animations in pencil. Again a big thank You.
Padorey.

**Comment by Jose-Moreno** [comment]
@Padorey You're welcome, and by all means any issue you have in the foreseeable future, you are welcome to report it so the team developers can review the issues. 

On a different note, Pencil2d is aiming to become a program that will hopefully bridge the gap between having to use novice and "pro" tools, so were not against you using different software to achieve your goal as an animator, in fact we encourage it. So if you're looking into Synfig as well, consider it as a tool to be used later in the animation pipeline, where you can take your polished rough animation from Pencil2D and then apply a "clean-up" and coloring stage with vector graphics, considering Pencil2D's own vector tools are still in development.

Synfig also offers the possibility of having some compositing work done to your animation, so it's definitely worth using it along to enhance your Pencil2D animation.
