### ISSUE TITLE
Onion Skin makes lines disappear

### ISSUE THREAD

**Issue by Am0reon** [pencil2d/pencil#986]
### --Issue Summary--
I was working on a second Frame using onion Skin when my lines disappered.

### --Actual Results--
The lines disapper and reapear when I turn onion Skin on/off. If I zoom out I can see the lines again but it is extremly inconvient for Details.

### --Expected Results--
Lines show up normally with and without onion skin

### --Steps to reproduce--
turn on onion Skin and draw on a second frame

### --System Information--
+ Pencil2D Version: 0.6.1

+ Operating System: Windows 10 Home

+ RAM Size:
7.88 GB, 4 GB full, 3.88 GB remaining

**Comment by chchwy** [comment]
Hi @Am0reon 
In markdown, `<!-- ` text inside `-->` won't show up.

**Comment by Jose-Moreno** [comment]
@Am0reon I'm trying to think of ways why this would happen but I'm not getting the same results as you. I literally created a new file, drew on the first frame, created a new frame and turned onion skin ON, and I could see both the previous and current frame strokes.

For now please try to use the latest development version to see if this issue still exists for you. (NOTE: You don't have to delete your previous Pencil2D version, this is just for testing purposes) http://pencil2d.org/download#nightlybuild

If you try it out and this issue does continue to happen on the nightly build, we urge you to provide a couple of screenshots depicting this behavior (you can simply use the print screen key and CTRL+V on the github issue text), and also provide more detailed information on the steps you take for this to happen.

**Comment by Creanimo** [comment]
I have this bug too in both the stable version and the nightly build, 32- and 64-bit:
https://www.youtube.com/watch?v=jufwLFa5CWU

All I need to do is to open a new project, add frames on the vector layer, activate onion skin and the issue occurs: Lines of the current frame disappear on certain zoom levels.

I am using Windows 10 PRO 64-bit, 16GB RAM, GeForce GTX 1060 6 GB

**Comment by Creanimo** [comment]
Nevermind that... I used an old nightly build. It's fixed for me when I use 2018-08-16

**Comment by Jose-Moreno** [comment]
@Creanimo Hi! thank you for reporting and following up on this issue (and for recording a video, it always helps) :slightly_smiling_face: Since the OP didn't respond to see if this was fixed, I'm going to take your interaction into account in order to close this ticket as it seems to have been solved already. If you experience any other issue, let us know by opening a new ticket (or commenting on a previously opened ticket that aligns with your issue as you did here). Thanks!

**Comment by piruzinho** [comment]
I have the same problem even having the latest version pls help me : c

**Comment by Jose-Moreno** [comment]
@piruzinho Hi. Please download and test the latest development build to rule out various possible issues, and then report back.
https://pencil2d.org/download/#nightlybuild
