### ISSUE TITLE
[BUG] Onion Skin rendering modified by passive, fully colored, layer

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#989]
### --Issue Summary--
For context: https://discuss.pencil2d.org/t/problems-with-onion-skin-feature/2669

In the latest nightly build, It seems that when you create a layer with a background color that covers the entire canvas, the onion skin rendering will not show above said layer.

The test was performed with bitmap layers but this also happens with vector layers.

### --Expected Results--
Since currently onion skin affects the active layer, you should be able to see the onion skin effect on any active layer without other layer rendering interfering with the visualization. That is, each layer should have it's own display of onion skin properly represented.

### --Video or Image Reference--
https://www.youtube.com/watch?v=qg_V8FQ-Ibw

### --Steps to reproduce--
0) Create a new file
1) Draw a moving line for a few frames to help see the issue better.
2) activate onion skin and verify it's working
3) Create a new layer below the current animation and fill it with a solid color.
4) Select the animation layer as the active layer and note how the onion skin "disappears"
5) turn off the Background color layer and notice how the onion skin "reappears"

### --System Information--
+ Pencil2D Version:
Version: 0.6.1.1
commit: 2520cd4d3249b49628b75e3e4caa97e55150bdd5
date: 2018-06-06_09:47:33
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by scribblemaniac** [comment]
Not sure why this wasn't auto-closed but anyway it's fixed with #1251.
