### ISSUE TITLE
non-functional zoom in Pencil2D

### ISSUE THREAD

**Issue by Meganssketches** [pencil2d/pencil#993]
When pressing "zoom in" or "zoom out" it is not working, it does nothing. I am unable to zoom in or out to draw details. Does anyone know how to fix this?

**Comment by Meganssketches** [comment]
never mind i fixed it i just had to press "ctrl and H "

**Comment by Jose-Moreno** [comment]
@Meganssketches Hi. Thank you for reporting. Just in case. You can activate the **zoom** function in four distinct ways.

1) Using the mouse scroll wheel. Just roll it forward (zoom-in) or backwards (zoom-out).
2) Press CTRL + UP ARROW or DOWN ARROW for discrete increments on your zoom percentage
3) Press CTRL + CLICK Middle Mouse Button & DRAG to smoothly zoom in and out
4) Use the VIEW menu > Select the [Zoom-In] or [Zoom-Out] options

To **reset** as you found out you can:

1) Press CTRL + H
2) Go to the VIEW menu > Select the [Reset Zoom/ Rotate] option

Note: Github is used to report recurring bugs, if you have a question or a new problem next time please visit us at our forums or at our discord server first to determine if you're having an issue that should be reported or if it's something that we can fix on the spot to avoid generating a ticket here. To access those you can visit https://www.pencil2d.org/community/

Lastly if this ticket is solved please close it manually to avoid saturating the system with solved issues. Thank you and happy week :slightly_smiling_face:
