### ISSUE TITLE
Onion Skin

### ISSUE THREAD

**Issue by Anaqitube** [pencil2d/pencil#998]
The Onion Skin Cant Work.

**Comment by Jose-Moreno** [comment]
@Anaqitube This is not a user forum but a place to report verified problems, if you're not sure how a feature work always please go to the Pencil2D forum https://discuss.pencil2d.org/ and ask there first.

That sentence has too little information for the developers to investigate the problem, but my bet is that you clicked on the "onion skins" button on the timeline right?
![image](https://user-images.githubusercontent.com/4912907/41545118-0ac05ae8-72e0-11e8-9b20-09671d0ec0bd.png)

**That button is NOT used to activate onion skin** but to see drawings or adjacent frames relative to the current frame you’re viewing. 

1. To activate onion skin you have to use the buttons on the “display panel” 

![image](https://user-images.githubusercontent.com/4912907/41545195-486ce582-72e0-11e8-9b6e-3d6943c96014.png)

2. Or press the hotkeys **[O Key]** (previous frame) and **[ALT + O]** (next frame)

3. Also once activated to modify the onion skin parameters you have to visit the **preferences** by going to **EDIT** > **PREFERENCES** > **TOOLS** > **Onion Skin**

![image](https://user-images.githubusercontent.com/4912907/41545218-549ce6e0-72e0-11e8-9e74-2f5018a41c09.png)
